processed 13 tasks

task 1, lines 6-50:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 9256800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 52:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3739200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 54:
//# view-object 2,0
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, lines 56-59:
//# view-object 2,1
Owner: Account Address ( BFC002f0e5131bf235e188cab1300e3789f1c0160ef500eec7b29787f0b71b75845cdfd )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5, lines 60-62:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: tto::M1::pass_through(Input(1));
//> tto::M1::receiver(Input(0), Result(0));
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 3739200,  storage_rebate: 3701808, non_refundable_storage_fee: 37392

task 6, lines 64-66:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: tto::M1::pass_through_a(Input(1));
//> tto::M1::receiver(Input(0), Result(0));
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(1) } }

task 7, lines 68-70:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: tto::M1::pass_through_mut_ref_a(Input(1));
//> tto::M1::receiver(Input(0), Input(1));
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(1) } }

task 8, lines 72-76:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: tto::M1::pass_through_ref_a(Input(1));
//> tto::M1::receiver(Input(0), Input(1));
// make vec, then unpack it and make sure the type is fixed
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(1) } }

task 9, lines 77-79:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: MakeMoveVec<sui::transfer::Receiving<tto::M1::A>>([Input(1)]);
//> 1: tto::M1::unpacker_b(Result(0));
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: None, command: Some(1) } }

task 10, lines 81-86:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: MakeMoveVec<sui::transfer::Receiving<tto::M1::A>>([Input(1)]);
//> 1: tto::M1::unpacker_a(Result(0));
//> 2: tto::M1::receiver(Input(0), Result(1));
// This is fine since we are going A -> A in the unpack. But we should fail the call.
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(2) } }

task 11, lines 87-92:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: MakeMoveVec<sui::transfer::Receiving<tto::M1::A>>([Input(1)]);
//> 1: tto::M1::unpacker_generic<tto::M1::A>(Result(0));
//> 2: tto::M1::receiver(Input(0), Result(1));
// This should fail since we're going A -> B in the unpack.
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(2) } }

task 12, lines 93-95:
//# programmable --inputs object(2,0) receiving(2,1)
//> 0: MakeMoveVec<sui::transfer::Receiving<tto::M1::A>>([Input(1)]);
//> 1: tto::M1::unpacker_generic<tto::M1::B>(Result(0));
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: None, command: Some(1) } }
