processed 8 tasks

task 1 'publish'. lines 6-29:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6923600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 31-31:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3739200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3 'view-object'. lines 33-33:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4 'view-object'. lines 35-37:
Owner: Account Address ( BFC13c346c8558cad29672b5d3240beb3225520c309c2446456115d971e94d26af25581 )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5 'programmable'. lines 38-39:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 6 'view-object'. lines 41-41:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 7 'view-object'. lines 43-43:
Owner: Account Address ( BFC13c346c8558cad29672b5d3240beb3225520c309c2446456115d971e94d26af25581 )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}
