processed 8 tasks

task 1 'publish'. lines 6-30:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 350360,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 32-32:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 186960,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 3 'view-object'. lines 34-34:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4 'view-object'. lines 36-38:
Owner: Account Address ( BFCa8f3cf99110b5f96c724bd07f8766c78b94b6dd7638c1b641c541cbd4054f84493fa )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5 'run'. lines 39-39:
Error: Transaction Effects Status: Move Runtime Abort. Location: tto::M1::receiver (function index 1) at offset 6, Abort Code: 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: tto, name: Identifier("M1") }, function: 1, instruction: 6, function_name: Some("receiver") }, 0), source: Some(VMError { major_status: ABORTED, sub_status: Some(0), message: Some("tto::M1::receiver at offset 6"), exec_state: None, location: Module(ModuleId { address: tto, name: Identifier("M1") }), indices: [], offsets: [(FunctionDefinitionIndex(1), 6)] }), command: Some(0) } }

task 6 'view-object'. lines 41-41:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 7 'view-object'. lines 43-43:
Owner: Account Address ( BFCa8f3cf99110b5f96c724bd07f8766c78b94b6dd7638c1b641c541cbd4054f84493fa )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}
