processed 10 tasks

task 1 'publish'. lines 6-29:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6969200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 31-31:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3739200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3 'view-object'. lines 33-33:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4 'view-object'. lines 35-35:
Owner: Account Address ( BFC481dcdd47770f21ed46bbff2958b8c2e4d0596fd3a3c0ffd3795b16adbb911448be7 )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5 'run'. lines 37-37:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6 'programmable'. lines 39-40:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 7 'programmable'. lines 42-43:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 8 'view-object'. lines 45-45:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 9 'view-object'. lines 47-47:
Owner: Account Address ( BFC481dcdd47770f21ed46bbff2958b8c2e4d0596fd3a3c0ffd3795b16adbb911448be7 )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}
