processed 11 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-36:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 407740,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 38-38:
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 193040,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 3 'view-object'. lines 40-40:
Owner: Account Address ( BFCfc01dc06506b798d86b30ad68a6f5108421235de6719dc5fad3bf00ab7bf75aecf7f )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 4 'view-object'. lines 42-42:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 5 'run'. lines 44-44:
Error: Error checking transaction input objects: IncorrectUserSignature { error: "Object object(2,0) is owned by account address object(2,1), but given owner/signer address is 0xd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8b" }

task 6 'view-object'. lines 46-46:
Owner: Account Address ( BFCfc01dc06506b798d86b30ad68a6f5108421235de6719dc5fad3bf00ab7bf75aecf7f )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 7 'view-object'. lines 48-48:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 8 'view-object'. lines 50-50:
Error: task 8, lines 50-50. Unbound fake id 5,0

task 9 'view-object'. lines 52-52:
Error: task 9, lines 52-52. Unbound fake id 5,1

task 10 'view-object'. lines 54-54:
Error: task 10, lines 54-54. Unbound fake id 5,2
