processed 9 tasks

task 1 'publish'. lines 6-44:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 8390400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 46-46:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4955200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3 'view-object'. lines 48-48:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4 'view-object'. lines 50-50:
Owner: Account Address ( BFC7e97086439ef205701e1db770d82ee9f4ffdf410b1b6dd430afa80e270a89bb15ca9 )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5 'view-object'. lines 52-54:
Owner: Account Address ( BFC3cd7f1d0d39e95bef3aaaa61aec5cb5d563551f1877eedc9d81753b2e38d2c8704cc )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
}

task 6 'programmable'. lines 55-58:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 2497968, non_refundable_storage_fee: 25232

task 7 'programmable'. lines 59-63:
Error: Error checking transaction input objects: DuplicateObjectRefInput

task 8 'programmable'. lines 64-67:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::receive_impl (function index 12) at offset 0, Abort Code: 3
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 12, instruction: 0, function_name: Some("receive_impl") }, 3), source: Some(VMError { major_status: ABORTED, sub_status: Some(3), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("transfer") }), indices: [], offsets: [(FunctionDefinitionIndex(12), 0)] }), command: Some(1) } }
