processed 9 tasks

task 1 'publish'. lines 6-44:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 419520,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 46-46:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 247760,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 3 'view-object'. lines 48-48:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4 'view-object'. lines 50-50:
Owner: Account Address ( BFCacab70746918610394388c266eaf502c0ecc2c00f788e12d0fe7e3e8c0ac189657ed )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5 'view-object'. lines 52-54:
Owner: Account Address ( BFC2124650cf8f149e62b3ccafc021a547b416b975fc4f7f777f310fa4134c14dcb55e1 )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
}

task 6 'programmable'. lines 55-58:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 126160,  storage_rebate: 124898, non_refundable_storage_fee: 1262

task 7 'programmable'. lines 59-63:
Error: Error checking transaction input objects: DuplicateObjectRefInput

task 8 'programmable'. lines 64-67:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::receive_impl (function index 12) at offset 0, Abort Code: 3
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 12, instruction: 0, function_name: Some("receive_impl") }, 3), source: Some(VMError { major_status: ABORTED, sub_status: Some(3), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("transfer") }), indices: [], offsets: [(FunctionDefinitionIndex(12), 0)] }), command: Some(1) } }
