processed 11 tasks

init:
A: object(0,0)

task 1, lines 6-36:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8154800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 38:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3860800,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 40:
//# view-object 2,0
Owner: Account Address ( BFC79d56270062e2b0eb0e466cc859b76be52187fbed46f032de89f2f4c442b4577f1a0 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 4, line 42:
//# view-object 2,1
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 5, line 44:
//# run tto::M1::receive --args object(2,0) receiving(2,1)
Error: Error checking transaction input objects: IncorrectUserSignature { error: "Object object(2,0) is owned by account address object(2,1), but given owner/signer address is 0xd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8b" }

task 6, line 46:
//# view-object 2,0
Owner: Account Address ( BFC79d56270062e2b0eb0e466cc859b76be52187fbed46f032de89f2f4c442b4577f1a0 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 7, line 48:
//# view-object 2,1
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 8, line 50:
//# view-object 5,0
Error: task 8, lines 50-50
//# view-object 5,0
. Unbound fake id 5,0

task 9, line 52:
//# view-object 5,1
Error: task 9, lines 52-52
//# view-object 5,1
. Unbound fake id 5,1

task 10, line 54:
//# view-object 5,2
Error: task 10, lines 54-54
//# view-object 5,2
. Unbound fake id 5,2
