processed 22 tasks

task 1 'publish'. lines 6-77:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 580260,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 79-79:
created: object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 369360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 3 'view-object'. lines 81-81:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4 'view-object'. lines 83-83:
Owner: Account Address ( BFCa911a3e4805f171d915042b8a8231fc7277ba34f0cd75bf4426f241722d3957bab1e )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5 'view-object'. lines 85-85:
Owner: Account Address ( BFCa911a3e4805f171d915042b8a8231fc7277ba34f0cd75bf4426f241722d3957bab1e )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
}

task 6 'view-object'. lines 87-87:
Owner: Account Address ( BFCa911a3e4805f171d915042b8a8231fc7277ba34f0cd75bf4426f241722d3957bab1e )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
}

task 7 'view-object'. lines 89-91:
Owner: Account Address ( BFCa911a3e4805f171d915042b8a8231fc7277ba34f0cd75bf4426f241722d3957bab1e )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,4),
        },
    },
}

task 8 'programmable'. lines 92-95:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 126160,  storage_rebate: 124898, non_refundable_storage_fee: 1262

task 9 'programmable'. lines 96-100:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 126160,  storage_rebate: 124898, non_refundable_storage_fee: 1262

task 10 'programmable'. lines 101-105:
mutated: object(0,0), object(2,0), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 308560,  storage_rebate: 305474, non_refundable_storage_fee: 3086

task 11 'programmable'. lines 106-111:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 369360,  storage_rebate: 365666, non_refundable_storage_fee: 3694

task 12 'programmable'. lines 112-117:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 369360,  storage_rebate: 365666, non_refundable_storage_fee: 3694

task 13 'programmable'. lines 118-123:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 369360,  storage_rebate: 365666, non_refundable_storage_fee: 3694

task 14 'programmable'. lines 124-129:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 369360,  storage_rebate: 365666, non_refundable_storage_fee: 3694

task 15 'programmable'. lines 130-135:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 369360,  storage_rebate: 365666, non_refundable_storage_fee: 3694

task 16 'programmable'. lines 136-138:
mutated: object(0,0), object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 369360,  storage_rebate: 365666, non_refundable_storage_fee: 3694

task 17 'view-object'. lines 140-140:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 12
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 18 'view-object'. lines 142-142:
Owner: Account Address ( BFC000000000000000000000000000000000000000000000000000000000000000060e0 )
Version: 12
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 19 'view-object'. lines 144-144:
Owner: Account Address ( BFC000000000000000000000000000000000000000000000000000000000000000060e0 )
Version: 12
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
}

task 20 'view-object'. lines 146-146:
Owner: Account Address ( BFC000000000000000000000000000000000000000000000000000000000000000060e0 )
Version: 12
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
}

task 21 'view-object'. lines 148-148:
Owner: Account Address ( BFC000000000000000000000000000000000000000000000000000000000000000060e0 )
Version: 12
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,4),
        },
    },
}
