processed 13 tasks

init:
A: object(0,0)

task 1, lines 6-36:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7326400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 38:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3739200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 40:
//# run tto::M1::middle --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, line 42:
//# view-object 2,0
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 5, lines 44-46:
//# view-object 2,1
Owner: Account Address ( BFC23298b6dae40eb633ac4583ea44dee4115a47c20a007683c0fec30de90b12b26ab32 )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 6, line 47:
//# run tto::M1::send_back --args object(2,0) receiving(2,1)
mutated: object(0,1), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 3739200,  storage_rebate: 3701808, non_refundable_storage_fee: 37392

task 7, line 49:
//# view-object 2,0
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 4
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 8, lines 51-53:
//# view-object 2,1
Owner: Account Address ( BFC23298b6dae40eb633ac4583ea44dee4115a47c20a007683c0fec30de90b12b26ab32 )
Version: 4
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 9, lines 54-56:
//# run tto::M1::send_back --args object(2,0) receiving(2,1)@3
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::receive_impl (function index 12) at offset 0, Abort Code: 3
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 12, instruction: 0, function_name: Some("receive_impl") }, 3), source: Some(VMError { major_status: ABORTED, sub_status: Some(3), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("transfer") }), indices: [], offsets: [(FunctionDefinitionIndex(12), 0)] }), command: Some(0) } }

task 10, lines 57-59:
//# run tto::M1::send_back --args object(2,0) receiving(2,1)@4
mutated: object(0,1), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 3739200,  storage_rebate: 3701808, non_refundable_storage_fee: 37392

task 11, lines 60-62:
//# run tto::M1::send_back --summarize --args object(3,0) receiving(2,1)@6 --sender A
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::receive_impl (function index 12) at offset 0, Abort Code: 3
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 12, instruction: 0, function_name: Some("receive_impl") }, 3), source: Some(VMError { major_status: ABORTED, sub_status: Some(3), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("transfer") }), indices: [], offsets: [(FunctionDefinitionIndex(12), 0)] }), command: Some(0) } }

task 12, line 63:
//# run tto::M1::send_back --args object(2,0) receiving(2,1)@6
mutated: object(0,1), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 3739200,  storage_rebate: 3701808, non_refundable_storage_fee: 37392
