processed 12 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-34:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8147200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 36-36:
created: object(2,0), object(2,1), object(2,2), object(2,3)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7592400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 38-38:
Owner: Object ID: ( BFCbe0db64e9fd0856318b10337155172e70fe937aa66a05bb06d5147268dfe7d2fbaa0 )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,1),
    },
}

task 4 'view-object'. lines 40-40:
Owner: Object ID: ( BFCbe482abaf6c904724c659d3f5647453094e438b21d5aa36c0b7bed3690b7a3da6312 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 5 'view-object'. lines 42-42:
Owner: Account Address ( BFCfeb1573d0c6f8283581fbdd54ffde00866b2b56693b60f89df2acbc0721650b6f491 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 0u64,
}

task 6 'view-object'. lines 44-44:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
    value: 0u64,
}

task 7 'run'. lines 46-46:
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(2,1), parent_id: object(2,0) }

task 8 'view-object'. lines 48-48:
Owner: Object ID: ( BFCbe0db64e9fd0856318b10337155172e70fe937aa66a05bb06d5147268dfe7d2fbaa0 )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,1),
    },
}

task 9 'view-object'. lines 50-50:
Owner: Object ID: ( BFCbe482abaf6c904724c659d3f5647453094e438b21d5aa36c0b7bed3690b7a3da6312 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 10 'view-object'. lines 52-52:
Owner: Account Address ( BFCfeb1573d0c6f8283581fbdd54ffde00866b2b56693b60f89df2acbc0721650b6f491 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 0u64,
}

task 11 'view-object'. lines 54-54:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
    value: 0u64,
}
