processed 9 tasks

task 1, lines 6-30:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7045200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 32:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3739200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 34:
//# view-object 2,0
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, lines 36-38:
//# view-object 2,1
Owner: Account Address ( BFC93dbc4b39a7f8aedda277e3364c6c1e4b9b113c59c2d1ab292cef8ed4313e0a7a679 )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5, line 39:
//# run tto::M1::deleter --args object(2,0) receiving(2,1)
mutated: object(0,0), object(2,0)
deleted: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 3701808, non_refundable_storage_fee: 37392

task 6, line 41:
//# view-object 2,0
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 7, lines 43-45:
//# view-object 2,1
No object at id 2,1

task 8, line 46:
//# run tto::M1::deleter --args object(2,0) receiving(2,1)@3
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::receive_impl (function index 12) at offset 0, Abort Code: 3
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 12, instruction: 0, function_name: Some("receive_impl") }, 3), source: Some(VMError { major_status: ABORTED, sub_status: Some(3), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("transfer") }), indices: [], offsets: [(FunctionDefinitionIndex(12), 0)] }), command: Some(0) } }
