processed 3 tasks

task 1 'publish'. lines 6-24:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 617120,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 26-26:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 373920,  storage_rebate: 129413, non_refundable_storage_fee: 1307
