processed 4 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-24:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 57076,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 26-35:
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 13072,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 3 'programmable'. lines 37-40:
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 13072,  storage_rebate: 12941, non_refundable_storage_fee: 131
