processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-23:
created: object(1,0), object(1,1), object(1,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 546820,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 25-27:
created: object(2,0)
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 216600,  storage_rebate: 148975, non_refundable_storage_fee: 1505

task 3 'view-object'. lines 29-29:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: sui::coin::Coin<test::fake::FAKE> {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, balance: sui::balance::Balance<test::fake::FAKE> {value: 100u64}}

task 4 'programmable'. lines 31-37:
created: object(4,0)
mutated: object(0,0), object(1,2)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 216600,  storage_rebate: 214434, non_refundable_storage_fee: 2166
