processed 3 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'programmable'. lines 8-9:
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 130720,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 11-11:
Owner: Account Address ( B )
Version: 2
Contents: sui::coin::Coin<sui::bfc::BFC> {id: sui::object::UID {id: sui::object::ID {bytes: fake(0,0)}}, balance: sui::balance::Balance<sui::bfc::BFC> {value: 299999999769280u64}}
