processed 8 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 8-47:
created: object(1,0)
mutated: object(0,3)
gas summary: computation_cost: 1000000, storage_cost: 373920,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 48-55:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'programmable'. lines 56-63:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 4 'programmable'. lines 64-68:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 5 'programmable'. lines 69-71:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 129960,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 6 'view-object'. lines 73-73:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 5
Contents: test::m1::Pub {id: sui::object::UID {id: sui::object::ID {bytes: fake(5,0)}}, value: 112u64}

task 7 'programmable'. lines 75-81:
mutated: object(0,0)
deleted: object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 128660, non_refundable_storage_fee: 1300
