processed 3 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-19:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 497800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 21-26:
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 130720,  storage_rebate: 129413, non_refundable_storage_fee: 1307
