processed 3 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-19:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 249280,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 21-26:
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654
