processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-29:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 656640,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 31-35:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 495520,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'programmable'. lines 37-41:
mutated: object(0,0)
deleted: object(2,0), object(2,1), object(2,2)
gas summary: computation_cost: 100000, storage_cost: 130720,  storage_rebate: 490565, non_refundable_storage_fee: 4955

task 4 'programmable'. lines 43-46:
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 130720,  storage_rebate: 129413, non_refundable_storage_fee: 1307
