processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-15:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 4947600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 17-19:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2538400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 21-21:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: test::m1::Pub {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}}

task 4 'programmable'. lines 23-25:
created: object(4,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2538400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5 'view-object'. lines 27-27:
Owner: Shared
Version: 3
Contents: test::m1::Pub {id: sui::object::UID {id: sui::object::ID {bytes: fake(4,0)}}}

task 6 'programmable'. lines 29-31:
created: object(6,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2538400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 7 'view-object'. lines 33-33:
Owner: Immutable
Version: 4
Contents: test::m1::Pub {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}}
