processed 20 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-26:
warning[W02021]: duplicate alias
   ┌─ /var/folders/9l/kfqd6hv17d1_8yxpd6zwys8m0000gn/T/tmp.WXmZv3PwS1/.tmpxRKY2w:11:14
   │
11 │     use std::vector;
   │              ^^^^^^ Unnecessary alias 'vector' for module 'std::vector'. This alias is provided by default
   │
   = This warning can be suppressed with '#[allow(duplicate_alias)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

warning[W02021]: duplicate alias
   ┌─ /var/folders/9l/kfqd6hv17d1_8yxpd6zwys8m0000gn/T/tmp.WXmZv3PwS1/.tmpxRKY2w:13:14
   │
13 │     use sui::transfer;
   │              ^^^^^^^^ Unnecessary alias 'transfer' for module 'sui::transfer'. This alias is provided by default
   │
   = This warning can be suppressed with '#[allow(duplicate_alias)]' applied to the 'module' or module member ('const', 'fun', or 'struct')

created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 564680,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 28-32:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 261440,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 33-33:
created: object(3,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 392160,  storage_rebate: 258826, non_refundable_storage_fee: 2614

task 4 'view-object'. lines 35-37:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 1000u64,
    },
}

task 5 'programmable'. lines 38-40:
created: object(5,0)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 392160,  storage_rebate: 258826, non_refundable_storage_fee: 2614

task 6 'view-object'. lines 42-42:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 900u64,
    },
}

task 7 'view-object'. lines 44-47:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 4
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(5,0),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 100u64,
    },
}

task 8 'programmable'. lines 48-50:
created: object(8,0), object(8,1)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 522880,  storage_rebate: 258826, non_refundable_storage_fee: 2614

task 9 'view-object'. lines 52-52:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 5
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 700u64,
    },
}

task 10 'view-object'. lines 54-54:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 5
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(8,0),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 100u64,
    },
}

task 11 'view-object'. lines 56-58:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 5
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(8,1),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 100u64,
    },
}

task 12 'programmable'. lines 59-62:
created: object(12,0), object(12,1)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 522880,  storage_rebate: 258826, non_refundable_storage_fee: 2614

task 13 'view-object'. lines 64-64:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 6
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 500u64,
    },
}

task 14 'view-object'. lines 66-66:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 6
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(12,0),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 100u64,
    },
}

task 15 'view-object'. lines 68-71:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 6
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(12,1),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 100u64,
    },
}

task 16 'programmable'. lines 72-76:
created: object(16,0), object(16,1)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 522880,  storage_rebate: 258826, non_refundable_storage_fee: 2614

task 17 'view-object'. lines 78-78:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 7
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 300u64,
    },
}

task 18 'view-object'. lines 80-80:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 7
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(16,0),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 100u64,
    },
}

task 19 'view-object'. lines 82-82:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 7
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(16,1),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 100u64,
    },
}
