processed 8 tasks

init:
A: object(0,0)

task 1, lines 10-19:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4940000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 21-23:
//# programmable --sender A --inputs @A
//> 0: test::mod::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2546000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 25-27:
//# programmable --sender A --inputs 42 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 29:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 31-35:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC0aab5a53b8e88a4dc6e6161b1b877b1c00fea4efbf04f8eb91e5f5dd0d7a8f63839e",
      "version": "1",
      "digest": "E1iRgnnzwM9FzhbozoBMx8wU4LRBbgpJRKDWQX2D36Pu",
      "content": {
        "dataType": "package",
        "disassembled": {
          "mod": "// Move bytecode v6\nmodule aab5a53b8e88a4dc6e6161b1b877b1c00fea4efbf04f8eb91e5f5dd0d7a8f63.mod {\nuse 0000000000000000000000000000000000000000000000000000000000000002::object;\nuse 0000000000000000000000000000000000000000000000000000000000000002::tx_context;\n\nstruct Foo has store, key {\n\tid: UID\n}\n\npublic new(Arg0: &mut TxContext): Foo {\nB0:\n\t0: MoveLoc[0](Arg0: &mut TxContext)\n\t1: Call object::new(&mut TxContext): UID\n\t2: Pack[0](Foo)\n\t3: Ret\n}\n\n}\n"
        }
      },
      "bcs": {
        "dataType": "package",
        "id": "BFC0aab5a53b8e88a4dc6e6161b1b877b1c00fea4efbf04f8eb91e5f5dd0d7a8f63839e",
        "version": 1,
        "moduleMap": {
          "mod": "oRzrCwYAAAAIAQAGAgYMAxIKBRwLBycvCFZACpYBBgycAQ0ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAAMAAQcIAgEIAAABCAEDRm9vCVR4Q29udGV4dANVSUQCaWQDbW9kA25ldwZvYmplY3QKdHhfY29udGV4dAqrWlO46IpNxuYWGxuHexwA/qTvvwT465Hl9d0Neo9jAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAgEDCAEAAQAAAgQLABEBEgACAA=="
        },
        "typeOriginTable": [
          {
            "module_name": "mod",
            "datatype_name": "Foo",
            "package": "BFC0aab5a53b8e88a4dc6e6161b1b877b1c00fea4efbf04f8eb91e5f5dd0d7a8f63839e"
          }
        ],
        "linkageTable": {
          "BFC0000000000000000000000000000000000000000000000000000000000000001c386": {
            "upgraded_id": "BFC0000000000000000000000000000000000000000000000000000000000000001c386",
            "upgraded_version": 1
          },
          "BFC000000000000000000000000000000000000000000000000000000000000000268e4": {
            "upgraded_id": "BFC000000000000000000000000000000000000000000000000000000000000000268e4",
            "upgraded_version": 1
          }
        }
      }
    }
  }
}

task 6, lines 37-41:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC1228bf2638d94f2631a7834d6ea46dfbc1fd6711de1f3b5e0a967759582e130ee5cc",
      "version": "2",
      "digest": "D3nemuB78NCGhNXEAXajafhRQey8NWUSm4VXE3u8mfWn",
      "content": {
        "dataType": "moveObject",
        "type": "0x0aab5a53b8e88a4dc6e6161b1b877b1c00fea4efbf04f8eb91e5f5dd0d7a8f63::mod::Foo",
        "hasPublicTransfer": true,
        "fields": {
          "id": {
            "id": "BFC1228bf2638d94f2631a7834d6ea46dfbc1fd6711de1f3b5e0a967759582e130ee5cc"
          }
        }
      },
      "bcs": {
        "dataType": "moveObject",
        "type": "0x0aab5a53b8e88a4dc6e6161b1b877b1c00fea4efbf04f8eb91e5f5dd0d7a8f63::mod::Foo",
        "hasPublicTransfer": true,
        "version": 2,
        "bcsBytes": "Eii/JjjZTyYxp4NNbqRt+8H9ZxHeHzteCpZ3WVguEw4="
      }
    }
  }
}

task 7, lines 43-47:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFCcafd5b116d16b3826ee966fc273e83044eb27eca342c520b2778f5739f4c36ea519c",
      "version": "3",
      "digest": "EzHTbtM9LZMesM3zJnjNCzcGd5enYmCvJLodqVQprwm8",
      "content": {
        "dataType": "moveObject",
        "type": "0x2::coin::Coin<0x2::bfc::BFC>",
        "hasPublicTransfer": true,
        "fields": {
          "balance": "42",
          "id": {
            "id": "BFCcafd5b116d16b3826ee966fc273e83044eb27eca342c520b2778f5739f4c36ea519c"
          }
        }
      },
      "bcs": {
        "dataType": "moveObject",
        "type": "0x2::coin::Coin<0x2::bfc::BFC>",
        "hasPublicTransfer": true,
        "version": 3,
        "bcsBytes": "yv1bEW0Ws4Ju6Wb8Jz6DBE6yfso0LFILJ3j1c59MNuoqAAAAAAAAAA=="
      }
    }
  }
}
