processed 8 tasks

init:
A: object(0,0)

task 1, lines 10-19:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4940000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 21-23:
//# programmable --sender A --inputs @A
//> 0: test::mod::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2546000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 25-27:
//# programmable --sender A --inputs 42 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 29:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 31-35:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFCe94f5e6ea43b948f43a2bdaebc7f2362bb1fc578828fe693c4f36888974907604c76",
      "version": "1",
      "digest": "J6pXBh4sukivhi4MsA5YMsN6HFdVYt1S75LoiB6KKu2b",
      "content": {
        "dataType": "package",
        "disassembled": {
          "mod": "// Move bytecode v6\nmodule e94f5e6ea43b948f43a2bdaebc7f2362bb1fc578828fe693c4f3688897490760.mod {\nuse 0000000000000000000000000000000000000000000000000000000000000002::object;\nuse 0000000000000000000000000000000000000000000000000000000000000002::tx_context;\n\nstruct Foo has store, key {\n\tid: UID\n}\n\npublic new(Arg0: &mut TxContext): Foo {\nB0:\n\t0: MoveLoc[0](Arg0: &mut TxContext)\n\t1: Call object::new(&mut TxContext): UID\n\t2: Pack[0](Foo)\n\t3: Ret\n}\n\n}\n"
        }
      },
      "bcs": {
        "dataType": "package",
        "id": "BFCe94f5e6ea43b948f43a2bdaebc7f2362bb1fc578828fe693c4f36888974907604c76",
        "version": 1,
        "moduleMap": {
          "mod": "oRzrCwYAAAAIAQAGAgYMAxIKBRwLBycvCFZACpYBBgycAQ0ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAAMAAQcIAgEIAAABCAEDRm9vCVR4Q29udGV4dANVSUQCaWQDbW9kA25ldwZvYmplY3QKdHhfY29udGV4dOlPXm6kO5SPQ6K9rrx/I2K7H8V4go/mk8TzaIiXSQdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAgEDCAEAAQAAAgQLABEBEgACAA=="
        },
        "typeOriginTable": [
          {
            "module_name": "mod",
            "datatype_name": "Foo",
            "package": "BFCe94f5e6ea43b948f43a2bdaebc7f2362bb1fc578828fe693c4f36888974907604c76"
          }
        ],
        "linkageTable": {
          "BFC0000000000000000000000000000000000000000000000000000000000000001c386": {
            "upgraded_id": "BFC0000000000000000000000000000000000000000000000000000000000000001c386",
            "upgraded_version": 1
          },
          "BFC000000000000000000000000000000000000000000000000000000000000000268e4": {
            "upgraded_id": "BFC000000000000000000000000000000000000000000000000000000000000000268e4",
            "upgraded_version": 1
          }
        }
      }
    }
  }
}

task 6, lines 37-41:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC773a5623681fe126aa86902ff5694c9e5cdead69fb2e719ae9d28014571b7fde2812",
      "version": "2",
      "digest": "ExMSkstTkJtn5SALhnB5iGHXVSFTXTGEvQSNXgm2FsBG",
      "content": {
        "dataType": "moveObject",
        "type": "0xe94f5e6ea43b948f43a2bdaebc7f2362bb1fc578828fe693c4f3688897490760::mod::Foo",
        "hasPublicTransfer": true,
        "fields": {
          "id": {
            "id": "BFC773a5623681fe126aa86902ff5694c9e5cdead69fb2e719ae9d28014571b7fde2812"
          }
        }
      },
      "bcs": {
        "dataType": "moveObject",
        "type": "0xe94f5e6ea43b948f43a2bdaebc7f2362bb1fc578828fe693c4f3688897490760::mod::Foo",
        "hasPublicTransfer": true,
        "version": 2,
        "bcsBytes": "dzpWI2gf4SaqhpAv9WlMnlzerWn7LnGa6dKAFFcbf94="
      }
    }
  }
}

task 7, lines 43-47:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC047f235c606a165fd1540192e731aa27243e8dcff537795c02550a6a97e1494f94c1",
      "version": "3",
      "digest": "TVvyXRPxjeXHJLwBKSK4zJRGAHLGk2bhTF8GQDbKDpq",
      "content": {
        "dataType": "moveObject",
        "type": "0x2::coin::Coin<0x2::bfc::BFC>",
        "hasPublicTransfer": true,
        "fields": {
          "balance": "42",
          "id": {
            "id": "BFC047f235c606a165fd1540192e731aa27243e8dcff537795c02550a6a97e1494f94c1"
          }
        }
      },
      "bcs": {
        "dataType": "moveObject",
        "type": "0x2::coin::Coin<0x2::bfc::BFC>",
        "hasPublicTransfer": true,
        "version": 3,
        "bcsBytes": "BH8jXGBqFl/RVAGS5zGqJyQ+jc/1N3lcAlUKapfhSU8qAAAAAAAAAA=="
      }
    }
  }
}
