processed 8 tasks

init:
A: object(0,0)

task 1, lines 10-19:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4940000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 21-23:
//# programmable --sender A --inputs @A
//> 0: test::mod::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2546000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 25-27:
//# programmable --sender A --inputs 42 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 29:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 31-35:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC34cfa451e126de9ccfd1f321f4014c3ba5b3c4dc19421b57f2d6d04a3b8733d26f41",
      "version": "1",
      "digest": "J5ybfAPASMgBk8m8pKiYgeDCA4oceF66PqwwNG3KudgK",
      "content": {
        "dataType": "package",
        "disassembled": {
          "mod": "// Move bytecode v6\nmodule 34cfa451e126de9ccfd1f321f4014c3ba5b3c4dc19421b57f2d6d04a3b8733d2.mod {\nuse 0000000000000000000000000000000000000000000000000000000000000002::object;\nuse 0000000000000000000000000000000000000000000000000000000000000002::tx_context;\n\nstruct Foo has store, key {\n\tid: UID\n}\n\npublic new(Arg0: &mut TxContext): Foo {\nB0:\n\t0: MoveLoc[0](Arg0: &mut TxContext)\n\t1: Call object::new(&mut TxContext): UID\n\t2: Pack[0](Foo)\n\t3: Ret\n}\n\n}\n"
        }
      },
      "bcs": {
        "dataType": "package",
        "id": "BFC34cfa451e126de9ccfd1f321f4014c3ba5b3c4dc19421b57f2d6d04a3b8733d26f41",
        "version": 1,
        "moduleMap": {
          "mod": "oRzrCwYAAAAIAQAGAgYMAxIKBRwLBycvCFZACpYBBgycAQ0ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAAMAAQcIAgEIAAABCAEDRm9vCVR4Q29udGV4dANVSUQCaWQDbW9kA25ldwZvYmplY3QKdHhfY29udGV4dDTPpFHhJt6cz9HzIfQBTDuls8TcGUIbV/LW0Eo7hzPSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAgEDCAEAAQAAAgQLABEBEgACAA=="
        },
        "typeOriginTable": [
          {
            "module_name": "mod",
            "datatype_name": "Foo",
            "package": "BFC34cfa451e126de9ccfd1f321f4014c3ba5b3c4dc19421b57f2d6d04a3b8733d26f41"
          }
        ],
        "linkageTable": {
          "BFC0000000000000000000000000000000000000000000000000000000000000001c386": {
            "upgraded_id": "BFC0000000000000000000000000000000000000000000000000000000000000001c386",
            "upgraded_version": 1
          },
          "BFC000000000000000000000000000000000000000000000000000000000000000268e4": {
            "upgraded_id": "BFC000000000000000000000000000000000000000000000000000000000000000268e4",
            "upgraded_version": 1
          }
        }
      }
    }
  }
}

task 6, lines 37-41:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC8702cb15ca6e0b81c093f1450e0b7617a159b40017e4002400169c049489db2674d6",
      "version": "2",
      "digest": "8PaJFrLwtgbyc2CGDnYKF5RxfyASKK2HbDgyB1fXVfKB",
      "content": {
        "dataType": "moveObject",
        "type": "0x34cfa451e126de9ccfd1f321f4014c3ba5b3c4dc19421b57f2d6d04a3b8733d2::mod::Foo",
        "hasPublicTransfer": true,
        "fields": {
          "id": {
            "id": "BFC8702cb15ca6e0b81c093f1450e0b7617a159b40017e4002400169c049489db2674d6"
          }
        }
      },
      "bcs": {
        "dataType": "moveObject",
        "type": "0x34cfa451e126de9ccfd1f321f4014c3ba5b3c4dc19421b57f2d6d04a3b8733d2::mod::Foo",
        "hasPublicTransfer": true,
        "version": 2,
        "bcsBytes": "hwLLFcpuC4HAk/FFDgt2F6FZtAAX5AAkABacBJSJ2yY="
      }
    }
  }
}

task 7, lines 43-47:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC3cd7262afd8f72424136e84ba4ba07882c534eb973244fa656363fe69f50730e56b5",
      "version": "3",
      "digest": "87ptxrYAyXyo4nruopZzT3x7fCeCv4xaazucSCX5ay2C",
      "content": {
        "dataType": "moveObject",
        "type": "0x2::coin::Coin<0x2::bfc::BFC>",
        "hasPublicTransfer": true,
        "fields": {
          "balance": "42",
          "id": {
            "id": "BFC3cd7262afd8f72424136e84ba4ba07882c534eb973244fa656363fe69f50730e56b5"
          }
        }
      },
      "bcs": {
        "dataType": "moveObject",
        "type": "0x2::coin::Coin<0x2::bfc::BFC>",
        "hasPublicTransfer": true,
        "version": 3,
        "bcsBytes": "PNcmKv2PckJBNuhLpLoHiCxTTrlzJE+mVjY/5p9Qcw4qAAAAAAAAAA=="
      }
    }
  }
}
