processed 13 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 12-14:
//# programmable --sender A --inputs 42 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 16-18:
//# programmable --sender A --inputs 43 @B
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 20-22:
//# programmable --sender A --inputs 44
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: sui::transfer::public_share_object<sui::coin::Coin<sui::sui::SUI>>(Result(0))
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: LINKER_ERROR, sub_status: None, message: Some("Cannot find ModuleId { address: sui, name: Identifier(\"sui\") } in data cache"), exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(1) } }

task 4, lines 24-26:
//# programmable --sender A --inputs 45
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: sui::transfer::public_freeze_object<sui::coin::Coin<sui::sui::SUI>>(Result(0))
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: LINKER_ERROR, sub_status: None, message: Some("Cannot find ModuleId { address: sui, name: Identifier(\"sui\") } in data cache"), exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(1) } }

task 5, lines 28-30:
//# programmable --sender A --inputs @A
//> 0: sui::table::new<u64, u64>();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2652400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6, lines 32-33:
//# programmable --sender A --inputs object(5,0) 46 47
//> 0: sui::table::add<u64, u64>(Input(0), Input(1), Input(2))
created: object(6,0)
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 4119200,  storage_rebate: 2625876, non_refundable_storage_fee: 26524

task 7, line 35:
//# create-checkpoint
Checkpoint created: 1

task 8, lines 37-41:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFCa5b98f5e2a30b475d77be23bb5bd25605d72abfc7fa4d3d21ad0b1768c3ff5acb7e1",
      "version": "2",
      "digest": "DmaVBmcxAj9jufnXFRTq832uWFCTxf71uX4Fba8RAMSP",
      "owner": {
        "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
      }
    }
  }
}

task 9, lines 43-47:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFCc303ac99e4e4d221a918092c8ea0927dcfaccf8d03a48564fde12d3ed31fda6e00b1",
      "version": "3",
      "digest": "A8Sr62NYjGtNSR3sjtBLJjmCSeDvL3JrFwUAXfFc9ni2",
      "owner": {
        "AddressOwner": "BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9"
      }
    }
  }
}

task 10, lines 49-53:
//# run-jsonrpc
Error: Unknown variable: obj_3_0
Allowed variable mappings are {
    "A": "@A",
    "A_opt": "@A",
    "B": "@B",
    "B_opt": "@B",
    "bfc_system": "0xc8",
    "bfc_system_opt": "0xc8",
    "bridge": "0xb",
    "bridge_opt": "0xb",
    "digest_1": "8BuUFdJ7qwcs9DeZxB4HGkFuEaECpsDpSCagNt7hFZbK",
    "digest_2": "Crbz95whXgUnnssYg36LaceQoZJJFrNUwoPx8j2Yyf6r",
    "digest_3": "9MmLSzA4a6sMSSv67UNCW6FuB3H4oBTsk6dNAvRBcqkU",
    "digest_4": "Acb41nV8ARv7Y5a3jUcA7ESrtPsou4LGfNE5kzuauWRs",
    "digest_5": "5Bj7RWH1uRchxQeAGZHf5gNgVx8LJrc9AtgyB2uyhp5",
    "digest_6": "FNxdy3A3iMsduLKfruY6izNoNQBjwKhVuB8uTDQgVsRq",
    "obj_0_0": "object(0,0)",
    "obj_0_0_opt": "object(0,0)",
    "obj_0_1": "object(0,1)",
    "obj_0_1_opt": "object(0,1)",
    "obj_0_2": "object(0,2)",
    "obj_0_2_opt": "object(0,2)",
    "obj_1_0": "object(1,0)",
    "obj_1_0_opt": "object(1,0)",
    "obj_2_0": "object(2,0)",
    "obj_2_0_opt": "object(2,0)",
    "obj_5_0": "object(5,0)",
    "obj_5_0_opt": "object(5,0)",
    "obj_6_0": "object(6,0)",
    "obj_6_0_opt": "object(6,0)",
    "std": "0x1",
    "std_opt": "0x1",
    "sui": "0x2",
    "sui_opt": "0x2",
    "sui_system": "0x3",
    "sui_system_opt": "0x3",
    "test": "0x0",
    "test_opt": "0x0",
    "validator_0": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
    "validator_0_opt": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
}

task 11, lines 55-59:
//# run-jsonrpc
Error: Unknown variable: obj_4_0
Allowed variable mappings are {
    "A": "@A",
    "A_opt": "@A",
    "B": "@B",
    "B_opt": "@B",
    "bfc_system": "0xc8",
    "bfc_system_opt": "0xc8",
    "bridge": "0xb",
    "bridge_opt": "0xb",
    "digest_1": "8BuUFdJ7qwcs9DeZxB4HGkFuEaECpsDpSCagNt7hFZbK",
    "digest_2": "Crbz95whXgUnnssYg36LaceQoZJJFrNUwoPx8j2Yyf6r",
    "digest_3": "9MmLSzA4a6sMSSv67UNCW6FuB3H4oBTsk6dNAvRBcqkU",
    "digest_4": "Acb41nV8ARv7Y5a3jUcA7ESrtPsou4LGfNE5kzuauWRs",
    "digest_5": "5Bj7RWH1uRchxQeAGZHf5gNgVx8LJrc9AtgyB2uyhp5",
    "digest_6": "FNxdy3A3iMsduLKfruY6izNoNQBjwKhVuB8uTDQgVsRq",
    "obj_0_0": "object(0,0)",
    "obj_0_0_opt": "object(0,0)",
    "obj_0_1": "object(0,1)",
    "obj_0_1_opt": "object(0,1)",
    "obj_0_2": "object(0,2)",
    "obj_0_2_opt": "object(0,2)",
    "obj_1_0": "object(1,0)",
    "obj_1_0_opt": "object(1,0)",
    "obj_2_0": "object(2,0)",
    "obj_2_0_opt": "object(2,0)",
    "obj_5_0": "object(5,0)",
    "obj_5_0_opt": "object(5,0)",
    "obj_6_0": "object(6,0)",
    "obj_6_0_opt": "object(6,0)",
    "std": "0x1",
    "std_opt": "0x1",
    "sui": "0x2",
    "sui_opt": "0x2",
    "sui_system": "0x3",
    "sui_system_opt": "0x3",
    "test": "0x0",
    "test_opt": "0x0",
    "validator_0": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
    "validator_0_opt": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
}

task 12, lines 61-65:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC30d2b3d44d88428ce9f20948b9adab7efc647c83b1f57a2e931adb094d53168baf7c",
      "version": "7",
      "digest": "5t7aaCw3RW4gBSnpxiGajaiwwPBMYaEr7jEJLHguDucf",
      "owner": {
        "ObjectOwner": "BFC6ac5895b0c5ba98a5934af5a1d61ea6a79e9875b6f71b87f2c7c67d7bf1f43d13c75"
      }
    }
  }
}
