processed 13 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 12-14:
//# programmable --sender A --inputs 42 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 16-18:
//# programmable --sender A --inputs 43 @B
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 20-22:
//# programmable --sender A --inputs 44
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: sui::transfer::public_share_object<sui::coin::Coin<sui::sui::SUI>>(Result(0))
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: LINKER_ERROR, sub_status: None, message: Some("Cannot find ModuleId { address: sui, name: Identifier(\"sui\") } in data cache"), exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(1) } }

task 4, lines 24-26:
//# programmable --sender A --inputs 45
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: sui::transfer::public_freeze_object<sui::coin::Coin<sui::sui::SUI>>(Result(0))
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: LINKER_ERROR, sub_status: None, message: Some("Cannot find ModuleId { address: sui, name: Identifier(\"sui\") } in data cache"), exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(1) } }

task 5, lines 28-30:
//# programmable --sender A --inputs @A
//> 0: sui::table::new<u64, u64>();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2652400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6, lines 32-33:
//# programmable --sender A --inputs object(5,0) 46 47
//> 0: sui::table::add<u64, u64>(Input(0), Input(1), Input(2))
created: object(6,0)
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 4119200,  storage_rebate: 2625876, non_refundable_storage_fee: 26524

task 7, line 35:
//# create-checkpoint
Checkpoint created: 1

task 8, lines 37-41:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC3b7914be876df3190b7ea4389bd18d716fc22f21e5e0f41505ebb2a08b0b7189021f",
      "version": "2",
      "digest": "8nx6yb4R7iPuQUnZAbKS5ssSiokvsQ1JuMWoMDgEZ9ja",
      "owner": {
        "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
      }
    }
  }
}

task 9, lines 43-47:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFCc82806c4a23718aff09fbbbd660cdae21e458da15cbdf8134a647988c7d5ff53cd14",
      "version": "3",
      "digest": "75VtMGNrR2pLiogr2k981MbM85fbc2dL9exs8AQcciYg",
      "owner": {
        "AddressOwner": "BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9"
      }
    }
  }
}

task 10, lines 49-53:
//# run-jsonrpc
Error: Unknown variable: obj_3_0
Allowed variable mappings are {
    "A": "@A",
    "A_opt": "@A",
    "B": "@B",
    "B_opt": "@B",
    "bfc_system": "0xc8",
    "bfc_system_opt": "0xc8",
    "bridge": "0xb",
    "bridge_opt": "0xb",
    "digest_1": "Antz3FzDFhTxEx8egBfshgn8CMpwwbu5Uoe6LWhwxvGk",
    "digest_2": "CNHMt5ySwitEYyheYAvKqCoUHVbJveXEJMXjQKBg7RBQ",
    "digest_3": "5jgvVAUj5HwZtjbypkEVxfmM1GUNBNyntJoTbXd5chD",
    "digest_4": "BnUW6EusND9ZKyaAsLkqKCYAbkrzo4LYATCbDVnnbGzF",
    "digest_5": "G37yXViUBhWPJAahk1SHtQEF4LbhbkQXHgJJnmxZSjP4",
    "digest_6": "8dfWXEqV8jSesLbmUDkypVmiraNKViHXw5qWch99GijT",
    "obj_0_0": "object(0,0)",
    "obj_0_0_opt": "object(0,0)",
    "obj_0_1": "object(0,1)",
    "obj_0_1_opt": "object(0,1)",
    "obj_0_2": "object(0,2)",
    "obj_0_2_opt": "object(0,2)",
    "obj_1_0": "object(1,0)",
    "obj_1_0_opt": "object(1,0)",
    "obj_2_0": "object(2,0)",
    "obj_2_0_opt": "object(2,0)",
    "obj_5_0": "object(5,0)",
    "obj_5_0_opt": "object(5,0)",
    "obj_6_0": "object(6,0)",
    "obj_6_0_opt": "object(6,0)",
    "std": "0x1",
    "std_opt": "0x1",
    "sui": "0x2",
    "sui_opt": "0x2",
    "sui_system": "0x3",
    "sui_system_opt": "0x3",
    "test": "0x0",
    "test_opt": "0x0",
    "validator_0": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
    "validator_0_opt": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
}

task 11, lines 55-59:
//# run-jsonrpc
Error: Unknown variable: obj_4_0
Allowed variable mappings are {
    "A": "@A",
    "A_opt": "@A",
    "B": "@B",
    "B_opt": "@B",
    "bfc_system": "0xc8",
    "bfc_system_opt": "0xc8",
    "bridge": "0xb",
    "bridge_opt": "0xb",
    "digest_1": "Antz3FzDFhTxEx8egBfshgn8CMpwwbu5Uoe6LWhwxvGk",
    "digest_2": "CNHMt5ySwitEYyheYAvKqCoUHVbJveXEJMXjQKBg7RBQ",
    "digest_3": "5jgvVAUj5HwZtjbypkEVxfmM1GUNBNyntJoTbXd5chD",
    "digest_4": "BnUW6EusND9ZKyaAsLkqKCYAbkrzo4LYATCbDVnnbGzF",
    "digest_5": "G37yXViUBhWPJAahk1SHtQEF4LbhbkQXHgJJnmxZSjP4",
    "digest_6": "8dfWXEqV8jSesLbmUDkypVmiraNKViHXw5qWch99GijT",
    "obj_0_0": "object(0,0)",
    "obj_0_0_opt": "object(0,0)",
    "obj_0_1": "object(0,1)",
    "obj_0_1_opt": "object(0,1)",
    "obj_0_2": "object(0,2)",
    "obj_0_2_opt": "object(0,2)",
    "obj_1_0": "object(1,0)",
    "obj_1_0_opt": "object(1,0)",
    "obj_2_0": "object(2,0)",
    "obj_2_0_opt": "object(2,0)",
    "obj_5_0": "object(5,0)",
    "obj_5_0_opt": "object(5,0)",
    "obj_6_0": "object(6,0)",
    "obj_6_0_opt": "object(6,0)",
    "std": "0x1",
    "std_opt": "0x1",
    "sui": "0x2",
    "sui_opt": "0x2",
    "sui_system": "0x3",
    "sui_system_opt": "0x3",
    "test": "0x0",
    "test_opt": "0x0",
    "validator_0": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
    "validator_0_opt": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
}

task 12, lines 61-65:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFCbf47a0b8a391516137451b748a2ebc0365c1ea11c4e164099b7005828b50761a29c8",
      "version": "7",
      "digest": "2DoSkBcEeRLwsCNNNvfEkuTsDCwddn4vqmn3XWzCqb6H",
      "owner": {
        "ObjectOwner": "BFC3f57ec31eca98c02fdb50057574123f36e54785527e1f2837222e743670e0d8ce976"
      }
    }
  }
}
