processed 13 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 12-14:
//# programmable --sender A --inputs 42 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 16-18:
//# programmable --sender A --inputs 43 @B
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 20-22:
//# programmable --sender A --inputs 44
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: sui::transfer::public_share_object<sui::coin::Coin<sui::sui::SUI>>(Result(0))
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: LINKER_ERROR, sub_status: None, message: Some("Cannot find ModuleId { address: sui, name: Identifier(\"sui\") } in data cache"), exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(1) } }

task 4, lines 24-26:
//# programmable --sender A --inputs 45
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: sui::transfer::public_freeze_object<sui::coin::Coin<sui::sui::SUI>>(Result(0))
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: LINKER_ERROR, sub_status: None, message: Some("Cannot find ModuleId { address: sui, name: Identifier(\"sui\") } in data cache"), exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(1) } }

task 5, lines 28-30:
//# programmable --sender A --inputs @A
//> 0: sui::table::new<u64, u64>();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2652400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6, lines 32-33:
//# programmable --sender A --inputs object(5,0) 46 47
//> 0: sui::table::add<u64, u64>(Input(0), Input(1), Input(2))
created: object(6,0)
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 4119200,  storage_rebate: 2625876, non_refundable_storage_fee: 26524

task 7, line 35:
//# create-checkpoint
Checkpoint created: 1

task 8, lines 37-41:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC7e1e2f6e95b2c922359fa573b8dc402ca4dc096423678ff2e06632db5ec3318aa62e",
      "version": "2",
      "digest": "D2hMNwRTabXJ7xHf3dqq9A2Z8zPqQFYr1MU6MRW561VQ",
      "owner": {
        "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
      }
    }
  }
}

task 9, lines 43-47:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC9a2921fd8cdfe135cf057920fcae36247c1905a7cdc0ba9245f207e4e8bdd04594b1",
      "version": "3",
      "digest": "5aBDWZd86frR6QZTRu2gjDgcQ5QrPYPoXSnBgRcMRq9o",
      "owner": {
        "AddressOwner": "BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9"
      }
    }
  }
}

task 10, lines 49-53:
//# run-jsonrpc
Error: Unknown variable: obj_3_0
Allowed variable mappings are {
    "A": "@A",
    "A_opt": "@A",
    "B": "@B",
    "B_opt": "@B",
    "bfc_system": "0xc8",
    "bfc_system_opt": "0xc8",
    "bridge": "0xb",
    "bridge_opt": "0xb",
    "digest_1": "EhuT6EVckyEoyd7nhuwfbxn5WJ3affhXob6XTDYwnELT",
    "digest_2": "EZg7GetxpuzXUhyyy3xQmW4cJJ52XGMzGZnEA3Ek4cNG",
    "digest_3": "BL2q44uAYwVf25g7fqbVeRe6B2osX8bY8a4CwKgbaAkw",
    "digest_4": "H5KjPm1MaSo7GmTgGz7zH12V4mBAXBCXDcrCXKDKtWe",
    "digest_5": "F5LQYRrb81sMm6ZAiYEJAoVJzDCqA9pXLSvvZz38nBzZ",
    "digest_6": "9ruWHgwLXaMkwH8U85vLZKM74p4QTSr2yCRermoVjefY",
    "obj_0_0": "object(0,0)",
    "obj_0_0_opt": "object(0,0)",
    "obj_0_1": "object(0,1)",
    "obj_0_1_opt": "object(0,1)",
    "obj_0_2": "object(0,2)",
    "obj_0_2_opt": "object(0,2)",
    "obj_1_0": "object(1,0)",
    "obj_1_0_opt": "object(1,0)",
    "obj_2_0": "object(2,0)",
    "obj_2_0_opt": "object(2,0)",
    "obj_5_0": "object(5,0)",
    "obj_5_0_opt": "object(5,0)",
    "obj_6_0": "object(6,0)",
    "obj_6_0_opt": "object(6,0)",
    "std": "0x1",
    "std_opt": "0x1",
    "sui": "0x2",
    "sui_opt": "0x2",
    "sui_system": "0x3",
    "sui_system_opt": "0x3",
    "test": "0x0",
    "test_opt": "0x0",
    "validator_0": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
    "validator_0_opt": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
}

task 11, lines 55-59:
//# run-jsonrpc
Error: Unknown variable: obj_4_0
Allowed variable mappings are {
    "A": "@A",
    "A_opt": "@A",
    "B": "@B",
    "B_opt": "@B",
    "bfc_system": "0xc8",
    "bfc_system_opt": "0xc8",
    "bridge": "0xb",
    "bridge_opt": "0xb",
    "digest_1": "EhuT6EVckyEoyd7nhuwfbxn5WJ3affhXob6XTDYwnELT",
    "digest_2": "EZg7GetxpuzXUhyyy3xQmW4cJJ52XGMzGZnEA3Ek4cNG",
    "digest_3": "BL2q44uAYwVf25g7fqbVeRe6B2osX8bY8a4CwKgbaAkw",
    "digest_4": "H5KjPm1MaSo7GmTgGz7zH12V4mBAXBCXDcrCXKDKtWe",
    "digest_5": "F5LQYRrb81sMm6ZAiYEJAoVJzDCqA9pXLSvvZz38nBzZ",
    "digest_6": "9ruWHgwLXaMkwH8U85vLZKM74p4QTSr2yCRermoVjefY",
    "obj_0_0": "object(0,0)",
    "obj_0_0_opt": "object(0,0)",
    "obj_0_1": "object(0,1)",
    "obj_0_1_opt": "object(0,1)",
    "obj_0_2": "object(0,2)",
    "obj_0_2_opt": "object(0,2)",
    "obj_1_0": "object(1,0)",
    "obj_1_0_opt": "object(1,0)",
    "obj_2_0": "object(2,0)",
    "obj_2_0_opt": "object(2,0)",
    "obj_5_0": "object(5,0)",
    "obj_5_0_opt": "object(5,0)",
    "obj_6_0": "object(6,0)",
    "obj_6_0_opt": "object(6,0)",
    "std": "0x1",
    "std_opt": "0x1",
    "sui": "0x2",
    "sui_opt": "0x2",
    "sui_system": "0x3",
    "sui_system_opt": "0x3",
    "test": "0x0",
    "test_opt": "0x0",
    "validator_0": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
    "validator_0_opt": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
}

task 12, lines 61-65:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC75b9448169c3f2e659ca8276e7c2e07359d38a0f99d3978e99210bae96afb20bafe4",
      "version": "7",
      "digest": "8UAGsJ5DYpC1HJnoLE5KhfL6at2opzhsd5KNLjC5dv5B",
      "owner": {
        "ObjectOwner": "BFC6ff79b3fedb7ba197b65347011588dbf1d276a613ccf4a0bcb4d6720251f9a85a7d6"
      }
    }
  }
}
