processed 11 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 9-11:
//# programmable --sender A --inputs 42 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 13-15:
//# programmable --sender A --inputs 43 @B
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 17-19:
//# programmable --sender A --inputs 44
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: sui::transfer::public_share_object<sui::coin::Coin<sui::sui::SUI>>(Result(0))
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: LINKER_ERROR, sub_status: None, message: Some("Cannot find ModuleId { address: sui, name: Identifier(\"sui\") } in data cache"), exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(1) } }

task 4, lines 21-23:
//# programmable --sender A --inputs 45
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: sui::transfer::public_freeze_object<sui::coin::Coin<sui::sui::SUI>>(Result(0))
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: LINKER_ERROR, sub_status: None, message: Some("Cannot find ModuleId { address: sui, name: Identifier(\"sui\") } in data cache"), exec_state: None, location: Undefined, indices: [], offsets: [] }), command: Some(1) } }

task 5, lines 25-27:
//# programmable --sender A --inputs @A
//> 0: sui::table::new<u64, u64>();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2652400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6, lines 29-30:
//# programmable --sender A --inputs object(5,0) 46 47
//> 0: sui::table::add<u64, u64>(Input(0), Input(1), Input(2))
created: object(6,0)
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 4119200,  storage_rebate: 2625876, non_refundable_storage_fee: 26524

task 7, lines 32-33:
//# programmable --sender A --inputs object(5,0) 46
//> 0: sui::table::remove<u64, u64>(Input(0), Input(1))
mutated: object(0,0), object(5,0)
deleted: object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 2652400,  storage_rebate: 4078008, non_refundable_storage_fee: 41192

task 8, line 35:
//# create-checkpoint
Checkpoint created: 1

task 9, lines 37-52:
//# run-jsonrpc
Error: Unknown variable: obj_4_0
Allowed variable mappings are {
    "A": "@A",
    "A_opt": "@A",
    "B": "@B",
    "B_opt": "@B",
    "bfc_system": "0xc8",
    "bfc_system_opt": "0xc8",
    "bridge": "0xb",
    "bridge_opt": "0xb",
    "digest_1": "9UMTuHchq1WCHwNNADp21wRNL7zsM9UTJZ7Xsnwo4rhy",
    "digest_2": "APSkLmf8R3XCrXGuP4ph6imFVbH4rPduqqmPecaR1yxC",
    "digest_3": "4p5iXWmaGYDR6ZccYjMP3cVDNBVjByWEyH3wqLqsDyEg",
    "digest_4": "46on87zwgpz2PXRo6ooTyTEQ9AqXWWGwYZCwQHFAefCZ",
    "digest_5": "5YLk7nYZ74K98RA6FeQtm5XqujX3wp32fF4vxzv6Qs6x",
    "digest_6": "A4DwxoDtdTtZQRZ7SGK11o1Y7DJSj6w9SSsYeYgiBsPr",
    "digest_7": "CrxwQovVhtehhrEWuvUUvcEjJ3NWfX1v5VVu14YpuEzs",
    "obj_0_0": "object(0,0)",
    "obj_0_0_opt": "object(0,0)",
    "obj_0_1": "object(0,1)",
    "obj_0_1_opt": "object(0,1)",
    "obj_0_2": "object(0,2)",
    "obj_0_2_opt": "object(0,2)",
    "obj_1_0": "object(1,0)",
    "obj_1_0_opt": "object(1,0)",
    "obj_2_0": "object(2,0)",
    "obj_2_0_opt": "object(2,0)",
    "obj_5_0": "object(5,0)",
    "obj_5_0_opt": "object(5,0)",
    "obj_6_0": "object(6,0)",
    "obj_6_0_opt": "object(6,0)",
    "std": "0x1",
    "std_opt": "0x1",
    "sui": "0x2",
    "sui_opt": "0x2",
    "sui_system": "0x3",
    "sui_system_opt": "0x3",
    "test": "0x0",
    "test_opt": "0x0",
    "validator_0": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
    "validator_0_opt": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
}

task 10, lines 54-75:
//# run-jsonrpc
Error: Unknown variable: obj_4_0
Allowed variable mappings are {
    "A": "@A",
    "A_opt": "@A",
    "B": "@B",
    "B_opt": "@B",
    "bfc_system": "0xc8",
    "bfc_system_opt": "0xc8",
    "bridge": "0xb",
    "bridge_opt": "0xb",
    "digest_1": "9UMTuHchq1WCHwNNADp21wRNL7zsM9UTJZ7Xsnwo4rhy",
    "digest_2": "APSkLmf8R3XCrXGuP4ph6imFVbH4rPduqqmPecaR1yxC",
    "digest_3": "4p5iXWmaGYDR6ZccYjMP3cVDNBVjByWEyH3wqLqsDyEg",
    "digest_4": "46on87zwgpz2PXRo6ooTyTEQ9AqXWWGwYZCwQHFAefCZ",
    "digest_5": "5YLk7nYZ74K98RA6FeQtm5XqujX3wp32fF4vxzv6Qs6x",
    "digest_6": "A4DwxoDtdTtZQRZ7SGK11o1Y7DJSj6w9SSsYeYgiBsPr",
    "digest_7": "CrxwQovVhtehhrEWuvUUvcEjJ3NWfX1v5VVu14YpuEzs",
    "obj_0_0": "object(0,0)",
    "obj_0_0_opt": "object(0,0)",
    "obj_0_1": "object(0,1)",
    "obj_0_1_opt": "object(0,1)",
    "obj_0_2": "object(0,2)",
    "obj_0_2_opt": "object(0,2)",
    "obj_1_0": "object(1,0)",
    "obj_1_0_opt": "object(1,0)",
    "obj_2_0": "object(2,0)",
    "obj_2_0_opt": "object(2,0)",
    "obj_5_0": "object(5,0)",
    "obj_5_0_opt": "object(5,0)",
    "obj_6_0": "object(6,0)",
    "obj_6_0_opt": "object(6,0)",
    "std": "0x1",
    "std_opt": "0x1",
    "sui": "0x2",
    "sui_opt": "0x2",
    "sui_system": "0x3",
    "sui_system_opt": "0x3",
    "test": "0x0",
    "test_opt": "0x0",
    "validator_0": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
    "validator_0_opt": "0xfbc51a8acf096f86198d5fa470620ed6a20abc09b94ea891ef029a5de3f39713",
}
