processed 12 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 14-16:
//# programmable --sender A --inputs 42 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 18-20:
//# programmable --sender A --inputs 43 object(1,0)
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: MergeCoins(Input(1), [Result(0)])
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 2588256, non_refundable_storage_fee: 26144

task 3, lines 22-23:
//# programmable --sender A --inputs object(1,0)
//> 0: MergeCoins(Gas, [Input(0)])
mutated: object(0,0)
deleted: object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 2588256, non_refundable_storage_fee: 26144

task 4, line 25:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 27-31:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "status": "VersionNotFound",
    "details": [
      "BFC63c41d4634cff8bec9b984c247a8477854148c6029b21a960b6ab4c9a36ccbcb9e40",
      1
    ]
  }
}

task 6, lines 33-37:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC63c41d4634cff8bec9b984c247a8477854148c6029b21a960b6ab4c9a36ccbcb9e40",
      "version": "2",
      "digest": "3XD8vk945P5UT4DEpNrJhBQ9yeDRhLKJWg24R4EkVrSf"
    }
  }
}

task 7, lines 39-43:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC63c41d4634cff8bec9b984c247a8477854148c6029b21a960b6ab4c9a36ccbcb9e40",
      "version": "3",
      "digest": "DVQsEE9F2fPchA6xasWpJZVcZAVWFf8oqKQbGzHZMj3R"
    }
  }
}

task 8, lines 45-49:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "status": "ObjectDeleted",
    "details": {
      "objectId": "BFC63c41d4634cff8bec9b984c247a8477854148c6029b21a960b6ab4c9a36ccbcb9e40",
      "version": 4,
      "digest": "7gyGAp71YXQRoxmFBaHxofQXAipvgHyBKPyxmdSJxyvz"
    }
  }
}

task 9, lines 51-64:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "status": "VersionNotFound",
    "details": [
      "BFC63c41d4634cff8bec9b984c247a8477854148c6029b21a960b6ab4c9a36ccbcb9e40",
      1
    ]
  }
}

task 10, lines 66-79:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 5,
  "result": {
    "status": "VersionFound",
    "details": {
      "objectId": "BFC63c41d4634cff8bec9b984c247a8477854148c6029b21a960b6ab4c9a36ccbcb9e40",
      "version": "2",
      "digest": "3XD8vk945P5UT4DEpNrJhBQ9yeDRhLKJWg24R4EkVrSf",
      "type": "0x2::coin::Coin<0x2::bfc::BFC>",
      "owner": {
        "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
      },
      "previousTransaction": "8gKLc4fDzTpSrAStKpgcFvJVGjFZwrU8tj3cdSKQNNGp",
      "storageRebate": "1307200"
    }
  }
}

task 11, lines 81-94:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 6,
  "result": {
    "status": "ObjectDeleted",
    "details": {
      "objectId": "BFC63c41d4634cff8bec9b984c247a8477854148c6029b21a960b6ab4c9a36ccbcb9e40",
      "version": 4,
      "digest": "7gyGAp71YXQRoxmFBaHxofQXAipvgHyBKPyxmdSJxyvz"
    }
  }
}
