processed 6 tasks

task 1, lines 6-33:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7501200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 35:
//# run tto::M1::start
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3739200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 37-40:
//# programmable --inputs object(2,0) receiving(2,1)
//> tto::M1::send_back(Input(0), Input(1))
// Include the receiving argument, but don't use it at the PTB level
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 3739200,  storage_rebate: 3701808, non_refundable_storage_fee: 37392

task 4, lines 41-45:
//# programmable --inputs object(2,0) receiving(2,1)
//> tto::M1::nop(Input(0))
// Include the receiving argument, but don't use it at the Move level. The
// receiving object should not be mutated by this.
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 2497968, non_refundable_storage_fee: 25232

task 5, lines 46-47:
//# programmable --inputs object(2,0) receiving(2,1)
//> tto::M1::nop_with_receiver(Input(0), Input(1))
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 2497968, non_refundable_storage_fee: 25232
