processed 6 tasks

task 1 'publish'. lines 6-33:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 750120,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 35-35:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 373920,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 3 'programmable'. lines 37-40:
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 373920,  storage_rebate: 370181, non_refundable_storage_fee: 3739

task 4 'programmable'. lines 41-45:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 252320,  storage_rebate: 249797, non_refundable_storage_fee: 2523

task 5 'programmable'. lines 46-47:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 252320,  storage_rebate: 249797, non_refundable_storage_fee: 2523
