processed 12 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-34:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 410020,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 36-36:
created: object(2,0), object(2,1), object(2,2), object(2,3)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 379620,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 3 'view-object'. lines 38-38:
Owner: Object ID: ( BFCd66f4dcc0823a811ad04756b0c3ce99e2449b7ae29b1ac9e7a2303feb6d0d5299cce )
Version: 3
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,2),
    },
}

task 4 'view-object'. lines 40-40:
Owner: Shared
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 5 'view-object'. lines 42-42:
Owner: Object ID: ( BFCa4cfb3ba5307577bbe6202c4b3689e9a0ff1405b7ac082dbf4070ad850900d8d4218 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 0u64,
}

task 6 'view-object'. lines 44-44:
Owner: Account Address ( BFC3ebd18ccc63a44441240ff596b1690c7fa536a609e160ede13fbb7c9365c24ca90a5 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
    value: 0u64,
}

task 7 'run'. lines 46-46:
created: object(7,0)
mutated: object(0,1), object(2,1), object(2,3)
gas summary: computation_cost: 1000000, storage_cost: 315780,  storage_rebate: 191110, non_refundable_storage_fee: 1930

task 8 'view-object'. lines 48-48:
Owner: Object ID: ( BFCd66f4dcc0823a811ad04756b0c3ce99e2449b7ae29b1ac9e7a2303feb6d0d5299cce )
Version: 3
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,2),
    },
}

task 9 'view-object'. lines 50-50:
Owner: Shared
Version: 4
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 10 'view-object'. lines 52-52:
Owner: Object ID: ( BFCa4cfb3ba5307577bbe6202c4b3689e9a0ff1405b7ac082dbf4070ad850900d8d4218 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 0u64,
}

task 11 'view-object'. lines 54-54:
Owner: Object ID: ( BFC1301816a7a5291393a7a424763e0a82bd3f5c7534c9959ef3956c9824ff1bd030716 )
Version: 4
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
    value: 100u64,
}
