processed 13 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-37:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 375060,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 39-39:
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 186960,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 3 'run'. lines 41-41:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 126160,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'view-object'. lines 43-43:
Owner: Shared
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 5 'view-object'. lines 45-47:
Owner: Account Address ( BFC5898b5b6250e2d10ee260a3f1b8d2b5d96f26b3ed0c359ee6d43d4c3c4df1f7e1a7e )
Version: 3
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 6 'run'. lines 48-48:
mutated: object(0,1), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 186960,  storage_rebate: 185090, non_refundable_storage_fee: 1870

task 7 'view-object'. lines 50-50:
Owner: Shared
Version: 4
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 8 'view-object'. lines 52-54:
Owner: Account Address ( BFC5898b5b6250e2d10ee260a3f1b8d2b5d96f26b3ed0c359ee6d43d4c3c4df1f7e1a7e )
Version: 4
Contents: tto::M1::B {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 9 'run'. lines 55-57:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::receive_impl (function index 12) at offset 0, Abort Code: 3
Debug of error: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 12, instruction: 0, function_name: Some("receive_impl") }, 3) at command Some(0)

task 10 'run'. lines 58-60:
mutated: object(0,1), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 186960,  storage_rebate: 185090, non_refundable_storage_fee: 1870

task 11 'run'. lines 61-63:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::receive_impl (function index 12) at offset 0, Abort Code: 3
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 12, instruction: 0, function_name: Some("receive_impl") }, 3), source: Some(VMError { major_status: ABORTED, sub_status: Some(3), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("transfer") }), indices: [], offsets: [(FunctionDefinitionIndex(12), 0)] }), command: Some(0) } }

task 12 'run'. lines 64-64:
mutated: object(0,1), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 186960,  storage_rebate: 185090, non_refundable_storage_fee: 1870
