processed 12 tasks

init:
A: object(0,0)

task 1, lines 6-34:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8200400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 36:
//# run tto::M1::start
created: object(2,0), object(2,1), object(2,2), object(2,3)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7592400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 38:
//# view-object 2,0
Owner: Object ID: ( BFC40f4c968966718d0d7d27c89b313f5367915981f0bc09f1be17ae07224706f07b78f )
Version: 3
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,3),
    },
}

task 4, line 40:
//# view-object 2,1
Owner: Shared( 3 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 5, line 42:
//# view-object 2,2
Owner: Account Address ( BFC2a26de2bdfd43b295b8515934b65868a66994c5c18a05b9d9010577c6f01cd96a40d )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 0u64,
}

task 6, line 44:
//# view-object 2,3
Owner: Object ID: ( BFC2c87b822cf0a9d7d905c8251e495aa5633c2f58af6efd43bce42b6c85dd0eb52304e )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
    value: 0u64,
}

task 7, line 46:
//# run tto::M1::receive --args object(2,1) receiving(2,3)
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(2,3), parent_id: object(2,0) }

task 8, line 48:
//# view-object 2,0
Owner: Object ID: ( BFC40f4c968966718d0d7d27c89b313f5367915981f0bc09f1be17ae07224706f07b78f )
Version: 3
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,3),
    },
}

task 9, line 50:
//# view-object 2,1
Owner: Shared( 3 )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 10, line 52:
//# view-object 2,2
Owner: Account Address ( BFC2a26de2bdfd43b295b8515934b65868a66994c5c18a05b9d9010577c6f01cd96a40d )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 0u64,
}

task 11, line 54:
//# view-object 2,3
Owner: Object ID: ( BFC2c87b822cf0a9d7d905c8251e495aa5633c2f58af6efd43bce42b6c85dd0eb52304e )
Version: 3
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
    value: 0u64,
}
