packages:
  - 'apps/**'
  - 'sdk/typescript'
  - 'sdk/ledgerjs-hw-app-sui'
  - 'sdk/build-scripts'
  - '!sdk/typescript/bcs'
  - '!sdk/typescript/client'
  - '!sdk/typescript/cryptography'
  - '!sdk/typescript/faucet'
  - '!sdk/typescript/graphql'
  - '!sdk/typescript/multisig'
  - '!sdk/typescript/transactions'
  - '!sdk/typescript/utils'
  - '!sdk/typescript/verify'
  - '!sdk/typescript/dapp-kit'
  - '!sdk/typescript/wallet-standard'
  - '!sdk/typescript/wallet-kit-core'
  - '!sdk/typescript/zklogin'
