packages:
  - 'sdk/**'
  - 'apps/**'
  - 'dapps/**'
  - 'examples/**'
  - '!**/dist/**'
  - '!**/.next/**'
  - '!sdk/create-dapp/templates'
  - '!sdk/typescript/scripts'
  - '!sdk/typescript/transactions'
  - '!sdk/typescript/cryptography'
  - '!sdk/typescript/faucet'
  - '!sdk/typescript/transactions'
  - '!sdk/typescript/client'
  - '!sdk/typescript/verify'
  - '!sdk/typescript/multisig'
  - '!sdk/typescript/utils'
  - '!sdk/typescript/bcs'
  - '!sdk/typescript/dapp-kit'
  - '!sdk/typescript/wallet-standard'
  - '!sdk/typescript/wallet-kit-core'
  - '!sdk/typescript/zklogin'
  - '!sdk/typescript/graphql'
  - '!sdk/typescript/keypairs/ed25519'
  - '!sdk/typescript/keypairs/secp256k1'
  - '!sdk/typescript/keypairs/secp256r1'
  - '!sdk/typescript/graphql/schemas/2024.1'
  - '!sdk/typescript/graphql/schemas/2024.4'
