packages:
  - 'sdk/**'
  - 'apps/**'
  - 'dapps/**'
  - '!**/dist/**'
  - '!**/.next/**'
  - '!sdk/create-dapp/templates'
  - '!sdk/typescript/*/**'
  - '!sdk/typescript/scripts'
  - '!sdk/typescript/transactions'
  - '!sdk/typescript/cryptography'
  - '!sdk/typescript/faucet'
  - '!sdk/typescript/transactions'
  - '!sdk/typescript/client'
  - '!sdk/typescript/verify'
  - '!sdk/typescript/multisig'
  - '!sdk/typescript/utils'
  - '!sdk/typescript/bcs'
<<<<<<< HEAD
  - '!sdk/typescript/dapp-kit'
  - '!sdk/typescript/wallet-standard'
  - '!sdk/typescript/wallet-kit-core'
=======
  - '!sdk/typescript/zklogin'
  - '!sdk/enoki/react'
  - '!sdk/move-bytecode-template/pkg'
  - '!sdk/move-bytecode-template/pkg'
  - '!sdk/typescript/graphql'
>>>>>>> mainnet-v1.24.1
