processed 6 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 10-70:
created: object(1,0)
mutated: object(0,3)
gas summary: computation_cost: 1000000, storage_cost: 8702000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 72-72:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 74-74:
created: object(3,0), object(3,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6178800,  storage_rebate: 2490444, non_refundable_storage_fee: 25156

task 4 'view-object'. lines 76-76:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}}

task 5 'run'. lines 78-78:
mutated: object(0,0)
deleted: object(2,0), object(3,0), object(3,1)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 6117012, non_refundable_storage_fee: 61788
