processed 6 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-33:
created: object(1,0)
mutated: object(0,3)
gas summary: computation_cost: 100000, storage_cost: 634600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 35-35:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 251560,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 37-37:
created: object(3,0), object(3,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 100000, storage_cost: 617880,  storage_rebate: 249044, non_refundable_storage_fee: 2516

task 4 'view-object'. lines 39-39:
Owner: Account Address ( A )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}}

task 5 'run'. lines 41-41:
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 100000, storage_cost: 130720,  storage_rebate: 249044, non_refundable_storage_fee: 2516
