processed 10 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-46:
created: object(1,0)
mutated: object(0,3)
gas summary: computation_cost: 1000000, storage_cost: 364800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 48-48:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 308940,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 50-54:
Owner: Object ID: ( BFCfaeccb41267e22d3ab0fb5f7d68cd66a0bed90e7d01af7ec074601d57f016ae82968 )
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 4 'run'. lines 56-56:
created: object(4,0), object(4,1), object(4,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 308940,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 5 'run'. lines 58-58:
mutated: object(0,0), object(4,2)
gas summary: computation_cost: 1000000, storage_cost: 125780,  storage_rebate: 124522, non_refundable_storage_fee: 1258

task 6 'view-object'. lines 60-64:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 4
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(4,2)}}}

task 7 'run'. lines 66-66:
created: object(7,0), object(7,1), object(7,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 308940,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 8 'transfer-object'. lines 68-68:
mutated: object(0,0), object(7,1)
gas summary: computation_cost: 1000000, storage_cost: 125780,  storage_rebate: 124522, non_refundable_storage_fee: 1258

task 9 'view-object'. lines 70-70:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 6
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(7,1)}}}
