processed 10 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-46:
created: object(1,0)
mutated: object(0,3)
gas summary: computation_cost: 1000000, storage_cost: 7296000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 48-48:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6178800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 50-54:
Owner: Shared
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 4 'run'. lines 56-56:
created: object(4,0), object(4,1), object(4,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6178800,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5 'run'. lines 58-58:
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: 0xd6237b8f2d738fdcc88df2982837d839e1cef58a617bef47223c102e06ad396f, parent_id: 0x0265402b3975e99677451be6f60649755166320dae9a716254cf6a45b820a302 }

task 6 'view-object'. lines 60-64:
Owner: Object ID: ( fake(4,0) )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(4,2)}}}

task 7 'run'. lines 66-66:
created: object(7,0), object(7,1), object(7,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6178800,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 8 'transfer-object'. lines 68-68:
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: 0x7748d2fa3b69efe2a5069c287b52e8f3478631284dc685868504932cf065ab57, parent_id: 0x79bf3776247112d863ad58301954ff782958b1474fbede4149eb2e7f1d78548f }

task 9 'view-object'. lines 70-70:
Owner: Object ID: ( fake(7,0) )
Version: 4
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(7,1)}}}
