processed 4 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-38:
created: object(1,0)
mutated: object(0,3)
gas summary: computation_cost: 100000, storage_cost: 63916,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 40-40:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 27588,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 42-42:
mutated: object(0,0)
unwrapped: object(3,0)
deleted: object(2,0)
gas summary: computation_cost: 100000, storage_cost: 25156,  storage_rebate: 27312, non_refundable_storage_fee: 276
