processed 4 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-39:
created: object(1,0)
mutated: object(0,3)
gas summary: computation_cost: 1000000, storage_cost: 6156000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 41-41:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2758800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 43-43:
mutated: object(0,0)
deleted: object(2,0)
unwrapped_then_deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 2731212, non_refundable_storage_fee: 27588
