processed 5 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-45:
created: object(1,0)
mutated: object(0,3)
gas summary: computation_cost: 1000000, storage_cost: 7007200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 47-47:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 49-49:
created: object(3,0), object(3,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6178800,  storage_rebate: 2490444, non_refundable_storage_fee: 25156

task 4 'run'. lines 51-51:
created: object(4,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2758800,  storage_rebate: 2490444, non_refundable_storage_fee: 25156
