processed 17 tasks

task 1, lines 8-30:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "digest": "9MhvZniBXmBU32ma6BGK8nW8hEjDiij7kcobb4q2Kk4T",
        "sequenceNumber": 0
      },
      "last": {
        "digest": "9MhvZniBXmBU32ma6BGK8nW8hEjDiij7kcobb4q2Kk4T",
        "sequenceNumber": 0
      }
    },
    "first": {
      "digest": "9MhvZniBXmBU32ma6BGK8nW8hEjDiij7kcobb4q2Kk4T",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "9MhvZniBXmBU32ma6BGK8nW8hEjDiij7kcobb4q2Kk4T",
      "sequenceNumber": 0
    }
  }
}

task 3, line 34:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 36-46:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "sequenceNumber": 0
      },
      "last": {
        "sequenceNumber": 1
      }
    }
  }
}

task 6, line 50:
//# create-checkpoint
Checkpoint created: 2

task 7, lines 52-62:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "sequenceNumber": 0
      },
      "last": {
        "sequenceNumber": 2
      }
    }
  }
}

task 9, line 66:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 68-78:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "sequenceNumber": 1
      },
      "last": {
        "sequenceNumber": 3
      }
    }
  }
}

task 12, line 82:
//# create-checkpoint
Checkpoint created: 4

task 13, lines 84-94:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "sequenceNumber": 2
      },
      "last": {
        "sequenceNumber": 4
      }
    }
  }
}

task 15, line 98:
//# create-checkpoint
Checkpoint created: 5

task 16, lines 100-120:
//# run-graphql
Response: {
  "data": {
    "availableRange": {
      "first": {
        "sequenceNumber": 3
      },
      "last": {
        "sequenceNumber": 5
      }
    },
    "first": {
      "digest": "9MhvZniBXmBU32ma6BGK8nW8hEjDiij7kcobb4q2Kk4T",
      "sequenceNumber": 0
    },
    "last": {
      "digest": "C9zN8NLLv3rNyf2w39Yt6UryjfaC6hsLx2L5kp68ACGJ",
      "sequenceNumber": 5
    }
  }
}
