processed 4 tasks

init:
A: object(0,0)

task 1, lines 6-33:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 15982800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 35:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 37-85:
//# run-graphql
Response: {
  "data": {
    "suiCoins": {
      "edges": [
        {
          "cursor": "IJa/ViAH2UoEZeNibQpwj2dEnJxs3baMLiVYgOflkLHYAQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
              }
            }
          }
        },
        {
          "cursor": "IMGP5R5ksxKXMS6Y42OgPyAYvLhioCh2OzR76kF19Cr6AQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983017200",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
              }
            }
          }
        },
        {
          "cursor": "IPTAV9ZngP5B5XtFRmykDZK4Ix0ZQXaRu9toQuKeYPDNAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "IEzgIR/E0KUYPZIaEy+7b3JZXyjqdp3Gu4/YcWEkWfMTAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xaad79abe6412a40fa5924c40f2c272f05a1c56722de3c9169c8c21ccff6c3e64::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IKNWxubfkOlLkolbf26+n5tEtT4mrTdgKYrkhuy1JP0CAQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xaad79abe6412a40fa5924c40f2c272f05a1c56722de3c9169c8c21ccff6c3e64::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "ILYl1TDiut29LSI3582g1S7F5uoe4P7D43qxlByGLZoTAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xaad79abe6412a40fa5924c40f2c272f05a1c56722de3c9169c8c21ccff6c3e64::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "IMGP5R5ksxKXMS6Y42OgPyAYvLhioCh2OzR76kF19Cr6AQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983017200",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpiZmM6OkJGQyIsImMiOjF9",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983017200"
            }
          },
          {
            "cursor": "eyJ0IjoiMHhhYWQ3OWFiZTY0MTJhNDBmYTU5MjRjNDBmMmMyNzJmMDVhMWM1NjcyMmRlM2M5MTY5YzhjMjFjY2ZmNmMzZTY0OjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0xaad79abe6412a40fa5924c40f2c272f05a1c56722de3c9169c8c21ccff6c3e64::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpiZmM6OkJGQyIsImMiOjF9"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHhhYWQ3OWFiZTY0MTJhNDBmYTU5MjRjNDBmMmMyNzJmMDVhMWM1NjcyMmRlM2M5MTY5YzhjMjFjY2ZmNmMzZTY0OjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
