processed 4 tasks

init:
A: object(0,0)

task 1, lines 6-33:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 15982800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 35:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 37-85:
//# run-graphql
Response: {
  "data": {
    "suiCoins": {
      "edges": [
        {
          "cursor": "ICMtsg/qbX5pTRZyyE75MzHctzMlAf3qYIM4uGQquvEfAQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
              }
            }
          }
        },
        {
          "cursor": "IDOndvV5J4fSkOyjx+pSodppRbAXPQp2zFwNt3UF8rHgAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
              }
            }
          }
        },
        {
          "cursor": "IJ8jnHxiAzgk2SxtF6lsMI5mgzyYtCkhYevqltFR67j2AQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983017200",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "IFkmoFEKOZ4n/ljEWHGx9kIFXeLVBIbxQbf3DaShgyZNAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xe057c3dee0c75b22015c6c9dbf0a180b9c156e585cbd81b7e91e2a493894a098::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "ILEoeHTpsnccPL1X8BGXfkt7EBbtM+fF2GBevsTUQ3oyAQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xe057c3dee0c75b22015c6c9dbf0a180b9c156e585cbd81b7e91e2a493894a098::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IO0XkveNtq4tD94LKyBWNYZUFxQA904vsU6hScvfEnedAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0xe057c3dee0c75b22015c6c9dbf0a180b9c156e585cbd81b7e91e2a493894a098::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "IJ8jnHxiAzgk2SxtF6lsMI5mgzyYtCkhYevqltFR67j2AQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983017200",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpiZmM6OkJGQyIsImMiOjF9",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983017200"
            }
          },
          {
            "cursor": "eyJ0IjoiMHhlMDU3YzNkZWUwYzc1YjIyMDE1YzZjOWRiZjBhMTgwYjljMTU2ZTU4NWNiZDgxYjdlOTFlMmE0OTM4OTRhMDk4OjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0xe057c3dee0c75b22015c6c9dbf0a180b9c156e585cbd81b7e91e2a493894a098::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpiZmM6OkJGQyIsImMiOjF9"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHhlMDU3YzNkZWUwYzc1YjIyMDE1YzZjOWRiZjBhMTgwYjljMTU2ZTU4NWNiZDgxYjdlOTFlMmE0OTM4OTRhMDk4OjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
