processed 5 tasks

init:
A: object(0,0)

task 1, lines 6-39:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7942000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 41-43:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3230000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 45:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 47-68:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xb2a27e2f6050796650ad914385d0bb8249dca1ab29030dd9e74c154140dfb4cd::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  35,
                                  82,
                                  221,
                                  39,
                                  96,
                                  117,
                                  246,
                                  194,
                                  114,
                                  24,
                                  68,
                                  221,
                                  160,
                                  104,
                                  14,
                                  57,
                                  2,
                                  144,
                                  217,
                                  167,
                                  58,
                                  77,
                                  142,
                                  97,
                                  71,
                                  211,
                                  189,
                                  152,
                                  99,
                                  84,
                                  62,
                                  229
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  35,
                                  82,
                                  221,
                                  39,
                                  96,
                                  117,
                                  246,
                                  194,
                                  114,
                                  24,
                                  68,
                                  221,
                                  160,
                                  104,
                                  14,
                                  57,
                                  2,
                                  144,
                                  217,
                                  167,
                                  58,
                                  77,
                                  142,
                                  97,
                                  71,
                                  211,
                                  189,
                                  152,
                                  99,
                                  84,
                                  62,
                                  229
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      35,
                                      82,
                                      221,
                                      39,
                                      96,
                                      117,
                                      246,
                                      194,
                                      114,
                                      24,
                                      68,
                                      221,
                                      160,
                                      104,
                                      14,
                                      57,
                                      2,
                                      144,
                                      217,
                                      167,
                                      58,
                                      77,
                                      142,
                                      97,
                                      71,
                                      211,
                                      189,
                                      152,
                                      99,
                                      84,
                                      62,
                                      229
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x2352dd276075f6c2721844dda0680e390290d9a73a4d8e6147d3bd9863543ee5",
                          "f0": "0x2352dd276075f6c2721844dda0680e390290d9a73a4d8e6147d3bd9863543ee5",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x2352dd276075f6c2721844dda0680e390290d9a73a4d8e6147d3bd9863543ee5"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  150,
                                  191,
                                  86,
                                  32,
                                  7,
                                  217,
                                  74,
                                  4,
                                  101,
                                  227,
                                  98,
                                  109,
                                  10,
                                  112,
                                  143,
                                  103,
                                  68,
                                  156,
                                  156,
                                  108,
                                  221,
                                  182,
                                  140,
                                  46,
                                  37,
                                  88,
                                  128,
                                  231,
                                  229,
                                  144,
                                  177,
                                  216
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988122128"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x96bf562007d94a0465e3626d0a708f67449c9c6cddb68c2e255880e7e590b1d8",
                          "balance": {
                            "value": "299999988122128"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
