processed 5 tasks

init:
A: object(0,0)

task 1, lines 6-39:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7942000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 41-43:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3230000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 45:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 47-68:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  35,
                                  45,
                                  178,
                                  15,
                                  234,
                                  109,
                                  126,
                                  105,
                                  77,
                                  22,
                                  114,
                                  200,
                                  78,
                                  249,
                                  51,
                                  49,
                                  220,
                                  183,
                                  51,
                                  37,
                                  1,
                                  253,
                                  234,
                                  96,
                                  131,
                                  56,
                                  184,
                                  100,
                                  42,
                                  186,
                                  241,
                                  31
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988122128"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x232db20fea6d7e694d1672c84ef93331dcb7332501fdea608338b8642abaf11f",
                          "balance": {
                            "value": "299999988122128"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x933afaf8f4a3204ea5bd35ccd9659a9d24b777b005662474fa41f6a72ce58a8f::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  214,
                                  66,
                                  190,
                                  70,
                                  126,
                                  190,
                                  53,
                                  43,
                                  54,
                                  168,
                                  114,
                                  200,
                                  69,
                                  252,
                                  143,
                                  15,
                                  168,
                                  172,
                                  246,
                                  180,
                                  13,
                                  241,
                                  118,
                                  163,
                                  3,
                                  162,
                                  239,
                                  73,
                                  174,
                                  28,
                                  244,
                                  160
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  214,
                                  66,
                                  190,
                                  70,
                                  126,
                                  190,
                                  53,
                                  43,
                                  54,
                                  168,
                                  114,
                                  200,
                                  69,
                                  252,
                                  143,
                                  15,
                                  168,
                                  172,
                                  246,
                                  180,
                                  13,
                                  241,
                                  118,
                                  163,
                                  3,
                                  162,
                                  239,
                                  73,
                                  174,
                                  28,
                                  244,
                                  160
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      214,
                                      66,
                                      190,
                                      70,
                                      126,
                                      190,
                                      53,
                                      43,
                                      54,
                                      168,
                                      114,
                                      200,
                                      69,
                                      252,
                                      143,
                                      15,
                                      168,
                                      172,
                                      246,
                                      180,
                                      13,
                                      241,
                                      118,
                                      163,
                                      3,
                                      162,
                                      239,
                                      73,
                                      174,
                                      28,
                                      244,
                                      160
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0xd642be467ebe352b36a872c845fc8f0fa8acf6b40df176a303a2ef49ae1cf4a0",
                          "f0": "0xd642be467ebe352b36a872c845fc8f0fa8acf6b40df176a303a2ef49ae1cf4a0",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0xd642be467ebe352b36a872c845fc8f0fa8acf6b40df176a303a2ef49ae1cf4a0"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
