processed 5 tasks

init:
A: object(0,0)

task 1, lines 6-39:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7942000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 41-43:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3230000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 45:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 47-68:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xd476c7f49700b0144b7a04dc2569a507c764a629051416d1b627b8a964f54f60::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  36,
                                  181,
                                  173,
                                  126,
                                  93,
                                  40,
                                  204,
                                  28,
                                  245,
                                  164,
                                  180,
                                  187,
                                  24,
                                  45,
                                  44,
                                  83,
                                  159,
                                  99,
                                  56,
                                  149,
                                  148,
                                  74,
                                  219,
                                  131,
                                  254,
                                  104,
                                  184,
                                  249,
                                  185,
                                  70,
                                  24,
                                  164
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  36,
                                  181,
                                  173,
                                  126,
                                  93,
                                  40,
                                  204,
                                  28,
                                  245,
                                  164,
                                  180,
                                  187,
                                  24,
                                  45,
                                  44,
                                  83,
                                  159,
                                  99,
                                  56,
                                  149,
                                  148,
                                  74,
                                  219,
                                  131,
                                  254,
                                  104,
                                  184,
                                  249,
                                  185,
                                  70,
                                  24,
                                  164
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      36,
                                      181,
                                      173,
                                      126,
                                      93,
                                      40,
                                      204,
                                      28,
                                      245,
                                      164,
                                      180,
                                      187,
                                      24,
                                      45,
                                      44,
                                      83,
                                      159,
                                      99,
                                      56,
                                      149,
                                      148,
                                      74,
                                      219,
                                      131,
                                      254,
                                      104,
                                      184,
                                      249,
                                      185,
                                      70,
                                      24,
                                      164
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x24b5ad7e5d28cc1cf5a4b4bb182d2c539f633895944adb83fe68b8f9b94618a4",
                          "f0": "0x24b5ad7e5d28cc1cf5a4b4bb182d2c539f633895944adb83fe68b8f9b94618a4",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x24b5ad7e5d28cc1cf5a4b4bb182d2c539f633895944adb83fe68b8f9b94618a4"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  150,
                                  191,
                                  86,
                                  32,
                                  7,
                                  217,
                                  74,
                                  4,
                                  101,
                                  227,
                                  98,
                                  109,
                                  10,
                                  112,
                                  143,
                                  103,
                                  68,
                                  156,
                                  156,
                                  108,
                                  221,
                                  182,
                                  140,
                                  46,
                                  37,
                                  88,
                                  128,
                                  231,
                                  229,
                                  144,
                                  177,
                                  216
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988122128"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x96bf562007d94a0465e3626d0a708f67449c9c6cddb68c2e255880e7e590b1d8",
                          "balance": {
                            "value": "299999988122128"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
