processed 5 tasks

init:
A: object(0,0)

task 1, lines 6-54:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10830000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 56-58:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3351600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 60:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 62-83:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  51,
                                  167,
                                  118,
                                  245,
                                  121,
                                  39,
                                  135,
                                  210,
                                  144,
                                  236,
                                  163,
                                  199,
                                  234,
                                  82,
                                  161,
                                  218,
                                  105,
                                  69,
                                  176,
                                  23,
                                  61,
                                  10,
                                  118,
                                  204,
                                  92,
                                  13,
                                  183,
                                  117,
                                  5,
                                  242,
                                  177,
                                  224
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995648400"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x33a776f5792787d290eca3c7ea52a1da6945b0173d0a76cc5c0db77505f2b1e0",
                          "balance": {
                            "value": "299999995648400"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x1374b5f7925f427610f57c6bcf35347f852532d33e32ddf8b19ae01874b1cbb0::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  88,
                                  3,
                                  131,
                                  126,
                                  15,
                                  217,
                                  15,
                                  120,
                                  215,
                                  70,
                                  2,
                                  12,
                                  242,
                                  250,
                                  57,
                                  54,
                                  213,
                                  225,
                                  245,
                                  163,
                                  134,
                                  237,
                                  29,
                                  160,
                                  57,
                                  189,
                                  186,
                                  185,
                                  164,
                                  16,
                                  30,
                                  0
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  88,
                                  3,
                                  131,
                                  126,
                                  15,
                                  217,
                                  15,
                                  120,
                                  215,
                                  70,
                                  2,
                                  12,
                                  242,
                                  250,
                                  57,
                                  54,
                                  213,
                                  225,
                                  245,
                                  163,
                                  134,
                                  237,
                                  29,
                                  160,
                                  57,
                                  189,
                                  186,
                                  185,
                                  164,
                                  16,
                                  30,
                                  0
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      88,
                                      3,
                                      131,
                                      126,
                                      15,
                                      217,
                                      15,
                                      120,
                                      215,
                                      70,
                                      2,
                                      12,
                                      242,
                                      250,
                                      57,
                                      54,
                                      213,
                                      225,
                                      245,
                                      163,
                                      134,
                                      237,
                                      29,
                                      160,
                                      57,
                                      189,
                                      186,
                                      185,
                                      164,
                                      16,
                                      30,
                                      0
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x5803837e0fd90f78d746020cf2fa3936d5e1f5a386ed1da039bdbab9a4101e00",
                          "f0": "0x5803837e0fd90f78d746020cf2fa3936d5e1f5a386ed1da039bdbab9a4101e00",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x5803837e0fd90f78d746020cf2fa3936d5e1f5a386ed1da039bdbab9a4101e00"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
