processed 5 tasks

init:
A: object(0,0)

task 1, lines 6-54:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10830000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 56-58:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3351600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 60:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 62-83:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  35,
                                  45,
                                  178,
                                  15,
                                  234,
                                  109,
                                  126,
                                  105,
                                  77,
                                  22,
                                  114,
                                  200,
                                  78,
                                  249,
                                  51,
                                  49,
                                  220,
                                  183,
                                  51,
                                  37,
                                  1,
                                  253,
                                  234,
                                  96,
                                  131,
                                  56,
                                  184,
                                  100,
                                  42,
                                  186,
                                  241,
                                  31
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999995648400"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x232db20fea6d7e694d1672c84ef93331dcb7332501fdea608338b8642abaf11f",
                          "balance": {
                            "value": "299999995648400"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x1435a1e407f2f7788d878ec11f6f0be05621c9478d9c260c7fda0f8d86de1631::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  138,
                                  253,
                                  23,
                                  119,
                                  0,
                                  89,
                                  254,
                                  186,
                                  16,
                                  68,
                                  39,
                                  97,
                                  170,
                                  181,
                                  153,
                                  32,
                                  110,
                                  124,
                                  79,
                                  1,
                                  123,
                                  42,
                                  57,
                                  228,
                                  100,
                                  98,
                                  182,
                                  98,
                                  78,
                                  34,
                                  209,
                                  206
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  138,
                                  253,
                                  23,
                                  119,
                                  0,
                                  89,
                                  254,
                                  186,
                                  16,
                                  68,
                                  39,
                                  97,
                                  170,
                                  181,
                                  153,
                                  32,
                                  110,
                                  124,
                                  79,
                                  1,
                                  123,
                                  42,
                                  57,
                                  228,
                                  100,
                                  98,
                                  182,
                                  98,
                                  78,
                                  34,
                                  209,
                                  206
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      138,
                                      253,
                                      23,
                                      119,
                                      0,
                                      89,
                                      254,
                                      186,
                                      16,
                                      68,
                                      39,
                                      97,
                                      170,
                                      181,
                                      153,
                                      32,
                                      110,
                                      124,
                                      79,
                                      1,
                                      123,
                                      42,
                                      57,
                                      228,
                                      100,
                                      98,
                                      182,
                                      98,
                                      78,
                                      34,
                                      209,
                                      206
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            },
                            {
                              "name": "f8",
                              "value": {
                                "Variant": {
                                  "name": "A",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f9",
                              "value": {
                                "Variant": {
                                  "name": "B",
                                  "fields": []
                                }
                              }
                            },
                            {
                              "name": "f10",
                              "value": {
                                "Variant": {
                                  "name": "C",
                                  "fields": [
                                    {
                                      "name": "pos0",
                                      "value": {
                                        "Number": "45"
                                      }
                                    }
                                  ]
                                }
                              }
                            },
                            {
                              "name": "f11",
                              "value": {
                                "Variant": {
                                  "name": "D",
                                  "fields": [
                                    {
                                      "name": "x",
                                      "value": {
                                        "Number": "46"
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x8afd17770059feba10442761aab599206e7c4f017b2a39e46462b6624e22d1ce",
                          "f0": "0x8afd17770059feba10442761aab599206e7c4f017b2a39e46462b6624e22d1ce",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x8afd17770059feba10442761aab599206e7c4f017b2a39e46462b6624e22d1ce"
                          ],
                          "f7": 44,
                          "f8": {
                            "A": {}
                          },
                          "f9": {
                            "B": {}
                          },
                          "f10": {
                            "C": {
                              "pos0": 45
                            }
                          },
                          "f11": {
                            "D": {
                              "x": "46"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
