processed 14 tasks

task 1, lines 6-19:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5494800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 21:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 23:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 25:
//# run Test::M1::create --args 2 @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5, line 27:
//# run Test::M1::create --args 3 @A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6, line 29:
//# run Test::M1::create --args 4 @A
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 7, line 31:
//# create-checkpoint
Checkpoint created: 1

task 8, lines 33-43:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IE6zuxbaqJDvWXDtpAwRs+2F51tvknXe4VRvttkY+w8fAQAAAAAAAAA="
          },
          {
            "cursor": "IIV/GtREvOmWxGbM2H0RwY3aNGyV5PTK+obVVLUC+lMAAQAAAAAAAAA="
          },
          {
            "cursor": "IKQEx9toPEKIqqLMA4Amzh936wSYqd2Pn9z/S69uKahEAQAAAAAAAAA="
          },
          {
            "cursor": "IMmQh57fKEXS00Aq/fAMENh7Jgx13EyoaBAfi/20/J84AQAAAAAAAAA="
          },
          {
            "cursor": "IOTmfQLOBiFnRDdGCS3Nz7YjgxH82rk1ZUwkpFdJa9vsAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 9, lines 45-55:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IE6zuxbaqJDvWXDtpAwRs+2F51tvknXe4VRvttkY+w8fAQAAAAAAAAA="
          },
          {
            "cursor": "IIV/GtREvOmWxGbM2H0RwY3aNGyV5PTK+obVVLUC+lMAAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 10, lines 57-69:
//# run-graphql --cursors @{obj_5_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IKQEx9toPEKIqqLMA4Amzh936wSYqd2Pn9z/S69uKahEAQAAAAAAAAA="
          },
          {
            "cursor": "IMmQh57fKEXS00Aq/fAMENh7Jgx13EyoaBAfi/20/J84AQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 11, lines 71-81:
//# run-graphql --cursors @{obj_4_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IOTmfQLOBiFnRDdGCS3Nz7YjgxH82rk1ZUwkpFdJa9vsAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 12, lines 83-93:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IKQEx9toPEKIqqLMA4Amzh936wSYqd2Pn9z/S69uKahEAQAAAAAAAAA="
          },
          {
            "cursor": "IMmQh57fKEXS00Aq/fAMENh7Jgx13EyoaBAfi/20/J84AQAAAAAAAAA="
          }
        ]
      }
    }
  }
}

task 13, lines 95-104:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "cursor": "IMmQh57fKEXS00Aq/fAMENh7Jgx13EyoaBAfi/20/J84AQAAAAAAAAA="
          },
          {
            "cursor": "IOTmfQLOBiFnRDdGCS3Nz7YjgxH82rk1ZUwkpFdJa9vsAQAAAAAAAAA="
          }
        ]
      }
    }
  }
}
