processed 5 tasks

init:
A: object(0,0)

task 1, lines 6-26:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5890000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 28-31:
//# programmable --inputs @A
//> 0: P0::m::foo();
//> 1: P0::m::bar();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0), object(2,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 3754400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 33:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 35-53:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        }
                      },
                      "hasPublicTransfer": true
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x9432905f01d89b0860046251581b6454e34b655600f9e312eae07f7888ae220f::m::Foo"
                        }
                      },
                      "hasPublicTransfer": true
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x9432905f01d89b0860046251581b6454e34b655600f9e312eae07f7888ae220f::m::Bar"
                        }
                      },
                      "hasPublicTransfer": false
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
