processed 7 tasks

init:
C: object(0,0)

task 1, lines 6-31:
//# run-graphql
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "IMGP5R5ksxKXMS6Y42OgPyAYvLhioCh2OzR76kF19Cr6AAAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedSui": {
                "principal": "200000000000000"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedSuis": {
        "edges": []
      }
    }
  }
}

task 2, lines 33-35:
//# programmable --sender C --inputs 10000000000 @C
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 37:
//# run 0x3::sui_system::request_add_stake --args object(0x5) object(2,0) @validator_0 --sender C
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [19, 254, 188, 80, 102, 229, 198, 85, 110, 227, 100, 33, 90, 119, 228, 215, 93, 175, 10, 39, 212, 70, 170, 249, 156, 225, 197, 93, 56, 215, 176, 223, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(3,0), object(3,1)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(_), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 27534800,  storage_rebate: 2588256, non_refundable_storage_fee: 26144

task 4, line 39:
//# create-checkpoint
Checkpoint created: 1

task 5, line 41:
//# advance-epoch
Epoch advanced: 0

task 6, lines 43-69:
//# run-graphql
Response: {
  "data": {
    "objects": {
      "edges": [
        {
          "cursor": "IHaSobowMRWE2qvRZPzYhtxptR1PCWfpbheHFDjo0ls3AgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedSui": {
                "principal": "40000",
                "poolId": "0x13febc5066e5c6556ee364215a77e4d75daf0a27d446aaf99ce1c55d38d7b0df"
              }
            }
          }
        },
        {
          "cursor": "IH5CjG0clwD96NHfAcEdN7d9TC3n29vsgvoHNRQACsiZAgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedSui": {
                "principal": "10000000000",
                "poolId": "0x13febc5066e5c6556ee364215a77e4d75daf0a27d446aaf99ce1c55d38d7b0df"
              }
            }
          }
        },
        {
          "cursor": "IMGP5R5ksxKXMS6Y42OgPyAYvLhioCh2OzR76kF19Cr6AgAAAAAAAAA=",
          "node": {
            "asMoveObject": {
              "asStakedSui": {
                "principal": "200000000000000",
                "poolId": "0x13febc5066e5c6556ee364215a77e4d75daf0a27d446aaf99ce1c55d38d7b0df"
              }
            }
          }
        }
      ]
    },
    "address": {
      "stakedSuis": {
        "edges": [
          {
            "cursor": "IH5CjG0clwD96NHfAcEdN7d9TC3n29vsgvoHNRQACsiZAgAAAAAAAAA=",
            "node": {
              "principal": "10000000000"
            }
          }
        ]
      }
    }
  }
}
