processed 13 tasks

init:
A: object(0,0)

task 1, lines 6-10:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "epoch": "0",
    "protocolVersion": "70",
    "systemStateVersion": "1",
    "storageFundTotalObjectStorageRebates": "0",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "0",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200000000000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFC6ad06565a01de32de4a2a14ec53160275a3ad2f007a3f3c2d64a7ac100c6d2a70faf",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200000000000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFC90f951ed44aa1f65ff3cf2419629ead5ec7c93381577836fdb60b31096417448249f",
        "stablePools": {
          "id": {
            "id": "BFC53f436961d3d79aa858bfedfaa6350f554e5258061c934cf1c36cce7b72a23a9005e"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200000000000000",
        "rewardsPool": "0",
        "poolTokenBalance": "200000000000000",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFC1b3718da931e43f9d41bc9a5e34907507f2c5ef4593f4eb300334fe79f4e34e423d6",
        "exchangeRatesSize": "1"
      }
    ],
    "pendingActiveValidatorsId": "BFC7f14e0edb0b1f093d13077c1538175203f88f7023168cc43016061de6fd1c5b4b8d2",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFC6235807651ebceb13ef6d26763983328f9c7a55ca72af43efb5c70f9203ee30a6133",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFCdb576fc8cd465f89721aa6517e373eac9f7382fa6395a902908db28004629439e42f",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC4802cbcf45568d82264f7251c4f89cbd5fe7b75d6ce613533a40c1c7c189a9459b2c",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 2, lines 12-14:
//# programmable --sender A --inputs 1000000000 object(0x5) @validator_0
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: sui_system::sui_system::request_add_stake(Input(1), Result(0), Input(2))
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: A, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [144, 249, 81, 237, 68, 170, 31, 101, 255, 60, 242, 65, 150, 41, 234, 213, 236, 124, 147, 56, 21, 119, 131, 111, 219, 96, 179, 16, 150, 65, 116, 72, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 202, 154, 59, 0, 0, 0, 0] }
created: object(2,0), object(2,1)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 27534800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 16:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 18-22:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "epoch": "0",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "0",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "0",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200000000000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFC6ad06565a01de32de4a2a14ec53160275a3ad2f007a3f3c2d64a7ac100c6d2a70faf",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200001000000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFC90f951ed44aa1f65ff3cf2419629ead5ec7c93381577836fdb60b31096417448249f",
        "stablePools": {
          "id": {
            "id": "BFC53f436961d3d79aa858bfedfaa6350f554e5258061c934cf1c36cce7b72a23a9005e"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200000000000000",
        "rewardsPool": "0",
        "poolTokenBalance": "200000000000000",
        "pendingStake": "1000000000",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFC1b3718da931e43f9d41bc9a5e34907507f2c5ef4593f4eb300334fe79f4e34e423d6",
        "exchangeRatesSize": "1"
      }
    ],
    "pendingActiveValidatorsId": "BFC7f14e0edb0b1f093d13077c1538175203f88f7023168cc43016061de6fd1c5b4b8d2",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFC6235807651ebceb13ef6d26763983328f9c7a55ca72af43efb5c70f9203ee30a6133",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFCdb576fc8cd465f89721aa6517e373eac9f7382fa6395a902908db28004629439e42f",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC4802cbcf45568d82264f7251c4f89cbd5fe7b75d6ce613533a40c1c7c189a9459b2c",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 6, line 26:
//# advance-epoch
Epoch advanced: 0

task 7, lines 28-32:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "epoch": "1",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "27534800",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "1",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200001001000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFC6ad06565a01de32de4a2a14ec53160275a3ad2f007a3f3c2d64a7ac100c6d2a70faf",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200001001000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFC90f951ed44aa1f65ff3cf2419629ead5ec7c93381577836fdb60b31096417448249f",
        "stablePools": {
          "id": {
            "id": "BFC53f436961d3d79aa858bfedfaa6350f554e5258061c934cf1c36cce7b72a23a9005e"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200001001000000",
        "rewardsPool": "980000",
        "poolTokenBalance": "200001000019995",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFC1b3718da931e43f9d41bc9a5e34907507f2c5ef4593f4eb300334fe79f4e34e423d6",
        "exchangeRatesSize": "2"
      }
    ],
    "pendingActiveValidatorsId": "BFC7f14e0edb0b1f093d13077c1538175203f88f7023168cc43016061de6fd1c5b4b8d2",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFC6235807651ebceb13ef6d26763983328f9c7a55ca72af43efb5c70f9203ee30a6133",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFCdb576fc8cd465f89721aa6517e373eac9f7382fa6395a902908db28004629439e42f",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC4802cbcf45568d82264f7251c4f89cbd5fe7b75d6ce613533a40c1c7c189a9459b2c",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 8, lines 34-35:
//# programmable --sender A --inputs object(0x5) object(2,1)
//> 0: sui_system::sui_system::request_withdraw_stake(Input(0), Input(1))
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: A, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("UnstakingRequestEvent"), type_params: [] }, contents: [144, 249, 81, 237, 68, 170, 31, 101, 255, 60, 242, 65, 150, 41, 234, 213, 236, 124, 147, 56, 21, 119, 131, 111, 219, 96, 179, 16, 150, 65, 116, 72, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 202, 154, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }
created: object(8,0)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0), object(2,0)
deleted: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 17229200,  storage_rebate: 27259452, non_refundable_storage_fee: 275348

task 9, line 37:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 39-43:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "epoch": "1",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "27534800",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "1",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200001001000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFC6ad06565a01de32de4a2a14ec53160275a3ad2f007a3f3c2d64a7ac100c6d2a70faf",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200000001000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFC90f951ed44aa1f65ff3cf2419629ead5ec7c93381577836fdb60b31096417448249f",
        "stablePools": {
          "id": {
            "id": "BFC53f436961d3d79aa858bfedfaa6350f554e5258061c934cf1c36cce7b72a23a9005e"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200001001000000",
        "rewardsPool": "980000",
        "poolTokenBalance": "200001000019995",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "1000000000",
        "pendingPoolTokenWithdraw": "999999995",
        "exchangeRatesId": "BFC1b3718da931e43f9d41bc9a5e34907507f2c5ef4593f4eb300334fe79f4e34e423d6",
        "exchangeRatesSize": "2"
      }
    ],
    "pendingActiveValidatorsId": "BFC7f14e0edb0b1f093d13077c1538175203f88f7023168cc43016061de6fd1c5b4b8d2",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFC6235807651ebceb13ef6d26763983328f9c7a55ca72af43efb5c70f9203ee30a6133",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFCdb576fc8cd465f89721aa6517e373eac9f7382fa6395a902908db28004629439e42f",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC4802cbcf45568d82264f7251c4f89cbd5fe7b75d6ce613533a40c1c7c189a9459b2c",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 11, line 45:
//# advance-epoch
Epoch advanced: 1

task 12, lines 47-51:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "epoch": "2",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "17229200",
    "storageFundNonRefundableBalance": "275348",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "1",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200000002000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFC6ad06565a01de32de4a2a14ec53160275a3ad2f007a3f3c2d64a7ac100c6d2a70faf",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200000002000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFC90f951ed44aa1f65ff3cf2419629ead5ec7c93381577836fdb60b31096417448249f",
        "stablePools": {
          "id": {
            "id": "BFC53f436961d3d79aa858bfedfaa6350f554e5258061c934cf1c36cce7b72a23a9005e"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200000002000000",
        "rewardsPool": "1960000",
        "poolTokenBalance": "200000000039999",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFC1b3718da931e43f9d41bc9a5e34907507f2c5ef4593f4eb300334fe79f4e34e423d6",
        "exchangeRatesSize": "3"
      }
    ],
    "pendingActiveValidatorsId": "BFC7f14e0edb0b1f093d13077c1538175203f88f7023168cc43016061de6fd1c5b4b8d2",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFC6235807651ebceb13ef6d26763983328f9c7a55ca72af43efb5c70f9203ee30a6133",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFCdb576fc8cd465f89721aa6517e373eac9f7382fa6395a902908db28004629439e42f",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC4802cbcf45568d82264f7251c4f89cbd5fe7b75d6ce613533a40c1c7c189a9459b2c",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}
