processed 13 tasks

init:
A: object(0,0)

task 1, lines 6-10:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "epoch": "0",
    "protocolVersion": "70",
    "systemStateVersion": "1",
    "storageFundTotalObjectStorageRebates": "0",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "0",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200000000000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFCda6516ee82bd87bf7882fc9da9e47b2e188db9b0e0c537965c4c6550f0e7d855123d",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200000000000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFCfa57724dbe75a4774727c8a27405b3d42df72f4e13fb1f3e8c18133b6422183b7705",
        "stablePools": {
          "id": {
            "id": "BFCd5a591cfb39e3bd6e4552ae0268af145403fa044d245c33a0075d735ec898c13847b"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200000000000000",
        "rewardsPool": "0",
        "poolTokenBalance": "200000000000000",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFCe7a79fc3a15828b875e5035430855cc2223c246fec3b843caa378a264ee583bc8368",
        "exchangeRatesSize": "1"
      }
    ],
    "pendingActiveValidatorsId": "BFCa2bd81a423942271c3e02a09a99352eb946e24e7f073b5d9fed14bed88ab6ec48d96",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFC079ab1ee889b90b744a0ce495a2bc07add53928327c4984a0cf061c9ff15559ab7a6",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFC85239339d78cdb65c16bcccdf3a1545cb009f0b75d41ef9e7947a9b8269d1cd1364d",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC4e67c69ab509ab5e0c1fde1256dba24a8cb17978c832e22c0f02072e7ed193e6bf09",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 2, lines 12-14:
//# programmable --sender A --inputs 1000000000 object(0x5) @validator_0
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: sui_system::sui_system::request_add_stake(Input(1), Result(0), Input(2))
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: A, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [250, 87, 114, 77, 190, 117, 164, 119, 71, 39, 200, 162, 116, 5, 179, 212, 45, 247, 47, 78, 19, 251, 31, 62, 140, 24, 19, 59, 100, 34, 24, 59, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 202, 154, 59, 0, 0, 0, 0] }
created: object(2,0), object(2,1)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 27534800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 16:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 18-22:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "epoch": "0",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "0",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "0",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200000000000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFCda6516ee82bd87bf7882fc9da9e47b2e188db9b0e0c537965c4c6550f0e7d855123d",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200001000000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFCfa57724dbe75a4774727c8a27405b3d42df72f4e13fb1f3e8c18133b6422183b7705",
        "stablePools": {
          "id": {
            "id": "BFCd5a591cfb39e3bd6e4552ae0268af145403fa044d245c33a0075d735ec898c13847b"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200000000000000",
        "rewardsPool": "0",
        "poolTokenBalance": "200000000000000",
        "pendingStake": "1000000000",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFCe7a79fc3a15828b875e5035430855cc2223c246fec3b843caa378a264ee583bc8368",
        "exchangeRatesSize": "1"
      }
    ],
    "pendingActiveValidatorsId": "BFCa2bd81a423942271c3e02a09a99352eb946e24e7f073b5d9fed14bed88ab6ec48d96",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFC079ab1ee889b90b744a0ce495a2bc07add53928327c4984a0cf061c9ff15559ab7a6",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFC85239339d78cdb65c16bcccdf3a1545cb009f0b75d41ef9e7947a9b8269d1cd1364d",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC4e67c69ab509ab5e0c1fde1256dba24a8cb17978c832e22c0f02072e7ed193e6bf09",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 6, line 26:
//# advance-epoch
Epoch advanced: 0

task 7, lines 28-32:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "epoch": "1",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "27534800",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "1",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200001001000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFCda6516ee82bd87bf7882fc9da9e47b2e188db9b0e0c537965c4c6550f0e7d855123d",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200001001000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFCfa57724dbe75a4774727c8a27405b3d42df72f4e13fb1f3e8c18133b6422183b7705",
        "stablePools": {
          "id": {
            "id": "BFCd5a591cfb39e3bd6e4552ae0268af145403fa044d245c33a0075d735ec898c13847b"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200001001000000",
        "rewardsPool": "980000",
        "poolTokenBalance": "200001000019995",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFCe7a79fc3a15828b875e5035430855cc2223c246fec3b843caa378a264ee583bc8368",
        "exchangeRatesSize": "2"
      }
    ],
    "pendingActiveValidatorsId": "BFCa2bd81a423942271c3e02a09a99352eb946e24e7f073b5d9fed14bed88ab6ec48d96",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFC079ab1ee889b90b744a0ce495a2bc07add53928327c4984a0cf061c9ff15559ab7a6",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFC85239339d78cdb65c16bcccdf3a1545cb009f0b75d41ef9e7947a9b8269d1cd1364d",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC4e67c69ab509ab5e0c1fde1256dba24a8cb17978c832e22c0f02072e7ed193e6bf09",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 8, lines 34-35:
//# programmable --sender A --inputs object(0x5) object(2,1)
//> 0: sui_system::sui_system::request_withdraw_stake(Input(0), Input(1))
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: A, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("UnstakingRequestEvent"), type_params: [] }, contents: [250, 87, 114, 77, 190, 117, 164, 119, 71, 39, 200, 162, 116, 5, 179, 212, 45, 247, 47, 78, 19, 251, 31, 62, 140, 24, 19, 59, 100, 34, 24, 59, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 202, 154, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }
created: object(8,0)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0), object(2,0)
deleted: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 27550000,  storage_rebate: 27259452, non_refundable_storage_fee: 275348

task 9, line 37:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 39-43:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "epoch": "1",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "27534800",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "1",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200001001000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFCda6516ee82bd87bf7882fc9da9e47b2e188db9b0e0c537965c4c6550f0e7d855123d",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200000001000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFCfa57724dbe75a4774727c8a27405b3d42df72f4e13fb1f3e8c18133b6422183b7705",
        "stablePools": {
          "id": {
            "id": "BFCd5a591cfb39e3bd6e4552ae0268af145403fa044d245c33a0075d735ec898c13847b"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200001001000000",
        "rewardsPool": "980000",
        "poolTokenBalance": "200001000019995",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "1000000000",
        "pendingPoolTokenWithdraw": "999999995",
        "exchangeRatesId": "BFCe7a79fc3a15828b875e5035430855cc2223c246fec3b843caa378a264ee583bc8368",
        "exchangeRatesSize": "2"
      }
    ],
    "pendingActiveValidatorsId": "BFCa2bd81a423942271c3e02a09a99352eb946e24e7f073b5d9fed14bed88ab6ec48d96",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFC079ab1ee889b90b744a0ce495a2bc07add53928327c4984a0cf061c9ff15559ab7a6",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFC85239339d78cdb65c16bcccdf3a1545cb009f0b75d41ef9e7947a9b8269d1cd1364d",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC4e67c69ab509ab5e0c1fde1256dba24a8cb17978c832e22c0f02072e7ed193e6bf09",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 11, line 45:
//# advance-epoch
Epoch advanced: 1

task 12, lines 47-51:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "epoch": "2",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "27550000",
    "storageFundNonRefundableBalance": "275348",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "1",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200000002000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFCda6516ee82bd87bf7882fc9da9e47b2e188db9b0e0c537965c4c6550f0e7d855123d",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200000002000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFCfa57724dbe75a4774727c8a27405b3d42df72f4e13fb1f3e8c18133b6422183b7705",
        "stablePools": {
          "id": {
            "id": "BFCd5a591cfb39e3bd6e4552ae0268af145403fa044d245c33a0075d735ec898c13847b"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200000002000000",
        "rewardsPool": "1960000",
        "poolTokenBalance": "200000000039999",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFCe7a79fc3a15828b875e5035430855cc2223c246fec3b843caa378a264ee583bc8368",
        "exchangeRatesSize": "3"
      }
    ],
    "pendingActiveValidatorsId": "BFCa2bd81a423942271c3e02a09a99352eb946e24e7f073b5d9fed14bed88ab6ec48d96",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFC079ab1ee889b90b744a0ce495a2bc07add53928327c4984a0cf061c9ff15559ab7a6",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFC85239339d78cdb65c16bcccdf3a1545cb009f0b75d41ef9e7947a9b8269d1cd1364d",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC4e67c69ab509ab5e0c1fde1256dba24a8cb17978c832e22c0f02072e7ed193e6bf09",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}
