processed 13 tasks

init:
A: object(0,0)

task 1, lines 6-10:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "epoch": "0",
    "protocolVersion": "70",
    "systemStateVersion": "1",
    "storageFundTotalObjectStorageRebates": "0",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "0",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200000000000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFC5ab2de4657113a31cd8ac23b835356b76d7acb9d07cde5513e32d2f3ef0f90320d13",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200000000000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFC570fc905b1f4ccb6f88e559cef87a93a95ae9675975bfb4c04eaf9c0db0dbff884cf",
        "stablePools": {
          "id": {
            "id": "BFC0f81f28de206ba0598560a2bdef5b49e075bd8814d6b683a2aa31e472ee6d504ad63"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200000000000000",
        "rewardsPool": "0",
        "poolTokenBalance": "200000000000000",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFC7ca814ba0214df0d11667a14d2cd89d0fb4a1156acfff71cb295d81970ad894ccb47",
        "exchangeRatesSize": "1"
      }
    ],
    "pendingActiveValidatorsId": "BFCb02e5047ff6b109195b8c15d1f9dd71f9c010e2a60cfe5ff0e95c037c979d0fedd07",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFCdaae6a37f608950aa8e5fdfbe0ed2d15f73a44a3b8ec1e332159d054ae9c3f0831a7",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFC261f6796c9a2bbaf35d06250cd71442211fec32419ec56f7b95ebc22209fa07bd98f",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC88fec6b3188facaf6cf792e1195c1ab11198a1689f6cd98bbe8e33f0d43508df83ed",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 2, lines 12-14:
//# programmable --sender A --inputs 1000000000 object(0x5) @validator_0
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: sui_system::sui_system::request_add_stake(Input(1), Result(0), Input(2))
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: A, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [87, 15, 201, 5, 177, 244, 204, 182, 248, 142, 85, 156, 239, 135, 169, 58, 149, 174, 150, 117, 151, 91, 251, 76, 4, 234, 249, 192, 219, 13, 191, 248, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 202, 154, 59, 0, 0, 0, 0] }
created: object(2,0), object(2,1)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 27534800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 16:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 18-22:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "epoch": "0",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "0",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "0",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200000000000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFC5ab2de4657113a31cd8ac23b835356b76d7acb9d07cde5513e32d2f3ef0f90320d13",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200001000000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFC570fc905b1f4ccb6f88e559cef87a93a95ae9675975bfb4c04eaf9c0db0dbff884cf",
        "stablePools": {
          "id": {
            "id": "BFC0f81f28de206ba0598560a2bdef5b49e075bd8814d6b683a2aa31e472ee6d504ad63"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200000000000000",
        "rewardsPool": "0",
        "poolTokenBalance": "200000000000000",
        "pendingStake": "1000000000",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFC7ca814ba0214df0d11667a14d2cd89d0fb4a1156acfff71cb295d81970ad894ccb47",
        "exchangeRatesSize": "1"
      }
    ],
    "pendingActiveValidatorsId": "BFCb02e5047ff6b109195b8c15d1f9dd71f9c010e2a60cfe5ff0e95c037c979d0fedd07",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFCdaae6a37f608950aa8e5fdfbe0ed2d15f73a44a3b8ec1e332159d054ae9c3f0831a7",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFC261f6796c9a2bbaf35d06250cd71442211fec32419ec56f7b95ebc22209fa07bd98f",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC88fec6b3188facaf6cf792e1195c1ab11198a1689f6cd98bbe8e33f0d43508df83ed",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 6, line 26:
//# advance-epoch
Epoch advanced: 0

task 7, lines 28-32:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "epoch": "1",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "27534800",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "1",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200001001000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFC5ab2de4657113a31cd8ac23b835356b76d7acb9d07cde5513e32d2f3ef0f90320d13",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200001001000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFC570fc905b1f4ccb6f88e559cef87a93a95ae9675975bfb4c04eaf9c0db0dbff884cf",
        "stablePools": {
          "id": {
            "id": "BFC0f81f28de206ba0598560a2bdef5b49e075bd8814d6b683a2aa31e472ee6d504ad63"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200001001000000",
        "rewardsPool": "980000",
        "poolTokenBalance": "200001000019995",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFC7ca814ba0214df0d11667a14d2cd89d0fb4a1156acfff71cb295d81970ad894ccb47",
        "exchangeRatesSize": "2"
      }
    ],
    "pendingActiveValidatorsId": "BFCb02e5047ff6b109195b8c15d1f9dd71f9c010e2a60cfe5ff0e95c037c979d0fedd07",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFCdaae6a37f608950aa8e5fdfbe0ed2d15f73a44a3b8ec1e332159d054ae9c3f0831a7",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFC261f6796c9a2bbaf35d06250cd71442211fec32419ec56f7b95ebc22209fa07bd98f",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC88fec6b3188facaf6cf792e1195c1ab11198a1689f6cd98bbe8e33f0d43508df83ed",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 8, lines 34-35:
//# programmable --sender A --inputs object(0x5) object(2,1)
//> 0: sui_system::sui_system::request_withdraw_stake(Input(0), Input(1))
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: A, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("UnstakingRequestEvent"), type_params: [] }, contents: [87, 15, 201, 5, 177, 244, 204, 182, 248, 142, 85, 156, 239, 135, 169, 58, 149, 174, 150, 117, 151, 91, 251, 76, 4, 234, 249, 192, 219, 13, 191, 248, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 202, 154, 59, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }
created: object(8,0)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0), object(2,0)
deleted: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 27550000,  storage_rebate: 27259452, non_refundable_storage_fee: 275348

task 9, line 37:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 39-43:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "epoch": "1",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "27534800",
    "storageFundNonRefundableBalance": "0",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "1",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200001001000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFC5ab2de4657113a31cd8ac23b835356b76d7acb9d07cde5513e32d2f3ef0f90320d13",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200000001000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFC570fc905b1f4ccb6f88e559cef87a93a95ae9675975bfb4c04eaf9c0db0dbff884cf",
        "stablePools": {
          "id": {
            "id": "BFC0f81f28de206ba0598560a2bdef5b49e075bd8814d6b683a2aa31e472ee6d504ad63"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200001001000000",
        "rewardsPool": "980000",
        "poolTokenBalance": "200001000019995",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "1000000000",
        "pendingPoolTokenWithdraw": "999999995",
        "exchangeRatesId": "BFC7ca814ba0214df0d11667a14d2cd89d0fb4a1156acfff71cb295d81970ad894ccb47",
        "exchangeRatesSize": "2"
      }
    ],
    "pendingActiveValidatorsId": "BFCb02e5047ff6b109195b8c15d1f9dd71f9c010e2a60cfe5ff0e95c037c979d0fedd07",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFCdaae6a37f608950aa8e5fdfbe0ed2d15f73a44a3b8ec1e332159d054ae9c3f0831a7",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFC261f6796c9a2bbaf35d06250cd71442211fec32419ec56f7b95ebc22209fa07bd98f",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC88fec6b3188facaf6cf792e1195c1ab11198a1689f6cd98bbe8e33f0d43508df83ed",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}

task 11, line 45:
//# advance-epoch
Epoch advanced: 1

task 12, lines 47-51:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "epoch": "2",
    "protocolVersion": "70",
    "systemStateVersion": "2",
    "storageFundTotalObjectStorageRebates": "27550000",
    "storageFundNonRefundableBalance": "275348",
    "referenceGasPrice": "100",
    "safeMode": false,
    "safeModeStorageRewards": "0",
    "safeModeComputationRewards": "0",
    "safeModeStorageRebates": "0",
    "safeModeNonRefundableStorageFee": "0",
    "epochStartTimestampMs": "1",
    "epochDurationMs": "300000",
    "stakeSubsidyStartEpoch": "0",
    "maxValidatorCount": "150",
    "minValidatorJoiningStake": "300000000000000",
    "validatorLowStakeThreshold": "200000000000000",
    "validatorVeryLowStakeThreshold": "150000000000000",
    "validatorLowStakeGracePeriod": "7",
    "stakeSubsidyBalance": "496200000000000000",
    "stakeSubsidyDistributionCounter": "0",
    "stakeSubsidyCurrentDistributionAmount": "27000000000000",
    "stakeSubsidyPeriodLength": "10",
    "stakeSubsidyDecreaseRate": 0,
    "totalStake": "200000002000000",
    "activeValidators": [
      {
        "suiAddress": "BFCda83166d01afd7ddcf8af5f844f45aaa53f48548e5117c23f5a2978cfd4222443a3d",
        "protocolPubkeyBytes": "qqgbtEP57SCwGrO7tmcKwy/daeoOFwANmrMTm1Qu4jUJRhi2VePz/brF9YAcjmJ7BLOpN8c5Ia7zYzTNmGtGoaUnjoYrbvDG9E05s9antwSmkHAIGsM8mkmeBkSjSBrt",
        "networkPubkeyBytes": "ZeETulurG5EpRBoewpF26pyLQtpUqwH1T6LqgugHBIU=",
        "workerPubkeyBytes": "3sE4/d+MbOSh9pesKr7b89TSO5gFBuyGUjVa4GldmFU=",
        "proofOfPossessionBytes": "sIupbWI7yiRvXM22F2E5sJFRricflowHFu7yqXnzglaAvYTxInm4MSDNAgeMzHyJ",
        "name": "validator-0",
        "description": "",
        "imageUrl": "",
        "projectUrl": "",
        "netAddress": "/ip4/127.0.0.1/tcp/8000/http",
        "p2pAddress": "/ip4/127.0.0.1/udp/8001/http",
        "primaryAddress": "/ip4/127.0.0.1/udp/8004/http",
        "workerAddress": "/ip4/127.0.0.1/udp/8005/http",
        "nextEpochProtocolPubkeyBytes": null,
        "nextEpochProofOfPossession": null,
        "nextEpochNetworkPubkeyBytes": null,
        "nextEpochWorkerPubkeyBytes": null,
        "nextEpochNetAddress": null,
        "nextEpochP2pAddress": null,
        "nextEpochPrimaryAddress": null,
        "nextEpochWorkerAddress": null,
        "votingPower": "10000",
        "operationCapId": "BFC5ab2de4657113a31cd8ac23b835356b76d7acb9d07cde5513e32d2f3ef0f90320d13",
        "gasPrice": "100",
        "commissionRate": "200",
        "nextEpochStake": "200000002000000",
        "nextEpochGasPrice": "100",
        "nextEpochCommissionRate": "200",
        "stakingPoolId": "BFC570fc905b1f4ccb6f88e559cef87a93a95ae9675975bfb4c04eaf9c0db0dbff884cf",
        "stablePools": {
          "id": {
            "id": "BFC0f81f28de206ba0598560a2bdef5b49e075bd8814d6b683a2aa31e472ee6d504ad63"
          },
          "size": 17
        },
        "stakingPoolActivationEpoch": "0",
        "stakingPoolDeactivationEpoch": null,
        "stakingPoolSuiBalance": "200000002000000",
        "rewardsPool": "1960000",
        "poolTokenBalance": "200000000039999",
        "pendingStake": "0",
        "pendingTotalSuiWithdraw": "0",
        "pendingPoolTokenWithdraw": "0",
        "exchangeRatesId": "BFC7ca814ba0214df0d11667a14d2cd89d0fb4a1156acfff71cb295d81970ad894ccb47",
        "exchangeRatesSize": "3"
      }
    ],
    "pendingActiveValidatorsId": "BFCb02e5047ff6b109195b8c15d1f9dd71f9c010e2a60cfe5ff0e95c037c979d0fedd07",
    "pendingActiveValidatorsSize": "0",
    "pendingRemovals": [],
    "stakingPoolMappingsId": "BFCdaae6a37f608950aa8e5fdfbe0ed2d15f73a44a3b8ec1e332159d054ae9c3f0831a7",
    "stakingPoolMappingsSize": "1",
    "inactivePoolsId": "BFC261f6796c9a2bbaf35d06250cd71442211fec32419ec56f7b95ebc22209fa07bd98f",
    "inactivePoolsSize": "0",
    "validatorCandidatesId": "BFC88fec6b3188facaf6cf792e1195c1ab11198a1689f6cd98bbe8e33f0d43508df83ed",
    "validatorCandidatesSize": "0",
    "atRiskValidators": [],
    "validatorReportRecords": []
  }
}
