processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 13-26:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5494800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 28:
//# run Test::M1::create --args 0 @A --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 30:
//# run Test::M1::create --args 0 @A --sender A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 32:
//# run Test::M1::create --args 0 @A --sender A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5, line 34:
//# run Test::M1::create --args 0 @A --sender A
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6, line 36:
//# create-checkpoint
Checkpoint created: 1

task 7, line 38:
//# run Test::M1::create --args 0 @A --sender A
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 8, line 40:
//# run Test::M1::create --args 0 @A --sender A
created: object(8,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 9, line 42:
//# run Test::M1::create --args 0 @A --sender A
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 10, line 44:
//# create-checkpoint
Checkpoint created: 2

task 11, line 46:
//# run Test::M1::create --args 0 @A --sender A
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 12, line 48:
//# run Test::M1::create --args 0 @A --sender A
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 13, line 50:
//# create-checkpoint
Checkpoint created: 3

task 14, lines 52-76:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "transactionBlocks": {
            "edges": []
          }
        },
        {
          "sequenceNumber": 1,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0IjoyLCJpIjpmYWxzZX0",
                "node": {
                  "digest": "44jk3mmvZJ3GAqgLqcWrjoz3fCHonYSr9wsLFmRWiYYX",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INd16QTXoc3tPmTA8hbHKbwRv+lWGKUj6hBT1n5fT904AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjozLCJpIjpmYWxzZX0",
                "node": {
                  "digest": "7mjqTdisFsyjvW6DfmWu4rPXLFaZ6aojvWyx1BRsKvvK",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INd16QTXoc3tPmTA8hbHKbwRv+lWGKUj6hBT1n5fT904AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo0LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "8f2jHcL41fEiEVhrWHH97cQVccJZ2UtCCH6JfGozmNnJ",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INd16QTXoc3tPmTA8hbHKbwRv+lWGKUj6hBT1n5fT904AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo1LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "DNGgkJxPf4MjrGhFRxzRD2WQU5Gq4EXc2r4oo9QcV78m",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INd16QTXoc3tPmTA8hbHKbwRv+lWGKUj6hBT1n5fT904AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 2,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo2LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "7WEmbEmXaRDYjKVm24YmkTVJP1WjBU9k3EAmGx74tgtm",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INd16QTXoc3tPmTA8hbHKbwRv+lWGKUj6hBT1n5fT904AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo3LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "2Susx8351JuCRvf8KC9j3i2CniAxR4V6yt1EEHE7YETY",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INd16QTXoc3tPmTA8hbHKbwRv+lWGKUj6hBT1n5fT904AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo4LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "CfmSQktpRMoNt1X59hGSNP6bE8QPGM6sEhAaCQMexQao",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INd16QTXoc3tPmTA8hbHKbwRv+lWGKUj6hBT1n5fT904AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 3,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo5LCJpIjpmYWxzZX0",
                "node": {
                  "digest": "GZ3gE158C9xtAtqZgWJeJtC6BpCdXg85RjnWmbyVQzdg",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INd16QTXoc3tPmTA8hbHKbwRv+lWGKUj6hBT1n5fT904AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjoxMCwiaSI6ZmFsc2V9",
                "node": {
                  "digest": "6xYp25RwHNUw6FFqjimun9N8PPLam99SN1MgVeYQh3r8",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "INd16QTXoc3tPmTA8hbHKbwRv+lWGKUj6hBT1n5fT904AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}

task 15, lines 78-95:
//# run-graphql
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 1,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 2,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 3,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        }
      ]
    }
  }
}
