processed 15 tasks

init:
A: object(0,0)

task 1, lines 16-18:
//# programmable --sender A --inputs 12 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 20-22:
//# programmable --sender A --inputs 34 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 24-26:
//# programmable --sender A --inputs 56 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, lines 28-30:
//# programmable --sender A --inputs 78 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5, lines 32-34:
//# programmable --sender A --inputs 90 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6, line 36:
//# create-checkpoint
Checkpoint created: 1

task 7, lines 38-42:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "data": [
      {
        "digest": "B36pzC74iaPY5NxkHa3EPtYgn1G2wDSVL1R5PL2wVFdm"
      },
      {
        "digest": "3GwTahspEYYeP6R8MntgMEVHKYRpav52imXBFDmUBEzx"
      },
      {
        "digest": "AafCJQXD9cnnU7PB3jP98u6SpopGDE9n2F8YnkqqwJwJ"
      },
      {
        "digest": "2pNo61txdNEmWvvLeuiyLXwcMehusXV5nirUYHx9upnM"
      },
      {
        "digest": "BdKxfxjZXBhnp1Z82xvRcyQuTBBgPVJTLddidt61PJMp"
      },
      {
        "digest": "HVkj9dE313Znw7gZTje1BCqzMGosQz7Xsknz5zWiM5HN"
      }
    ],
    "nextCursor": "NQ==",
    "hasNextPage": false
  }
}

task 8, lines 44-52:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "data": [
      {
        "digest": "B36pzC74iaPY5NxkHa3EPtYgn1G2wDSVL1R5PL2wVFdm"
      },
      {
        "digest": "3GwTahspEYYeP6R8MntgMEVHKYRpav52imXBFDmUBEzx"
      },
      {
        "digest": "AafCJQXD9cnnU7PB3jP98u6SpopGDE9n2F8YnkqqwJwJ"
      }
    ],
    "nextCursor": "Mg==",
    "hasNextPage": true
  }
}

task 9, lines 54-62:
//# run-jsonrpc --cursors 2
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "data": [
      {
        "digest": "2pNo61txdNEmWvvLeuiyLXwcMehusXV5nirUYHx9upnM"
      },
      {
        "digest": "BdKxfxjZXBhnp1Z82xvRcyQuTBBgPVJTLddidt61PJMp"
      },
      {
        "digest": "HVkj9dE313Znw7gZTje1BCqzMGosQz7Xsknz5zWiM5HN"
      }
    ],
    "nextCursor": "NQ==",
    "hasNextPage": false
  }
}

task 10, lines 64-73:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "data": [
      {
        "digest": "HVkj9dE313Znw7gZTje1BCqzMGosQz7Xsknz5zWiM5HN"
      },
      {
        "digest": "BdKxfxjZXBhnp1Z82xvRcyQuTBBgPVJTLddidt61PJMp"
      },
      {
        "digest": "2pNo61txdNEmWvvLeuiyLXwcMehusXV5nirUYHx9upnM"
      },
      {
        "digest": "AafCJQXD9cnnU7PB3jP98u6SpopGDE9n2F8YnkqqwJwJ"
      },
      {
        "digest": "3GwTahspEYYeP6R8MntgMEVHKYRpav52imXBFDmUBEzx"
      },
      {
        "digest": "B36pzC74iaPY5NxkHa3EPtYgn1G2wDSVL1R5PL2wVFdm"
      }
    ],
    "nextCursor": "MA==",
    "hasNextPage": false
  }
}

task 11, lines 75-84:
//# run-jsonrpc --cursors 3
Response: {
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "data": [
      {
        "digest": "AafCJQXD9cnnU7PB3jP98u6SpopGDE9n2F8YnkqqwJwJ"
      },
      {
        "digest": "3GwTahspEYYeP6R8MntgMEVHKYRpav52imXBFDmUBEzx"
      }
    ],
    "nextCursor": "MQ==",
    "hasNextPage": true
  }
}

task 12, lines 86-93:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 5,
  "error": {
    "code": -32602,
    "message": "Invalid Params: Pagination issue: Failed to decode Base64: Invalid value was given to the function"
  }
}

task 13, lines 95-103:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 6,
  "error": {
    "code": -32602,
    "message": "Invalid Params: Pagination issue: Requested page size 10000 exceeds maximum 100"
  }
}

task 14, lines 105-117:
//# run-jsonrpc --cursors 1
Response: {
  "jsonrpc": "2.0",
  "id": 7,
  "result": {
    "data": [
      {
        "digest": "AafCJQXD9cnnU7PB3jP98u6SpopGDE9n2F8YnkqqwJwJ",
        "transaction": {
          "data": {
            "messageVersion": "v1",
            "transaction": {
              "kind": "ProgrammableTransaction",
              "inputs": [
                {
                  "type": "pure",
                  "valueType": "u64",
                  "value": "34"
                },
                {
                  "type": "pure",
                  "valueType": "address",
                  "value": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                }
              ],
              "transactions": [
                {
                  "SplitCoins": [
                    "GasCoin",
                    [
                      {
                        "Input": 0
                      }
                    ]
                  ]
                },
                {
                  "TransferObjects": [
                    [
                      {
                        "Result": 0
                      }
                    ],
                    {
                      "Input": 1
                    }
                  ]
                }
              ]
            },
            "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
            "gasData": {
              "payment": [
                {
                  "objectId": "BFC6156426cbfdc37ea964031e97d3e76145a5e8ba8a1c94ffac49d1816bd4ea867196e",
                  "version": 2,
                  "digest": "6f8Yt12YtYE3Nydb354erRztevNufTpeQUiNiAjMo7Bi"
                }
              ],
              "owner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
              "price": "1000",
              "budget": "5000000000"
            }
          },
          "txSignatures": [
            "ANpMpEGcjb8vhCDXzmFbQsTcWwgpc3VWRoch9LHy5MLGqshQeOEkJPYeX8bG+Q9jf7V3F6eS2DQ8xJvxPCfcrg9/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ]
        }
      },
      {
        "digest": "2pNo61txdNEmWvvLeuiyLXwcMehusXV5nirUYHx9upnM",
        "transaction": {
          "data": {
            "messageVersion": "v1",
            "transaction": {
              "kind": "ProgrammableTransaction",
              "inputs": [
                {
                  "type": "pure",
                  "valueType": "u64",
                  "value": "56"
                },
                {
                  "type": "pure",
                  "valueType": "address",
                  "value": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                }
              ],
              "transactions": [
                {
                  "SplitCoins": [
                    "GasCoin",
                    [
                      {
                        "Input": 0
                      }
                    ]
                  ]
                },
                {
                  "TransferObjects": [
                    [
                      {
                        "Result": 0
                      }
                    ],
                    {
                      "Input": 1
                    }
                  ]
                }
              ]
            },
            "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
            "gasData": {
              "payment": [
                {
                  "objectId": "BFC6156426cbfdc37ea964031e97d3e76145a5e8ba8a1c94ffac49d1816bd4ea867196e",
                  "version": 3,
                  "digest": "8DXf576C4JbzuGYnnXqSNaRUiMyibwd2KqieDhxDQxMx"
                }
              ],
              "owner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
              "price": "1000",
              "budget": "5000000000"
            }
          },
          "txSignatures": [
            "AERXjH84qQduhRwkHMos+8IZuuEaYhZbuzYHc98PGGOL8qQpN3zKFlmiEO2/PYbz/9XPecCbGrvFE7JwTLWFSAV/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ]
        }
      }
    ],
    "nextCursor": "Mw==",
    "hasNextPage": true
  }
}
