processed 15 tasks

init:
A: object(0,0)

task 1, lines 16-18:
//# programmable --sender A --inputs 12 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 20-22:
//# programmable --sender A --inputs 34 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 24-26:
//# programmable --sender A --inputs 56 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, lines 28-30:
//# programmable --sender A --inputs 78 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5, lines 32-34:
//# programmable --sender A --inputs 90 @A
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6, line 36:
//# create-checkpoint
Checkpoint created: 1

task 7, lines 38-42:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "data": [
      {
        "digest": "CCw6BpK6QYhjSCaWo1znFREveJf99oSk44BGWEx5wene"
      },
      {
        "digest": "2XFvmBf3CcDCWaMG3o12ZEqbScfQN9o52buQHCiB34Nc"
      },
      {
        "digest": "D5j42H5GqeQqP5KGYMPn2hoZt7MDEEbPt7hxB9udwM56"
      },
      {
        "digest": "EhyJ3mga9RcPpbcgJTjFNv6hPHcMmZ2ao6kVNvbKSV5M"
      },
      {
        "digest": "He7iB6Yd3c4Tvo35wd5v4Yebpio8UgUhVvKdoz8GrLHP"
      },
      {
        "digest": "5fphz3LxzLi6DSgDVN7SZ7iAJoaf2z1QnRAQcCWfZrgR"
      }
    ],
    "nextCursor": "NQ==",
    "hasNextPage": false
  }
}

task 8, lines 44-52:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "data": [
      {
        "digest": "CCw6BpK6QYhjSCaWo1znFREveJf99oSk44BGWEx5wene"
      },
      {
        "digest": "2XFvmBf3CcDCWaMG3o12ZEqbScfQN9o52buQHCiB34Nc"
      },
      {
        "digest": "D5j42H5GqeQqP5KGYMPn2hoZt7MDEEbPt7hxB9udwM56"
      }
    ],
    "nextCursor": "Mg==",
    "hasNextPage": true
  }
}

task 9, lines 54-62:
//# run-jsonrpc --cursors 2
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "data": [
      {
        "digest": "EhyJ3mga9RcPpbcgJTjFNv6hPHcMmZ2ao6kVNvbKSV5M"
      },
      {
        "digest": "He7iB6Yd3c4Tvo35wd5v4Yebpio8UgUhVvKdoz8GrLHP"
      },
      {
        "digest": "5fphz3LxzLi6DSgDVN7SZ7iAJoaf2z1QnRAQcCWfZrgR"
      }
    ],
    "nextCursor": "NQ==",
    "hasNextPage": false
  }
}

task 10, lines 64-73:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "data": [
      {
        "digest": "5fphz3LxzLi6DSgDVN7SZ7iAJoaf2z1QnRAQcCWfZrgR"
      },
      {
        "digest": "He7iB6Yd3c4Tvo35wd5v4Yebpio8UgUhVvKdoz8GrLHP"
      },
      {
        "digest": "EhyJ3mga9RcPpbcgJTjFNv6hPHcMmZ2ao6kVNvbKSV5M"
      },
      {
        "digest": "D5j42H5GqeQqP5KGYMPn2hoZt7MDEEbPt7hxB9udwM56"
      },
      {
        "digest": "2XFvmBf3CcDCWaMG3o12ZEqbScfQN9o52buQHCiB34Nc"
      },
      {
        "digest": "CCw6BpK6QYhjSCaWo1znFREveJf99oSk44BGWEx5wene"
      }
    ],
    "nextCursor": "MA==",
    "hasNextPage": false
  }
}

task 11, lines 75-84:
//# run-jsonrpc --cursors 3
Response: {
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "data": [
      {
        "digest": "D5j42H5GqeQqP5KGYMPn2hoZt7MDEEbPt7hxB9udwM56"
      },
      {
        "digest": "2XFvmBf3CcDCWaMG3o12ZEqbScfQN9o52buQHCiB34Nc"
      }
    ],
    "nextCursor": "MQ==",
    "hasNextPage": true
  }
}

task 12, lines 86-93:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 5,
  "error": {
    "code": -32602,
    "message": "Invalid Params: Pagination issue: Failed to decode Base64: Invalid value was given to the function"
  }
}

task 13, lines 95-103:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 6,
  "error": {
    "code": -32602,
    "message": "Invalid Params: Pagination issue: Requested page size 10000 exceeds maximum 100"
  }
}

task 14, lines 105-117:
//# run-jsonrpc --cursors 1
Response: {
  "jsonrpc": "2.0",
  "id": 7,
  "result": {
    "data": [
      {
        "digest": "D5j42H5GqeQqP5KGYMPn2hoZt7MDEEbPt7hxB9udwM56",
        "transaction": {
          "data": {
            "messageVersion": "v1",
            "transaction": {
              "kind": "ProgrammableTransaction",
              "inputs": [
                {
                  "type": "pure",
                  "valueType": "u64",
                  "value": "34"
                },
                {
                  "type": "pure",
                  "valueType": "address",
                  "value": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                }
              ],
              "transactions": [
                {
                  "SplitCoins": [
                    "GasCoin",
                    [
                      {
                        "Input": 0
                      }
                    ]
                  ]
                },
                {
                  "TransferObjects": [
                    [
                      {
                        "Result": 0
                      }
                    ],
                    {
                      "Input": 1
                    }
                  ]
                }
              ]
            },
            "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
            "gasData": {
              "payment": [
                {
                  "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
                  "version": 2,
                  "digest": "43z5HLVDUj4iekFBEErvckHLzxhUMQCCbPHyvspw4hxQ"
                }
              ],
              "owner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
              "price": "1000",
              "budget": "5000000000"
            }
          },
          "txSignatures": [
            "AMRqoFgYO9DNfciOn/up1Y+YUN4QI1PW2Nd86ERriJI0ndy/QFqD7numYSGGM9aeM3FfW1Frpve/E3mj1skQowB/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ]
        }
      },
      {
        "digest": "EhyJ3mga9RcPpbcgJTjFNv6hPHcMmZ2ao6kVNvbKSV5M",
        "transaction": {
          "data": {
            "messageVersion": "v1",
            "transaction": {
              "kind": "ProgrammableTransaction",
              "inputs": [
                {
                  "type": "pure",
                  "valueType": "u64",
                  "value": "56"
                },
                {
                  "type": "pure",
                  "valueType": "address",
                  "value": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                }
              ],
              "transactions": [
                {
                  "SplitCoins": [
                    "GasCoin",
                    [
                      {
                        "Input": 0
                      }
                    ]
                  ]
                },
                {
                  "TransferObjects": [
                    [
                      {
                        "Result": 0
                      }
                    ],
                    {
                      "Input": 1
                    }
                  ]
                }
              ]
            },
            "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
            "gasData": {
              "payment": [
                {
                  "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
                  "version": 3,
                  "digest": "B9xa4MRWDsV2eUMx5YgaGyBXEpMPn9diF2VnCLKrT5jt"
                }
              ],
              "owner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
              "price": "1000",
              "budget": "5000000000"
            }
          },
          "txSignatures": [
            "APScU9WSmDAsOKt8YUJ17nIQyXqtUq7KlalwXNmXD20WbNCUczIYSgO91IcS7TTp0sgk7LQPJZov8ALb4L/QJwZ/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ]
        }
      }
    ],
    "nextCursor": "Mw==",
    "hasNextPage": true
  }
}
