processed 15 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 10-27:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5776000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 29:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 31:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 33:
//# run Test::M1::update --sender A --args 100 object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1301652, non_refundable_storage_fee: 13148

task 5, line 35:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 37-65:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "after_obj_3_0": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
              },
              "json": {
                "id": "0x3cd416c0841fbfc6d4de02e48766b63347512b7d0cdf270a31266da76673e412",
                "value": "100"
              }
            }
          }
        ]
      }
    }
  }
}

task 7, line 67:
//# run Test::M1::update --sender A --args 200 object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 8, line 69:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 71-100:
//# run-graphql --cursors @{obj_3_0,1}
Response: {
  "data": {
    "after_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
              },
              "json": {
                "id": "0x3cd416c0841fbfc6d4de02e48766b63347512b7d0cdf270a31266da76673e412",
                "value": "100"
              }
            }
          }
        ]
      }
    }
  }
}

task 10, lines 102-177:
//# run-graphql --cursors @{obj_3_0,2}
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
              },
              "json": {
                "id": "0x3cd416c0841fbfc6d4de02e48766b63347512b7d0cdf270a31266da76673e412",
                "value": "200"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
              },
              "json": {
                "id": "0xf7ef7e57c3616d7b7b2464e75f581db13a6e9cf8923dd15a68e6438279928055",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
              },
              "json": {
                "id": "0x3cd416c0841fbfc6d4de02e48766b63347512b7d0cdf270a31266da76673e412",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
                        },
                        "json": {
                          "id": "0x3cd416c0841fbfc6d4de02e48766b63347512b7d0cdf270a31266da76673e412",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
                        },
                        "json": {
                          "id": "0xf7ef7e57c3616d7b7b2464e75f581db13a6e9cf8923dd15a68e6438279928055",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 11, line 179:
//# run Test::M1::update --sender A --args 300 object(3,0)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 12, line 181:
//# create-checkpoint
Checkpoint created: 3

task 13, lines 183-246:
//# run-graphql --cursors @{obj_3_0,2}
Response: {
  "data": {
    "after_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
              },
              "json": {
                "id": "0x3cd416c0841fbfc6d4de02e48766b63347512b7d0cdf270a31266da76673e412",
                "value": "200"
              }
            },
            "this_should_differ": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
                        },
                        "json": {
                          "id": "0x3cd416c0841fbfc6d4de02e48766b63347512b7d0cdf270a31266da76673e412",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
                        },
                        "json": {
                          "id": "0xf7ef7e57c3616d7b7b2464e75f581db13a6e9cf8923dd15a68e6438279928055",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 14, lines 248-323:
//# run-graphql --cursors @{obj_3_0,3}
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
              },
              "json": {
                "id": "0x3cd416c0841fbfc6d4de02e48766b63347512b7d0cdf270a31266da76673e412",
                "value": "200"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
              },
              "json": {
                "id": "0xf7ef7e57c3616d7b7b2464e75f581db13a6e9cf8923dd15a68e6438279928055",
                "value": "300"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": []
      }
    },
    "before_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
              },
              "json": {
                "id": "0x3cd416c0841fbfc6d4de02e48766b63347512b7d0cdf270a31266da76673e412",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
                        },
                        "json": {
                          "id": "0x3cd416c0841fbfc6d4de02e48766b63347512b7d0cdf270a31266da76673e412",
                          "value": "200"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xd1ba1841bdfd7becc3ec112756adaceb2a53ee0aa2d6e7d9899fe7994916810c::M1::Object"
                        },
                        "json": {
                          "id": "0xf7ef7e57c3616d7b7b2464e75f581db13a6e9cf8923dd15a68e6438279928055",
                          "value": "300"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}
