processed 17 tasks

init:
A: object(0,0)

task 1, lines 6-86:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 10906000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 88-89:
//# run P0::M::new_o
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2584000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 91-92:
//# run P0::M::new_w
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2576400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, lines 94-95:
//# run P0::M::new_dof
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5, lines 97-98:
//# run P0::M::new_dof
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6, lines 100-103:
//# run P0::M::connect --args object(2,0) object(3,0) object(4,0) object(5,0)
created: object(6,0), object(6,1)
mutated: object(0,1), object(2,0), object(4,0), object(5,0)
wrapped: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 10260000,  storage_rebate: 6357780, non_refundable_storage_fee: 64220

task 7, lines 105-107:
//# view-object 2,0
Owner: Account Address ( BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9 )
Version: 7
Contents: P0::M::O {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
    wrapped: std::option::Option<P0::M::W> {
        vec: vector[
            P0::M::W {
                id: sui::object::UID {
                    id: sui::object::ID {
                        bytes: fake(3,0),
                    },
                },
                count: 0u64,
            },
        ],
    },
}

task 8, lines 109-110:
//# run P0::M::touch_root --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2888000,  storage_rebate: 2859120, non_refundable_storage_fee: 28880

task 9, lines 112-113:
//# run P0::M::touch_wrapped --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2888000,  storage_rebate: 2859120, non_refundable_storage_fee: 28880

task 10, lines 115-116:
//# run P0::M::touch_inner --args object(2,0)
mutated: object(0,1), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 4172400,  storage_rebate: 4130676, non_refundable_storage_fee: 41724

task 11, lines 118-119:
//# run P0::M::touch_outer --args object(2,0)
mutated: object(0,1), object(2,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 4172400,  storage_rebate: 4130676, non_refundable_storage_fee: 41724

task 12, line 121:
//# view-object 2,0
Owner: Account Address ( BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9 )
Version: 11
Contents: P0::M::O {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 1u64,
    wrapped: std::option::Option<P0::M::W> {
        vec: vector[
            P0::M::W {
                id: sui::object::UID {
                    id: sui::object::ID {
                        bytes: fake(3,0),
                    },
                },
                count: 1u64,
            },
        ],
    },
}

task 13, line 123:
//# create-checkpoint
Checkpoint created: 1

task 14, lines 125-140:
//# run-graphql
Response: {
  "data": {
    "latest": {
      "asObject": {
        "asMoveObject": {
          "version": 11,
          "contents": {
            "json": {
              "id": "0xa284216e13357ebb15b55d1e20253732b432dd840b88e4791e5bb22909e628f9",
              "count": "1",
              "wrapped": {
                "id": "0x4718b1854e4dc5214bc13919a3850d22877b01c6d98c97d5bf375ac26219c6d2",
                "count": "1"
              }
            }
          }
        }
      }
    },
    "versioned": {
      "asObject": {
        "asMoveObject": {
          "version": 10,
          "contents": {
            "json": {
              "id": "0xa284216e13357ebb15b55d1e20253732b432dd840b88e4791e5bb22909e628f9",
              "count": "1",
              "wrapped": {
                "id": "0x4718b1854e4dc5214bc13919a3850d22877b01c6d98c97d5bf375ac26219c6d2",
                "count": "1"
              }
            }
          }
        }
      }
    },
    "beforeWrappedBump": {
      "asObject": {
        "asMoveObject": {
          "version": 8,
          "contents": {
            "json": {
              "id": "0xa284216e13357ebb15b55d1e20253732b432dd840b88e4791e5bb22909e628f9",
              "count": "1",
              "wrapped": {
                "id": "0x4718b1854e4dc5214bc13919a3850d22877b01c6d98c97d5bf375ac26219c6d2",
                "count": "0"
              }
            }
          }
        }
      }
    },
    "beforeBump": {
      "asObject": {
        "asMoveObject": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0xa284216e13357ebb15b55d1e20253732b432dd840b88e4791e5bb22909e628f9",
              "count": "0",
              "wrapped": {
                "id": "0x4718b1854e4dc5214bc13919a3850d22877b01c6d98c97d5bf375ac26219c6d2",
                "count": "0"
              }
            }
          }
        }
      }
    }
  }
}

task 15, lines 142-169:
//# run-graphql
Response: {
  "data": {
    "unversioned": {
      "dynamicObjectField": {
        "value": {
          "version": 10,
          "contents": {
            "json": {
              "id": "0x2f09c97b44ad21ac0b638461f64b04ec332fbc3c413f1cfeacd626e92bb387de",
              "count": "1"
            }
          }
        }
      }
    },
    "latest": {
      "dynamicObjectField": {
        "value": {
          "version": 10,
          "contents": {
            "json": {
              "id": "0x2f09c97b44ad21ac0b638461f64b04ec332fbc3c413f1cfeacd626e92bb387de",
              "count": "1"
            }
          }
        }
      }
    },
    "afterFirstInnerBump": {
      "dynamicObjectField": {
        "value": {
          "version": 10,
          "contents": {
            "json": {
              "id": "0x2f09c97b44ad21ac0b638461f64b04ec332fbc3c413f1cfeacd626e92bb387de",
              "count": "1"
            }
          }
        }
      }
    },
    "beforeFirstInnerBump": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0x2f09c97b44ad21ac0b638461f64b04ec332fbc3c413f1cfeacd626e92bb387de",
              "count": "0"
            }
          }
        }
      }
    },
    "beforeBumps": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0x2f09c97b44ad21ac0b638461f64b04ec332fbc3c413f1cfeacd626e92bb387de",
              "count": "0"
            }
          }
        }
      }
    }
  }
}

task 16, lines 171-206:
//# run-graphql
Response: {
  "data": {
    "unversioned": {
      "dynamicObjectField": {
        "value": {
          "version": 11,
          "contents": {
            "json": {
              "id": "0x3f34a1225d50c7ac61f2704ad4bc082f8c7b266ecd5f3c3e5778d596c544a4ad",
              "count": "1"
            }
          }
        }
      }
    },
    "latestObject": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0x3f34a1225d50c7ac61f2704ad4bc082f8c7b266ecd5f3c3e5778d596c544a4ad",
              "count": "0"
            }
          }
        }
      }
    },
    "latest": {
      "dynamicObjectField": {
        "value": {
          "version": 11,
          "contents": {
            "json": {
              "id": "0x3f34a1225d50c7ac61f2704ad4bc082f8c7b266ecd5f3c3e5778d596c544a4ad",
              "count": "1"
            }
          }
        }
      }
    },
    "beforeInnerBump": {
      "dynamicObjectField": {
        "value": {
          "version": 7,
          "contents": {
            "json": {
              "id": "0x3f34a1225d50c7ac61f2704ad4bc082f8c7b266ecd5f3c3e5778d596c544a4ad",
              "count": "0"
            }
          }
        }
      }
    }
  }
}
