processed 22 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 10-72:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 22283200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 73-75:
//# run sui::pay::split_and_transfer --args object(1,1) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(2,0)
mutated: object(0,0), object(1,1)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 4256000,  storage_rebate: 2753784, non_refundable_storage_fee: 27816

task 3, lines 76-78:
//# run test::regulated_coin::partial_wrap --args object(1,1) --sender A
created: object(3,0)
mutated: object(0,0), object(1,1)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 4438400,  storage_rebate: 2753784, non_refundable_storage_fee: 27816

task 4, lines 79-81:
//# run test::regulated_coin::partial_wrap --args object(1,1) --sender A
created: object(4,0)
mutated: object(0,0), object(1,1)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 4438400,  storage_rebate: 2753784, non_refundable_storage_fee: 27816

task 5, lines 82-84:
//# run sui::coin::deny_list_v2_enable_global_pause --args object(0x403) object(1,3) --type-args test::regulated_coin::REGULATED_COIN --sender A
events: Event { package_id: sui, transaction_module: Identifier("coin"), sender: A, type_: StructTag { address: sui, module: Identifier("deny_list"), name: Identifier("PerTypeConfigCreated"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0, 96, 48, 49, 101, 52, 48, 54, 50, 53, 54, 49, 55, 48, 50, 56, 100, 49, 57, 56, 55, 101, 56, 57, 50, 55, 54, 97, 100, 48, 57, 98, 49, 55, 98, 54, 102, 52, 57, 99, 101, 51, 56, 50, 100, 48, 102, 100, 49, 100, 49, 55, 98, 50, 99, 50, 100, 50, 48, 98, 100, 100, 52, 48, 97, 101, 58, 58, 114, 101, 103, 117, 108, 97, 116, 101, 100, 95, 99, 111, 105, 110, 58, 58, 82, 69, 71, 85, 76, 65, 84, 69, 68, 95, 67, 79, 73, 78, 207, 214, 9, 112, 148, 102, 221, 65, 156, 71, 110, 247, 42, 201, 148, 195, 78, 55, 90, 89, 136, 169, 6, 210, 230, 158, 253, 130, 69, 115, 127, 145] }
created: object(5,0), object(5,1), object(5,2)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 12304400,  storage_rebate: 3062268, non_refundable_storage_fee: 30932

task 6, lines 85-87:
//# run test::regulated_coin::assert_global_pause_status --args immshared(0x403) true --sender A
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 7, lines 88-90:
//# run sui::pay::split_and_transfer --args object(1,1) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,0)::regulated_coin::REGULATED_COIN" }

task 8, lines 91-93:
//# transfer-object 2,0 --sender B --recipient A
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,0)::regulated_coin::REGULATED_COIN" }

task 9, lines 94-97:
//# run sui::pay::split_and_transfer --args object(2,0) 1 @A --type-args test::regulated_coin::REGULATED_COIN --sender B
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,0)::regulated_coin::REGULATED_COIN" }

task 10, line 98:
//# run test::regulated_coin::unwrap --args object(3,0) --sender A
mutated: object(0,0)
unwrapped: object(10,0)
deleted: object(3,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2781600,  storage_rebate: 2934360, non_refundable_storage_fee: 29640

task 11, lines 100-103:
//# advance-epoch
Epoch advanced: 1

task 12, lines 104-106:
//# run test::regulated_coin::unwrap --args object(4,0) --sender A
Error: Transaction Effects Status: Coin type is globally paused for use: test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CoinTypeGlobalPause { coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 13, lines 107-109:
//# run sui::pay::split_and_transfer --args object(1,1) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
Error: Error checking transaction input objects: CoinTypeGlobalPause { coin_type: "object(1,0)::regulated_coin::REGULATED_COIN" }

task 14, lines 110-112:
//# run test::regulated_coin::assert_global_pause_status --args immshared(0x403) true --sender A
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 15, lines 113-115:
//# run sui::coin::deny_list_v2_disable_global_pause --args object(0x403) object(1,3) --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3), object(5,1)
gas summary: computation_cost: 1000000, storage_cost: 6976800,  storage_rebate: 6907032, non_refundable_storage_fee: 69768

task 16, lines 116-118:
//# run test::regulated_coin::assert_global_pause_status --args immshared(0x403) false --sender A
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 17, lines 119-121:
//# run sui::pay::split_and_transfer --args object(1,1) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
Error: Transaction Effects Status: Coin type is globally paused for use: test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CoinTypeGlobalPause { coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 18, lines 122-125:
//# run test::regulated_coin::full_wrap --args object(1,1) --sender A
created: object(18,0)
mutated: object(0,0)
wrapped: object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 2964000,  storage_rebate: 2753784, non_refundable_storage_fee: 27816

task 19, line 126:
//# run test::regulated_coin::unwrap --args object(18,0) --sender A
Error: Transaction Effects Status: Coin type is globally paused for use: test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CoinTypeGlobalPause { coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 20, lines 128-130:
//# advance-epoch
Epoch advanced: 2

task 21, line 131:
//# run test::regulated_coin::unwrap --args object(18,0) --sender A
mutated: object(0,0)
unwrapped: object(1,1)
deleted: object(18,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 2781600,  storage_rebate: 2934360, non_refundable_storage_fee: 29640
