processed 11 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 12-37:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 18711200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 38-40:
//# run sui::pay::split_and_transfer --args object(1,1) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(2,0)
mutated: object(0,0), object(1,1)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 4256000,  storage_rebate: 2753784, non_refundable_storage_fee: 27816

task 3, lines 41-43:
//# run sui::coin::deny_list_v2_add --args object(0x403) object(1,3) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
events: Event { package_id: sui, transaction_module: Identifier("coin"), sender: A, type_: StructTag { address: sui, module: Identifier("deny_list"), name: Identifier("PerTypeConfigCreated"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0, 96, 101, 55, 49, 100, 102, 50, 57, 56, 100, 101, 55, 100, 97, 50, 52, 56, 55, 97, 100, 55, 100, 101, 48, 55, 51, 49, 101, 49, 97, 55, 55, 54, 57, 100, 102, 98, 99, 54, 51, 100, 55, 97, 50, 99, 102, 53, 53, 100, 49, 56, 57, 48, 51, 99, 102, 54, 57, 100, 48, 57, 50, 102, 99, 57, 58, 58, 114, 101, 103, 117, 108, 97, 116, 101, 100, 95, 99, 111, 105, 110, 58, 58, 82, 69, 71, 85, 76, 65, 84, 69, 68, 95, 67, 79, 73, 78, 147, 197, 87, 27, 56, 224, 4, 6, 212, 10, 125, 127, 4, 70, 69, 197, 31, 229, 34, 1, 136, 59, 130, 216, 239, 115, 113, 181, 250, 216, 57, 10] }
created: object(3,0), object(3,1), object(3,2)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 12509600,  storage_rebate: 3062268, non_refundable_storage_fee: 30932

task 4, line 44:
//# run sui::pay::split_and_transfer --args object(1,1) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(4,0)
mutated: object(0,0), object(1,1)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 4256000,  storage_rebate: 2753784, non_refundable_storage_fee: 27816

task 5, lines 46-48:
//# advance-epoch
Epoch advanced: 1

task 6, lines 49-51:
//# run sui::pay::split_and_transfer --args object(1,1) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
Error: Transaction Effects Status: Address B is denied for coin test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: AddressDeniedForCoin { address: B, coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 7, lines 52-54:
//# run sui::coin::deny_list_v2_remove --args object(0x403) object(1,3) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3), object(3,1)
gas summary: computation_cost: 1000000, storage_cost: 7182000,  storage_rebate: 7110180, non_refundable_storage_fee: 71820

task 8, line 55:
//# run sui::pay::split_and_transfer --args object(1,1) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
Error: Transaction Effects Status: Address B is denied for coin test::regulated_coin::REGULATED_COIN
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: AddressDeniedForCoin { address: B, coin_type: "test::regulated_coin::REGULATED_COIN" }, source: None, command: None } }

task 9, lines 57-59:
//# advance-epoch
Epoch advanced: 2

task 10, line 60:
//# run sui::pay::split_and_transfer --args object(1,1) 1 @B --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(10,0)
mutated: object(0,0), object(1,1)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 4256000,  storage_rebate: 2753784, non_refundable_storage_fee: 27816
