processed 23 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 9-53:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 20748000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 54-56:
//# run sui::coin::deny_list_v2_add --args object(0x403) object(1,3) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
events: Event { package_id: sui, transaction_module: Identifier("coin"), sender: A, type_: StructTag { address: sui, module: Identifier("deny_list"), name: Identifier("PerTypeConfigCreated"), type_params: [] }, contents: [0, 0, 0, 0, 0, 0, 0, 0, 96, 49, 99, 100, 100, 50, 49, 102, 51, 57, 55, 101, 48, 101, 52, 52, 49, 53, 53, 53, 51, 57, 53, 97, 98, 54, 48, 98, 52, 55, 52, 52, 101, 98, 51, 50, 56, 52, 49, 100, 101, 49, 98, 56, 97, 53, 100, 56, 102, 49, 102, 55, 52, 100, 99, 48, 51, 54, 50, 49, 49, 49, 53, 49, 48, 58, 58, 114, 101, 103, 117, 108, 97, 116, 101, 100, 95, 99, 111, 105, 110, 58, 58, 82, 69, 71, 85, 76, 65, 84, 69, 68, 95, 67, 79, 73, 78, 154, 18, 11, 255, 97, 107, 24, 5, 226, 168, 20, 183, 129, 198, 62, 10, 249, 88, 53, 118, 76, 124, 226, 110, 184, 128, 63, 248, 221, 164, 22, 181] }
created: object(2,0), object(2,1), object(2,2)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 12509600,  storage_rebate: 3062268, non_refundable_storage_fee: 30932

task 3, lines 57-59:
//# run sui::coin::deny_list_v2_enable_global_pause --args object(0x403) object(1,3) --type-args test::regulated_coin::REGULATED_COIN --sender A
created: object(3,0)
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3)
gas summary: computation_cost: 1000000, storage_cost: 6976800,  storage_rebate: 4672404, non_refundable_storage_fee: 47196

task 4, line 60:
//# view-object 2,1
Owner: Object ID: ( BFC9a120bff616b1805e2a814b781c63e0af95835764c7ce26eb8803ff8dda416b500e9 )
Version: 3
Contents: sui::dynamic_field::Field<sui::deny_list::AddressKey, sui::config::Setting<bool>> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    name: sui::deny_list::AddressKey {
        pos0: B,
    },
    value: sui::config::Setting<bool> {
        data: std::option::Option<sui::config::SettingData<bool>> {
            vec: vector[
                sui::config::SettingData<bool> {
                    newer_value_epoch: 0u64,
                    newer_value: std::option::Option<bool> {
                        vec: vector[
                            true,
                        ],
                    },
                    older_value_opt: std::option::Option<bool> {
                        vec: vector[],
                    },
                },
            ],
        },
    },
}

task 5, line 62:
//# view-object 3,0
Owner: Object ID: ( BFC9a120bff616b1805e2a814b781c63e0af95835764c7ce26eb8803ff8dda416b500e9 )
Version: 4
Contents: sui::dynamic_field::Field<sui::deny_list::GlobalPauseKey, sui::config::Setting<bool>> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    name: sui::deny_list::GlobalPauseKey {
        dummy_field: false,
    },
    value: sui::config::Setting<bool> {
        data: std::option::Option<sui::config::SettingData<bool>> {
            vec: vector[
                sui::config::SettingData<bool> {
                    newer_value_epoch: 0u64,
                    newer_value: std::option::Option<bool> {
                        vec: vector[
                            true,
                        ],
                    },
                    older_value_opt: std::option::Option<bool> {
                        vec: vector[],
                    },
                },
            ],
        },
    },
}

task 6, lines 64-66:
//# advance-epoch
Epoch advanced: 1

task 7, lines 67-69:
//# run sui::coin::deny_list_v2_add --args object(0x403) object(1,3) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 7189600,  storage_rebate: 7110180, non_refundable_storage_fee: 71820

task 8, lines 70-72:
//# run sui::coin::deny_list_v2_enable_global_pause --args object(0x403) object(1,3) --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 6984400,  storage_rebate: 6907032, non_refundable_storage_fee: 69768

task 9, line 73:
//# view-object 2,1
Owner: Object ID: ( BFC9a120bff616b1805e2a814b781c63e0af95835764c7ce26eb8803ff8dda416b500e9 )
Version: 5
Contents: sui::dynamic_field::Field<sui::deny_list::AddressKey, sui::config::Setting<bool>> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    name: sui::deny_list::AddressKey {
        pos0: B,
    },
    value: sui::config::Setting<bool> {
        data: std::option::Option<sui::config::SettingData<bool>> {
            vec: vector[
                sui::config::SettingData<bool> {
                    newer_value_epoch: 1u64,
                    newer_value: std::option::Option<bool> {
                        vec: vector[
                            true,
                        ],
                    },
                    older_value_opt: std::option::Option<bool> {
                        vec: vector[
                            true,
                        ],
                    },
                },
            ],
        },
    },
}

task 10, line 75:
//# view-object 3,0
Owner: Object ID: ( BFC9a120bff616b1805e2a814b781c63e0af95835764c7ce26eb8803ff8dda416b500e9 )
Version: 6
Contents: sui::dynamic_field::Field<sui::deny_list::GlobalPauseKey, sui::config::Setting<bool>> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    name: sui::deny_list::GlobalPauseKey {
        dummy_field: false,
    },
    value: sui::config::Setting<bool> {
        data: std::option::Option<sui::config::SettingData<bool>> {
            vec: vector[
                sui::config::SettingData<bool> {
                    newer_value_epoch: 1u64,
                    newer_value: std::option::Option<bool> {
                        vec: vector[
                            true,
                        ],
                    },
                    older_value_opt: std::option::Option<bool> {
                        vec: vector[
                            true,
                        ],
                    },
                },
            ],
        },
    },
}

task 11, lines 77-79:
//# advance-epoch
Epoch advanced: 2

task 12, lines 80-82:
//# run sui::coin::deny_list_v2_remove --args object(0x403) object(1,3) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 7182000,  storage_rebate: 7117704, non_refundable_storage_fee: 71896

task 13, lines 83-85:
//# run sui::coin::deny_list_v2_disable_global_pause --args object(0x403) object(1,3) --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 6976800,  storage_rebate: 6914556, non_refundable_storage_fee: 69844

task 14, line 86:
//# view-object 2,1
Owner: Object ID: ( BFC9a120bff616b1805e2a814b781c63e0af95835764c7ce26eb8803ff8dda416b500e9 )
Version: 7
Contents: sui::dynamic_field::Field<sui::deny_list::AddressKey, sui::config::Setting<bool>> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    name: sui::deny_list::AddressKey {
        pos0: B,
    },
    value: sui::config::Setting<bool> {
        data: std::option::Option<sui::config::SettingData<bool>> {
            vec: vector[
                sui::config::SettingData<bool> {
                    newer_value_epoch: 2u64,
                    newer_value: std::option::Option<bool> {
                        vec: vector[],
                    },
                    older_value_opt: std::option::Option<bool> {
                        vec: vector[
                            true,
                        ],
                    },
                },
            ],
        },
    },
}

task 15, line 88:
//# view-object 3,0
Owner: Object ID: ( BFC9a120bff616b1805e2a814b781c63e0af95835764c7ce26eb8803ff8dda416b500e9 )
Version: 8
Contents: sui::dynamic_field::Field<sui::deny_list::GlobalPauseKey, sui::config::Setting<bool>> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    name: sui::deny_list::GlobalPauseKey {
        dummy_field: false,
    },
    value: sui::config::Setting<bool> {
        data: std::option::Option<sui::config::SettingData<bool>> {
            vec: vector[
                sui::config::SettingData<bool> {
                    newer_value_epoch: 2u64,
                    newer_value: std::option::Option<bool> {
                        vec: vector[],
                    },
                    older_value_opt: std::option::Option<bool> {
                        vec: vector[
                            true,
                        ],
                    },
                },
            ],
        },
    },
}

task 16, lines 90-92:
//# advance-epoch
Epoch advanced: 3

task 17, lines 93-95:
//# run sui::coin::deny_list_v2_remove --args object(0x403) object(1,3) @B --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3)
deleted: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 4719600,  storage_rebate: 7110180, non_refundable_storage_fee: 71820

task 18, lines 96-98:
//# run sui::coin::deny_list_v2_disable_global_pause --args object(0x403) object(1,3) --type-args test::regulated_coin::REGULATED_COIN --sender A
mutated: 0x0000000000000000000000000000000000000000000000000000000000000403, object(0,0), object(1,3)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 4719600,  storage_rebate: 6907032, non_refundable_storage_fee: 69768

task 19, line 99:
//# view-object 2,1
No object at id 2,1

task 20, lines 101-103:
//# view-object 3,0
No object at id 3,0

task 21, lines 104-106:
//# run test::regulated_coin::assert_address_deny_status --args immshared(0x403) @B false --sender A
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 22, line 107:
//# run test::regulated_coin::assert_global_pause_status --args immshared(0x403) false --sender A
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072
