processed 21 tasks

init:
A: object(0,0)

task 1, lines 6-16:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6634800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 18:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 20-199:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "HPgwMqphBgyveVmgNSfe2fbmeko1NuDwzgFG1TFEpRVo",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "ABCgX/aAFqQHMjKycxEj+WFjOFGq6aCfGwBAZwRB+7K20rRdFbUjaHFyGWHyEZo2OjjMWBzXIxm6cW5yZ26ciQp/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "PublishTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 0
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "C5pLchDXyUAW4ZP4HDy9y8puGQWc57ktZ94iCUz1GFV1"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-7634800",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x800ac628f43658bc6e0a7a3ded09f2c5cc6c4758f25a1295ac2c6e20ff9a0b02",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x800ac628f43658bc6e0a7a3ded09f2c5cc6c4758f25a1295ac2c6e20ff9a0b02",
                    "digest": "MXmoGTmB1Gf3EQV5qTgA1Ri4obZmgHWKtkcZ77iwcnE"
                  }
                },
                {
                  "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6",
                    "digest": "F11a72j4xq1NLvu2aXxyTE9sHhtRk3B3ywGoAJKVnw2P"
                  }
                },
                {
                  "address": "0xdcd57cbf1b86bf5ee867bc492f195b3c43211a934f0df38b8963201bb391908a",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xdcd57cbf1b86bf5ee867bc492f195b3c43211a934f0df38b8963201bb391908a",
                    "digest": "35HeufSiPqDpsH8BJiVpAXPFYmZ9KkcsRAtCcrroEQnb"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6634800",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "HPgwMqphBgyveVmgNSfe2fbmeko1NuDwzgFG1TFEpRVo"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4, lines 201-216:
//# upgrade --package P0 --upgrade-capability 1,1 --sender A
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 7455600,  storage_rebate: 2911788, non_refundable_storage_fee: 29412

task 5, line 218:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 220-399:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "5PXTjZnjcuZ1nLzkcdhZLnTVGDdP99hRp771xhwdsJ3e",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AMIQpaPuxCVBwgRIRfeHXpwixlgumXmexbTcgP1d8mjEgNjYvsBN3NoWKX0iX9RuRM1YLOStPGOjAC30zvtH6QJ/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "OwnedOrImmutable",
                    "address": "0xdcd57cbf1b86bf5ee867bc492f195b3c43211a934f0df38b8963201bb391908a",
                    "version": 2,
                    "digest": "35HeufSiPqDpsH8BJiVpAXPFYmZ9KkcsRAtCcrroEQnb",
                    "object": {
                      "address": "0xdcd57cbf1b86bf5ee867bc492f195b3c43211a934f0df38b8963201bb391908a",
                      "version": 2,
                      "digest": "35HeufSiPqDpsH8BJiVpAXPFYmZ9KkcsRAtCcrroEQnb",
                      "asMoveObject": {
                        "contents": {
                          "type": {
                            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                          },
                          "json": {
                            "id": "0xdcd57cbf1b86bf5ee867bc492f195b3c43211a934f0df38b8963201bb391908a",
                            "package": "0x800ac628f43658bc6e0a7a3ded09f2c5cc6c4758f25a1295ac2c6e20ff9a0b02",
                            "version": "1",
                            "policy": 0
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "AA=="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "IB06uIxstE0kmZjT+jfH3kN+iYnrghz7dagHvA6967Uh"
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "authorize_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "u8"
                        },
                        {
                          "repr": "vector<u8>"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "UpgradeTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002",
                      "0x00000000000000000000000000000000000000000000000000000000000000c8"
                    ],
                    "currentPackage": "0x800ac628f43658bc6e0a7a3ded09f2c5cc6c4758f25a1295ac2c6e20ff9a0b02",
                    "upgradeTicket": {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "commit_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                        }
                      ],
                      "return": []
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": {
              "nodes": [
                {
                  "digest": "C5pLchDXyUAW4ZP4HDy9y8puGQWc57ktZ94iCUz1GFV1"
                },
                {
                  "digest": "HPgwMqphBgyveVmgNSfe2fbmeko1NuDwzgFG1TFEpRVo"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-5543812",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6",
                    "digest": "8YxV8upRyNEdHsaCX6tnEACxyyCuaUha6up4LHKecQpw"
                  }
                },
                {
                  "address": "0xdcd57cbf1b86bf5ee867bc492f195b3c43211a934f0df38b8963201bb391908a",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xdcd57cbf1b86bf5ee867bc492f195b3c43211a934f0df38b8963201bb391908a",
                    "digest": "6yNthV12RzVFvyEJxHpNeTQC2fjLokYr3EwWFsE44i9g"
                  }
                },
                {
                  "address": "0xf7a007227be1e5bfb8c842c515fa1e7f3e2c1dd5403bde48d723886703a1e3c2",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xf7a007227be1e5bfb8c842c515fa1e7f3e2c1dd5403bde48d723886703a1e3c2",
                    "digest": "3k5PZsY3kmSQCbLsTtHRDZQYnvB6qyYiUeXMzxNWGEQV"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "7455600",
                "storageRebate": "2911788",
                "nonRefundableStorageFee": "29412"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "5PXTjZnjcuZ1nLzkcdhZLnTVGDdP99hRp771xhwdsJ3e"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7, lines 401-404:
//# programmable --sender A --inputs 41u64 @A
//> 0: MakeMoveVec<u64>([Input(0)]);
//> 1: P0::m::new(Result(0));
//> sui::transfer::public_transfer<P0::m::Foo>(Result(1), Input(1))
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2599200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 8, lines 406-415:
//# programmable --sender A --inputs 42u64 43u64 1000 @A
//> 0: MakeMoveVec<u64>([Input(0), Input(1)]);
//> 1: MakeMoveVec<u64>([]);
//> 2: SplitCoins(Gas, [Input(2), Input(2)]);
//> 3: P0::m::new(Result(0));
//> 4: TransferObjects([Result(3)], Input(3));
//> 5: P0::m::new(Result(1));
//> 6: P0::m::burn(Result(5));
//> 7: MergeCoins(NestedResult(2,0), [NestedResult(2,1)]);
//> TransferObjects([NestedResult(2,0)], Input(3))
created: object(8,0), object(8,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3967200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 9, line 417:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 419-607:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "2LGbDg6G1w9L7aLpAGi7W3b74gZpqHki8r4LiVkmKfHr",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AC+Ez41DEtSPAjcTw2clO3Z3Ow95l9daQC/nT09btPsdmh36PsB98r7/aE5vxPqOE3L0hOCSGgNIoEPKJpqcvQR/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KgAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KwAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": []
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 2
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xf7a007227be1e5bfb8c842c515fa1e7f3e2c1dd5403bde48d723886703a1e3c2",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x800ac628f43658bc6e0a7a3ded09f2c5cc6c4758f25a1295ac2c6e20ff9a0b02::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 3,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xf7a007227be1e5bfb8c842c515fa1e7f3e2c1dd5403bde48d723886703a1e3c2",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x800ac628f43658bc6e0a7a3ded09f2c5cc6c4758f25a1295ac2c6e20ff9a0b02::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0xf7a007227be1e5bfb8c842c515fa1e7f3e2c1dd5403bde48d723886703a1e3c2",
                    "module": "m",
                    "functionName": "burn",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 5,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "0x800ac628f43658bc6e0a7a3ded09f2c5cc6c4758f25a1295ac2c6e20ff9a0b02::m::Foo"
                        }
                      ],
                      "return": []
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjozfQ",
                  "node": {
                    "__typename": "MergeCoinsTransaction",
                    "coin": {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    },
                    "coins": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 0
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 5,
            "dependencies": {
              "nodes": [
                {
                  "digest": "2xdGZCxuTsZYWjDgCnZ55F37jQrr6McsjLDNBASiBPQz"
                },
                {
                  "digest": "5PXTjZnjcuZ1nLzkcdhZLnTVGDdP99hRp771xhwdsJ3e"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-3673072",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x44bb594477fa61fbfa3b61627878f69fa76e583e79dfdf2f34fb23a8c04aa45f",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x44bb594477fa61fbfa3b61627878f69fa76e583e79dfdf2f34fb23a8c04aa45f",
                    "digest": "tT71EbrL2WoudNfMtaNrpbJEFSaZoN8hUMUhRV6yUXC",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "json": {
                          "id": "0x44bb594477fa61fbfa3b61627878f69fa76e583e79dfdf2f34fb23a8c04aa45f",
                          "balance": {
                            "value": "2000"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0x6370d9d947d2f138d3e1b1f27c8ff69e697e80f761f80e1aec170990bd9361d2",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6370d9d947d2f138d3e1b1f27c8ff69e697e80f761f80e1aec170990bd9361d2",
                    "digest": "F8YbmuZY5qLzv7mRzhzr7xP6HFG8coXmUPNHpruWRYhi",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x800ac628f43658bc6e0a7a3ded09f2c5cc6c4758f25a1295ac2c6e20ff9a0b02::m::Foo"
                        },
                        "json": {
                          "id": "0x6370d9d947d2f138d3e1b1f27c8ff69e697e80f761f80e1aec170990bd9361d2",
                          "xs": [
                            "42",
                            "43"
                          ]
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6",
                    "digest": "CeE87cQoHcFEm4jiniqJXciZoFYK3RsqNb4r8HRBQEvq",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "json": {
                          "id": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6",
                          "balance": {
                            "value": "299999980841244"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3967200",
                "storageRebate": "1294128",
                "nonRefundableStorageFee": "13072"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "2LGbDg6G1w9L7aLpAGi7W3b74gZpqHki8r4LiVkmKfHr"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 11, lines 609-610:
//# programmable --sender A --inputs 1000
//> SplitCoins(Gas, [Input(0)])
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 12, line 612:
//# create-checkpoint
Checkpoint created: 4

task 13, lines 614-793:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "5bHbgksazUgwkSuSFLLLyCrTSia2BUW54mKvLZfkvjxa",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "ADlxyy0xZjMGBNJ52BY1ZUJfVIPEHdij8KpvQEuRapBwyHAldHKkTC24NBJF+GZ/ub1MmIszmBRY7zbzA6A56wF/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      }
                    ]
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 6,
            "dependencies": {
              "nodes": [
                {
                  "digest": "2LGbDg6G1w9L7aLpAGi7W3b74gZpqHki8r4LiVkmKfHr"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-1013072",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6",
                    "digest": "2Vz2BWJVorW63LFwwWpkqwR6rTcHYDAiVP8evVJeZiPK"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0x9f239c7c62033824d92c6d17a96c308e66833c98b4292161ebea96d151ebb8f6"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "1307200",
                "storageRebate": "1294128",
                "nonRefundableStorageFee": "13072"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "5bHbgksazUgwkSuSFLLLyCrTSia2BUW54mKvLZfkvjxa"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 14, lines 795-805:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 15, lines 807-817:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        }
      ]
    }
  }
}

task 16, lines 819-829:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 17, lines 831-838:
//# run-graphql
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": []
      }
    }
  }
}

task 18, lines 840-845:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0"
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}

task 19, lines 847-852:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}

task 20, lines 854-864:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}
