processed 21 tasks

init:
A: object(0,0)

task 1, lines 6-16:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6634800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 18:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 20-199:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "93JdoDHmyzn3tPqRWenboFBftW5uTLvsHDcJUtpkCXVh",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AP18PyoqfJzVSOyMIz7oQ28gaa8rk1vS6hE7s5V22kOT3kkOV0I+IsLAgwDv/k8K7a23FFs29SXfdoR5ZWp0XAR/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "PublishTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 0
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "AfXjHJLFUSWbh6G6XQVFi1SwCR5vJwiuSYyXckh7DyjV"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-7634800",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x89a6ad22137aecce2ec53b759101412fd83f047803543ae73dc15702edb3fd16",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x89a6ad22137aecce2ec53b759101412fd83f047803543ae73dc15702edb3fd16",
                    "digest": "9a7yqG3piNuQfEeMDVyryPraLKRzBbqdVqcbwfh6VGoB"
                  }
                },
                {
                  "address": "0x93e7953f3907b9cf290c4d6511716abecb06644d4e660e08f7fb4adcd5a38e4f",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x93e7953f3907b9cf290c4d6511716abecb06644d4e660e08f7fb4adcd5a38e4f",
                    "digest": "ERmNUdD5Hq64ijehrDxxVRpHEgyASSmSdXfPpEE2BEsX"
                  }
                },
                {
                  "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa",
                    "digest": "HRfn2t1RGJB4NzvK8mpHWqEV6BZBakmBEWfCCBgPbFdv"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6634800",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "93JdoDHmyzn3tPqRWenboFBftW5uTLvsHDcJUtpkCXVh"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4, lines 201-216:
//# upgrade --package P0 --upgrade-capability 1,1 --sender A
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 7455600,  storage_rebate: 2911788, non_refundable_storage_fee: 29412

task 5, line 218:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 220-399:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "2fPPMmoS7ZWxLGj8efq1QYY4fec3mNztHWy2jgQhhNDC",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AIY2wTp6yN/gNa19curJPFFEi1f2JL/p4b1Go7XZrSFPUM3I308SFyvf86jRrqyN/URWFMnrCkilPSZ6Axo1Uwp/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "OwnedOrImmutable",
                    "address": "0x89a6ad22137aecce2ec53b759101412fd83f047803543ae73dc15702edb3fd16",
                    "version": 2,
                    "digest": "9a7yqG3piNuQfEeMDVyryPraLKRzBbqdVqcbwfh6VGoB",
                    "object": {
                      "address": "0x89a6ad22137aecce2ec53b759101412fd83f047803543ae73dc15702edb3fd16",
                      "version": 2,
                      "digest": "9a7yqG3piNuQfEeMDVyryPraLKRzBbqdVqcbwfh6VGoB",
                      "asMoveObject": {
                        "contents": {
                          "type": {
                            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                          },
                          "json": {
                            "id": "0x89a6ad22137aecce2ec53b759101412fd83f047803543ae73dc15702edb3fd16",
                            "package": "0x93e7953f3907b9cf290c4d6511716abecb06644d4e660e08f7fb4adcd5a38e4f",
                            "version": "1",
                            "policy": 0
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "AA=="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "IB06uIxstE0kmZjT+jfH3kN+iYnrghz7dagHvA6967Uh"
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "authorize_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "u8"
                        },
                        {
                          "repr": "vector<u8>"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "UpgradeTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002",
                      "0x00000000000000000000000000000000000000000000000000000000000000c8"
                    ],
                    "currentPackage": "0x93e7953f3907b9cf290c4d6511716abecb06644d4e660e08f7fb4adcd5a38e4f",
                    "upgradeTicket": {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "commit_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                        }
                      ],
                      "return": []
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": {
              "nodes": [
                {
                  "digest": "93JdoDHmyzn3tPqRWenboFBftW5uTLvsHDcJUtpkCXVh"
                },
                {
                  "digest": "AfXjHJLFUSWbh6G6XQVFi1SwCR5vJwiuSYyXckh7DyjV"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-5543812",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x730c1b2d5a07244404ebd4bc6a5c95495478bd10e621f6d89e13ac672cda92b1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x730c1b2d5a07244404ebd4bc6a5c95495478bd10e621f6d89e13ac672cda92b1",
                    "digest": "HQWWAh8JkZVhWDHvSTLaFTPM5N1w7GopuzK8KFEpDTH2"
                  }
                },
                {
                  "address": "0x89a6ad22137aecce2ec53b759101412fd83f047803543ae73dc15702edb3fd16",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x89a6ad22137aecce2ec53b759101412fd83f047803543ae73dc15702edb3fd16",
                    "digest": "4SAfSYnqFfaaow3pcZtghZdD55LtpePtifyBcg65kQ4t"
                  }
                },
                {
                  "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa",
                    "digest": "Gi5WvqSfCJiUKd1L2AmL2QuX718H2wWS8nmCKygEsD4Y"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "7455600",
                "storageRebate": "2911788",
                "nonRefundableStorageFee": "29412"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "2fPPMmoS7ZWxLGj8efq1QYY4fec3mNztHWy2jgQhhNDC"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7, lines 401-404:
//# programmable --sender A --inputs 41u64 @A
//> 0: MakeMoveVec<u64>([Input(0)]);
//> 1: P0::m::new(Result(0));
//> sui::transfer::public_transfer<P0::m::Foo>(Result(1), Input(1))
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2599200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 8, lines 406-415:
//# programmable --sender A --inputs 42u64 43u64 1000 @A
//> 0: MakeMoveVec<u64>([Input(0), Input(1)]);
//> 1: MakeMoveVec<u64>([]);
//> 2: SplitCoins(Gas, [Input(2), Input(2)]);
//> 3: P0::m::new(Result(0));
//> 4: TransferObjects([Result(3)], Input(3));
//> 5: P0::m::new(Result(1));
//> 6: P0::m::burn(Result(5));
//> 7: MergeCoins(NestedResult(2,0), [NestedResult(2,1)]);
//> TransferObjects([NestedResult(2,0)], Input(3))
created: object(8,0), object(8,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3967200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 9, line 417:
//# create-checkpoint
Checkpoint created: 3

task 10, lines 419-607:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "4hdy6PNpnM9mvmviiSkPn1yVtghb13nPAVy2tLeKvZgG",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AHgcJTcGbQUBPHnrXkbCKAfPPmuinBGIixh0Edl4gSvgCfO/C4YPYLeKARt8LzQTMbKHS+GI15ACF3owH2vP+AB/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KgAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KwAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": []
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 2
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x730c1b2d5a07244404ebd4bc6a5c95495478bd10e621f6d89e13ac672cda92b1",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x93e7953f3907b9cf290c4d6511716abecb06644d4e660e08f7fb4adcd5a38e4f::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 3,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x730c1b2d5a07244404ebd4bc6a5c95495478bd10e621f6d89e13ac672cda92b1",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x93e7953f3907b9cf290c4d6511716abecb06644d4e660e08f7fb4adcd5a38e4f::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x730c1b2d5a07244404ebd4bc6a5c95495478bd10e621f6d89e13ac672cda92b1",
                    "module": "m",
                    "functionName": "burn",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 5,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "0x93e7953f3907b9cf290c4d6511716abecb06644d4e660e08f7fb4adcd5a38e4f::m::Foo"
                        }
                      ],
                      "return": []
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjozfQ",
                  "node": {
                    "__typename": "MergeCoinsTransaction",
                    "coin": {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    },
                    "coins": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 0
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 5,
            "dependencies": {
              "nodes": [
                {
                  "digest": "2fPPMmoS7ZWxLGj8efq1QYY4fec3mNztHWy2jgQhhNDC"
                },
                {
                  "digest": "FVkPLKsxUwLP5ZrZQxijNFFmdKaRWHA8HpM5uMdUtA2i"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-3673072",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x5576db321c52a2e4067f6f818b39a02e5e6ad214d8432c12b34f757292515e02",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5576db321c52a2e4067f6f818b39a02e5e6ad214d8432c12b34f757292515e02",
                    "digest": "CiTZhaTNmrbYYAgxmVWDY84CqU2qETkddZLBAN3ncMZL",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "json": {
                          "id": "0x5576db321c52a2e4067f6f818b39a02e5e6ad214d8432c12b34f757292515e02",
                          "balance": {
                            "value": "2000"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa",
                    "digest": "HL42shS1qF9QasHWMiL6hnU2SHa3YjT9N8GHc1hAsv9e",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "json": {
                          "id": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa",
                          "balance": {
                            "value": "299999980841244"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0xd76bf28ca50c5d68f0b8570254eb538687dd0b2956abae07db1ea713d6def0e2",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xd76bf28ca50c5d68f0b8570254eb538687dd0b2956abae07db1ea713d6def0e2",
                    "digest": "ENgaz1hVVKMPFaYXb8WJfTtx7XgnKsttqk52Sity82Pd",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x93e7953f3907b9cf290c4d6511716abecb06644d4e660e08f7fb4adcd5a38e4f::m::Foo"
                        },
                        "json": {
                          "id": "0xd76bf28ca50c5d68f0b8570254eb538687dd0b2956abae07db1ea713d6def0e2",
                          "xs": [
                            "42",
                            "43"
                          ]
                        }
                      }
                    }
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3967200",
                "storageRebate": "1294128",
                "nonRefundableStorageFee": "13072"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "4hdy6PNpnM9mvmviiSkPn1yVtghb13nPAVy2tLeKvZgG"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 11, lines 609-610:
//# programmable --sender A --inputs 1000
//> SplitCoins(Gas, [Input(0)])
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 12, line 612:
//# create-checkpoint
Checkpoint created: 4

task 13, lines 614-793:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "GLJoDLRBczZTGQJ3eHr1YLNhhvDc2yqCrsCB1dkb3QTC",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AIU5HYjHOtKKhrch5TlrBROOIiomMPNmylARY1ovEOaLFBsnq8Y18UCgB7byTvaYa5j0ACNfU9M9ptE50OyKKQd/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      }
                    ]
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 6,
            "dependencies": {
              "nodes": [
                {
                  "digest": "4hdy6PNpnM9mvmviiSkPn1yVtghb13nPAVy2tLeKvZgG"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-1013072",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa",
                    "digest": "B3seLb9gkTNVDtdP4hLA3KkNrp4pn21JWSFiia5ZN6Jd"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xc18fe51e64b31297312e98e363a03f2018bcb862a028763b347bea4175f42afa"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "1307200",
                "storageRebate": "1294128",
                "nonRefundableStorageFee": "13072"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "GLJoDLRBczZTGQJ3eHr1YLNhhvDc2yqCrsCB1dkb3QTC"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 14, lines 795-805:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 15, lines 807-817:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        }
      ]
    }
  }
}

task 16, lines 819-829:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoxLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1LCJpIjpmYWxzZX0",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 17, lines 831-838:
//# run-graphql
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": []
      }
    }
  }
}

task 18, lines 840-845:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyLCJpIjpmYWxzZX0"
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}

task 19, lines 847-852:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0LCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}

task 20, lines 854-864:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozLCJpIjpmYWxzZX0"
        }
      ]
    }
  }
}
