processed 7 tasks

task 1, lines 6-22:
//# publish
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7182000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 24-25:
//# programmable --inputs immshared(1,0)
//> 0: P0::m::get(Input(0))
mutated: object(0,0)
unchanged_shared: object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 27-28:
//# programmable --inputs object(1,0)
//> 0: P0::m::inc(Input(0))
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 2565684, non_refundable_storage_fee: 25916

task 4, lines 30-32:
//# programmable --inputs object(1,0)
//> 0: P0::m::get(Input(0));
//> P0::m::inc(Input(0))
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 2565684, non_refundable_storage_fee: 25916

task 5, line 34:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 36-84:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xdc07d42c89e9d12bbf466c6c524c9c42ec9f34ea80b29bfb91bedd88118179df",
                  "module": "m",
                  "functionName": "get"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": [
                {
                  "__typename": "SharedObjectRead",
                  "address": "0xabb5fdee53fe6c44e1c40d5b40516323d283f3fbd2e13774eeaebd869a4f4cac",
                  "version": 2,
                  "digest": "DZ444sBUBFTjfc8o1YRa3PVJ72gAAJ8U5BiyhwNiNWbL",
                  "object": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xdc07d42c89e9d12bbf466c6c524c9c42ec9f34ea80b29bfb91bedd88118179df::m::Foo"
                        },
                        "json": {
                          "id": "0xabb5fdee53fe6c44e1c40d5b40516323d283f3fbd2e13774eeaebd869a4f4cac",
                          "x": "0"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xdc07d42c89e9d12bbf466c6c524c9c42ec9f34ea80b29bfb91bedd88118179df",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xdc07d42c89e9d12bbf466c6c524c9c42ec9f34ea80b29bfb91bedd88118179df",
                  "module": "m",
                  "functionName": "get"
                },
                {
                  "package": "0xdc07d42c89e9d12bbf466c6c524c9c42ec9f34ea80b29bfb91bedd88118179df",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        }
      ]
    }
  }
}
