processed 7 tasks

task 1, lines 6-22:
//# publish
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7182000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 24-25:
//# programmable --inputs immshared(1,0)
//> 0: P0::m::get(Input(0))
mutated: object(0,0)
unchanged_shared: object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 27-28:
//# programmable --inputs object(1,0)
//> 0: P0::m::inc(Input(0))
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 2565684, non_refundable_storage_fee: 25916

task 4, lines 30-32:
//# programmable --inputs object(1,0)
//> 0: P0::m::get(Input(0));
//> P0::m::inc(Input(0))
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 2565684, non_refundable_storage_fee: 25916

task 5, line 34:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 36-84:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0x9cb56c94f05bc9e5e53322b0496032b84ed25bc3d61e4fde48dc3a2ad28d3a41",
                  "module": "m",
                  "functionName": "get"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": [
                {
                  "__typename": "SharedObjectRead",
                  "address": "0xf75d1f1a83d1f2b85dcec710f249c2dd15eab2df5679f3e81640ffad96da5f0f",
                  "version": 2,
                  "digest": "6TqZRAA5KPH8xzPb1GNrreCCBZxnrpRchMxfP1CsBNaW",
                  "object": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x9cb56c94f05bc9e5e53322b0496032b84ed25bc3d61e4fde48dc3a2ad28d3a41::m::Foo"
                        },
                        "json": {
                          "id": "0xf75d1f1a83d1f2b85dcec710f249c2dd15eab2df5679f3e81640ffad96da5f0f",
                          "x": "0"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0x9cb56c94f05bc9e5e53322b0496032b84ed25bc3d61e4fde48dc3a2ad28d3a41",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0x9cb56c94f05bc9e5e53322b0496032b84ed25bc3d61e4fde48dc3a2ad28d3a41",
                  "module": "m",
                  "functionName": "get"
                },
                {
                  "package": "0x9cb56c94f05bc9e5e53322b0496032b84ed25bc3d61e4fde48dc3a2ad28d3a41",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        }
      ]
    }
  }
}
