processed 8 tasks

task 1, lines 8-102:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "FXSSBjHgu4SZ78WHwXC2JRZYNsuCTEUEvs8j5k1SsKfj",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objects": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXNjaWkiLCJjIjowfQ",
                            "node": {
                              "name": "ascii"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYml0X3ZlY3RvciIsImMiOjB9",
                            "node": {
                              "name": "bit_vector"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVidWciLCJjIjowfQ",
                            "node": {
                              "name": "debug"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZml4ZWRfcG9pbnQzMiIsImMiOjB9",
                            "node": {
                              "name": "fixed_point32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaGFzaCIsImMiOjB9",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWFjcm9zIiwiYyI6MH0",
                            "node": {
                              "name": "macros"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3B0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "option"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RyaW5nIiwiYyI6MH0",
                            "node": {
                              "name": "string"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHlwZV9uYW1lIiwiYyI6MH0",
                            "node": {
                              "name": "type_name"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTEyOCIsImMiOjB9",
                            "node": {
                              "name": "u128"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTE2IiwiYyI6MH0",
                            "node": {
                              "name": "u16"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTI1NiIsImMiOjB9",
                            "node": {
                              "name": "u256"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTMyIiwiYyI6MH0",
                            "node": {
                              "name": "u32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTY0IiwiYyI6MH0",
                            "node": {
                              "name": "u64"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTgiLCJjIjowfQ",
                            "node": {
                              "name": "u8"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmVjdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "vector"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXV0aGVudGljYXRvcl9zdGF0ZSIsImMiOjB9",
                            "node": {
                              "name": "authenticator_state"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFnIiwiYyI6MH0",
                            "node": {
                              "name": "bag"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFsYW5jZSIsImMiOjB9",
                            "node": {
                              "name": "balance"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjIiwiYyI6MH0",
                            "node": {
                              "name": "bfc"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmxzMTIzODEiLCJjIjowfQ",
                            "node": {
                              "name": "bls12381"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm9ycm93IiwiYyI6MH0",
                            "node": {
                              "name": "borrow"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvY2siLCJjIjowfQ",
                            "node": {
                              "name": "clock"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbiIsImMiOjB9",
                            "node": {
                              "name": "coin"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29uZmlnIiwiYyI6MH0",
                            "node": {
                              "name": "config"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3VydmUiLCJjIjowfQ",
                            "node": {
                              "name": "curve"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVueV9saXN0IiwiYyI6MH0",
                            "node": {
                              "name": "deny_list"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGlzcGxheSIsImMiOjB9",
                            "node": {
                              "name": "display"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19maWVsZCIsImMiOjB9",
                            "node": {
                              "name": "dynamic_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19vYmplY3RfZmllbGQiLCJjIjowfQ",
                            "node": {
                              "name": "dynamic_object_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfazEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_k1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfcjEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_r1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWN2cmYiLCJjIjowfQ",
                            "node": {
                              "name": "ecvrf"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWQyNTUxOSIsImMiOjB9",
                            "node": {
                              "name": "ed25519"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiZ2VuZXNpcyIsImMiOjB9",
                            "node": {
                              "name": "genesis"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RhYmxlX3Bvb2wiLCJjIjowfQ",
                            "node": {
                              "name": "stable_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2Vfc3Vic2lkeSIsImMiOjB9",
                            "node": {
                              "name": "stake_subsidy"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2luZ19wb29sIiwiYyI6MH0",
                            "node": {
                              "name": "staking_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9mdW5kIiwiYyI6MH0",
                            "node": {
                              "name": "storage_fund"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3VpX3N5c3RlbSIsImMiOjB9",
                            "node": {
                              "name": "sui_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3VpX3N5c3RlbV9zdGF0ZV9pbm5lciIsImMiOjB9",
                            "node": {
                              "name": "sui_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "validator"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX2NhcCIsImMiOjB9",
                            "node": {
                              "name": "validator_cap"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3NldCIsImMiOjB9",
                            "node": {
                              "name": "validator_set"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3dyYXBwZXIiLCJjIjowfQ",
                            "node": {
                              "name": "validator_wrapper"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidm90aW5nX3Bvd2VyIiwiYyI6MH0",
                            "node": {
                              "name": "voting_power"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::sui_system::SuiSystemState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                          "version": "1",
                          "bfc_system_id": "0x00000000000000000000000000000000000000000000000000000000000000c9"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                          "timestamp_ms": "0"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000007",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                          "inner": {
                            "id": "0x02dcaca118fd03983bd92e749c37464a9bad35af266da5e3e63807ee1094a896",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000009",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x000000000000000000000000000000000000000000000000000000000000000b::bridge::Bridge"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000009",
                          "inner": {
                            "id": "0xd50e7b8809e6de08dace9fc354de2375c049e571984d739ed5517269d6f17e77",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYnJpZGdlIiwiYyI6MH0",
                            "node": {
                              "name": "bridge"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2hhaW5faWRzIiwiYyI6MH0",
                            "node": {
                              "name": "chain_ids"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29tbWl0dGVlIiwiYyI6MH0",
                            "node": {
                              "name": "committee"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3J5cHRvIiwiYyI6MH0",
                            "node": {
                              "name": "crypto"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibGltaXRlciIsImMiOjB9",
                            "node": {
                              "name": "limiter"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZSIsImMiOjB9",
                            "node": {
                              "name": "message"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZV90eXBlcyIsImMiOjB9",
                            "node": {
                              "name": "message_types"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHJlYXN1cnkiLCJjIjowfQ",
                            "node": {
                              "name": "treasury"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo5LCJjIjowfQ",
                  "node": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c8",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYmFycyIsImMiOjB9",
                            "node": {
                              "name": "bars"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmF1ZCIsImMiOjB9",
                            "node": {
                              "name": "baud"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmJybCIsImMiOjB9",
                            "node": {
                              "name": "bbrl"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNhZCIsImMiOjB9",
                            "node": {
                              "name": "bcad"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmV1ciIsImMiOjB9",
                            "node": {
                              "name": "beur"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX2RhbyIsImMiOjB9",
                            "node": {
                              "name": "bfc_dao"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX2Rhb19tYW5hZ2VyIiwiYyI6MH0",
                            "node": {
                              "name": "bfc_dao_manager"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX3N5c3RlbSIsImMiOjB9",
                            "node": {
                              "name": "bfc_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX3N5c3RlbV9zdGF0ZV9pbm5lciIsImMiOjB9",
                            "node": {
                              "name": "bfc_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmdicCIsImMiOjB9",
                            "node": {
                              "name": "bgbp"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmlkciIsImMiOjB9",
                            "node": {
                              "name": "bidr"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmluciIsImMiOjB9",
                            "node": {
                              "name": "binr"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmpweSIsImMiOjB9",
                            "node": {
                              "name": "bjpy"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmtydyIsImMiOjB9",
                            "node": {
                              "name": "bkrw"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm14biIsImMiOjB9",
                            "node": {
                              "name": "bmxn"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnJ1YiIsImMiOjB9",
                            "node": {
                              "name": "brub"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnNhciIsImMiOjB9",
                            "node": {
                              "name": "bsar"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnRyeSIsImMiOjB9",
                            "node": {
                              "name": "btry"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnVzZCIsImMiOjB9",
                            "node": {
                              "name": "busd"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnphciIsImMiOjB9",
                            "node": {
                              "name": "bzar"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxMCwiYyI6MH0",
                  "node": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x00000000000000000000000000000000000000000000000000000000000000c8::bfc_system::BfcSystemState"
                        },
                        "json": {
                          "id": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMSwiYyI6MH0",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::DenyList"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000403",
                          "lists": {
                            "id": "0x1663d1fd9b8ba848551a84dcd4c7292357911edf8e6ef93d7303b1a2008a8c06",
                            "size": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMiwiYyI6MH0",
                  "node": {
                    "address": "0x00da26249823ac2cfb6095f4716f6effe3e92918d2323d6b94d583d61380d427",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x00000000000000000000000000000000000000000000000000000000000000c8::binr::BINR>"
                        },
                        "json": {
                          "id": "0x00da26249823ac2cfb6095f4716f6effe3e92918d2323d6b94d583d61380d427",
                          "decimals": 9,
                          "name": "Benfen INR",
                          "symbol": "BINR",
                          "description": "",
                          "icon_url": null
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMywiYyI6MH0",
                  "node": {
                    "address": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000001::ascii::String,0x0000000000000000000000000000000000000000000000000000000000000003::stable_pool::StablePool<0x00000000000000000000000000000000000000000000000000000000000000c8::bidr::BIDR>>"
                        },
                        "json": {
                          "id": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                          "name": "00000000000000000000000000000000000000000000000000000000000000c8::bidr::BIDR",
                          "value": {
                            "id": "0xa8971f308036d827571d495f3a7ea5085b8069d7ccabd4472e30c1c9faa25ac3",
                            "activation_epoch": "0",
                            "deactivation_epoch": null,
                            "stable_balance": "0",
                            "rewards_pool": {
                              "value": "0"
                            },
                            "pool_token_balance": "0",
                            "exchange_rates": {
                              "id": "0xf970e819768ae5b85a78feb92876996e1db5a4dd1455c7a1a8af8ffd28daee39",
                              "size": "1"
                            },
                            "pending_stake": "0",
                            "pending_total_sui_withdraw": "0",
                            "pending_pool_token_withdraw": "0",
                            "extra_fields": {
                              "id": "0x003dd9916f633ba618a87a99e176de98dfa529f248e2e6e87987724cd6632d5a",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNCwiYyI6MH0",
                  "node": {
                    "address": "0x056b8364b8cca413406c3fe7489eedb3e342c27ad0ff7b13acb49022e36cea12",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::linked_table::Node<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::position::Position>>"
                        },
                        "json": {
                          "id": "0x056b8364b8cca413406c3fe7489eedb3e342c27ad0ff7b13acb49022e36cea12",
                          "name": "5",
                          "value": {
                            "prev": "4",
                            "next": "6",
                            "value": {
                              "vault_id": "0x17b138b1b8b518663752b57aa583207b6826e9f89332ff5a6264211cf2ce6ca3",
                              "index": "5",
                              "coin_type_a": {
                                "name": "00000000000000000000000000000000000000000000000000000000000000c8::busd::BUSD"
                              },
                              "coin_type_b": {
                                "name": "0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                              },
                              "name": "OpenBlock LP | Pool-1-5",
                              "tick_lower_index": {
                                "bits": 22028
                              },
                              "tick_upper_index": {
                                "bits": 24028
                              },
                              "liquidity": "13117090415630771"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNSwiYyI6MH0",
                  "node": {
                    "address": "0x05d8df77cf98a8e3703925dbe74501fb48e554163ee858476bcf64db96734136",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::skip_list::Node<0x00000000000000000000000000000000000000000000000000000000000000c8::tick::Tick>>"
                        },
                        "json": {
                          "id": "0x05d8df77cf98a8e3703925dbe74501fb48e554163ee858476bcf64db96734136",
                          "name": "471664",
                          "value": {
                            "score": "471664",
                            "nexts": [
                              {
                                "is_none": false,
                                "v": "473664"
                              }
                            ],
                            "prev": {
                              "is_none": false,
                              "v": "469664"
                            },
                            "value": {
                              "index": {
                                "bits": 28028
                              },
                              "sqrt_price": "74904788217296732259",
                              "liquidity_net": {
                                "bits": "0"
                              },
                              "liquidity_gross": "26234180831261542"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNiwiYyI6MH0",
                  "node": {
                    "address": "0x08fcc04e3c73a62f72f718b6a13967d9ee0f7506bf487101230b004097a1667a",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000001::ascii::String,0x0000000000000000000000000000000000000000000000000000000000000002::balance::Supply<0x00000000000000000000000000000000000000000000000000000000000000c8::busd::BUSD>>"
                        },
                        "json": {
                          "id": "0x08fcc04e3c73a62f72f718b6a13967d9ee0f7506bf487101230b004097a1667a",
                          "name": "00000000000000000000000000000000000000000000000000000000000000c8::busd::BUSD",
                          "value": {
                            "value": "1502979662744206"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNywiYyI6MH0",
                  "node": {
                    "address": "0x0b06fa7c85cc4239d2071f0027db792fd78671e07aadd9c317bb382e61c18cb6",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x00000000000000000000000000000000000000000000000000000000000000c8::brub::BRUB>"
                        },
                        "json": {
                          "id": "0x0b06fa7c85cc4239d2071f0027db792fd78671e07aadd9c317bb382e61c18cb6",
                          "decimals": 9,
                          "name": "Benfen RUB",
                          "symbol": "BRUB",
                          "description": "",
                          "icon_url": null
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOCwiYyI6MH0",
                  "node": {
                    "address": "0x15ea27e4c5bd0d1690cad3a7ba8c76c99172d2433416fa56ee8fee6f2762cf08",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000001::ascii::String,0x0000000000000000000000000000000000000000000000000000000000000003::stable_pool::StablePool<0x00000000000000000000000000000000000000000000000000000000000000c8::bcad::BCAD>>"
                        },
                        "json": {
                          "id": "0x15ea27e4c5bd0d1690cad3a7ba8c76c99172d2433416fa56ee8fee6f2762cf08",
                          "name": "00000000000000000000000000000000000000000000000000000000000000c8::bcad::BCAD",
                          "value": {
                            "id": "0x91adfbfc2d2bcc7b11767a975a3375772a1b0f37415bd9663326c604b95b7be3",
                            "activation_epoch": "0",
                            "deactivation_epoch": null,
                            "stable_balance": "0",
                            "rewards_pool": {
                              "value": "0"
                            },
                            "pool_token_balance": "0",
                            "exchange_rates": {
                              "id": "0x64a8aca696956fa4b9fe141c15ba28acca7d5894d8ffe707550309530e0a67cb",
                              "size": "1"
                            },
                            "pending_stake": "0",
                            "pending_total_sui_withdraw": "0",
                            "pending_pool_token_withdraw": "0",
                            "extra_fields": {
                              "id": "0x722a04fcca097b1995db077270733d2b0018c6bf3d0dc63d596d8340969c3c43",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOSwiYyI6MH0",
                  "node": {
                    "address": "0x160f9e78aa961f0e5d85db08aff55da7095e35dbdd406095d8f9d23a38b2f0ba",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::linked_table::Node<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::position::Position>>"
                        },
                        "json": {
                          "id": "0x160f9e78aa961f0e5d85db08aff55da7095e35dbdd406095d8f9d23a38b2f0ba",
                          "name": "3",
                          "value": {
                            "prev": "2",
                            "next": "4",
                            "value": {
                              "vault_id": "0x17b138b1b8b518663752b57aa583207b6826e9f89332ff5a6264211cf2ce6ca3",
                              "index": "3",
                              "coin_type_a": {
                                "name": "00000000000000000000000000000000000000000000000000000000000000c8::busd::BUSD"
                              },
                              "coin_type_b": {
                                "name": "0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                              },
                              "name": "OpenBlock LP | Pool-1-3",
                              "tick_lower_index": {
                                "bits": 18028
                              },
                              "tick_upper_index": {
                                "bits": 20028
                              },
                              "liquidity": "13117090415630771"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": {
              "nodes": []
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                  },
                  "amount": "3000000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                },
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "300000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "digest": "DYxjAPDF5BEXy2Byu4StpUCT4d652r4VsUE6v1DRyTM4"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "digest": "9DhUE918JkbHgBX6gyhMRbM1bdYgMmreiMKuT64nw5v"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "digest": "HBdGcwnzFfMq5wRm1Ke8SBsNfJ7sBT3TnXjdAJQ29JWS"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "ANoiLfMXHuKuoEnHE3avh931GiUtVATsHjRfVSHS6Umb"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "9MtaAW6enbcfVxc6NMscTd612SE1LwxVB8cuPFTgVpKc"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                    "digest": "Az7Hj88TPYRSW9Gs3RRc8EkfgqhmwsWscYtNVM4vqb6A"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "digest": "2gKhDzMYfLVwPfXv8SAhFgFCbkRmB4ZnbakC5KB6foQw"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000009",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000009",
                    "digest": "7aQkbQQqHUfx4yx35eVHf4BPGVga61RTLSkrVRNTWBiQ"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "digest": "7gm1KV19HLg9mnx4CDG8dktwzvHmnzJgkiXBxCtx7Tbh"
                  }
                },
                {
                  "address": "0x00000000000000000000000000000000000000000000000000000000000000c8",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c8",
                    "digest": "51esrUoSvk63GKkEwWbnYMEL2WwPrcZ4fHcp4XBruuBc"
                  }
                },
                {
                  "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                    "digest": "2c1sCDqeA1ULoKvXZsHjvL9tDQCVKL31JCJM1PVJZKzJ"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "digest": "FBpMMtT83AzDhV5ZvNPeDd1qkgRpPzFLRkMiskyUTJYo"
                  }
                },
                {
                  "address": "0x00da26249823ac2cfb6095f4716f6effe3e92918d2323d6b94d583d61380d427",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00da26249823ac2cfb6095f4716f6effe3e92918d2323d6b94d583d61380d427",
                    "digest": "AJefG6P6uCz3DfLpqunHirj3Dp5Q4dKDvTSG9puMumH5"
                  }
                },
                {
                  "address": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                    "digest": "7ArEqLaCeyeYjM3n5bEzfbdpRcuSUnbGqon3w3mHkqSu"
                  }
                },
                {
                  "address": "0x056b8364b8cca413406c3fe7489eedb3e342c27ad0ff7b13acb49022e36cea12",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x056b8364b8cca413406c3fe7489eedb3e342c27ad0ff7b13acb49022e36cea12",
                    "digest": "7D5Vgqhmvc4yaVcUfyEeLqFt4ptK2fR3X5cXYV81B5Uj"
                  }
                },
                {
                  "address": "0x05d8df77cf98a8e3703925dbe74501fb48e554163ee858476bcf64db96734136",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x05d8df77cf98a8e3703925dbe74501fb48e554163ee858476bcf64db96734136",
                    "digest": "2NEDDjtXLCpvXi8nZAsApUV7hbyWw8w2HHPJW2JAK8t4"
                  }
                },
                {
                  "address": "0x08fcc04e3c73a62f72f718b6a13967d9ee0f7506bf487101230b004097a1667a",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x08fcc04e3c73a62f72f718b6a13967d9ee0f7506bf487101230b004097a1667a",
                    "digest": "CgJmSgcatAtSBvPJN6DzDpvdgBHzPTJLp2ppvW1DYqxM"
                  }
                },
                {
                  "address": "0x0b06fa7c85cc4239d2071f0027db792fd78671e07aadd9c317bb382e61c18cb6",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0b06fa7c85cc4239d2071f0027db792fd78671e07aadd9c317bb382e61c18cb6",
                    "digest": "QPAVARBYHnfV5dL4ZQZ82ao451ui1sPXCpU6x8t3Yeu"
                  }
                },
                {
                  "address": "0x15ea27e4c5bd0d1690cad3a7ba8c76c99172d2433416fa56ee8fee6f2762cf08",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x15ea27e4c5bd0d1690cad3a7ba8c76c99172d2433416fa56ee8fee6f2762cf08",
                    "digest": "2uxSyBLWBBgXAreUfGRwgonZ744EHgMGVSXMF2Wd2SVx"
                  }
                },
                {
                  "address": "0x160f9e78aa961f0e5d85db08aff55da7095e35dbdd406095d8f9d23a38b2f0ba",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x160f9e78aa961f0e5d85db08aff55da7095e35dbdd406095d8f9d23a38b2f0ba",
                    "digest": "9cxhQ86F3Emyzhjh6qnfB3D6H3zJB3ejGCmSkwiufDQo"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "FXSSBjHgu4SZ78WHwXC2JRZYNsuCTEUEvs8j5k1SsKfj"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3, line 106:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 108-183:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "DPq7c2A5SyX36jGrNW6QNstAzSxtFPai1SZj4eF7oFDR",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "FXSSBjHgu4SZ78WHwXC2JRZYNsuCTEUEvs8j5k1SsKfj"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "Dbu2swR7jSwhxcjbyL1iGCuQPSrKR7Kyp8PEbKxsd9Uq"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "DPq7c2A5SyX36jGrNW6QNstAzSxtFPai1SZj4eF7oFDR"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6, line 187:
//# advance-epoch
Epoch advanced: 0

task 7, lines 189-276:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "BqM3PKbcC5TyViZHi4vPSyGGMSJdQc5CyzuAtdTYS99w",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "ChangeEpochTransaction",
                    "epoch": null,
                    "protocolVersion": 51,
                    "storageCharge": "0",
                    "computationCharge": "0",
                    "storageRebate": "0",
                    "nonRefundableStorageFee": "0",
                    "startTimestamp": "1970-01-01T00:01:25Z"
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 4,
            "dependencies": {
              "nodes": [
                {
                  "digest": "5PVjy7zeFAkE4pRWN5zuKYChDaGpF43BALgdEbGQEBhk"
                },
                {
                  "digest": "FXSSBjHgu4SZ78WHwXC2JRZYNsuCTEUEvs8j5k1SsKfj"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "2cw1tgq8rMmQWznMxxUVLDpqiWypjfLMvKmLgUjgvWYX"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "2HyqU84oRNFVMCsFs5WFcA3F8eHs6f54tyac3rtwNwq2"
                  }
                },
                {
                  "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                    "digest": "5n1q4yL6kPiCQEP54RgA46xUNDEuknKRNkuTc1ahkYA6"
                  }
                },
                {
                  "address": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                    "digest": "H1JSLZxrWaXEBN2F9vVPQwmDnzr2XQCX1u74J3NJLZHk"
                  }
                },
                {
                  "address": "0x15ea27e4c5bd0d1690cad3a7ba8c76c99172d2433416fa56ee8fee6f2762cf08",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x15ea27e4c5bd0d1690cad3a7ba8c76c99172d2433416fa56ee8fee6f2762cf08",
                    "digest": "8X4ZojUtrLC9Sz2EfFREZHe8qJX3f2h4mUS1qmq56wGv"
                  }
                },
                {
                  "address": "0x1c19d67877aa7ed94ad6e41fe029eca781f1aa497d74cefd045d3198dd4b0e88",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x1c19d67877aa7ed94ad6e41fe029eca781f1aa497d74cefd045d3198dd4b0e88",
                    "digest": "4oJApKmyshTCVrRRiaU5ZY75WQ8zjk4bFw3cQv3533Yk"
                  }
                },
                {
                  "address": "0x20f33d5559b63e11d334372b43f615a6ecef07769bda6b73a299aeeeb2208f98",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x20f33d5559b63e11d334372b43f615a6ecef07769bda6b73a299aeeeb2208f98",
                    "digest": "3Dj3Zv8uXbUPV2oag63bBcQmMBotgGFXzendrtxxU66o"
                  }
                },
                {
                  "address": "0x22fb878e6160b38d010f5b1275f2f551d36eb96326d8058d0e665764ab273b6c",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x22fb878e6160b38d010f5b1275f2f551d36eb96326d8058d0e665764ab273b6c",
                    "digest": "BNK3NASg7i1YtrWvjf3J74Q1QE8yqUm6DtkwBAf7bdnh"
                  }
                },
                {
                  "address": "0x36b833b8b2af69414480207b52946ab5cab66e98dbc2d2f2b64c5910378f2f5a",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x36b833b8b2af69414480207b52946ab5cab66e98dbc2d2f2b64c5910378f2f5a",
                    "digest": "wjsu3X223622pFtNxTRbcd5wujsGBFLeF9iMW7cfZP8"
                  }
                },
                {
                  "address": "0x435573fb8a2c87081e3a8d47e48657313112b77b8b0ce1f4970c4fe3002ac8a5",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x435573fb8a2c87081e3a8d47e48657313112b77b8b0ce1f4970c4fe3002ac8a5",
                    "digest": "JCbkKbjg54X5jhfWbWeDvkNiv1UVgkWSEmaYQyQ6wu4C"
                  }
                },
                {
                  "address": "0x49ad642bef617656def0960e6175647cc0e7d7c9cd52ed89e60b90cb9e80e571",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x49ad642bef617656def0960e6175647cc0e7d7c9cd52ed89e60b90cb9e80e571",
                    "digest": "3p751S9Er5FQDdfy7pJjDRdzfAsKPj9BeJupq7SChCFP"
                  }
                },
                {
                  "address": "0x56fc6c97a0b2df93c009ea4e83c266f8b0fae713213bbc3ba193b24e37eae5bb",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x56fc6c97a0b2df93c009ea4e83c266f8b0fae713213bbc3ba193b24e37eae5bb",
                    "digest": "3TPPNqhEZNpQQhMgkkFGAkGRHXzHWdmryqqoaQWKtDwM"
                  }
                },
                {
                  "address": "0x591597475790608094dd4d90f8f3b9f80c6441905a6ec9b07b95f7cc8f51df93",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x591597475790608094dd4d90f8f3b9f80c6441905a6ec9b07b95f7cc8f51df93",
                    "digest": "AHM6tXbSxdSL3BXJgr4F1bwYxAuVrakVdQNcmVNEp2PA"
                  }
                },
                {
                  "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                    "digest": "3WT3VNF55T8EJTJksQMn9xtEVYCX1Ue22wH1rvqdasWv"
                  }
                },
                {
                  "address": "0x61268aa98a34e73c28375ce928eb331917e76bc20e32506108bd134dd3fd6493",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x61268aa98a34e73c28375ce928eb331917e76bc20e32506108bd134dd3fd6493",
                    "digest": "BFYsAd8uL9j8toUGS6ppdbhwAvThgtt4oPYUbp185cVa"
                  }
                },
                {
                  "address": "0x66935e2ae4fca883263472421195b9e83a9138e778f62a9cd0513662f3671c2c",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x66935e2ae4fca883263472421195b9e83a9138e778f62a9cd0513662f3671c2c",
                    "digest": "5ZYTjkvcXgoiYLP94LjVLfe9Q98JQPjzzEKR4dM7Gsf2"
                  }
                },
                {
                  "address": "0x6af2a2b7ca60bf76174adfd3e9c4957f8e937759603182f9b46c7f6c5f19c6d2",
                  "idCreated": false,
                  "idDeleted": true,
                  "outputState": null
                },
                {
                  "address": "0x75c7b192025c25d5b1bf1f8244f703b51d5f6a9fc5903b860bcc29f16a36cf1d",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x75c7b192025c25d5b1bf1f8244f703b51d5f6a9fc5903b860bcc29f16a36cf1d",
                    "digest": "7cf4nqAb9fh25ftWpPUWdW1SqEyauLgYLyWSeB9TtNT3"
                  }
                },
                {
                  "address": "0x785e2cf3bd60fea56ca6d91af7d456a1028c550cf2c4f4f421afd1bac75c83c9",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x785e2cf3bd60fea56ca6d91af7d456a1028c550cf2c4f4f421afd1bac75c83c9",
                    "digest": "8TzbRra2AeEpWMHP9j1zgUntnxDAG67rcfGftPGdJJsn"
                  }
                },
                {
                  "address": "0x78f70fd6291225d2be492ec25dd019de7110125421364942333016477d0a3b61",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x78f70fd6291225d2be492ec25dd019de7110125421364942333016477d0a3b61",
                    "digest": "AGPRNafg1bKXKRBpiHdtDEC3YCtgQxzANKML2z3eWwUL"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "BqM3PKbcC5TyViZHi4vPSyGGMSJdQc5CyzuAtdTYS99w"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
