processed 8 tasks

task 1, lines 8-102:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "6m4pASBi1bE4RQNpA7gPiGgCKPVDk46ZcC9cg25fHcbi",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objects": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXNjaWkiLCJjIjowfQ",
                            "node": {
                              "name": "ascii"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYml0X3ZlY3RvciIsImMiOjB9",
                            "node": {
                              "name": "bit_vector"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVidWciLCJjIjowfQ",
                            "node": {
                              "name": "debug"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZml4ZWRfcG9pbnQzMiIsImMiOjB9",
                            "node": {
                              "name": "fixed_point32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaGFzaCIsImMiOjB9",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWFjcm9zIiwiYyI6MH0",
                            "node": {
                              "name": "macros"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3B0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "option"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RyaW5nIiwiYyI6MH0",
                            "node": {
                              "name": "string"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHlwZV9uYW1lIiwiYyI6MH0",
                            "node": {
                              "name": "type_name"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTEyOCIsImMiOjB9",
                            "node": {
                              "name": "u128"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTE2IiwiYyI6MH0",
                            "node": {
                              "name": "u16"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTI1NiIsImMiOjB9",
                            "node": {
                              "name": "u256"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTMyIiwiYyI6MH0",
                            "node": {
                              "name": "u32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTY0IiwiYyI6MH0",
                            "node": {
                              "name": "u64"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTgiLCJjIjowfQ",
                            "node": {
                              "name": "u8"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidXEzMl8zMiIsImMiOjB9",
                            "node": {
                              "name": "uq32_32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidXE2NF82NCIsImMiOjB9",
                            "node": {
                              "name": "uq64_64"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmVjdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "vector"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWJmYyIsImMiOjB9",
                            "node": {
                              "name": "abfc"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYW5vbnltb3VzIiwiYyI6MH0",
                            "node": {
                              "name": "anonymous"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYW5vbnltb3VzX2JhbGFuY2UiLCJjIjowfQ",
                            "node": {
                              "name": "anonymous_balance"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYW5vbnltb3VzX2NvaW4iLCJjIjowfQ",
                            "node": {
                              "name": "anonymous_coin"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYW5vbnltb3VzX3BheSIsImMiOjB9",
                            "node": {
                              "name": "anonymous_pay"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXV0aGVudGljYXRvcl9zdGF0ZSIsImMiOjB9",
                            "node": {
                              "name": "authenticator_state"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFnIiwiYyI6MH0",
                            "node": {
                              "name": "bag"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFsYW5jZSIsImMiOjB9",
                            "node": {
                              "name": "balance"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjIiwiYyI6MH0",
                            "node": {
                              "name": "bfc"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmxzMTIzODEiLCJjIjowfQ",
                            "node": {
                              "name": "bls12381"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm9ycm93IiwiYyI6MH0",
                            "node": {
                              "name": "borrow"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvY2siLCJjIjowfQ",
                            "node": {
                              "name": "clock"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbiIsImMiOjB9",
                            "node": {
                              "name": "coin"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29uZmlnIiwiYyI6MH0",
                            "node": {
                              "name": "config"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3VydmUiLCJjIjowfQ",
                            "node": {
                              "name": "curve"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVueV9saXN0IiwiYyI6MH0",
                            "node": {
                              "name": "deny_list"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGlzcGxheSIsImMiOjB9",
                            "node": {
                              "name": "display"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19maWVsZCIsImMiOjB9",
                            "node": {
                              "name": "dynamic_field"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiZ2VuZXNpcyIsImMiOjB9",
                            "node": {
                              "name": "genesis"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RhYmxlX3Bvb2wiLCJjIjowfQ",
                            "node": {
                              "name": "stable_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2Vfc3Vic2lkeSIsImMiOjB9",
                            "node": {
                              "name": "stake_subsidy"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2luZ19wb29sIiwiYyI6MH0",
                            "node": {
                              "name": "staking_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9mdW5kIiwiYyI6MH0",
                            "node": {
                              "name": "storage_fund"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3VpX3N5c3RlbSIsImMiOjB9",
                            "node": {
                              "name": "sui_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3VpX3N5c3RlbV9zdGF0ZV9pbm5lciIsImMiOjB9",
                            "node": {
                              "name": "sui_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "validator"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX2NhcCIsImMiOjB9",
                            "node": {
                              "name": "validator_cap"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3NldCIsImMiOjB9",
                            "node": {
                              "name": "validator_set"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3dyYXBwZXIiLCJjIjowfQ",
                            "node": {
                              "name": "validator_wrapper"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidm90aW5nX3Bvd2VyIiwiYyI6MH0",
                            "node": {
                              "name": "voting_power"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::sui_system::SuiSystemState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                          "version": "1",
                          "bfc_system_id": "0x00000000000000000000000000000000000000000000000000000000000000c9"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                          "timestamp_ms": "0"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000007",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                          "inner": {
                            "id": "0x02dcaca118fd03983bd92e749c37464a9bad35af266da5e3e63807ee1094a896",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000009",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x000000000000000000000000000000000000000000000000000000000000000b::bridge::Bridge"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000009",
                          "inner": {
                            "id": "0xfafb0def3bef80e90a20761e8c95dd5c9e674bb3a6717265469df447d73bb0d3",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYnJpZGdlIiwiYyI6MH0",
                            "node": {
                              "name": "bridge"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2hhaW5faWRzIiwiYyI6MH0",
                            "node": {
                              "name": "chain_ids"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29tbWl0dGVlIiwiYyI6MH0",
                            "node": {
                              "name": "committee"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3J5cHRvIiwiYyI6MH0",
                            "node": {
                              "name": "crypto"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibGltaXRlciIsImMiOjB9",
                            "node": {
                              "name": "limiter"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZSIsImMiOjB9",
                            "node": {
                              "name": "message"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZV90eXBlcyIsImMiOjB9",
                            "node": {
                              "name": "message_types"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidG9rZW5saXN0IiwiYyI6MH0",
                            "node": {
                              "name": "tokenlist"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHJlYXN1cnkiLCJjIjowfQ",
                            "node": {
                              "name": "treasury"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo5LCJjIjowfQ",
                  "node": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c8",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYXV0aF91dGlscyIsImMiOjB9",
                            "node": {
                              "name": "auth_utils"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFycyIsImMiOjB9",
                            "node": {
                              "name": "bars"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmF1ZCIsImMiOjB9",
                            "node": {
                              "name": "baud"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmJybCIsImMiOjB9",
                            "node": {
                              "name": "bbrl"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNhZCIsImMiOjB9",
                            "node": {
                              "name": "bcad"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmV1ciIsImMiOjB9",
                            "node": {
                              "name": "beur"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX2RhbyIsImMiOjB9",
                            "node": {
                              "name": "bfc_dao"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX2Rhb19tYW5hZ2VyIiwiYyI6MH0",
                            "node": {
                              "name": "bfc_dao_manager"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX3N5c3RlbSIsImMiOjB9",
                            "node": {
                              "name": "bfc_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX3N5c3RlbV9zdGF0ZV9pbm5lciIsImMiOjB9",
                            "node": {
                              "name": "bfc_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmdicCIsImMiOjB9",
                            "node": {
                              "name": "bgbp"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmlkciIsImMiOjB9",
                            "node": {
                              "name": "bidr"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmluciIsImMiOjB9",
                            "node": {
                              "name": "binr"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmpweSIsImMiOjB9",
                            "node": {
                              "name": "bjpy"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmtydyIsImMiOjB9",
                            "node": {
                              "name": "bkrw"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm14biIsImMiOjB9",
                            "node": {
                              "name": "bmxn"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnJ1YiIsImMiOjB9",
                            "node": {
                              "name": "brub"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnNhciIsImMiOjB9",
                            "node": {
                              "name": "bsar"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnRyeSIsImMiOjB9",
                            "node": {
                              "name": "btry"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnVzZCIsImMiOjB9",
                            "node": {
                              "name": "busd"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxMCwiYyI6MH0",
                  "node": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x00000000000000000000000000000000000000000000000000000000000000c8::bfc_system::BfcSystemState"
                        },
                        "json": {
                          "id": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMSwiYyI6MH0",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::DenyList"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000403",
                          "lists": {
                            "id": "0x1663d1fd9b8ba848551a84dcd4c7292357911edf8e6ef93d7303b1a2008a8c06",
                            "size": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMiwiYyI6MH0",
                  "node": {
                    "address": "0x00285145aba81cb87651a2ff719afe39129fa27ff2af3149d59bcd234f250f94",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::skip_list::Node<0x00000000000000000000000000000000000000000000000000000000000000c8::tick::Tick>>"
                        },
                        "json": {
                          "id": "0x00285145aba81cb87651a2ff719afe39129fa27ff2af3149d59bcd234f250f94",
                          "name": "462516",
                          "value": {
                            "score": "462516",
                            "nexts": [
                              {
                                "is_none": false,
                                "v": "464516"
                              },
                              {
                                "is_none": true,
                                "v": "0"
                              },
                              {
                                "is_none": true,
                                "v": "0"
                              }
                            ],
                            "prev": {
                              "is_none": false,
                              "v": "460516"
                            },
                            "value": {
                              "index": {
                                "bits": 18880
                              },
                              "sqrt_price": "47410355963964328657",
                              "liquidity_net": {
                                "bits": "0"
                              },
                              "liquidity_gross": "30705914872908046"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMywiYyI6MH0",
                  "node": {
                    "address": "0x02b22a2384788887f90412af5a5626986926ece750ed0fb63894c2f8ed61e238",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::skip_list::Node<0x00000000000000000000000000000000000000000000000000000000000000c8::tick::Tick>>"
                        },
                        "json": {
                          "id": "0x02b22a2384788887f90412af5a5626986926ece750ed0fb63894c2f8ed61e238",
                          "name": "436840",
                          "value": {
                            "score": "436840",
                            "nexts": [
                              {
                                "is_none": false,
                                "v": "438840"
                              },
                              {
                                "is_none": true,
                                "v": "0"
                              },
                              {
                                "is_none": true,
                                "v": "0"
                              }
                            ],
                            "prev": {
                              "is_none": false,
                              "v": "434840"
                            },
                            "value": {
                              "index": {
                                "bits": 4294960500
                              },
                              "sqrt_price": "13132694322582077330",
                              "liquidity_net": {
                                "bits": "0"
                              },
                              "liquidity_gross": "110851461136996140"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNCwiYyI6MH0",
                  "node": {
                    "address": "0x038006c4cd6d3055ebf18d72f8502d245381796e0761a00ddfbe28ed163be366",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::skip_list::Node<0x00000000000000000000000000000000000000000000000000000000000000c8::tick::Tick>>"
                        },
                        "json": {
                          "id": "0x038006c4cd6d3055ebf18d72f8502d245381796e0761a00ddfbe28ed163be366",
                          "name": "434840",
                          "value": {
                            "score": "434840",
                            "nexts": [
                              {
                                "is_none": false,
                                "v": "436840"
                              },
                              {
                                "is_none": false,
                                "v": "436840"
                              }
                            ],
                            "prev": {
                              "is_none": false,
                              "v": "432840"
                            },
                            "value": {
                              "index": {
                                "bits": 4294958500
                              },
                              "sqrt_price": "11883012633654615533",
                              "liquidity_net": {
                                "bits": "0"
                              },
                              "liquidity_gross": "110851461136996140"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNSwiYyI6MH0",
                  "node": {
                    "address": "0x040c1f0621a02e0005fd4b179fb2567a6f94611f47c8633121c609b076c80a26",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::linked_table::Node<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::position::Position>>"
                        },
                        "json": {
                          "id": "0x040c1f0621a02e0005fd4b179fb2567a6f94611f47c8633121c609b076c80a26",
                          "name": "4",
                          "value": {
                            "prev": "3",
                            "next": "5",
                            "value": {
                              "vault_id": "0x989f4e807affc81f819ad8e402212b78be0e8894060cf2f1a60ce953f95dd6af",
                              "index": "4",
                              "coin_type_a": {
                                "name": "00000000000000000000000000000000000000000000000000000000000000c8::baud::BAUD"
                              },
                              "coin_type_b": {
                                "name": "0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                              },
                              "name": "OpenBlock LP | Pool-4-4",
                              "tick_lower_index": {
                                "bits": 16022
                              },
                              "tick_upper_index": {
                                "bits": 18022
                              },
                              "liquidity": "16025897019376837"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNiwiYyI6MH0",
                  "node": {
                    "address": "0x0472c7ea9df1aca04ae667ae7dc836370cb4c676d49ef6996b1b59af531b3056",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::linked_table::Node<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::position::Position>>"
                        },
                        "json": {
                          "id": "0x0472c7ea9df1aca04ae667ae7dc836370cb4c676d49ef6996b1b59af531b3056",
                          "name": "5",
                          "value": {
                            "prev": "4",
                            "next": "6",
                            "value": {
                              "vault_id": "0xa664d23579751d39472d61eb95364db4ae28f5fcccf3f17fa227403e8bb62588",
                              "index": "5",
                              "coin_type_a": {
                                "name": "00000000000000000000000000000000000000000000000000000000000000c8::bmxn::BMXN"
                              },
                              "coin_type_b": {
                                "name": "0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                              },
                              "name": "OpenBlock LP | Pool-16-5",
                              "tick_lower_index": {
                                "bits": 4294960500
                              },
                              "tick_upper_index": {
                                "bits": 4294962500
                              },
                              "liquidity": "55425730568498070"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNywiYyI6MH0",
                  "node": {
                    "address": "0x05194f67560aa7ef3c09a608f5daabf3d0929ee6454cb4aacaa1ef8c4ed42ccd",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::linked_table::Node<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::position::Position>>"
                        },
                        "json": {
                          "id": "0x05194f67560aa7ef3c09a608f5daabf3d0929ee6454cb4aacaa1ef8c4ed42ccd",
                          "name": "3",
                          "value": {
                            "prev": "2",
                            "next": "4",
                            "value": {
                              "vault_id": "0x05020b571285f72d8e29330835eacc07444b2ab0b7097e870d3160b0613611ae",
                              "index": "3",
                              "coin_type_a": {
                                "name": "00000000000000000000000000000000000000000000000000000000000000c8::brub::BRUB"
                              },
                              "coin_type_b": {
                                "name": "0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                              },
                              "name": "OpenBlock LP | Pool-12-3",
                              "tick_lower_index": {
                                "bits": 4294940222
                              },
                              "tick_upper_index": {
                                "bits": 4294942222
                              },
                              "liquidity": "125073710103528295"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOCwiYyI6MH0",
                  "node": {
                    "address": "0x05376194e55b11da1ff8651d5d44b7fee21d8e1cae1373e8fca5875995228087",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::linked_table::Node<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::position::Position>>"
                        },
                        "json": {
                          "id": "0x05376194e55b11da1ff8651d5d44b7fee21d8e1cae1373e8fca5875995228087",
                          "name": "6",
                          "value": {
                            "prev": "5",
                            "next": "7",
                            "value": {
                              "vault_id": "0x2dc1c19cb76b0cc40878cd80ecd17a6ca9bbc33351856f9bd98325848b5192dd",
                              "index": "6",
                              "coin_type_a": {
                                "name": "00000000000000000000000000000000000000000000000000000000000000c8::btry::BTRY"
                              },
                              "coin_type_b": {
                                "name": "0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                              },
                              "name": "OpenBlock LP | Pool-14-6",
                              "tick_lower_index": {
                                "bits": 4294956258
                              },
                              "tick_upper_index": {
                                "bits": 4294958258
                              },
                              "liquidity": "75726512678872870"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOSwiYyI6MH0",
                  "node": {
                    "address": "0x057d69d682d7a8e0f42b3ccb8c044f713277d40e03917aa39f638d629bead088",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::skip_list::Node<0x00000000000000000000000000000000000000000000000000000000000000c8::tick::Tick>>"
                        },
                        "json": {
                          "id": "0x057d69d682d7a8e0f42b3ccb8c044f713277d40e03917aa39f638d629bead088",
                          "name": "472286",
                          "value": {
                            "score": "472286",
                            "nexts": [
                              {
                                "is_none": false,
                                "v": "474286"
                              }
                            ],
                            "prev": {
                              "is_none": false,
                              "v": "470286"
                            },
                            "value": {
                              "index": {
                                "bits": 28650
                              },
                              "sqrt_price": "77270809776289461667",
                              "liquidity_net": {
                                "bits": "0"
                              },
                              "liquidity_gross": "23010939354019002"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": {
              "nodes": []
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                  },
                  "amount": "3000000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                },
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "300000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "digest": "MbHvYHphqhfD6egBYxaFKQ5kFu1qNGU67RDZTegN7YY"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "digest": "CUHCf139TF9J7k7tt6ehW7ACRnfutpi6xq7XsfbFXuTc"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "digest": "G5VaLCAgTYUFG1y3zUYLQTV6r9mwmcAbNajQuYk9pjq6"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "6nFWzMX9b4cLDVhQ72j81BJiXQcQ8nYWiSTVB3StcYyH"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "C9dbujaiQZMyggUvV7E8rQuaDfgnaYszDLXMMZvmPcvN"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                    "digest": "FW2rHBbUvZJsbcEgj2vX3Bm9wKaz1QN5nHkvUzJsAnVL"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "digest": "BXkyFod7pU3ffi1JRRSiugp6AqZSnweiHMFbUgSQLVyu"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000009",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000009",
                    "digest": "GNVqbqxvmyKzbSHAERrLMDNDPSwwGNDPVvkL84SJutL9"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "digest": "CxaUastZCKPVioCiABDpHXJqJQbkiKRsqEHtWtcmYsnc"
                  }
                },
                {
                  "address": "0x00000000000000000000000000000000000000000000000000000000000000c8",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c8",
                    "digest": "Hg6z8wK4h9pNNFdJPkKeW3bzgscoQ7FMCNY3oyCmj3rx"
                  }
                },
                {
                  "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                    "digest": "5pSDuwEPscKVxDSPCmKuiKNc7BYmr5FB1qW8xET7WZ6p"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "digest": "5cr8YnJ5xZwyUskJs6uS98zno2xXAnDzVzeRRRbXw6NG"
                  }
                },
                {
                  "address": "0x00285145aba81cb87651a2ff719afe39129fa27ff2af3149d59bcd234f250f94",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00285145aba81cb87651a2ff719afe39129fa27ff2af3149d59bcd234f250f94",
                    "digest": "6ui2dNVrEVmtzX7vZ3GwqbQvcq2ZYWoqQHvTJp7bixnE"
                  }
                },
                {
                  "address": "0x02b22a2384788887f90412af5a5626986926ece750ed0fb63894c2f8ed61e238",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x02b22a2384788887f90412af5a5626986926ece750ed0fb63894c2f8ed61e238",
                    "digest": "DAibU4kvxfeym1chPxcHs6Y8pDq4ABuagdQKFiiia1cX"
                  }
                },
                {
                  "address": "0x038006c4cd6d3055ebf18d72f8502d245381796e0761a00ddfbe28ed163be366",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x038006c4cd6d3055ebf18d72f8502d245381796e0761a00ddfbe28ed163be366",
                    "digest": "D2U9GbQ1aXKL9YuURyLqV94Yh5KT71CXaW2CavWpdDJ3"
                  }
                },
                {
                  "address": "0x040c1f0621a02e0005fd4b179fb2567a6f94611f47c8633121c609b076c80a26",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x040c1f0621a02e0005fd4b179fb2567a6f94611f47c8633121c609b076c80a26",
                    "digest": "F8psAGZiHVPzotLvKzrdRw62F2wAXkRFF72LktwqrNu1"
                  }
                },
                {
                  "address": "0x0472c7ea9df1aca04ae667ae7dc836370cb4c676d49ef6996b1b59af531b3056",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0472c7ea9df1aca04ae667ae7dc836370cb4c676d49ef6996b1b59af531b3056",
                    "digest": "GzWJuHvvHqhMKod8LET5YCsJ9R1FeivNzvP7yxXSUFmq"
                  }
                },
                {
                  "address": "0x05194f67560aa7ef3c09a608f5daabf3d0929ee6454cb4aacaa1ef8c4ed42ccd",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x05194f67560aa7ef3c09a608f5daabf3d0929ee6454cb4aacaa1ef8c4ed42ccd",
                    "digest": "2Ny2Q51k2AGBtuAmkQdEAqWgwPLqxZgiUCoVQDvGeFYC"
                  }
                },
                {
                  "address": "0x05376194e55b11da1ff8651d5d44b7fee21d8e1cae1373e8fca5875995228087",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x05376194e55b11da1ff8651d5d44b7fee21d8e1cae1373e8fca5875995228087",
                    "digest": "BZtdx9t6iYJEzFTDswSGq9EJoSiMfgzQTu9QqfgEvCtX"
                  }
                },
                {
                  "address": "0x057d69d682d7a8e0f42b3ccb8c044f713277d40e03917aa39f638d629bead088",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x057d69d682d7a8e0f42b3ccb8c044f713277d40e03917aa39f638d629bead088",
                    "digest": "GrG2KfMJ7f7iotcA2sx66qESfUwGgFc9Yj3G7Hey9w6p"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "6m4pASBi1bE4RQNpA7gPiGgCKPVDk46ZcC9cg25fHcbi"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3, line 106:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 108-183:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "DPq7c2A5SyX36jGrNW6QNstAzSxtFPai1SZj4eF7oFDR",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "6m4pASBi1bE4RQNpA7gPiGgCKPVDk46ZcC9cg25fHcbi"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "Dbu2swR7jSwhxcjbyL1iGCuQPSrKR7Kyp8PEbKxsd9Uq"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "DPq7c2A5SyX36jGrNW6QNstAzSxtFPai1SZj4eF7oFDR"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6, line 187:
//# advance-epoch
Epoch advanced: 0

task 7, lines 189-276:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "BqM3PKbcC5TyViZHi4vPSyGGMSJdQc5CyzuAtdTYS99w",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "ChangeEpochTransaction",
                    "epoch": null,
                    "protocolVersion": 51,
                    "storageCharge": "0",
                    "computationCharge": "0",
                    "storageRebate": "0",
                    "nonRefundableStorageFee": "0",
                    "startTimestamp": "1970-01-01T00:01:25Z"
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 4,
            "dependencies": {
              "nodes": [
                {
                  "digest": "5PVjy7zeFAkE4pRWN5zuKYChDaGpF43BALgdEbGQEBhk"
                },
                {
                  "digest": "6m4pASBi1bE4RQNpA7gPiGgCKPVDk46ZcC9cg25fHcbi"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "2cw1tgq8rMmQWznMxxUVLDpqiWypjfLMvKmLgUjgvWYX"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "2HyqU84oRNFVMCsFs5WFcA3F8eHs6f54tyac3rtwNwq2"
                  }
                },
                {
                  "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                    "digest": "74eb6sJEFY7s86EwubEB238JiupyNb3NDytMFv7dmED5"
                  }
                },
                {
                  "address": "0x123b1851bfb78554f1e8545e1324eb60726020aab728e1736f1bf4a0afa1d0a9",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x123b1851bfb78554f1e8545e1324eb60726020aab728e1736f1bf4a0afa1d0a9",
                    "digest": "AsmqYYavyuKxSjBuQQRMfv9SVuUnwTPcLGLundVqTJbB"
                  }
                },
                {
                  "address": "0x131640e087436ecebd22a11998d19e6520ae60024d8d2a24986d0b20b3794b16",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x131640e087436ecebd22a11998d19e6520ae60024d8d2a24986d0b20b3794b16",
                    "digest": "7yq3iRj6DmGD3wdwbYSuRJHCh2819AgqFJ4AeFzgnDK6"
                  }
                },
                {
                  "address": "0x1a8a7b83f41b9e841aa53990df5e9f2b656767b977db741806d753c55de385a1",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x1a8a7b83f41b9e841aa53990df5e9f2b656767b977db741806d753c55de385a1",
                    "digest": "F66iC4aHvGHXKJitx19rikrVPrBZ3xji2zfkN9Vu5nf4"
                  }
                },
                {
                  "address": "0x1eb7db761ca569facdf7e20301f14357e3314bfed3c3c72188eaa8d2cc7d4df9",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x1eb7db761ca569facdf7e20301f14357e3314bfed3c3c72188eaa8d2cc7d4df9",
                    "digest": "51t1WQWA1cqFNE4JncRPFLMtF4AqH75mFmixLSybRYk6"
                  }
                },
                {
                  "address": "0x20f33d5559b63e11d334372b43f615a6ecef07769bda6b73a299aeeeb2208f98",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x20f33d5559b63e11d334372b43f615a6ecef07769bda6b73a299aeeeb2208f98",
                    "digest": "3Dj3Zv8uXbUPV2oag63bBcQmMBotgGFXzendrtxxU66o"
                  }
                },
                {
                  "address": "0x26b1572ce4c464d4497f44be111553a20c7cb6120876cfae8a114a6f02416e07",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x26b1572ce4c464d4497f44be111553a20c7cb6120876cfae8a114a6f02416e07",
                    "digest": "JvyY37nAmJ4h1Fi9PT9nzpFibescAT98qRKrHcG7fej"
                  }
                },
                {
                  "address": "0x2ec3b234728c4ae9939f62ff122dddf2763de0c21e62160408de9a3a777c09af",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": null
                },
                {
                  "address": "0x330323fa4af34d416058b2b8511cb0c3f7e8646114cbb6cf86ca74e175d2c173",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x330323fa4af34d416058b2b8511cb0c3f7e8646114cbb6cf86ca74e175d2c173",
                    "digest": "MegYX6v41SCVpKsNysVTRYy7xPURJn5CL91XLxFxvwy"
                  }
                },
                {
                  "address": "0x3e9cf6d9508308740a28ee26a7ea97ea4290616c319e6ea5e69f5187c5987b7f",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x3e9cf6d9508308740a28ee26a7ea97ea4290616c319e6ea5e69f5187c5987b7f",
                    "digest": "9fqKg43MqMwc2HnnTKVfD3PrRHprAc2GqAazRswKsWQV"
                  }
                },
                {
                  "address": "0x435573fb8a2c87081e3a8d47e48657313112b77b8b0ce1f4970c4fe3002ac8a5",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x435573fb8a2c87081e3a8d47e48657313112b77b8b0ce1f4970c4fe3002ac8a5",
                    "digest": "JCbkKbjg54X5jhfWbWeDvkNiv1UVgkWSEmaYQyQ6wu4C"
                  }
                },
                {
                  "address": "0x50393fae9c11c79c34957a551802ffbb14030b7a8061375f23a2082240b05864",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x50393fae9c11c79c34957a551802ffbb14030b7a8061375f23a2082240b05864",
                    "digest": "A9epb8amkwtHs6koBTtnwxNEi2dB55ZpPRZiJAwtz1db"
                  }
                },
                {
                  "address": "0x50b9dcb00870c4bb152a4aac659992c87fa2487e66801f480f5937c6ce49936c",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x50b9dcb00870c4bb152a4aac659992c87fa2487e66801f480f5937c6ce49936c",
                    "digest": "G9tvLzeEnC1msMEtA6Rhsgzknx5Y4TkE2BNmvxnhve9S"
                  }
                },
                {
                  "address": "0x518ec3c7f24cbb37d1006816cf63772b5cf8a4c98a7a6be382623fb3eb6b642f",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x518ec3c7f24cbb37d1006816cf63772b5cf8a4c98a7a6be382623fb3eb6b642f",
                    "digest": "9tVHBvsaJqFk5nQRSZ6twEG1b4AxTWt99Bq2mY9z8GzQ"
                  }
                },
                {
                  "address": "0x591597475790608094dd4d90f8f3b9f80c6441905a6ec9b07b95f7cc8f51df93",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x591597475790608094dd4d90f8f3b9f80c6441905a6ec9b07b95f7cc8f51df93",
                    "digest": "AHM6tXbSxdSL3BXJgr4F1bwYxAuVrakVdQNcmVNEp2PA"
                  }
                },
                {
                  "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5b890eaf2abcfa2ab90b77b8e6f3d5d8609586c3e583baf3dccd5af17edf48d1",
                    "digest": "CYHWF4P9ry8fnGx2Ee3ZR3c1haQwrc6FxyzPb6zc7pdt"
                  }
                },
                {
                  "address": "0x5f4885b0ae701287150b9c985f67b31bfb9d170096bc125a796cf9d9942131a0",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x5f4885b0ae701287150b9c985f67b31bfb9d170096bc125a796cf9d9942131a0",
                    "digest": "4Qhina7qDZLpiYmTZekwNZW1VaMyw2pdAY3oxv9Ux4Cx"
                  }
                },
                {
                  "address": "0x61268aa98a34e73c28375ce928eb331917e76bc20e32506108bd134dd3fd6493",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x61268aa98a34e73c28375ce928eb331917e76bc20e32506108bd134dd3fd6493",
                    "digest": "BFYsAd8uL9j8toUGS6ppdbhwAvThgtt4oPYUbp185cVa"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "BqM3PKbcC5TyViZHi4vPSyGGMSJdQc5CyzuAtdTYS99w"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
