processed 8 tasks

task 1, lines 8-102:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "7Q9t6hwU6mq5iJAmdYXb7y4cL4xJEeoNxg7vSgRvCZ5",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "GenesisTransaction",
            "objects": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXNjaWkiLCJjIjowfQ",
                            "node": {
                              "name": "ascii"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYml0X3ZlY3RvciIsImMiOjB9",
                            "node": {
                              "name": "bit_vector"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVidWciLCJjIjowfQ",
                            "node": {
                              "name": "debug"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZml4ZWRfcG9pbnQzMiIsImMiOjB9",
                            "node": {
                              "name": "fixed_point32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiaGFzaCIsImMiOjB9",
                            "node": {
                              "name": "hash"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWFjcm9zIiwiYyI6MH0",
                            "node": {
                              "name": "macros"
                            }
                          },
                          {
                            "cursor": "eyJuIjoib3B0aW9uIiwiYyI6MH0",
                            "node": {
                              "name": "option"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RyaW5nIiwiYyI6MH0",
                            "node": {
                              "name": "string"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHlwZV9uYW1lIiwiYyI6MH0",
                            "node": {
                              "name": "type_name"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTEyOCIsImMiOjB9",
                            "node": {
                              "name": "u128"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTE2IiwiYyI6MH0",
                            "node": {
                              "name": "u16"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTI1NiIsImMiOjB9",
                            "node": {
                              "name": "u256"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTMyIiwiYyI6MH0",
                            "node": {
                              "name": "u32"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTY0IiwiYyI6MH0",
                            "node": {
                              "name": "u64"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidTgiLCJjIjowfQ",
                            "node": {
                              "name": "u8"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmVjdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "vector"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYWRkcmVzcyIsImMiOjB9",
                            "node": {
                              "name": "address"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYXV0aGVudGljYXRvcl9zdGF0ZSIsImMiOjB9",
                            "node": {
                              "name": "authenticator_state"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFnIiwiYyI6MH0",
                            "node": {
                              "name": "bag"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFsYW5jZSIsImMiOjB9",
                            "node": {
                              "name": "balance"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNzIiwiYyI6MH0",
                            "node": {
                              "name": "bcs"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjIiwiYyI6MH0",
                            "node": {
                              "name": "bfc"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmxzMTIzODEiLCJjIjowfQ",
                            "node": {
                              "name": "bls12381"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm9ycm93IiwiYyI6MH0",
                            "node": {
                              "name": "borrow"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2xvY2siLCJjIjowfQ",
                            "node": {
                              "name": "clock"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29pbiIsImMiOjB9",
                            "node": {
                              "name": "coin"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29uZmlnIiwiYyI6MH0",
                            "node": {
                              "name": "config"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3VydmUiLCJjIjowfQ",
                            "node": {
                              "name": "curve"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGVueV9saXN0IiwiYyI6MH0",
                            "node": {
                              "name": "deny_list"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZGlzcGxheSIsImMiOjB9",
                            "node": {
                              "name": "display"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19maWVsZCIsImMiOjB9",
                            "node": {
                              "name": "dynamic_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZHluYW1pY19vYmplY3RfZmllbGQiLCJjIjowfQ",
                            "node": {
                              "name": "dynamic_object_field"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfazEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_k1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWNkc2FfcjEiLCJjIjowfQ",
                            "node": {
                              "name": "ecdsa_r1"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWN2cmYiLCJjIjowfQ",
                            "node": {
                              "name": "ecvrf"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiZWQyNTUxOSIsImMiOjB9",
                            "node": {
                              "name": "ed25519"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiZ2VuZXNpcyIsImMiOjB9",
                            "node": {
                              "name": "genesis"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RhYmxlX3Bvb2wiLCJjIjowfQ",
                            "node": {
                              "name": "stable_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2Vfc3Vic2lkeSIsImMiOjB9",
                            "node": {
                              "name": "stake_subsidy"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3Rha2luZ19wb29sIiwiYyI6MH0",
                            "node": {
                              "name": "staking_pool"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3RvcmFnZV9mdW5kIiwiYyI6MH0",
                            "node": {
                              "name": "storage_fund"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3VpX3N5c3RlbSIsImMiOjB9",
                            "node": {
                              "name": "sui_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoic3VpX3N5c3RlbV9zdGF0ZV9pbm5lciIsImMiOjB9",
                            "node": {
                              "name": "sui_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yIiwiYyI6MH0",
                            "node": {
                              "name": "validator"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX2NhcCIsImMiOjB9",
                            "node": {
                              "name": "validator_cap"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3NldCIsImMiOjB9",
                            "node": {
                              "name": "validator_set"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidmFsaWRhdG9yX3dyYXBwZXIiLCJjIjowfQ",
                            "node": {
                              "name": "validator_wrapper"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidm90aW5nX3Bvd2VyIiwiYyI6MH0",
                            "node": {
                              "name": "voting_power"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000003::sui_system::SuiSystemState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000005",
                          "version": "1",
                          "bfc_system_id": "0x00000000000000000000000000000000000000000000000000000000000000c9"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::clock::Clock"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000006",
                          "timestamp_ms": "0"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::authenticator_state::AuthenticatorState"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000007",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::random::Random"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000008",
                          "inner": {
                            "id": "0x02dcaca118fd03983bd92e749c37464a9bad35af266da5e3e63807ee1094a896",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjowfQ",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000009",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x000000000000000000000000000000000000000000000000000000000000000b::bridge::Bridge"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000009",
                          "inner": {
                            "id": "0xd50e7b8809e6de08dace9fc354de2375c049e571984d739ed5517269d6f17e77",
                            "version": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjowfQ",
                  "node": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYnJpZGdlIiwiYyI6MH0",
                            "node": {
                              "name": "bridge"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY2hhaW5faWRzIiwiYyI6MH0",
                            "node": {
                              "name": "chain_ids"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY29tbWl0dGVlIiwiYyI6MH0",
                            "node": {
                              "name": "committee"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiY3J5cHRvIiwiYyI6MH0",
                            "node": {
                              "name": "crypto"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibGltaXRlciIsImMiOjB9",
                            "node": {
                              "name": "limiter"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZSIsImMiOjB9",
                            "node": {
                              "name": "message"
                            }
                          },
                          {
                            "cursor": "eyJuIjoibWVzc2FnZV90eXBlcyIsImMiOjB9",
                            "node": {
                              "name": "message_types"
                            }
                          },
                          {
                            "cursor": "eyJuIjoidHJlYXN1cnkiLCJjIjowfQ",
                            "node": {
                              "name": "treasury"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo5LCJjIjowfQ",
                  "node": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c8",
                    "asMoveObject": null,
                    "asMovePackage": {
                      "modules": {
                        "edges": [
                          {
                            "cursor": "eyJuIjoiYXV0aF91dGlscyIsImMiOjB9",
                            "node": {
                              "name": "auth_utils"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmFycyIsImMiOjB9",
                            "node": {
                              "name": "bars"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmF1ZCIsImMiOjB9",
                            "node": {
                              "name": "baud"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmJybCIsImMiOjB9",
                            "node": {
                              "name": "bbrl"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmNhZCIsImMiOjB9",
                            "node": {
                              "name": "bcad"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmV1ciIsImMiOjB9",
                            "node": {
                              "name": "beur"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX2RhbyIsImMiOjB9",
                            "node": {
                              "name": "bfc_dao"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX2Rhb19tYW5hZ2VyIiwiYyI6MH0",
                            "node": {
                              "name": "bfc_dao_manager"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX3N5c3RlbSIsImMiOjB9",
                            "node": {
                              "name": "bfc_system"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmZjX3N5c3RlbV9zdGF0ZV9pbm5lciIsImMiOjB9",
                            "node": {
                              "name": "bfc_system_state_inner"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmdicCIsImMiOjB9",
                            "node": {
                              "name": "bgbp"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmlkciIsImMiOjB9",
                            "node": {
                              "name": "bidr"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmluciIsImMiOjB9",
                            "node": {
                              "name": "binr"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmpweSIsImMiOjB9",
                            "node": {
                              "name": "bjpy"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYmtydyIsImMiOjB9",
                            "node": {
                              "name": "bkrw"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYm14biIsImMiOjB9",
                            "node": {
                              "name": "bmxn"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnJ1YiIsImMiOjB9",
                            "node": {
                              "name": "brub"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnNhciIsImMiOjB9",
                            "node": {
                              "name": "bsar"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnRyeSIsImMiOjB9",
                            "node": {
                              "name": "btry"
                            }
                          },
                          {
                            "cursor": "eyJuIjoiYnVzZCIsImMiOjB9",
                            "node": {
                              "name": "busd"
                            }
                          }
                        ]
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxMCwiYyI6MH0",
                  "node": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x00000000000000000000000000000000000000000000000000000000000000c8::bfc_system::BfcSystemState"
                        },
                        "json": {
                          "id": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                          "version": "1"
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMSwiYyI6MH0",
                  "node": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::deny_list::DenyList"
                        },
                        "json": {
                          "id": "0x0000000000000000000000000000000000000000000000000000000000000403",
                          "lists": {
                            "id": "0x1663d1fd9b8ba848551a84dcd4c7292357911edf8e6ef93d7303b1a2008a8c06",
                            "size": "1"
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMiwiYyI6MH0",
                  "node": {
                    "address": "0x00086aea7bd7014130116bb0672cdfb1dd3db42de2679f401d47bfc228b04216",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::skip_list::Node<0x00000000000000000000000000000000000000000000000000000000000000c8::tick::Tick>>"
                        },
                        "json": {
                          "id": "0x00086aea7bd7014130116bb0672cdfb1dd3db42de2679f401d47bfc228b04216",
                          "name": "458516",
                          "value": {
                            "score": "458516",
                            "nexts": [
                              {
                                "is_none": false,
                                "v": "460516"
                              }
                            ],
                            "prev": {
                              "is_none": false,
                              "v": "456516"
                            },
                            "value": {
                              "index": {
                                "bits": 14880
                              },
                              "sqrt_price": "38816704581301083970",
                              "liquidity_net": {
                                "bits": "0"
                              },
                              "liquidity_gross": "30705914872908046"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxMywiYyI6MH0",
                  "node": {
                    "address": "0x00da26249823ac2cfb6095f4716f6effe3e92918d2323d6b94d583d61380d427",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::CoinMetadata<0x00000000000000000000000000000000000000000000000000000000000000c8::binr::BINR>"
                        },
                        "json": {
                          "id": "0x00da26249823ac2cfb6095f4716f6effe3e92918d2323d6b94d583d61380d427",
                          "decimals": 9,
                          "name": "Benfen INR",
                          "symbol": "BINR",
                          "description": "",
                          "icon_url": null
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNCwiYyI6MH0",
                  "node": {
                    "address": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<0x0000000000000000000000000000000000000000000000000000000000000001::ascii::String,0x0000000000000000000000000000000000000000000000000000000000000003::stable_pool::StablePool<0x00000000000000000000000000000000000000000000000000000000000000c8::bidr::BIDR>>"
                        },
                        "json": {
                          "id": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                          "name": "00000000000000000000000000000000000000000000000000000000000000c8::bidr::BIDR",
                          "value": {
                            "id": "0xa8971f308036d827571d495f3a7ea5085b8069d7ccabd4472e30c1c9faa25ac3",
                            "activation_epoch": "0",
                            "deactivation_epoch": null,
                            "stable_balance": "0",
                            "rewards_pool": {
                              "value": "0"
                            },
                            "pool_token_balance": "0",
                            "exchange_rates": {
                              "id": "0xf970e819768ae5b85a78feb92876996e1db5a4dd1455c7a1a8af8ffd28daee39",
                              "size": "1"
                            },
                            "pending_stake": "0",
                            "pending_total_sui_withdraw": "0",
                            "pending_pool_token_withdraw": "0",
                            "extra_fields": {
                              "id": "0x003dd9916f633ba618a87a99e176de98dfa529f248e2e6e87987724cd6632d5a",
                              "size": "0"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNSwiYyI6MH0",
                  "node": {
                    "address": "0x040c1f0621a02e0005fd4b179fb2567a6f94611f47c8633121c609b076c80a26",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::linked_table::Node<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::position::Position>>"
                        },
                        "json": {
                          "id": "0x040c1f0621a02e0005fd4b179fb2567a6f94611f47c8633121c609b076c80a26",
                          "name": "4",
                          "value": {
                            "prev": "3",
                            "next": "5",
                            "value": {
                              "vault_id": "0x989f4e807affc81f819ad8e402212b78be0e8894060cf2f1a60ce953f95dd6af",
                              "index": "4",
                              "coin_type_a": {
                                "name": "00000000000000000000000000000000000000000000000000000000000000c8::bars::BARS"
                              },
                              "coin_type_b": {
                                "name": "0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                              },
                              "name": "OpenBlock LP | Pool-5-4",
                              "tick_lower_index": {
                                "bits": 4294919198
                              },
                              "tick_upper_index": {
                                "bits": 4294921198
                              },
                              "liquidity": "395458435516460111"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNiwiYyI6MH0",
                  "node": {
                    "address": "0x0472c7ea9df1aca04ae667ae7dc836370cb4c676d49ef6996b1b59af531b3056",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::linked_table::Node<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::position::Position>>"
                        },
                        "json": {
                          "id": "0x0472c7ea9df1aca04ae667ae7dc836370cb4c676d49ef6996b1b59af531b3056",
                          "name": "5",
                          "value": {
                            "prev": "4",
                            "next": "6",
                            "value": {
                              "vault_id": "0xa664d23579751d39472d61eb95364db4ae28f5fcccf3f17fa227403e8bb62588",
                              "index": "5",
                              "coin_type_a": {
                                "name": "00000000000000000000000000000000000000000000000000000000000000c8::mgg::MGG"
                              },
                              "coin_type_b": {
                                "name": "0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                              },
                              "name": "OpenBlock LP | Pool-17-5",
                              "tick_lower_index": {
                                "bits": 4294964670
                              },
                              "tick_upper_index": {
                                "bits": 4294966670
                              },
                              "liquidity": "44995134465213955"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxNywiYyI6MH0",
                  "node": {
                    "address": "0x05194f67560aa7ef3c09a608f5daabf3d0929ee6454cb4aacaa1ef8c4ed42ccd",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::linked_table::Node<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::position::Position>>"
                        },
                        "json": {
                          "id": "0x05194f67560aa7ef3c09a608f5daabf3d0929ee6454cb4aacaa1ef8c4ed42ccd",
                          "name": "3",
                          "value": {
                            "prev": "2",
                            "next": "4",
                            "value": {
                              "vault_id": "0x05020b571285f72d8e29330835eacc07444b2ab0b7097e870d3160b0613611ae",
                              "index": "3",
                              "coin_type_a": {
                                "name": "00000000000000000000000000000000000000000000000000000000000000c8::bsar::BSAR"
                              },
                              "coin_type_b": {
                                "name": "0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                              },
                              "name": "OpenBlock LP | Pool-13-3",
                              "tick_lower_index": {
                                "bits": 4934
                              },
                              "tick_upper_index": {
                                "bits": 6934
                              },
                              "liquidity": "25243867602656885"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOCwiYyI6MH0",
                  "node": {
                    "address": "0x05376194e55b11da1ff8651d5d44b7fee21d8e1cae1373e8fca5875995228087",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::linked_table::Node<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::position::Position>>"
                        },
                        "json": {
                          "id": "0x05376194e55b11da1ff8651d5d44b7fee21d8e1cae1373e8fca5875995228087",
                          "name": "6",
                          "value": {
                            "prev": "5",
                            "next": "7",
                            "value": {
                              "vault_id": "0x2dc1c19cb76b0cc40878cd80ecd17a6ca9bbc33351856f9bd98325848b5192dd",
                              "index": "6",
                              "coin_type_a": {
                                "name": "00000000000000000000000000000000000000000000000000000000000000c8::bzar::BZAR"
                              },
                              "coin_type_b": {
                                "name": "0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                              },
                              "name": "OpenBlock LP | Pool-15-6",
                              "tick_lower_index": {
                                "bits": 4294962320
                              },
                              "tick_upper_index": {
                                "bits": 4294964320
                              },
                              "liquidity": "55926788469725370"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                },
                {
                  "cursor": "eyJpIjoxOSwiYyI6MH0",
                  "node": {
                    "address": "0x056b8364b8cca413406c3fe7489eedb3e342c27ad0ff7b13acb49022e36cea12",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::dynamic_field::Field<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::linked_table::Node<u64,0x00000000000000000000000000000000000000000000000000000000000000c8::position::Position>>"
                        },
                        "json": {
                          "id": "0x056b8364b8cca413406c3fe7489eedb3e342c27ad0ff7b13acb49022e36cea12",
                          "name": "5",
                          "value": {
                            "prev": "4",
                            "next": "6",
                            "value": {
                              "vault_id": "0x17b138b1b8b518663752b57aa583207b6826e9f89332ff5a6264211cf2ce6ca3",
                              "index": "5",
                              "coin_type_a": {
                                "name": "00000000000000000000000000000000000000000000000000000000000000c8::busd::BUSD"
                              },
                              "coin_type_b": {
                                "name": "0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                              },
                              "name": "OpenBlock LP | Pool-1-5",
                              "tick_lower_index": {
                                "bits": 22028
                              },
                              "tick_upper_index": {
                                "bits": 24028
                              },
                              "liquidity": "13117090415630771"
                            }
                          }
                        }
                      }
                    },
                    "asMovePackage": null
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 1,
            "dependencies": {
              "nodes": []
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
                  },
                  "amount": "3000000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                },
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "300000000000000",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "digest": "D12mDdgdnn9iUZzPEAtcJgKtFcQdXdJXxU6pqEfEBdU9"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "digest": "HC9dxuKdEsya3K56WVxJjLCbxJBs3Y1qCCh2dxYJsTRN"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "digest": "FNJkmXwLwLwd2bbyWsiVQEtzySAaDtEpEHUVx9t1ZkhW"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "GTYXV9e5ci8D3mH4bb4vgw8bsiQff8HsmE3Spkvvn1dt"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "DKqTFz1oE8Q6pHBQatRuHf2mxpj82RXdhpQoZQDPvyfE"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000007",
                    "digest": "8WRcXeWa3ykGBPAJhMVjBQNE3CuhXsiGcsAdd3MsDCqc"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000008",
                    "digest": "5mH3hUvUd9AcBoS6dnWqDUJE6iuALi5Yc69Sb4VfVdUQ"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000009",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000009",
                    "digest": "HpshYk81gg47Nktj7YVz1u2DcAUxgki77cQSzy2boopU"
                  }
                },
                {
                  "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x000000000000000000000000000000000000000000000000000000000000000b",
                    "digest": "Fydb6SwPZh8uzB5Qd1u3Ga5tnvybmBLNjgaNgjbmyMWJ"
                  }
                },
                {
                  "address": "0x00000000000000000000000000000000000000000000000000000000000000c8",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c8",
                    "digest": "9Zf77TQpw5kEnhZxjYmvQphFWmjNa2xjSCK4Ja3nKL5T"
                  }
                },
                {
                  "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                    "digest": "7vThVAgmaRX4qit7wVkXpc5ZRmA69SZreuL3q9fwDphJ"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000403",
                    "digest": "FsRKeBXsaJ3CmzRaKprAgizpjEJmqHSsrTPqsoWy67cm"
                  }
                },
                {
                  "address": "0x00086aea7bd7014130116bb0672cdfb1dd3db42de2679f401d47bfc228b04216",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00086aea7bd7014130116bb0672cdfb1dd3db42de2679f401d47bfc228b04216",
                    "digest": "5ofqYPCssPo9rtKL3usx1yHaHbL3g4EQpS6zUogXcGCU"
                  }
                },
                {
                  "address": "0x00da26249823ac2cfb6095f4716f6effe3e92918d2323d6b94d583d61380d427",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00da26249823ac2cfb6095f4716f6effe3e92918d2323d6b94d583d61380d427",
                    "digest": "HPKCLxG5ZR5xT6riHsH2JqjprvYXVD4SyouQxnJJwArr"
                  }
                },
                {
                  "address": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                    "digest": "F4eVmE5m5hgVsn5njt8apA9WF9oywTkphPZxE4wqFdge"
                  }
                },
                {
                  "address": "0x040c1f0621a02e0005fd4b179fb2567a6f94611f47c8633121c609b076c80a26",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x040c1f0621a02e0005fd4b179fb2567a6f94611f47c8633121c609b076c80a26",
                    "digest": "5Eq5fXfkubkJLaebkJM8RxRj31xsHuuSQ6ACTZDpvNWZ"
                  }
                },
                {
                  "address": "0x0472c7ea9df1aca04ae667ae7dc836370cb4c676d49ef6996b1b59af531b3056",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0472c7ea9df1aca04ae667ae7dc836370cb4c676d49ef6996b1b59af531b3056",
                    "digest": "APDqMByNks4n4NMFNGTZxSFWLtJKVRXGkqoeyVCgEgXK"
                  }
                },
                {
                  "address": "0x05194f67560aa7ef3c09a608f5daabf3d0929ee6454cb4aacaa1ef8c4ed42ccd",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x05194f67560aa7ef3c09a608f5daabf3d0929ee6454cb4aacaa1ef8c4ed42ccd",
                    "digest": "2umchRiZmnApkWBXFu34xRJf98KWGnvPVp2bXG6Q2ZuD"
                  }
                },
                {
                  "address": "0x05376194e55b11da1ff8651d5d44b7fee21d8e1cae1373e8fca5875995228087",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x05376194e55b11da1ff8651d5d44b7fee21d8e1cae1373e8fca5875995228087",
                    "digest": "7D5oxmtV5eeehL5jSNbKBoKGDy4ptys73FYQvBNEMYed"
                  }
                },
                {
                  "address": "0x056b8364b8cca413406c3fe7489eedb3e342c27ad0ff7b13acb49022e36cea12",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x056b8364b8cca413406c3fe7489eedb3e342c27ad0ff7b13acb49022e36cea12",
                    "digest": "93SduSKKzcMuu3LgjV1mNPKJNaM8gprMQ5eyzWLzqp56"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 0
            },
            "transactionBlock": {
              "digest": "7Q9t6hwU6mq5iJAmdYXb7y4cL4xJEeoNxg7vSgRvCZ5"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 3, line 106:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 108-183:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "DPq7c2A5SyX36jGrNW6QNstAzSxtFPai1SZj4eF7oFDR",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "ConsensusCommitPrologueTransaction",
            "epoch": {
              "epochId": 0
            },
            "round": 0,
            "commitTimestamp": "1970-01-01T00:00:42Z",
            "consensusCommitDigest": "11111111111111111111111111111111"
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "7Q9t6hwU6mq5iJAmdYXb7y4cL4xJEeoNxg7vSgRvCZ5"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "Dbu2swR7jSwhxcjbyL1iGCuQPSrKR7Kyp8PEbKxsd9Uq"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:42Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "DPq7c2A5SyX36jGrNW6QNstAzSxtFPai1SZj4eF7oFDR"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 6, line 187:
//# advance-epoch
Epoch advanced: 0

task 7, lines 189-276:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "BqM3PKbcC5TyViZHi4vPSyGGMSJdQc5CyzuAtdTYS99w",
          "sender": null,
          "signatures": [
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0x0000000000000000000000000000000000000000000000000000000000000000"
            },
            "gasPayment": {
              "nodes": []
            },
            "gasPrice": "1",
            "gasBudget": "0"
          },
          "kind": {
            "__typename": "EndOfEpochTransaction",
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "ChangeEpochTransaction",
                    "epoch": null,
                    "protocolVersion": 51,
                    "storageCharge": "0",
                    "computationCharge": "0",
                    "storageRebate": "0",
                    "nonRefundableStorageFee": "0",
                    "startTimestamp": "1970-01-01T00:01:25Z"
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 4,
            "dependencies": {
              "nodes": [
                {
                  "digest": "7Q9t6hwU6mq5iJAmdYXb7y4cL4xJEeoNxg7vSgRvCZ5"
                },
                {
                  "digest": "5PVjy7zeFAkE4pRWN5zuKYChDaGpF43BALgdEbGQEBhk"
                }
              ]
            },
            "balanceChanges": {
              "nodes": []
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000005",
                    "digest": "2cw1tgq8rMmQWznMxxUVLDpqiWypjfLMvKmLgUjgvWYX"
                  }
                },
                {
                  "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0000000000000000000000000000000000000000000000000000000000000006",
                    "digest": "2HyqU84oRNFVMCsFs5WFcA3F8eHs6f54tyac3rtwNwq2"
                  }
                },
                {
                  "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x00000000000000000000000000000000000000000000000000000000000000c9",
                    "digest": "74eb6sJEFY7s86EwubEB238JiupyNb3NDytMFv7dmED5"
                  }
                },
                {
                  "address": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x015350f7b113a25b95ac033001f3d363b1e91e0d759b7b689fa94f2fa2ab57a1",
                    "digest": "H1JSLZxrWaXEBN2F9vVPQwmDnzr2XQCX1u74J3NJLZHk"
                  }
                },
                {
                  "address": "0x0927685cacd4ef7d8a8115941c7801a173079fa17047f70d989d36fa81371b58",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x0927685cacd4ef7d8a8115941c7801a173079fa17047f70d989d36fa81371b58",
                    "digest": "7o9hL2J2UpHeX2sHmvo1uUvwvHf3GfabMYzWgXek3MZS"
                  }
                },
                {
                  "address": "0x15ea27e4c5bd0d1690cad3a7ba8c76c99172d2433416fa56ee8fee6f2762cf08",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x15ea27e4c5bd0d1690cad3a7ba8c76c99172d2433416fa56ee8fee6f2762cf08",
                    "digest": "8X4ZojUtrLC9Sz2EfFREZHe8qJX3f2h4mUS1qmq56wGv"
                  }
                },
                {
                  "address": "0x1b142518118a7cefd36bd7004bb38f4cbb2a3a1a26f23cad41e5731dcfb80d37",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x1b142518118a7cefd36bd7004bb38f4cbb2a3a1a26f23cad41e5731dcfb80d37",
                    "digest": "DYtUSXi7ffkEUWCJDQr1T4UcDDFfiKFeodcWe5GEwXiG"
                  }
                },
                {
                  "address": "0x1c19d67877aa7ed94ad6e41fe029eca781f1aa497d74cefd045d3198dd4b0e88",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x1c19d67877aa7ed94ad6e41fe029eca781f1aa497d74cefd045d3198dd4b0e88",
                    "digest": "4oJApKmyshTCVrRRiaU5ZY75WQ8zjk4bFw3cQv3533Yk"
                  }
                },
                {
                  "address": "0x20f33d5559b63e11d334372b43f615a6ecef07769bda6b73a299aeeeb2208f98",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x20f33d5559b63e11d334372b43f615a6ecef07769bda6b73a299aeeeb2208f98",
                    "digest": "3Dj3Zv8uXbUPV2oag63bBcQmMBotgGFXzendrtxxU66o"
                  }
                },
                {
                  "address": "0x21796b706465625d1f363ff8918cc03d731851ffd30dfd5ce6a7afe5e47103d7",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x21796b706465625d1f363ff8918cc03d731851ffd30dfd5ce6a7afe5e47103d7",
                    "digest": "D1aJ1fXMrWuFe35pxNLfKcdxNUCUz6hsVCdc1mdKzRcS"
                  }
                },
                {
                  "address": "0x223b3f2eb9b16a50973859e7015be839174e02521cdd0eb742e258847714331c",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x223b3f2eb9b16a50973859e7015be839174e02521cdd0eb742e258847714331c",
                    "digest": "9AUSqgPS9nj38zKSN63Zuv3vFQiyBSLPDWGw9cMrTJaT"
                  }
                },
                {
                  "address": "0x22fb878e6160b38d010f5b1275f2f551d36eb96326d8058d0e665764ab273b6c",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x22fb878e6160b38d010f5b1275f2f551d36eb96326d8058d0e665764ab273b6c",
                    "digest": "BNK3NASg7i1YtrWvjf3J74Q1QE8yqUm6DtkwBAf7bdnh"
                  }
                },
                {
                  "address": "0x26b1572ce4c464d4497f44be111553a20c7cb6120876cfae8a114a6f02416e07",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x26b1572ce4c464d4497f44be111553a20c7cb6120876cfae8a114a6f02416e07",
                    "digest": "AHNL74uDwdBUuhxyCZqCLUxW7JS5RpFbZsM4RQr2U1mM"
                  }
                },
                {
                  "address": "0x2ec3b234728c4ae9939f62ff122dddf2763de0c21e62160408de9a3a777c09af",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": null
                },
                {
                  "address": "0x30fca2fde7a07ef1dd895dbad374359a453247ad140a647d22e75f68ef6a1b71",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x30fca2fde7a07ef1dd895dbad374359a453247ad140a647d22e75f68ef6a1b71",
                    "digest": "BPuQTQaaGM2wCDeU1auUsFFc1WKyxT9w5NSy9M127BRY"
                  }
                },
                {
                  "address": "0x36b833b8b2af69414480207b52946ab5cab66e98dbc2d2f2b64c5910378f2f5a",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x36b833b8b2af69414480207b52946ab5cab66e98dbc2d2f2b64c5910378f2f5a",
                    "digest": "wjsu3X223622pFtNxTRbcd5wujsGBFLeF9iMW7cfZP8"
                  }
                },
                {
                  "address": "0x39c4c932ec6648f17a57f4ffeaffb41890bb157b21b6a8e3d67dd03b56688fae",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x39c4c932ec6648f17a57f4ffeaffb41890bb157b21b6a8e3d67dd03b56688fae",
                    "digest": "Esen1zbbtxL5SPoxF47BGuMk5njB5A2W5hMgPCcsMLeF"
                  }
                },
                {
                  "address": "0x3c8230b669067b7df404d4935d845100b49f8d4fbfb0a9ffbeb1d4ee1626c18e",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x3c8230b669067b7df404d4935d845100b49f8d4fbfb0a9ffbeb1d4ee1626c18e",
                    "digest": "98BHvK8Mq7GmKHA1SVWhKS57DPbAGnrPLe5iZP5y7X1M"
                  }
                },
                {
                  "address": "0x435573fb8a2c87081e3a8d47e48657313112b77b8b0ce1f4970c4fe3002ac8a5",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x435573fb8a2c87081e3a8d47e48657313112b77b8b0ce1f4970c4fe3002ac8a5",
                    "digest": "JCbkKbjg54X5jhfWbWeDvkNiv1UVgkWSEmaYQyQ6wu4C"
                  }
                },
                {
                  "address": "0x49ad642bef617656def0960e6175647cc0e7d7c9cd52ed89e60b90cb9e80e571",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x49ad642bef617656def0960e6175647cc0e7d7c9cd52ed89e60b90cb9e80e571",
                    "digest": "3p751S9Er5FQDdfy7pJjDRdzfAsKPj9BeJupq7SChCFP"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": null,
              "gasSummary": {
                "computationCost": "0",
                "storageCost": "0",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:01:25Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "BqM3PKbcC5TyViZHi4vPSyGGMSJdQc5CyzuAtdTYS99w"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}
