processed 7 tasks

init:
A: object(0,0)

task 1, lines 9-23:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5092000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 25-27:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 29-30:
//# programmable --sender A --inputs object(2,0)
//> 0: P0::M::delete(Input(0))
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 2490444, non_refundable_storage_fee: 25156

task 4, line 32:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 34-38:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "qMzauhDkWpvJQWrKVn3iJvjrh2uaBUF9AMp55gwXJDv",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFCbc292ffb154b66cba578e7e593f87f03f86eacfb317109297c2f786298c116afd38e",
        "version": "2",
        "previousVersion": "1",
        "digest": "GBaebqfdwdzAw83o2ybc2SNxazZTFFnsjmbwVJ8yBh4j"
      },
      {
        "type": "created",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x11657d6478b0655047ecc472b47a63be8f5f8b78e03ed06341d4bb185b264de9::M::O",
        "objectId": "BFCd45151dc23b8f955a117eb79f0b0bc86af866fd6f5eab742cf832119cebbc5badd32",
        "version": "2",
        "digest": "8jukvWZGs3v1guckKaCLucsXvtyGb24piD76HuCzb6Az"
      }
    ]
  }
}

task 6, lines 40-44:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "digest": "2JxEgrXfP4SB3Q6YFabRF8f8uzpJpr5mJra4nkjjxCxh",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFCbc292ffb154b66cba578e7e593f87f03f86eacfb317109297c2f786298c116afd38e",
        "version": "3",
        "previousVersion": "2",
        "digest": "DPMR2ny6EjGCWxcx1NA936Com9mD4LAKLDpVcJjFTTmg"
      },
      {
        "type": "deleted",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "objectType": "0x11657d6478b0655047ecc472b47a63be8f5f8b78e03ed06341d4bb185b264de9::M::O",
        "objectId": "BFCd45151dc23b8f955a117eb79f0b0bc86af866fd6f5eab742cf832119cebbc5badd32",
        "version": "3"
      }
    ]
  }
}
