processed 8 tasks

init:
A: object(0,0)

task 1, lines 9-36:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7037600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 38-40:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 42-43:
//# programmable --sender A --inputs object(2,0)
//> 0: P0::M::wrap(Input(0))
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2766400,  storage_rebate: 2497968, non_refundable_storage_fee: 25232

task 4, lines 45-47:
//# programmable --sender A --inputs object(2,0)
//> 0: P0::M::unwrap(Input(0));
//> 1: P0::M::delete(Result(0))
mutated: object(0,0), object(2,0)
unwrapped_then_deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 2738736, non_refundable_storage_fee: 27664

task 5, line 49:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 51-55:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "7g9BJxPeoqgD6si5ZRTUSCwSbubwW9ZpJsK9snanBjgC",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC6156426cbfdc37ea964031e97d3e76145a5e8ba8a1c94ffac49d1816bd4ea867196e",
        "version": "3",
        "previousVersion": "2",
        "digest": "2skTfraZEQGLZ83zxYPEKqaqbBXizLjw6pJBYwnMZkZQ"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0xcfd4f1d5991e12a7b442a849a21d35ae25ab26e751660851a1c6b4e1bdb4fe49::M::O",
        "objectId": "BFCc08e83596f5f7430a9d72db0db4964052d6e8e6caa74f8367a7c9b1bc09144dec75d",
        "version": "3",
        "previousVersion": "2",
        "digest": "Bk5Q6F1RtCWhZwwUa4KYLHrPGmBoRn7ceWvsRJMVRoH7"
      }
    ]
  }
}

task 7, lines 57-61:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "digest": "5RZhjku6Hk4yrKuXCbJyEf8H9SAiatCmqFR5bbdfiGrb",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC6156426cbfdc37ea964031e97d3e76145a5e8ba8a1c94ffac49d1816bd4ea867196e",
        "version": "4",
        "previousVersion": "3",
        "digest": "33P6QpcCyFPqcfJPuWdwQfGZti2YkdE1SYNmDzmzTHrn"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0xcfd4f1d5991e12a7b442a849a21d35ae25ab26e751660851a1c6b4e1bdb4fe49::M::O",
        "objectId": "BFCc08e83596f5f7430a9d72db0db4964052d6e8e6caa74f8367a7c9b1bc09144dec75d",
        "version": "4",
        "previousVersion": "3",
        "digest": "9miZJjEJSnDhLGKYTh6WxWMHKHhhviVVhNq4JZnaHsRd"
      }
    ]
  }
}
