processed 7 tasks

init:
A: object(0,0)

task 1, lines 9-23:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5092000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 25-27:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 29-30:
//# programmable --sender A --inputs object(2,0)
//> 0: P0::M::delete(Input(0))
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 2490444, non_refundable_storage_fee: 25156

task 4, line 32:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 34-38:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "6YsS23x85tnjZk4ByhuQ8BmFgspwp6NckJXyYXWQ4aMb",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "2",
        "previousVersion": "1",
        "digest": "262pRKZ1hkTMDDrnPvZqHGS2ByaNrxwczqaN2odkZ95t"
      },
      {
        "type": "created",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0xa61aae51a777f35b5e36da0013e6e4826e7342f4dfe0c0501af2c8d88766201e::M::O",
        "objectId": "BFC667ecf89e21200c4c581495846944469fbca220a9249dc1e084ff0038a8eeb317b33",
        "version": "2",
        "digest": "HK3Y7kJ8c5JAGyLc83MyV8DV4Mc9v1WS9pMxNo2boc76"
      }
    ]
  }
}

task 6, lines 40-44:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "digest": "AADwSF32DJZrJ2bPxm1b2rMM3mGytEYQ642DNe7CLdJf",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "3",
        "previousVersion": "2",
        "digest": "MmfQ2VY2daHjda54FmzCZZ7QUSaFUYBJUhdDDNanw5G"
      },
      {
        "type": "deleted",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "objectType": "0xa61aae51a777f35b5e36da0013e6e4826e7342f4dfe0c0501af2c8d88766201e::M::O",
        "objectId": "BFC667ecf89e21200c4c581495846944469fbca220a9249dc1e084ff0038a8eeb317b33",
        "version": "3"
      }
    ]
  }
}
