processed 7 tasks

init:
A: object(0,0)

task 1, lines 9-23:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5092000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 25-27:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 29-30:
//# programmable --sender A --inputs object(2,0)
//> 0: P0::M::delete(Input(0))
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 2490444, non_refundable_storage_fee: 25156

task 4, line 32:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 34-38:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "HKvXokbzT3o8VL5KHqNqp47MziR4PVkAweDtatKaswCf",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "2",
        "previousVersion": "1",
        "digest": "5w4zjehD4VhLKJAMepEtxvDu27e6WMxuTXEjkAKsPtH5"
      },
      {
        "type": "created",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x4e1b3c744a4f405127b04b5b48fac6ab99999f330d6bd7a1f4bd19d57aa7bfb3::M::O",
        "objectId": "BFC253abb3bf238be9391dd6e2f62c9c7a63c9f55af909e017c908ce981402262f74da2",
        "version": "2",
        "digest": "36e5jijiRd2bEzdnZ4YURKtBGqn9w1XKfrgVacor3pFg"
      }
    ]
  }
}

task 6, lines 40-44:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "digest": "HbEkpZx14KMjNEDNKzDNMrv4Zm5tS5zd8mw7MAuPd7br",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "3",
        "previousVersion": "2",
        "digest": "6FDxDWkz6DDB7VRSrcpLJxZTKLcShG8gSgRCa5YaoNZH"
      },
      {
        "type": "deleted",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "objectType": "0x4e1b3c744a4f405127b04b5b48fac6ab99999f330d6bd7a1f4bd19d57aa7bfb3::M::O",
        "objectId": "BFC253abb3bf238be9391dd6e2f62c9c7a63c9f55af909e017c908ce981402262f74da2",
        "version": "3"
      }
    ]
  }
}
