processed 8 tasks

init:
A: object(0,0)

task 1, lines 9-36:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7037600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 38-40:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 42-43:
//# programmable --sender A --inputs object(2,0)
//> 0: P0::M::wrap(Input(0))
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2766400,  storage_rebate: 2497968, non_refundable_storage_fee: 25232

task 4, lines 45-47:
//# programmable --sender A --inputs object(2,0)
//> 0: P0::M::unwrap(Input(0));
//> 1: P0::M::delete(Result(0))
mutated: object(0,0), object(2,0)
unwrapped_then_deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 2738736, non_refundable_storage_fee: 27664

task 5, line 49:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 51-55:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "CbpH6XZZCU1LFNmkn8N4AmCdJPnHJ3LqzMprFiaDgHgj",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x9d9c2523941b35ea1d3fd64bfd9692ff5c60bfa722de1679b945ec9626dd755e::M::O",
        "objectId": "BFC7624db1175578ede3589ca57616310ff8c2a83bb97dcfd419c0d232b6f946a4d2109",
        "version": "3",
        "previousVersion": "2",
        "digest": "8Zu5SpZ1bmwgz9Uz9sLvwRF1xbcBYQA6az7hQ34cii2p"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFCbc292ffb154b66cba578e7e593f87f03f86eacfb317109297c2f786298c116afd38e",
        "version": "3",
        "previousVersion": "2",
        "digest": "8LwSJYh9yBgFCRDBdTMijRPmqxz3n6fdfKFet9vRkS6z"
      }
    ]
  }
}

task 7, lines 57-61:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "digest": "AAryUnZ8QrVgC4Bf6ubgW6Yh2LXpkCQRHLGJLSvDrEpN",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x9d9c2523941b35ea1d3fd64bfd9692ff5c60bfa722de1679b945ec9626dd755e::M::O",
        "objectId": "BFC7624db1175578ede3589ca57616310ff8c2a83bb97dcfd419c0d232b6f946a4d2109",
        "version": "4",
        "previousVersion": "3",
        "digest": "Fv1kJE86QCryiw98W2nTWFsXsDfLfHEjK4nH7MdnpGMN"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFCbc292ffb154b66cba578e7e593f87f03f86eacfb317109297c2f786298c116afd38e",
        "version": "4",
        "previousVersion": "3",
        "digest": "BrsCcVyfV9w1Ce6G872ZaEsXgMrfGvLbYWTzX6HeZD9N"
      }
    ]
  }
}
