processed 8 tasks

init:
A: object(0,0)

task 1, lines 9-36:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7037600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 38-40:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 42-43:
//# programmable --sender A --inputs object(2,0)
//> 0: P0::M::wrap(Input(0))
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2766400,  storage_rebate: 2497968, non_refundable_storage_fee: 25232

task 4, lines 45-47:
//# programmable --sender A --inputs object(2,0)
//> 0: P0::M::unwrap(Input(0));
//> 1: P0::M::delete(Result(0))
mutated: object(0,0), object(2,0)
unwrapped_then_deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 2738736, non_refundable_storage_fee: 27664

task 5, line 49:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 51-55:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "77PzPqm7R982r7m77Tn2omctDQbgbP8dXmuT5zHUGXQK",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "3",
        "previousVersion": "2",
        "digest": "64pMCReWtnCvLztmEUt1sZGYmGnhCQkvjoYM4VbP88hL"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x41db118433fe737c5e84f79e7943c32c17a0e99aaab0e02c5e702da7b723198f::M::O",
        "objectId": "BFCb93ea6fc840cf64351d0f33fb5819a4ae31ff008bae988276c48b247a846ac9071c7",
        "version": "3",
        "previousVersion": "2",
        "digest": "3J6Hr9Bc2afK6GUzY3fwSkdrqcnksZBnJ1AfaND6mG2q"
      }
    ]
  }
}

task 7, lines 57-61:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "digest": "Hgxx1F4bcpV4aHFDKb8tCJXBbtMMsr1ZLbmxQL9Yzeqi",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "4",
        "previousVersion": "3",
        "digest": "FcBRLc4bYaaWPtEPgwDG7cuDvuYUDDpfxR8gBAhuoYWy"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x41db118433fe737c5e84f79e7943c32c17a0e99aaab0e02c5e702da7b723198f::M::O",
        "objectId": "BFCb93ea6fc840cf64351d0f33fb5819a4ae31ff008bae988276c48b247a846ac9071c7",
        "version": "4",
        "previousVersion": "3",
        "digest": "F9sVcUFuE95Y62FRtq1a7yrRJqHuYwH45XkZNkmz8ZCe"
      }
    ]
  }
}
