processed 6 tasks

init:
A: object(0,0)

task 1, lines 9-12:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5396000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 14-21:
//# upgrade --package P0 --upgrade-capability 1,1 --sender A
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6634800,  storage_rebate: 2911788, non_refundable_storage_fee: 29412

task 3, line 23:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 25-29:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "9itsqG44gbQxUcHqn51NHFA6gBZL9uW6KWgoJcDvM2Xe",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "2",
        "previousVersion": "1",
        "digest": "BqomF7QQjsA89EDtkbmJeD6yc5bsraLNzWZGEnY5VK5"
      },
      {
        "type": "published",
        "packageId": "BFC6f8d4760d48c6b41976ee7eeb276cd7e9e8bb24485a7ac4d04d2b2222297d6c22062",
        "version": "1",
        "digest": "A3ke8p8LU68UFt5HtpZ6aCXs2UEkiJmrEYXgyVpf1WPF",
        "modules": [
          "M"
        ]
      },
      {
        "type": "created",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::package::UpgradeCap",
        "objectId": "BFC92a91aa72517c8539a05cabbf06c34eb5d56ccdec4f880236786fb79c2a7d77f09de",
        "version": "2",
        "digest": "9ZYbDsBUiSX86aETewmaMPK2aGMSax9dkDUUhAxGXBWQ"
      }
    ]
  }
}

task 5, lines 31-35:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "digest": "4JJrbsS5ZTvZZtFnFAsz3vcxyMcseSxVxe6xB9rSpEAa",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "3",
        "previousVersion": "2",
        "digest": "CdCdF8AFQzscZ1sZ8sGQpHZLBYZpRUgsszV571oUS2FB"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::package::UpgradeCap",
        "objectId": "BFC92a91aa72517c8539a05cabbf06c34eb5d56ccdec4f880236786fb79c2a7d77f09de",
        "version": "3",
        "previousVersion": "2",
        "digest": "C1fCV4iS59eBgqGgUxmy5jQhkgL5Q2my7yMAGfsA9fXk"
      },
      {
        "type": "published",
        "packageId": "BFC9d3898f4267aeb695535ee38fee42ac70197d5a0a003ebec64e0142e232fd4939e95",
        "version": "2",
        "digest": "ALWEtT2NnjbUzzAqMn5Ks33B31dcrxGiuFRmBzNiw8bm",
        "modules": [
          "M",
          "N"
        ]
      }
    ]
  }
}
