processed 6 tasks

init:
A: object(0,0)

task 1, lines 9-12:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5396000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 14-21:
//# upgrade --package P0 --upgrade-capability 1,1 --sender A
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6634800,  storage_rebate: 2911788, non_refundable_storage_fee: 29412

task 3, line 23:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 25-29:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "6Y4pKiiyym3TcDZSQRapG5uWsjwxQwZkiqXasoty6WFc",
    "objectChanges": [
      {
        "type": "published",
        "packageId": "BFC40d53258b4f783c74a805c629f018396dcaa1026933e9cebea2c3a76ff2b76d85ba4",
        "version": "1",
        "digest": "9YQ4tRj85QakxQCBKmVRftx8ZG6ZP1ydmdtxmRbdN6AM",
        "modules": [
          "M"
        ]
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFCbc292ffb154b66cba578e7e593f87f03f86eacfb317109297c2f786298c116afd38e",
        "version": "2",
        "previousVersion": "1",
        "digest": "3V8WJP24NkGyQUKGu6ypfzKtHyZh4xy8UfEbUVohqUT7"
      },
      {
        "type": "created",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::package::UpgradeCap",
        "objectId": "BFCfac512e5bd9a7ea65f62bf74ffac50d3c7bfb63b7f88e7710779716f5ae0d047c8fb",
        "version": "2",
        "digest": "FSawnt9LywcFrBJetjLhvteDpYrThAufVoxkgRwjUDEF"
      }
    ]
  }
}

task 5, lines 31-35:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "digest": "28XQugvpYNFsBaKKZvQsN6sCCHozScTmcWXbPzuk2Wr2",
    "objectChanges": [
      {
        "type": "published",
        "packageId": "BFC182721c9cf019ccfd1bc2284389bd159b3a064c000486b9baa9b3189097f7cabddd9",
        "version": "2",
        "digest": "Ap92H3A7q3GRpLds2DQknd6LUezBPqDMZmKjs4uxuAzq",
        "modules": [
          "M",
          "N"
        ]
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFCbc292ffb154b66cba578e7e593f87f03f86eacfb317109297c2f786298c116afd38e",
        "version": "3",
        "previousVersion": "2",
        "digest": "7kTjJqKSH9USduPzPk1DwZ1QZhJ3DfLFG5nZw1cYY51E"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::package::UpgradeCap",
        "objectId": "BFCfac512e5bd9a7ea65f62bf74ffac50d3c7bfb63b7f88e7710779716f5ae0d047c8fb",
        "version": "3",
        "previousVersion": "2",
        "digest": "J8RnjDUG7QLpEC7NVd8K9NjVpsGmrnXkf6d8ZomiZZpo"
      }
    ]
  }
}
