processed 6 tasks

init:
A: object(0,0)

task 1, lines 9-12:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5396000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 14-21:
//# upgrade --package P0 --upgrade-capability 1,1 --sender A
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6634800,  storage_rebate: 2911788, non_refundable_storage_fee: 29412

task 3, line 23:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 25-29:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "7xushSCGFFDQuc3pc3TpRwUK8o3CWVrUk8m4Km2qTpRd",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "2",
        "previousVersion": "1",
        "digest": "48M2QuqkdGQGEdx3drDgw2PNjzCPdFPPX6ihMffia49c"
      },
      {
        "type": "published",
        "packageId": "BFC1c8c986122357bb4a096c2eb36bba3b4c0526d16c35da46deb13a9b10e4450ed0802",
        "version": "1",
        "digest": "2xojkLdcQzey82g6EUxnoGCzTiPvfLNJMeYySeh1oHmq",
        "modules": [
          "M"
        ]
      },
      {
        "type": "created",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::package::UpgradeCap",
        "objectId": "BFC69dc2b5c196c7e317c1364461dd8df9c4d38e5a8a7520a8f3938a2ba39ce11674426",
        "version": "2",
        "digest": "GAsPqosbFQTXVt4i4Qy3ZSp3QmwTaGF5hFuZiqB9E4gV"
      }
    ]
  }
}

task 5, lines 31-35:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "digest": "2htFTpDZqXnzar7tdDp7tc7EG7uop5dHvyr7QKU3J3NL",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "3",
        "previousVersion": "2",
        "digest": "CCNkkuBeHztGyoPirCYzyj2a8AXKogcr19BBb2mdmxWq"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::package::UpgradeCap",
        "objectId": "BFC69dc2b5c196c7e317c1364461dd8df9c4d38e5a8a7520a8f3938a2ba39ce11674426",
        "version": "3",
        "previousVersion": "2",
        "digest": "GHqHoDrL83bkYjbeogT9f58b3NvwtUb4n5om7zq4YTgj"
      },
      {
        "type": "published",
        "packageId": "BFC82e4cb16bc186ff0607553e2b47d15e479d35c397cac77448920006e84896420ecd8",
        "version": "2",
        "digest": "22VLPrF68fzHurGSbSkTxGnjQC2BtmEw2S77hgd7Dyqd",
        "modules": [
          "M",
          "N"
        ]
      }
    ]
  }
}
