processed 6 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 8-17:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 4864000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 19-21:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 23-24:
//# programmable --sender A --inputs object(2,0) @B
//> 0: TransferObjects([Input(0)], Input(1))
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 2490444, non_refundable_storage_fee: 25156

task 4, line 26:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 28-32:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "BwZwBPJAcAUvA9RMHsrZTbmnmz5HmjFyAUTdLhN7Af1b",
    "objectChanges": [
      {
        "type": "transferred",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "recipient": {
          "AddressOwner": "BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9"
        },
        "objectType": "0xf3a4a6c0fff447446c98e3999ef3be73e85e75e00685767db1ed0d45fe1f7546::M::O",
        "objectId": "BFC44184c8b0991aaaf96bf0bc8c682f03a40984d29ee3a6b8e2ddafce65fb32010c4c9",
        "version": "3",
        "digest": "J96Qp9T7r2RF9MNKuDsjMSwXGPkAyZifYqhA17zvYPYo"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFCa016256dc9858e74591041652d515c888e08b0e27350fcead8a1484266b50ef0b0b0",
        "version": "3",
        "previousVersion": "2",
        "digest": "GqAdRng3QGAUEmQdC2PNMJ23i48vspbibqPoChv8qM26"
      }
    ]
  }
}
