processed 6 tasks

init:
A: object(0,0)

task 1, lines 8-27:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6437200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 29-31:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2766400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 33-35:
//# programmable --sender A --inputs object(2,0) @A
//> 0: P0::M::unwrap(Input(0));
//> 1: TransferObjects([Result(0)], Input(1))
mutated: object(0,0), object(2,0)
unwrapped: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3731600,  storage_rebate: 2738736, non_refundable_storage_fee: 27664

task 4, line 37:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 39-43:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "32XCmFfRgoiB6XTdfnQ5PUXzb5rFFsZEjJyrLzQSrLse",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x0a26ef5ccfaf7650e2358936a683f166d8e46efd16aad44e8894756dccc2609e::M::O",
        "objectId": "BFC5c39c74dfa21b997e0f21667861648293c1e783df2f894aa7bff62bdb6dc8ee1cac9",
        "version": "3",
        "previousVersion": "2",
        "digest": "6z7McNZiqt4FSvq73eRgpcs8qWHde79EBEbcmDWUaoVy"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC6156426cbfdc37ea964031e97d3e76145a5e8ba8a1c94ffac49d1816bd4ea867196e",
        "version": "3",
        "previousVersion": "2",
        "digest": "6xnsv95TWtWLVGCUQ1ViGeo2nfCpKvpDgTRYjc3HfJpj"
      }
    ]
  }
}
