processed 6 tasks

init:
A: object(0,0)

task 1, lines 8-27:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6437200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 29-31:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2766400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 33-35:
//# programmable --sender A --inputs object(2,0) @A
//> 0: P0::M::unwrap(Input(0));
//> 1: TransferObjects([Result(0)], Input(1))
mutated: object(0,0), object(2,0)
unwrapped: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3731600,  storage_rebate: 2738736, non_refundable_storage_fee: 27664

task 4, line 37:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 39-43:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "DH4PUR7jvNqNjuscoAjAvacZ4oCLgqmsGkuaS24JdHxb",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFCbc292ffb154b66cba578e7e593f87f03f86eacfb317109297c2f786298c116afd38e",
        "version": "3",
        "previousVersion": "2",
        "digest": "8RDWJP9yb3f69RNptqcgqFAv7hf1dcAtHAsyKTo9SPfh"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0xe694129650898dab4aa8bc8e927db820187766d4ba3b6ac732e57eef37232d3e::M::O",
        "objectId": "BFCf3c1226f23123bb89ab1dd61f01ae6da35a14a370e8dc4ec55bc55a0fec94d7bdb3d",
        "version": "3",
        "previousVersion": "2",
        "digest": "Bs8DRFk4LWjgAGwdMZFyRgyvXPSqTwAqUYX23RDG9cc9"
      }
    ]
  }
}
