processed 6 tasks

init:
A: object(0,0)

task 1, lines 8-27:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6437200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 29-31:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2766400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 33-35:
//# programmable --sender A --inputs object(2,0) @A
//> 0: P0::M::unwrap(Input(0));
//> 1: TransferObjects([Result(0)], Input(1))
mutated: object(0,0), object(2,0)
unwrapped: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3731600,  storage_rebate: 2738736, non_refundable_storage_fee: 27664

task 4, line 37:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 39-43:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "HVA19u1q4TP1ogMXmTr3gBVGHes3P9eXRhaGecCTPfLL",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "3",
        "previousVersion": "2",
        "digest": "3A2EM3BkR41tbQM3S76hCqcwuCWXpd99iBFZHJpAHjop"
      },
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0xef9a9a7d431c9ca6250b7715e0751bb5eae2863d4916bf2ff856274ec46eee04::M::O",
        "objectId": "BFC193d2a863d0bfec650088bdba58d6d6ea36c3efca16b14959fed565c18e3ca2011ae",
        "version": "3",
        "previousVersion": "2",
        "digest": "4G5VJ1YGZAjpDpxymqRBD4xnUdxyoChQjMU14iKj1ub6"
      }
    ]
  }
}
