processed 6 tasks

init:
A: object(0,0)

task 1, lines 8-26:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6156000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 28-30:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 32-34:
//# programmable --sender A --inputs object(2,0) @A
//> 0: P0::M::wrap(Input(0));
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2766400,  storage_rebate: 2490444, non_refundable_storage_fee: 25156

task 4, line 36:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 38-42:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "3FTKhBzXFbmwC33CGNJBV9TDeoHRWVNkaJfQzdqssgg2",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "3",
        "previousVersion": "2",
        "digest": "B74MGQbQJSNpqcfjQ1ZxGwjKXbZa6d5t7CG7hQ5teU4T"
      },
      {
        "type": "created",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0xa20bb06cf27cbec35eb826e6e14b47052becba3ea88c587402c0385ec95121da::M::O",
        "objectId": "BFC6d7407d9d3203a362a73a733ed62c287375d4f248f40cb7587beef09a4cf2236fde7",
        "version": "3",
        "digest": "BBuM8uybup2C1R72ngFGEXWzxTNH5uvKPw24orFussjY"
      },
      {
        "type": "wrapped",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "objectType": "0xa20bb06cf27cbec35eb826e6e14b47052becba3ea88c587402c0385ec95121da::M::I",
        "objectId": "BFCd17079158f85cc098a6ca7612ee262ea6b30656359403469a8814fab691406cc30ca",
        "version": "3"
      }
    ]
  }
}
