processed 6 tasks

init:
A: object(0,0)

task 1, lines 8-26:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6156000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 28-30:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 32-34:
//# programmable --sender A --inputs object(2,0) @A
//> 0: P0::M::wrap(Input(0));
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2766400,  storage_rebate: 2490444, non_refundable_storage_fee: 25156

task 4, line 36:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 38-42:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "23MXXqDoR5wQKdaPCrCHsYzDLK2zYPi5TaNEGyqSw8e5",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "3",
        "previousVersion": "2",
        "digest": "13fxJff3ZWp3E7cDHPUifgYaizRyTMSpLDaV6HR2YY4L"
      },
      {
        "type": "created",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x091f363a061e36000b379d0f3d823b003ab24717a8563b67f55ac7ed1eb016b9::M::O",
        "objectId": "BFC8a4e74b15974e570ef80350cbb3fa785735ea9eb17eb088620584adbfd2eee34d8f4",
        "version": "3",
        "digest": "EKo1YL2CNVjfsonrZqTGBQuT537oHT7odqfVpGaW9Jta"
      },
      {
        "type": "wrapped",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "objectType": "0x091f363a061e36000b379d0f3d823b003ab24717a8563b67f55ac7ed1eb016b9::M::I",
        "objectId": "BFCf131cfe2467d92bb4f65bd3bc4c60030d732ee9651b6dbcfb959895d4e3359c1ee5f",
        "version": "3"
      }
    ]
  }
}
