processed 6 tasks

init:
A: object(0,0)

task 1, lines 8-26:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6156000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 28-30:
//# programmable --sender A --inputs @A
//> 0: P0::M::new();
//> 1: TransferObjects([Result(0)], Input(0))
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, lines 32-34:
//# programmable --sender A --inputs object(2,0) @A
//> 0: P0::M::wrap(Input(0));
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2766400,  storage_rebate: 2490444, non_refundable_storage_fee: 25156

task 4, line 36:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 38-42:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "DN1SY3YzGDBDeXGZSkfGMWW3ZiSdqXfASNWZ6Xw2Egxp",
    "objectChanges": [
      {
        "type": "mutated",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0x2::coin::Coin<0x2::bfc::BFC>",
        "objectId": "BFC1368f3ce1a354a08e6a92821900897ceb1ad5c9ba4ddcde7c0f0f88a2e9bfbfd4278",
        "version": "3",
        "previousVersion": "2",
        "digest": "9q6Y3nxe1TKrYd7HZ5w16Mah8zzukNrP3BLhBjnWRh9k"
      },
      {
        "type": "wrapped",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "objectType": "0xb94e4106a19e743481afe14f2c58a876b47e8cf3e97e548a14cd38f78ec8fef4::M::I",
        "objectId": "BFCd1504f0757bf1d94ea077a11fbe2595fee39232a2f5f98253b2210779fa9f08c9030",
        "version": "3"
      },
      {
        "type": "created",
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "objectType": "0xb94e4106a19e743481afe14f2c58a876b47e8cf3e97e548a14cd38f78ec8fef4::M::O",
        "objectId": "BFCe7bc8ec851532484f24d71c2422e78db51d61c11da8dfe7a4bb154c2c4efd03e7f39",
        "version": "3",
        "digest": "2VT8uVpTNiSkn9cQbouHFQwV1bTmbrPxoxUmgGMGDbVZ"
      }
    ]
  }
}
