processed 11 tasks

init:
C: object(0,0)

task 1, line 8:
//# create-checkpoint
Checkpoint created: 1

task 2, line 10:
//# advance-epoch
Epoch advanced: 0

task 3, lines 12-14:
//# programmable --sender C --inputs 10000000000 @C
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, lines 16-18:
//# run 0x3::sui_system::request_add_stake --args object(0x5) object(3,0) @validator_0 --sender C
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [19, 254, 188, 80, 102, 229, 198, 85, 110, 227, 100, 33, 90, 119, 228, 215, 93, 175, 10, 39, 212, 70, 170, 249, 156, 225, 197, 93, 56, 215, 176, 223, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(4,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 27534800,  storage_rebate: 2588256, non_refundable_storage_fee: 26144

task 5, line 19:
//# create-checkpoint
Checkpoint created: 3

task 6, lines 21-23:
//# advance-epoch
Epoch advanced: 1

task 7, lines 24-28:
//# programmable --sender C --inputs 10000000000 @C
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1))
// TODO: Short term hack to get around indexer epoch issue
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 8, line 29:
//# create-checkpoint
Checkpoint created: 5

task 9, lines 31-32:
//# advance-epoch
Epoch advanced: 2

task 10, lines 33-62:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "totalStake": "200010002000000",
        "activeValidators": {
          "nodes": [
            {
              "name": "validator-0"
            }
          ]
        },
        "validatorCandidatesSize": 0,
        "inactivePoolsId": "0x7bc722dfae9746ccecf59708b40ca1fc2a1754cc99bb40a4a0cc0a1feeec4d89"
      },
      "totalGasFees": "1000000",
      "totalStakeRewards": "1000000",
      "totalStakeSubsidies": "0",
      "fundSize": "27560944",
      "fundInflow": "2614400",
      "fundOutflow": "1294128",
      "netInflow": "1320272",
      "transactionBlocks": {
        "nodes": [
          {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            },
            "digest": "B4Ph7iKKsoB2DapSSSd5Z9ZtnNKu9bdSMSKBp8KLMjVy"
          },
          {
            "kind": {
              "__typename": "EndOfEpochTransaction"
            },
            "digest": "5wAUJhwyZERQUzb3BcdLWM3PU8SgGPqBu4dyeL1ios8i"
          }
        ]
      }
    }
  }
}
