processed 13 tasks

init:
C: object(0,0)

task 1, line 6:
//# create-checkpoint
Checkpoint created: 1

task 2, line 8:
//# advance-epoch
Epoch advanced: 0

task 3, lines 10-12:
//# programmable --sender C --inputs 10000000000 @C
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1));
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4, lines 14-16:
//# programmable --sender C --inputs 5000000000 @C
//> SplitCoins(Gas, [Input(0)]);
//> TransferObjects([Result(0)], Input(1));
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5, line 18:
//# run 0x3::sui_system::request_add_stake --args object(0x5) object(3,0) @validator_0 --sender C
events: Event { package_id: sui_system, transaction_module: Identifier("sui_system"), sender: C, type_: StructTag { address: sui_system, module: Identifier("validator"), name: Identifier("StakingRequestEvent"), type_params: [] }, contents: [19, 254, 188, 80, 102, 229, 198, 85, 110, 227, 100, 33, 90, 119, 228, 215, 93, 175, 10, 39, 212, 70, 170, 249, 156, 225, 197, 93, 56, 215, 176, 223, 218, 131, 22, 109, 1, 175, 215, 221, 207, 138, 245, 248, 68, 244, 90, 170, 83, 244, 133, 72, 229, 17, 124, 35, 245, 162, 151, 140, 253, 66, 34, 68, 252, 204, 154, 66, 27, 187, 19, 193, 166, 106, 26, 169, 143, 10, 215, 80, 41, 237, 233, 72, 87, 119, 156, 105, 21, 180, 79, 148, 6, 139, 146, 30, 1, 0, 0, 0, 0, 0, 0, 0, 0, 228, 11, 84, 2, 0, 0, 0] }
created: object(5,0)
mutated: object(_), 0x0000000000000000000000000000000000000000000000000000000000000005, object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 17214000,  storage_rebate: 2588256, non_refundable_storage_fee: 26144

task 6, line 20:
//# create-checkpoint
Checkpoint created: 3

task 7, lines 22-72:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "epochId": 1,
      "referenceGasPrice": "100",
      "validatorSet": {
        "totalStake": "200000000000000",
        "activeValidators": {
          "nodes": [
            {
              "name": "validator-0"
            }
          ]
        }
      },
      "startTimestamp": "1970-01-01T00:00:00Z",
      "totalCheckpoints": 0,
      "totalTransactions": null,
      "totalGasFees": null,
      "totalStakeRewards": null,
      "totalStakeSubsidies": null,
      "fundSize": "0",
      "netInflow": null,
      "fundInflow": null,
      "fundOutflow": null,
      "storageFund": {
        "totalObjectStorageRebates": "0",
        "nonRefundableBalance": "0"
      },
      "safeMode": {
        "enabled": false
      },
      "systemStateVersion": 2,
      "systemParameters": {
        "stakeSubsidyStartEpoch": 0
      },
      "systemStakeSubsidy": {
        "balance": "496200000000000000",
        "currentDistributionAmount": "27000000000000"
      },
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 3
          }
        ]
      },
      "transactionBlocks": {
        "nodes": [
          {
            "digest": "6ZP9B6ZLNia9JWUgg91BtZ4LMu1oWN6Lw9UErRrN49kf"
          }
        ]
      },
      "endTimestamp": null
    }
  }
}

task 8, line 74:
//# create-checkpoint
Checkpoint created: 4

task 9, line 76:
//# advance-epoch
Epoch advanced: 1

task 10, line 78:
//# create-checkpoint
Checkpoint created: 6

task 11, lines 80-130:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "epochId": 1,
      "referenceGasPrice": "100",
      "validatorSet": {
        "totalStake": "200000000000000",
        "activeValidators": {
          "nodes": [
            {
              "name": "validator-0"
            }
          ]
        }
      },
      "startTimestamp": "1970-01-01T00:00:00Z",
      "totalCheckpoints": 2,
      "totalTransactions": 4,
      "totalGasFees": "3000000",
      "totalStakeRewards": "3000000",
      "totalStakeSubsidies": "0",
      "fundSize": "0",
      "netInflow": "18560416",
      "fundInflow": "22442800",
      "fundOutflow": "3882384",
      "storageFund": {
        "totalObjectStorageRebates": "0",
        "nonRefundableBalance": "0"
      },
      "safeMode": {
        "enabled": false
      },
      "systemStateVersion": 2,
      "systemParameters": {
        "stakeSubsidyStartEpoch": 0
      },
      "systemStakeSubsidy": {
        "balance": "496200000000000000",
        "currentDistributionAmount": "27000000000000"
      },
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 5
          }
        ]
      },
      "transactionBlocks": {
        "nodes": [
          {
            "digest": "EDskZcQCmyBiP4x6TprPEzsajHbvgxGcVRnABfEq1VD9"
          }
        ]
      },
      "endTimestamp": "1970-01-01T00:00:00Z"
    }
  }
}

task 12, lines 132-182:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "epochId": 2,
      "referenceGasPrice": "100",
      "validatorSet": {
        "totalStake": "200010003000000",
        "activeValidators": {
          "nodes": [
            {
              "name": "validator-0"
            }
          ]
        }
      },
      "startTimestamp": "1970-01-01T00:00:00Z",
      "totalCheckpoints": 0,
      "totalTransactions": null,
      "totalGasFees": null,
      "totalStakeRewards": null,
      "totalStakeSubsidies": null,
      "fundSize": "18560416",
      "netInflow": null,
      "fundInflow": null,
      "fundOutflow": null,
      "storageFund": {
        "totalObjectStorageRebates": "18521200",
        "nonRefundableBalance": "39216"
      },
      "safeMode": {
        "enabled": false
      },
      "systemStateVersion": 2,
      "systemParameters": {
        "stakeSubsidyStartEpoch": 0
      },
      "systemStakeSubsidy": {
        "balance": "496200000000000000",
        "currentDistributionAmount": "27000000000000"
      },
      "checkpoints": {
        "nodes": [
          {
            "sequenceNumber": 6
          }
        ]
      },
      "transactionBlocks": {
        "nodes": []
      },
      "endTimestamp": null
    }
  }
}
