processed 11 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-79:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 200000, storage_cost: 127148,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 81-81:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 25308,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 83-83:
created: object(3,0), object(3,1), object(3,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 100000, storage_cost: 68324,  storage_rebate: 25055, non_refundable_storage_fee: 253

task 4 'run'. lines 85-85:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 100000, storage_cost: 25308,  storage_rebate: 25055, non_refundable_storage_fee: 253

task 5 'run'. lines 87-87:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 100000, storage_cost: 25308,  storage_rebate: 25055, non_refundable_storage_fee: 253

task 6 'run'. lines 89-89:
mutated: object(0,0), object(2,0), object(3,0), object(3,1), object(3,2)
gas summary: computation_cost: 100000, storage_cost: 68324,  storage_rebate: 67641, non_refundable_storage_fee: 683

task 7 'run'. lines 91-91:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 100000, storage_cost: 25308,  storage_rebate: 25055, non_refundable_storage_fee: 253

task 8 'run'. lines 93-93:
mutated: object(0,0), object(2,0)
deleted: object(3,1), object(3,2)
gas summary: computation_cost: 100000, storage_cost: 25308,  storage_rebate: 53646, non_refundable_storage_fee: 542

task 9 'run'. lines 95-95:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 100000, storage_cost: 25308,  storage_rebate: 25055, non_refundable_storage_fee: 253

task 10 'run'. lines 97-97:
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 100000, storage_cost: 13072,  storage_rebate: 25055, non_refundable_storage_fee: 253
