processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 11-45:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 795720,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 47-47:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 256120,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 49-49:
created: object(3,0), object(3,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 627000,  storage_rebate: 253559, non_refundable_storage_fee: 2561

task 4 'run'. lines 51-51:
mutated: object(0,0), object(2,0), object(3,1)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 381520,  storage_rebate: 620730, non_refundable_storage_fee: 6270

task 5 'run'. lines 53-53:
created: object(3,0), object(5,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 627000,  storage_rebate: 253559, non_refundable_storage_fee: 2561

task 6 'run'. lines 55-55:
mutated: object(0,0), object(2,0)
deleted: object(3,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 256120,  storage_rebate: 620730, non_refundable_storage_fee: 6270
