processed 11 tasks

init:
A: object(0,0)

task 1 'publish'. lines 10-67:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 963680,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 69-69:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 253080,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 71-71:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 253080,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 4 'run'. lines 73-73:
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 100000, storage_cost: 630040,  storage_rebate: 250549, non_refundable_storage_fee: 2531

task 5 'run'. lines 75-75:
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 100000, storage_cost: 384560,  storage_rebate: 380714, non_refundable_storage_fee: 3846

task 6 'run'. lines 77-77:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 100000, storage_cost: 253080,  storage_rebate: 250549, non_refundable_storage_fee: 2531

task 7 'run'. lines 79-79:
created: object(7,0)
mutated: object(0,0), object(2,0), object(3,0), object(4,0)
deleted: object(4,1)
gas summary: computation_cost: 100000, storage_cost: 752400,  storage_rebate: 744876, non_refundable_storage_fee: 7524

task 8 'run'. lines 81-81:
mutated: object(0,0), object(3,0), object(4,0)
gas summary: computation_cost: 100000, storage_cost: 384560,  storage_rebate: 380714, non_refundable_storage_fee: 3846

task 9 'run'. lines 83-83:
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 100000, storage_cost: 253080,  storage_rebate: 250549, non_refundable_storage_fee: 2531

task 10 'run'. lines 85-85:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::dynamic_field::borrow_child_object_mut (function index 12) at offset 0, Abort Code: 1
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("dynamic_field") }, function: 12, instruction: 0, function_name: Some("borrow_child_object_mut") }, 1), source: Some(VMError { major_status: ABORTED, sub_status: Some(1), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("dynamic_field") }), indices: [], offsets: [(FunctionDefinitionIndex(12), 0)] }), command: Some(0) } }
