processed 10 tasks

init:
A: object(0,0)

task 1, lines 10-82:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 10548800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 84:
//# run a::m::t0 --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2530800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 86:
//# run a::m::t1 --sender A --args object(2,0)
created: object(3,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4567600,  storage_rebate: 2505492, non_refundable_storage_fee: 25308

task 4, line 88:
//# run a::m::t2 --sender A --args object(2,0)
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 4567600,  storage_rebate: 4521924, non_refundable_storage_fee: 45676

task 5, line 90:
//# run a::m::t3 --sender A --args object(2,0)
created: object(5,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2804400,  storage_rebate: 2505492, non_refundable_storage_fee: 25308

task 6, line 92:
//# view-object 3,0
Owner: Object ID: ( BFC062510bdc247ce486b8b70c260cf7b21c5fdd623d8e4ec9fb6e9987a4e1a6ec82054 )
Version: 4
Contents: sui::dynamic_field::Field<u64, a::m::Counter> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    name: 0u64,
    value: a::m::Counter {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: _,
            },
        },
        count: 1u64,
    },
}

task 7, line 94:
//# run a::m::t4 --sender A --args object(5,0)
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 2804400,  storage_rebate: 2776356, non_refundable_storage_fee: 28044

task 8, line 96:
//# run a::m::t5 --sender A --args object(5,0)
mutated: object(0,0)
deleted: object(5,0)
unwrapped_then_deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 2776356, non_refundable_storage_fee: 28044

task 9, line 98:
//# view-object 3,0
Owner: Object ID: ( BFC062510bdc247ce486b8b70c260cf7b21c5fdd623d8e4ec9fb6e9987a4e1a6ec82054 )
Version: 4
Contents: sui::dynamic_field::Field<u64, a::m::Counter> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    name: 0u64,
    value: a::m::Counter {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: _,
            },
        },
        count: 1u64,
    },
}
