processed 12 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-41:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 779760,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 43-43:
created: object(2,0), object(2,1), object(2,2)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 620920,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 45-45:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: a::m::Obj {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,1)}}}

task 4 'run'. lines 47-47:
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: 0x582b53219b4ca9000b37949317607471985da26ddfd532e6c521f1b3b41dec12, parent_id: 0x2412b9ace14d79b41401a156039e23f97e40b1ddca30d47403a1fdb7ac83ba8a }

task 5 'run'. lines 50-50:
created: object(5,0), object(5,1), object(5,2)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 620920,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 6 'view-object'. lines 52-52:
Owner: Object ID: ( BFCc552b45063364d8c97347ed7ea026bb79ba0c8a323d07b8d5cb8b62ea615521d8564 )
Version: 3
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(5,2)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(5,0)}}

task 7 'run'. lines 54-54:
mutated: object(0,0), object(5,1)
deleted: object(5,0), object(5,2)
gas summary: computation_cost: 100000, storage_cost: 253080,  storage_rebate: 614711, non_refundable_storage_fee: 6209

task 8 'run'. lines 57-57:
created: object(8,0), object(8,1), object(8,2)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 620920,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 9 'view-object'. lines 59-59:
Owner: Object ID: ( BFC3742ca16cf8652c1ba4a958b8cf8ecea1b723e650d5f22e372d4d0c3abcef1ca7a9f )
Version: 5
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(8,2)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(8,0)}}

task 10 'run'. lines 61-61:
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: 0x14468ae733012802631e4becb1d7c943ee5173b9ca72694c2028ef10b09fa0a7, parent_id: 0xe25f3ee60cbd269a8b36e0727c2749181414cc286de9f02cbf266f41cf63fc4d }

task 11 'view-object'. lines 63-63:
Owner: Object ID: ( BFC3742ca16cf8652c1ba4a958b8cf8ecea1b723e650d5f22e372d4d0c3abcef1ca7a9f )
Version: 5
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {id: sui::object::UID {id: sui::object::ID {bytes: fake(8,2)}}, name: sui::dynamic_object_field::Wrapper<u64> {name: 0u64}, value: sui::object::ID {bytes: fake(8,0)}}
