processed 5 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 8-29:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 635360,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 31-31:
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 254600,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 3 'view-object'. lines 33-33:
Owner: Shared
Version: 3
Contents: t2::o2::Obj2 {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4 'programmable'. lines 35-37:
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 130720,  storage_rebate: 122641, non_refundable_storage_fee: 1239
