processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-17:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5130000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 19-19:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3 'view-object'. lines 21-21:
Owner: Shared
Version: 3
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 0u64,
    },
}

task 4 'programmable'. lines 23-24:
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072
