processed 9 tasks

init:
A: object(0,0)

task 3 'programmable'. lines 27-32:
created: object(3,0), object(3,1), object(3,2), object(3,3), object(3,4)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 95152,  storage_rebate: 0, non_refundable_storage_fee: 0

task 6 'programmable'. lines 38-40:
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 13072,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 7 'publish'. lines 42-47:
created: object(7,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 55404,  storage_rebate: 0, non_refundable_storage_fee: 0

task 8 'run'. lines 49-49:
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 13072,  storage_rebate: 12941, non_refundable_storage_fee: 131
