processed 11 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-18:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 46740,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'publish'. lines 20-23:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 53960,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'publish'. lines 25-28:
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 37620,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 5 'programmable'. lines 36-41:
Error: Transaction Effects Status: Invalid package upgrade. Digest in upgrade ticket and computed digest disagree
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: PackageUpgradeError { upgrade_error: DigestDoesNotMatch { digest: [137, 155, 24, 6, 166, 197, 75, 45, 54, 149, 132, 164, 27, 168, 248, 9, 162, 199, 175, 134, 88, 120, 129, 62, 214, 196, 34, 108, 15, 138, 147, 112] } }, source: None, command: Some(2) } }

task 6 'programmable'. lines 43-45:
Error: Transaction Effects Status: Move Runtime Abort. Location: p::n::bar (function index 0) at offset 6, Abort Code: 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: p, name: Identifier("n") }, function: 0, instruction: 6, function_name: Some("bar") }, 0), source: Some(VMError { major_status: ABORTED, sub_status: Some(0), message: Some("p::n::bar at offset 6"), exec_state: None, location: Module(ModuleId { address: p, name: Identifier("n") }), indices: [], offsets: [(FunctionDefinitionIndex(0), 6)] }), command: Some(1) } }

task 7 'set-address'. lines 47-47:
Error: INVALID TEST. Unknown object, object(5,0)

task 8 'programmable'. lines 49-51:
Error: Error checking transaction input objects: BFCObjectNotFound { object_id: "BFC000000000000000000000000000000000000000000000000000000000000000060e0", version: None }

task 9 'publish'. lines 53-58:
Error: Error checking transaction input objects: BFCObjectNotFound { object_id: "BFC000000000000000000000000000000000000000000000000000000000000000060e0", version: None }

task 10 'run'. lines 60-60:
Error: Error checking transaction input objects: BFCObjectNotFound { object_id: "BFC000000000000000000000000000000000000000000000000000000000000000060e0", version: None }
