processed 11 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-18:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 233700,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'publish'. lines 20-23:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 269800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'publish'. lines 25-28:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 188100,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 5 'programmable'. lines 36-41:
Error: Transaction Effects Status: Invalid package upgrade. Digest in upgrade ticket and computed digest disagree
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: PackageUpgradeError { upgrade_error: DigestDoesNotMatch { digest: [129, 120, 43, 41, 44, 76, 207, 34, 162, 14, 160, 157, 252, 110, 45, 26, 71, 231, 129, 203, 85, 90, 185, 252, 99, 77, 29, 78, 220, 27, 149, 83] } }, source: None, command: Some(2) } }

task 6 'programmable'. lines 43-45:
Error: Transaction Effects Status: Move Runtime Abort. Location: p::n::bar (function index 0) at offset 6, Abort Code: 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: p, name: Identifier("n") }, function: 0, instruction: 6, function_name: Some("bar") }, 0), source: Some(VMError { major_status: ABORTED, sub_status: Some(0), message: Some("p::n::bar at offset 6"), exec_state: None, location: Module(ModuleId { address: p, name: Identifier("n") }), indices: [], offsets: [(FunctionDefinitionIndex(0), 6)] }), command: Some(1) } }

task 7 'set-address'. lines 47-47:
Error: INVALID TEST. Unknown object, object(5,0)

task 8 'programmable'. lines 49-51:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 9 'publish'. lines 53-58:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }

task 10 'run'. lines 60-60:
Error: Error checking transaction input objects: DependentPackageNotFound { package_id: 0x0000000000000000000000000000000000000000000000000000000000000000 }
