processed 5 tasks

task 0 'publish'. lines 6-13:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 42788,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1 'publish'. lines 15-22:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 42864,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 2 'publish'. lines 24-31:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 42864,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 3 'publish'. lines 33-41:
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 48260,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 4 'publish'. lines 43-51:
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 48412,  storage_rebate: 12941, non_refundable_storage_fee: 131
