processed 5 tasks

task 0, lines 6-13:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4278800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1, lines 15-22:
//# publish
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4286400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 2, lines 24-31:
//# publish
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4286400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 33-41:
//# publish
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4826000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, lines 43-51:
//# publish
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4841200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072
