---
version: "3.9"
services:
  fullnode:
    image: xxx/bfc-dev:1.1.2
    ports:
    - "8084:8084/udp"
    - "9000:9000"
    - "9184:9184"
    volumes:
    - ./fullnode.yaml:/bfc/fullnode.yaml:ro
    - ./genesis.blob:/bfc/genesis.blob:ro
    - suidb:/sui/suidb:rw
    command: ["/usr/local/bin/bfc-node", "--config-path", "/bfc/fullnode.yaml"]
volumes:
  suidb:
