processed 26 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 15-28:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5494800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 30:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 32:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 34:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 36-64:
//# run-graphql --cursors @{obj_2_0} @{obj_3_0}
Response: {
  "data": {
    "one_of_these_will_yield_an_object": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0xbc7f04c6b9c1ed1c8b9d1bbc318b6e0b2af28b5cbf9a4f9dfb60eddcbaa6d4aa",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "if_the_other_does_not": {
      "nodes": []
    }
  }
}

task 6, line 66:
//# run Test::M1::create --args 2 @A
created: object(6,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 7, line 68:
//# run Test::M1::create --args 3 @A
created: object(7,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 8, line 70:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 72-100:
//# run-graphql --cursors @{obj_2_0,1} @{obj_3_0,1}
Response: {
  "data": {
    "paginating_on_checkpoint_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0xbc7f04c6b9c1ed1c8b9d1bbc318b6e0b2af28b5cbf9a4f9dfb60eddcbaa6d4aa",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "should_not_have_more_than_one_result": {
      "nodes": []
    }
  }
}

task 10, lines 102-117:
//# run-graphql
Response: {
  "data": {
    "four_objects": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x05e32ebb5bd47ef6c6b8087e7c3da99d689d7bc79e7add8c1eae0caa113a176b",
                "value": "0"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x43e56caee80d9a4bbeb24b6480e2239f0d4add92d43fd6e0f4475939e653bbb4",
                "value": "2"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x5390fa44e410f510c367bf2ef7c6ee2d4fb00a09e125eeb233da8ac4d78247fa",
                "value": "3"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0xbc7f04c6b9c1ed1c8b9d1bbc318b6e0b2af28b5cbf9a4f9dfb60eddcbaa6d4aa",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 11, lines 119-144:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x05e32ebb5bd47ef6c6b8087e7c3da99d689d7bc79e7add8c1eae0caa113a176b",
                "value": "0"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x43e56caee80d9a4bbeb24b6480e2239f0d4add92d43fd6e0f4475939e653bbb4",
                "value": "2"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x5390fa44e410f510c367bf2ef7c6ee2d4fb00a09e125eeb233da8ac4d78247fa",
                "value": "3"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0xbc7f04c6b9c1ed1c8b9d1bbc318b6e0b2af28b5cbf9a4f9dfb60eddcbaa6d4aa",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 12, lines 146-147:
//# programmable --sender A --inputs object(2,0) object(3,0) object(6,0) object(7,0) @B
//> TransferObjects([Input(0), Input(1), Input(2), Input(3)], Input(4))
mutated: object(0,0), object(2,0), object(3,0), object(6,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 6566400,  storage_rebate: 5206608, non_refundable_storage_fee: 52592

task 13, line 149:
//# create-checkpoint
Checkpoint created: 3

task 14, lines 151-213:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": {
    "after_obj_6_0_at_checkpoint_2": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x5390fa44e410f510c367bf2ef7c6ee2d4fb00a09e125eeb233da8ac4d78247fa",
                "value": "3"
              }
            },
            "owner_at_latest_state_has_sui_only": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0x05e32ebb5bd47ef6c6b8087e7c3da99d689d7bc79e7add8c1eae0caa113a176b",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0x43e56caee80d9a4bbeb24b6480e2239f0d4add92d43fd6e0f4475939e653bbb4",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0x5390fa44e410f510c367bf2ef7c6ee2d4fb00a09e125eeb233da8ac4d78247fa",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0xbc7f04c6b9c1ed1c8b9d1bbc318b6e0b2af28b5cbf9a4f9dfb60eddcbaa6d4aa",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "json": {
                          "id": "0xc4d025e3b61772ee54b5c0def62920911ec3b1145de5d76d12c260ff9b6c20ad",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0xbc7f04c6b9c1ed1c8b9d1bbc318b6e0b2af28b5cbf9a4f9dfb60eddcbaa6d4aa",
                "value": "1"
              }
            },
            "owner_at_latest_state_has_sui_only": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0x05e32ebb5bd47ef6c6b8087e7c3da99d689d7bc79e7add8c1eae0caa113a176b",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0x43e56caee80d9a4bbeb24b6480e2239f0d4add92d43fd6e0f4475939e653bbb4",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0x5390fa44e410f510c367bf2ef7c6ee2d4fb00a09e125eeb233da8ac4d78247fa",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0xbc7f04c6b9c1ed1c8b9d1bbc318b6e0b2af28b5cbf9a4f9dfb60eddcbaa6d4aa",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "json": {
                          "id": "0xc4d025e3b61772ee54b5c0def62920911ec3b1145de5d76d12c260ff9b6c20ad",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_6_0_at_checkpoint_2": {
      "nodes": [
        {
          "version": 3,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x05e32ebb5bd47ef6c6b8087e7c3da99d689d7bc79e7add8c1eae0caa113a176b",
                "value": "0"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0x05e32ebb5bd47ef6c6b8087e7c3da99d689d7bc79e7add8c1eae0caa113a176b",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0x43e56caee80d9a4bbeb24b6480e2239f0d4add92d43fd6e0f4475939e653bbb4",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0x5390fa44e410f510c367bf2ef7c6ee2d4fb00a09e125eeb233da8ac4d78247fa",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
                        },
                        "json": {
                          "id": "0xbc7f04c6b9c1ed1c8b9d1bbc318b6e0b2af28b5cbf9a4f9dfb60eddcbaa6d4aa",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "json": {
                          "id": "0xc4d025e3b61772ee54b5c0def62920911ec3b1145de5d76d12c260ff9b6c20ad",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      ]
    }
  }
}

task 16, line 217:
//# create-checkpoint
Checkpoint created: 4

task 18, line 221:
//# create-checkpoint
Checkpoint created: 5

task 20, line 225:
//# create-checkpoint
Checkpoint created: 6

task 22, line 229:
//# create-checkpoint
Checkpoint created: 7

task 23, lines 231-255:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 11,
          "column": 3
        }
      ],
      "path": [
        "before_obj_6_0_at_checkpoint_2"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 24, lines 257-273:
//# run-graphql
Response: {
  "data": {
    "owned_by_address_b_latest": {
      "objects": {
        "nodes": [
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x05e32ebb5bd47ef6c6b8087e7c3da99d689d7bc79e7add8c1eae0caa113a176b",
                "value": "0"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x43e56caee80d9a4bbeb24b6480e2239f0d4add92d43fd6e0f4475939e653bbb4",
                "value": "2"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x5390fa44e410f510c367bf2ef7c6ee2d4fb00a09e125eeb233da8ac4d78247fa",
                "value": "3"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0xbc7f04c6b9c1ed1c8b9d1bbc318b6e0b2af28b5cbf9a4f9dfb60eddcbaa6d4aa",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 25, lines 275-301:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x05e32ebb5bd47ef6c6b8087e7c3da99d689d7bc79e7add8c1eae0caa113a176b",
                "value": "0"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x43e56caee80d9a4bbeb24b6480e2239f0d4add92d43fd6e0f4475939e653bbb4",
                "value": "2"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0x5390fa44e410f510c367bf2ef7c6ee2d4fb00a09e125eeb233da8ac4d78247fa",
                "value": "3"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xd4c8f3a1ffcc361925bc6921a5637399220d31761d06b611ad5cc933a5fec690::M1::Object"
              },
              "json": {
                "id": "0xbc7f04c6b9c1ed1c8b9d1bbc318b6e0b2af28b5cbf9a4f9dfb60eddcbaa6d4aa",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}
