processed 26 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 15-28:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5494800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 30:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 32:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 34:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 36-64:
//# run-graphql --cursors @{obj_2_0} @{obj_3_0}
Response: {
  "data": {
    "one_of_these_will_yield_an_object": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0xf9715cc028a4b1790267310d6de13fbece6f2d67a56c8e7dee3405160766e6b1",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "if_the_other_does_not": {
      "nodes": []
    }
  }
}

task 6, line 66:
//# run Test::M1::create --args 2 @A
created: object(6,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 7, line 68:
//# run Test::M1::create --args 3 @A
created: object(7,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 8, line 70:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 72-100:
//# run-graphql --cursors @{obj_2_0,1} @{obj_3_0,1}
Response: {
  "data": {
    "paginating_on_checkpoint_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0xf9715cc028a4b1790267310d6de13fbece6f2d67a56c8e7dee3405160766e6b1",
                "value": "1"
              }
            }
          }
        ]
      }
    },
    "should_not_have_more_than_one_result": {
      "nodes": []
    }
  }
}

task 10, lines 102-117:
//# run-graphql
Response: {
  "data": {
    "four_objects": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0x0622a6975ff358cd8a0b4679cc4da0f266c6515c602097a38635192164940e1f",
                "value": "0"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0x0f736b74fafc0d024612bad8dc200efa549a5f3d680fb317f86490054e24d7f6",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0xb528ceca76c07dd2f441ee8126a1d778e52343375abfef07957f98a2119409ac",
                "value": "2"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0xf9715cc028a4b1790267310d6de13fbece6f2d67a56c8e7dee3405160766e6b1",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 11, lines 119-144:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0x0622a6975ff358cd8a0b4679cc4da0f266c6515c602097a38635192164940e1f",
                "value": "0"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0x0f736b74fafc0d024612bad8dc200efa549a5f3d680fb317f86490054e24d7f6",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0xb528ceca76c07dd2f441ee8126a1d778e52343375abfef07957f98a2119409ac",
                "value": "2"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0xf9715cc028a4b1790267310d6de13fbece6f2d67a56c8e7dee3405160766e6b1",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 12, lines 146-147:
//# programmable --sender A --inputs object(2,0) object(3,0) object(6,0) object(7,0) @B
//> TransferObjects([Input(0), Input(1), Input(2), Input(3)], Input(4))
mutated: object(0,0), object(2,0), object(3,0), object(6,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 6566400,  storage_rebate: 5206608, non_refundable_storage_fee: 52592

task 13, line 149:
//# create-checkpoint
Checkpoint created: 3

task 14, lines 151-213:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": {
    "after_obj_6_0_at_checkpoint_2": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0xf9715cc028a4b1790267310d6de13fbece6f2d67a56c8e7dee3405160766e6b1",
                "value": "1"
              }
            },
            "owner_at_latest_state_has_sui_only": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0x0622a6975ff358cd8a0b4679cc4da0f266c6515c602097a38635192164940e1f",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "json": {
                          "id": "0x0d9ef729c7068a42a0dd64b37174f1030aca181b4fdea3d477008c23e8ea1ea7",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0x0f736b74fafc0d024612bad8dc200efa549a5f3d680fb317f86490054e24d7f6",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0xb528ceca76c07dd2f441ee8126a1d778e52343375abfef07957f98a2119409ac",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0xf9715cc028a4b1790267310d6de13fbece6f2d67a56c8e7dee3405160766e6b1",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_6_0_at_checkpoint_2": {
      "nodes": [
        {
          "version": 3,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0x0622a6975ff358cd8a0b4679cc4da0f266c6515c602097a38635192164940e1f",
                "value": "0"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0x0622a6975ff358cd8a0b4679cc4da0f266c6515c602097a38635192164940e1f",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "json": {
                          "id": "0x0d9ef729c7068a42a0dd64b37174f1030aca181b4fdea3d477008c23e8ea1ea7",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0x0f736b74fafc0d024612bad8dc200efa549a5f3d680fb317f86490054e24d7f6",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0xb528ceca76c07dd2f441ee8126a1d778e52343375abfef07957f98a2119409ac",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0xf9715cc028a4b1790267310d6de13fbece6f2d67a56c8e7dee3405160766e6b1",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        {
          "version": 6,
          "asMoveObject": {
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0x0f736b74fafc0d024612bad8dc200efa549a5f3d680fb317f86490054e24d7f6",
                "value": "3"
              }
            },
            "note_that_owner_result_should_reflect_latest_state": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 3,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0x0622a6975ff358cd8a0b4679cc4da0f266c6515c602097a38635192164940e1f",
                          "value": "0"
                        }
                      }
                    },
                    {
                      "version": 1,
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                        },
                        "json": {
                          "id": "0x0d9ef729c7068a42a0dd64b37174f1030aca181b4fdea3d477008c23e8ea1ea7",
                          "balance": {
                            "value": "300000000000000"
                          }
                        }
                      }
                    },
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0x0f736b74fafc0d024612bad8dc200efa549a5f3d680fb317f86490054e24d7f6",
                          "value": "3"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0xb528ceca76c07dd2f441ee8126a1d778e52343375abfef07957f98a2119409ac",
                          "value": "2"
                        }
                      }
                    },
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
                        },
                        "json": {
                          "id": "0xf9715cc028a4b1790267310d6de13fbece6f2d67a56c8e7dee3405160766e6b1",
                          "value": "1"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      ]
    }
  }
}

task 16, line 217:
//# create-checkpoint
Checkpoint created: 4

task 18, line 221:
//# create-checkpoint
Checkpoint created: 5

task 20, line 225:
//# create-checkpoint
Checkpoint created: 6

task 22, line 229:
//# create-checkpoint
Checkpoint created: 7

task 23, lines 231-255:
//# run-graphql --cursors @{obj_6_0,2}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 11,
          "column": 3
        }
      ],
      "path": [
        "before_obj_6_0_at_checkpoint_2"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 24, lines 257-273:
//# run-graphql
Response: {
  "data": {
    "owned_by_address_b_latest": {
      "objects": {
        "nodes": [
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0x0622a6975ff358cd8a0b4679cc4da0f266c6515c602097a38635192164940e1f",
                "value": "0"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0x0f736b74fafc0d024612bad8dc200efa549a5f3d680fb317f86490054e24d7f6",
                "value": "3"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0xb528ceca76c07dd2f441ee8126a1d778e52343375abfef07957f98a2119409ac",
                "value": "2"
              }
            }
          },
          {
            "version": 7,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0xf9715cc028a4b1790267310d6de13fbece6f2d67a56c8e7dee3405160766e6b1",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}

task 25, lines 275-301:
//# run-graphql
Response: {
  "data": {
    "objects_at_version": {
      "objects": {
        "nodes": [
          {
            "version": 3,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0x0622a6975ff358cd8a0b4679cc4da0f266c6515c602097a38635192164940e1f",
                "value": "0"
              }
            }
          },
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0x0f736b74fafc0d024612bad8dc200efa549a5f3d680fb317f86490054e24d7f6",
                "value": "3"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0xb528ceca76c07dd2f441ee8126a1d778e52343375abfef07957f98a2119409ac",
                "value": "2"
              }
            }
          },
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0xb52ededdcd70a94f54a3f7342b8eb16669a2b26f2579bbba00562d8aab3a95bb::M1::Object"
              },
              "json": {
                "id": "0xf9715cc028a4b1790267310d6de13fbece6f2d67a56c8e7dee3405160766e6b1",
                "value": "1"
              }
            }
          }
        ]
      }
    }
  }
}
