processed 15 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 10-27:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5776000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 29:
//# run Test::M1::create --args 0 @A
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 31:
//# run Test::M1::create --args 1 @A
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 33:
//# run Test::M1::update --sender A --args 100 object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1301652, non_refundable_storage_fee: 13148

task 5, line 35:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 37-65:
//# run-graphql --cursors @{obj_3_0}
Response: {
  "data": {
    "after_obj_3_0": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
              },
              "json": {
                "id": "0x482730bb4de43f0e5e489d8c7cd34ffdf1557925023e9372991107dfa26ccbb8",
                "value": "100"
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 7, line 67:
//# run Test::M1::update --sender A --args 200 object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 8, line 69:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 71-100:
//# run-graphql --cursors @{obj_3_0,1}
Response: {
  "data": {
    "after_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
              },
              "json": {
                "id": "0x482730bb4de43f0e5e489d8c7cd34ffdf1557925023e9372991107dfa26ccbb8",
                "value": "100"
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_1": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 10, lines 102-177:
//# run-graphql --cursors @{obj_3_0,2}
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 4,
            "contents": {
              "type": {
                "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
              },
              "json": {
                "id": "0x364ebf31abbfb3eb138baa7fd29281c9a85b43059c9b0581108d632a10f0fac1",
                "value": "1"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
              },
              "json": {
                "id": "0x482730bb4de43f0e5e489d8c7cd34ffdf1557925023e9372991107dfa26ccbb8",
                "value": "200"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
              },
              "json": {
                "id": "0x482730bb4de43f0e5e489d8c7cd34ffdf1557925023e9372991107dfa26ccbb8",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
                        },
                        "json": {
                          "id": "0x364ebf31abbfb3eb138baa7fd29281c9a85b43059c9b0581108d632a10f0fac1",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
                        },
                        "json": {
                          "id": "0x482730bb4de43f0e5e489d8c7cd34ffdf1557925023e9372991107dfa26ccbb8",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_2": {
      "consistent_with_above": {
        "nodes": []
      }
    }
  }
}

task 11, line 179:
//# run Test::M1::update --sender A --args 300 object(3,0)
mutated: object(0,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 12, line 181:
//# create-checkpoint
Checkpoint created: 3

task 13, lines 183-246:
//# run-graphql --cursors @{obj_3_0,2}
Response: {
  "data": {
    "after_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
              },
              "json": {
                "id": "0x482730bb4de43f0e5e489d8c7cd34ffdf1557925023e9372991107dfa26ccbb8",
                "value": "200"
              }
            },
            "this_should_differ": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 4,
                      "contents": {
                        "type": {
                          "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
                        },
                        "json": {
                          "id": "0x364ebf31abbfb3eb138baa7fd29281c9a85b43059c9b0581108d632a10f0fac1",
                          "value": "1"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
                        },
                        "json": {
                          "id": "0x482730bb4de43f0e5e489d8c7cd34ffdf1557925023e9372991107dfa26ccbb8",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_2": {
      "objects": {
        "nodes": []
      }
    }
  }
}

task 14, lines 248-323:
//# run-graphql --cursors @{obj_3_0,3}
Response: {
  "data": {
    "address": {
      "objects": {
        "nodes": [
          {
            "version": 6,
            "contents": {
              "type": {
                "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
              },
              "json": {
                "id": "0x364ebf31abbfb3eb138baa7fd29281c9a85b43059c9b0581108d632a10f0fac1",
                "value": "300"
              }
            }
          },
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
              },
              "json": {
                "id": "0x482730bb4de43f0e5e489d8c7cd34ffdf1557925023e9372991107dfa26ccbb8",
                "value": "200"
              }
            }
          }
        ]
      }
    },
    "after_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": [
          {
            "version": 5,
            "contents": {
              "type": {
                "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
              },
              "json": {
                "id": "0x482730bb4de43f0e5e489d8c7cd34ffdf1557925023e9372991107dfa26ccbb8",
                "value": "200"
              }
            },
            "owner": {
              "owner": {
                "objects": {
                  "nodes": [
                    {
                      "version": 6,
                      "contents": {
                        "type": {
                          "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
                        },
                        "json": {
                          "id": "0x364ebf31abbfb3eb138baa7fd29281c9a85b43059c9b0581108d632a10f0fac1",
                          "value": "300"
                        }
                      }
                    },
                    {
                      "version": 5,
                      "contents": {
                        "type": {
                          "repr": "0x0acfcaa838d28ffa10d38923da8a60da296cb484a2532052ebfc87e88f0f487e::M1::Object"
                        },
                        "json": {
                          "id": "0x482730bb4de43f0e5e489d8c7cd34ffdf1557925023e9372991107dfa26ccbb8",
                          "value": "200"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "before_obj_3_0_chkpt_3": {
      "consistent_with_above": {
        "nodes": []
      }
    }
  }
}
