processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 17-34:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5798800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 36-37:
//# programmable --sender A --inputs 0 1 @A
//> 0: Test::M1::create(Input(0), Input(2));
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 39:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 41-44:
//# programmable --sender A --inputs object(2,0) 100 2 3 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(4));
//> Test::M1::create(Input(3), Input(4));
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5251600,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5, line 46:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 48-52:
//# programmable --sender A --inputs object(2,0) 200 4 5 6 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(5));
//> Test::M1::create(Input(3), Input(5));
//> Test::M1::create(Input(4), Input(5));
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6566400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 7, line 54:
//# create-checkpoint
Checkpoint created: 3

task 9, line 58:
//# create-checkpoint
Checkpoint created: 4

task 10, lines 60-134:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                "value": "200"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                "value": "6"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                "value": "2"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                "value": "5"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                "value": "3"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                "value": "4"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0xc4d025e3b61772ee54b5c0def62920911ec3b1145de5d76d12c260ff9b6c20ad",
                        "balance": {
                          "value": "299999992722180"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11, lines 136-180:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0xc4d025e3b61772ee54b5c0def62920911ec3b1145de5d76d12c260ff9b6c20ad",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0xc4d025e3b61772ee54b5c0def62920911ec3b1145de5d76d12c260ff9b6c20ad",
                        "balance": {
                          "value": "299999996378000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0xc4d025e3b61772ee54b5c0def62920911ec3b1145de5d76d12c260ff9b6c20ad",
                        "balance": {
                          "value": "299999992722180"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12, line 182:
//# create-checkpoint
Checkpoint created: 5

task 13, lines 184-258:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                "value": "200"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                "value": "6"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                "value": "2"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                "value": "5"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                "value": "3"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                "value": "4"
              },
              "type": {
                "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0xc4d025e3b61772ee54b5c0def62920911ec3b1145de5d76d12c260ff9b6c20ad",
                        "balance": {
                          "value": "299999992722180"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 14, line 260:
//# create-checkpoint
Checkpoint created: 6

task 15, lines 262-295:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x033787b9ad6ead129d501a261ff4586046b58ed3c759ebd5f4468c154547156b",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x0c95ec02ddb57bd84dbf821c6852fc0192d2bd2104636a2e93b2c046016abcde",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x15ae4452822de9493ef4c64490c9d9a73df380b30b412c39092749fc18e3c394",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8c61dca68376f763a3ba3e624b417fe87a786fe2c2c8a24e11de5ed4373dca33",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xaa165560c5a37da503553fb64a618e7318fbc795e096382bdc78bcad04053ac3",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xb1fa3161cd0c5337437178ea96e106f0f93dbb214eefda00cd6de6ab9e18031b",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0xcfa66613860d889c5ae45e50b22b98b530bfac46232ab8ce9eb18089253dbecf::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
