processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 17-34:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5798800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 36-37:
//# programmable --sender A --inputs 0 1 @A
//> 0: Test::M1::create(Input(0), Input(2));
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 39:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 41-44:
//# programmable --sender A --inputs object(2,0) 100 2 3 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(4));
//> Test::M1::create(Input(3), Input(4));
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5251600,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5, line 46:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 48-52:
//# programmable --sender A --inputs object(2,0) 200 4 5 6 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(5));
//> Test::M1::create(Input(3), Input(5));
//> Test::M1::create(Input(4), Input(5));
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6566400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 7, line 54:
//# create-checkpoint
Checkpoint created: 3

task 9, line 58:
//# create-checkpoint
Checkpoint created: 4

task 10, lines 60-134:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                "value": "6"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                "value": "5"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                "value": "200"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                "value": "4"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                "value": "2"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                "value": "3"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0x0d9ef729c7068a42a0dd64b37174f1030aca181b4fdea3d477008c23e8ea1ea7",
                        "balance": {
                          "value": "299999992722180"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11, lines 136-180:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0x0d9ef729c7068a42a0dd64b37174f1030aca181b4fdea3d477008c23e8ea1ea7",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0x0d9ef729c7068a42a0dd64b37174f1030aca181b4fdea3d477008c23e8ea1ea7",
                        "balance": {
                          "value": "299999996378000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0x0d9ef729c7068a42a0dd64b37174f1030aca181b4fdea3d477008c23e8ea1ea7",
                        "balance": {
                          "value": "299999992722180"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12, line 182:
//# create-checkpoint
Checkpoint created: 5

task 13, lines 184-258:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                "value": "6"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                "value": "5"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                "value": "200"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                "value": "4"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                "value": "2"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                "value": "3"
              },
              "type": {
                "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0x0d9ef729c7068a42a0dd64b37174f1030aca181b4fdea3d477008c23e8ea1ea7",
                        "balance": {
                          "value": "299999992722180"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 14, line 260:
//# create-checkpoint
Checkpoint created: 6

task 15, lines 262-295:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x09eb7f13ba8474b37b92953feff66a1101b104c9feeb3394fae87cd07efbbcab",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x5f8adb60a0a9066f259e6a3c0ccdb8f7754c70331c792fa3fd4ab563d348082c",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x81e0ded4622dff939bb2b13a18a2039cde5ee3e6f2744507ce558e0925801578",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x85a0dcd0cd62bb6e1717b58c01ea17533dcc416f3abcb3b0e19ded6974d3824e",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x91dab29527339893543a0b4385610b85c1c79946167180e048c394724ef31c2b",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc2e61e371b90e74427920979e83bd3450f8480f937668426cf607a57180d9671",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x6855d722726a7b36fb7c3d19477be6b227ea7cd6c3283ac2ab9309b96ad5c64f::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
