processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 17-34:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5798800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 36-37:
//# programmable --sender A --inputs 0 1 @A
//> 0: Test::M1::create(Input(0), Input(2));
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 39:
//# create-checkpoint
Checkpoint created: 1

task 4, lines 41-44:
//# programmable --sender A --inputs object(2,0) 100 2 3 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(4));
//> Test::M1::create(Input(3), Input(4));
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 5251600,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5, line 46:
//# create-checkpoint
Checkpoint created: 2

task 6, lines 48-52:
//# programmable --sender A --inputs object(2,0) 200 4 5 6 @A
//> Test::M1::set_value(Input(0), Input(1));
//> Test::M1::create(Input(2), Input(5));
//> Test::M1::create(Input(3), Input(5));
//> Test::M1::create(Input(4), Input(5));
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6566400,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 7, line 54:
//# create-checkpoint
Checkpoint created: 3

task 9, line 58:
//# create-checkpoint
Checkpoint created: 4

task 10, lines 60-134:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                "value": "5"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                "value": "6"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                "value": "200"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                "value": "3"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                "value": "2"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                "value": "4"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0xff5ec56af80270da66abcaf4556184f6543232a9e9cd9f28acb35ac2f18cf74e",
                        "balance": {
                          "value": "299999992722180"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11, lines 136-180:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0xff5ec56af80270da66abcaf4556184f6543232a9e9cd9f28acb35ac2f18cf74e",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0xff5ec56af80270da66abcaf4556184f6543232a9e9cd9f28acb35ac2f18cf74e",
                        "balance": {
                          "value": "299999996378000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0xff5ec56af80270da66abcaf4556184f6543232a9e9cd9f28acb35ac2f18cf74e",
                        "balance": {
                          "value": "299999992722180"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12, line 182:
//# create-checkpoint
Checkpoint created: 5

task 13, lines 184-258:
//# run-graphql
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                "value": "5"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                "value": "6"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                "value": "200"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                "value": "3"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                "value": "2"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                "value": "4"
              },
              "type": {
                "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                      },
                      "json": {
                        "id": "0xff5ec56af80270da66abcaf4556184f6543232a9e9cd9f28acb35ac2f18cf74e",
                        "balance": {
                          "value": "299999992722180"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 14, line 260:
//# create-checkpoint
Checkpoint created: 6

task 15, lines 262-295:
//# run-graphql
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1a9a918e4a5d5f23869c78c2d2b8d19030cd20799dedaf7653981cdae1c02c8e",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x58fc7dca905ac5040244c43133a396abb3e3348c2cf70a938877544deaf961cd",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6589145b2e96526c005529c5116d21ac8ff7d9379deaf43e25769a04a1fc529d",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x6bf0e770d3aed52978ff08889fa4b3ad8721394875644b6ff7d8fadd3bdfc140",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xc6bd03cf19ac14b33f3a07e991546999b3e375f9e2a31128b68242954d568dfa",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0xf9de0a28674b209e5ac33bd7e13142ca1cbfa6855ade9edad5bc851a5952976f",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x9f10afdb6fdde363c20b5b3650689907da5f5ff0448af63f7e9d7cb1f4aa5a7b::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
