processed 14 tasks

init:
P1: object(0,0), P2: object(0,1)

task 1 'publish'. lines 8-53:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 387600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 55-57:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 125780,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'programmable'. lines 59-60:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 125780,  storage_rebate: 124522, non_refundable_storage_fee: 1258

task 4 'programmable'. lines 62-63:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 125780,  storage_rebate: 124522, non_refundable_storage_fee: 1258

task 5 'view-object'. lines 65-68:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: test::m::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 6 'programmable'. lines 70-72:
created: object(6,0), object(6,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 199120,  storage_rebate: 0, non_refundable_storage_fee: 0

task 7 'view-object'. lines 74-74:
Owner: Object ID: ( BFC9a8cc422ec707269846fc523e86ddf10ce99b298f5c286c5b68671166e593c5b4a4a )
Version: 2
Contents: sui::dynamic_field::Field<u64, u64> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(6,0),
        },
    },
    name: 0u64,
    value: 0u64,
}

task 8 'programmable'. lines 76-77:
mutated: object(0,1), object(6,0), object(6,1)
gas summary: computation_cost: 1000000, storage_cost: 199120,  storage_rebate: 197129, non_refundable_storage_fee: 1991

task 9 'view-object'. lines 79-83:
Owner: Object ID: ( BFC9a8cc422ec707269846fc523e86ddf10ce99b298f5c286c5b68671166e593c5b4a4a )
Version: 3
Contents: sui::dynamic_field::Field<u64, u64> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(6,0),
        },
    },
    name: 0u64,
    value: 1u64,
}

task 10 'programmable'. lines 85-90:
created: object(10,0)
mutated: object(_), object(2,0)
wrapped: object(6,1)
gas summary: computation_cost: 500000, storage_cost: 222300,  storage_rebate: 119632, non_refundable_storage_fee: 1208

task 11 'programmable'. lines 92-96:
created: object(10,0)
mutated: object(_), object(2,0)
wrapped: object(6,1)
gas summary: computation_cost: 500000, storage_cost: 222300,  storage_rebate: 119632, non_refundable_storage_fee: 1208

task 12 'programmable'. lines 98-102:
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 4, instruction: 13, function_name: Some("check") }, 0) in command 1
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 4, instruction: 13, function_name: Some("check") }, 0) in command 1

task 13 'programmable'. lines 104-106:
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 4, instruction: 13, function_name: Some("check") }, 0) in command 1
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 4, instruction: 13, function_name: Some("check") }, 0) in command 1
