processed 14 tasks

init:
A: object(0,0)

task 1, lines 6-76:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 12844000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 78:
//# run tto::M1::start --sender A
created: object(2,0), object(2,1), object(2,2), object(2,3), object(2,4), object(2,5), object(2,6), object(2,7)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15618000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 80:
//# view-object 2,0
Owner: Object ID: ( BFCa2ee8737ad71a70658c81fd36b9ed66db0137eb0423af035d0582412f68412d783d4 )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 1u64,
    },
    value: sui::object::ID {
        bytes: fake(2,4),
    },
}

task 4, line 82:
//# view-object 2,1
Owner: Object ID: ( BFCa2ee8737ad71a70658c81fd36b9ed66db0137eb0423af035d0582412f68412d783d4 )
Version: 2
Contents: sui::dynamic_field::Field<u64, tto::M1::A> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    name: 0u64,
    value: tto::M1::A {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: _,
            },
        },
        value: vector[
            98u8,
            95u8,
            99u8,
            104u8,
            105u8,
            108u8,
            100u8,
            95u8,
            99u8,
            104u8,
            105u8,
            108u8,
            100u8,
        ],
    },
}

task 5, line 84:
//# view-object 2,2
Owner: Object ID: ( BFC01105f4ecd40a6ca37b5edd619b82ebe69170026cc33220346f8bfb68b1d67f84b6c )
Version: 2
Contents: sui::dynamic_field::Field<u64, tto::M1::A> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    name: 0u64,
    value: tto::M1::A {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: _,
            },
        },
        value: vector[
            119u8,
            114u8,
            97u8,
            112u8,
            112u8,
            101u8,
            100u8,
            95u8,
            100u8,
            111u8,
            102u8,
        ],
    },
}

task 6, line 86:
//# view-object 2,3
Owner: Object ID: ( BFC7e6e2b3e854d1aeff8db812b7d3d5d4feaeca70733bfd2ae46fbbb131d9bad4d1ca6 )
Version: 2
Contents: sui::dynamic_field::Field<u64, tto::M1::A> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
    name: 0u64,
    value: tto::M1::A {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: _,
            },
        },
        value: vector[
            98u8,
            95u8,
            99u8,
            104u8,
            105u8,
            108u8,
            100u8,
        ],
    },
}

task 7, line 88:
//# view-object 2,4
Owner: Object ID: ( BFCcb7bfc4288bb77648ddc6b1c642576589409f950de00cf14d5cec9cf4a4b9d78a2ba )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,4),
        },
    },
    value: vector[
        98u8,
        95u8,
        99u8,
        104u8,
        105u8,
        108u8,
        100u8,
        95u8,
        99u8,
        104u8,
        105u8,
        108u8,
        100u8,
        95u8,
        100u8,
        111u8,
        102u8,
    ],
}

task 8, line 90:
//# view-object 2,5
Owner: Account Address ( BFCf0072af81bc83cf2fee5e6224276e5f757398c4506255f9b67f3a3fe95c4c663e53c )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,5),
        },
    },
    value: vector[
        98u8,
        95u8,
        112u8,
        97u8,
        114u8,
        101u8,
        110u8,
        116u8,
    ],
}

task 9, line 92:
//# view-object 2,6
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,6),
        },
    },
    value: vector[
        97u8,
        95u8,
        112u8,
        97u8,
        114u8,
        101u8,
        110u8,
        116u8,
    ],
}

task 10, lines 94-97:
//# view-object 2,7
Owner: Account Address ( BFCf0072af81bc83cf2fee5e6224276e5f757398c4506255f9b67f3a3fe95c4c663e53c )
Version: 2
Contents: tto::M1::Wrapper<tto::M1::A> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,7),
        },
    },
    value: tto::M1::A {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: _,
            },
        },
        value: vector[
            119u8,
            114u8,
            97u8,
            112u8,
            112u8,
            101u8,
            100u8,
        ],
    },
}

task 11, line 98:
//# run tto::M1::receive_b_parent --args object(2,4) receiving(2,7) --sender A
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(2,4), parent_id: object(2,0) }

task 12, line 100:
//# run tto::M1::receive_b_parent --args object(2,4) receiving(2,6) --sender A
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(2,4), parent_id: object(2,0) }

task 13, line 102:
//# run tto::M1::receive_wrapped --args object(2,4) receiving(2,7) --sender A
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(2,4), parent_id: object(2,0) }
