processed 16 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-76:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 641440,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 78-78:
created: object(2,0), object(2,1), object(2,2), object(2,3), object(2,4), object(2,5), object(2,6), object(2,7), object(2,8), object(2,9)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 953420,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 80-80:
Owner: Object ID: ( BFCfb4a31f360771b141fbdb7d38555b5e4563f0391fd433707391a64ad4a69f27372cf )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,4),
    },
}

task 4 'view-object'. lines 82-82:
Owner: Object ID: ( BFCcb5dde231b05f2b7cf3d6e347f2c61e0865481e08838dd1d1e7ad6580d902cc084c2 )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,5),
    },
}

task 5 'view-object'. lines 84-84:
Owner: Object ID: ( BFCa0a0853a4174e28453578e32dbaf4c4ceccbfff3dabeab142eba725c05b47ec865cc )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,7),
    },
}

task 6 'view-object'. lines 86-86:
Owner: Object ID: ( BFCcb5dde231b05f2b7cf3d6e347f2c61e0865481e08838dd1d1e7ad6580d902cc084c2 )
Version: 2
Contents: sui::dynamic_field::Field<u64, tto::M1::A> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
    name: 1u64,
    value: tto::M1::A {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: _,
            },
        },
        value: vector[
            98u8,
            95u8,
            99u8,
            104u8,
            105u8,
            108u8,
            100u8,
            95u8,
            99u8,
            104u8,
            105u8,
            108u8,
            100u8,
            95u8,
            100u8,
            102u8,
        ],
    },
}

task 7 'view-object'. lines 88-88:
Owner: Object ID: ( BFC5569de555205559c49038baffd07f9df46609dbf3a2dd6abb47741ad1c22d34b30c1 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,4),
        },
    },
    value: vector[
        119u8,
        114u8,
        97u8,
        112u8,
        112u8,
        101u8,
        100u8,
        95u8,
        100u8,
        102u8,
    ],
}

task 8 'view-object'. lines 90-90:
Owner: Object ID: ( BFCa13ffe5a2b72a099e6fdfdc408eb59ef0ad9561015cdbbf19133b1de0e78cf8a9402 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,5),
        },
    },
    value: vector[
        98u8,
        95u8,
        99u8,
        104u8,
        105u8,
        108u8,
        100u8,
        95u8,
        99u8,
        104u8,
        105u8,
        108u8,
        100u8,
    ],
}

task 9 'view-object'. lines 92-92:
Owner: Account Address ( BFCd127958831daecbad1a531945b9b0d10935944e1b747361eabfb4523762c60ff6e14 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,6),
        },
    },
    value: vector[
        98u8,
        95u8,
        112u8,
        97u8,
        114u8,
        101u8,
        110u8,
        116u8,
    ],
}

task 10 'view-object'. lines 94-94:
Owner: Object ID: ( BFCba1238ff888cfe4bd12505d47a897c85d13c255c6fd681568f932e131c9af107fdab )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,7),
        },
    },
    value: vector[
        98u8,
        95u8,
        99u8,
        104u8,
        105u8,
        108u8,
        100u8,
    ],
}

task 11 'view-object'. lines 96-96:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,8),
        },
    },
    value: vector[
        97u8,
        95u8,
        112u8,
        97u8,
        114u8,
        101u8,
        110u8,
        116u8,
    ],
}

task 12 'view-object'. lines 98-101:
Owner: Account Address ( BFCd127958831daecbad1a531945b9b0d10935944e1b747361eabfb4523762c60ff6e14 )
Version: 2
Contents: tto::M1::Wrapper<tto::M1::A> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,9),
        },
    },
    value: tto::M1::A {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: _,
            },
        },
        value: vector[
            119u8,
            114u8,
            97u8,
            112u8,
            112u8,
            101u8,
            100u8,
        ],
    },
}

task 13 'run'. lines 102-102:
Error: Transaction Effects Status: Move Runtime Abort. Location: sui::transfer::receive_impl (function index 12) at offset 0, Abort Code: 2
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("transfer") }, function: 12, instruction: 0, function_name: Some("receive_impl") }, 2), source: Some(VMError { major_status: ABORTED, sub_status: Some(2), message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("transfer") }), indices: [], offsets: [(FunctionDefinitionIndex(12), 0)] }), command: Some(0) } }

task 14 'run'. lines 104-104:
created: object(14,0)
mutated: object(0,0), object(2,6), object(2,8)
gas summary: computation_cost: 1000000, storage_cost: 316540,  storage_rebate: 191862, non_refundable_storage_fee: 1938

task 15 'run'. lines 106-106:
created: object(15,0)
mutated: object(0,0), object(2,8), object(2,9)
gas summary: computation_cost: 1000000, storage_cost: 345420,  storage_rebate: 220453, non_refundable_storage_fee: 2227
