processed 24 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-58:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 10852800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 60-60:
created: object(2,0), object(2,1), object(2,2), object(2,3)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7592400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 62-62:
Owner: Object ID: ( BFC524d6d8bcc996f44069c96b178de951a7101e0a63864be37aef12fdbe0bfe41d1799 )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,3),
    },
}

task 4 'view-object'. lines 64-64:
Owner: Object ID: ( BFC9a860864495ee17c01896280573b1dd56c90fcbfc6db11b19dd442f91a0f83c3a4fc )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
    value: 0u64,
}

task 5 'view-object'. lines 66-66:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 6 'view-object'. lines 68-68:
Owner: Account Address ( BFC00ab340fb31f0174cba64ca258e9e2c162d822ec582f65ef6aac52b996b281299a01 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 0u64,
}

task 7 'run'. lines 70-70:
Error: Error checking transaction input objects: IncorrectUserSignature { error: "Object object(2,2) is owned by account address object(2,1), but given owner/signer address is @A" }

task 8 'view-object'. lines 72-74:
Owner: Object ID: ( BFC524d6d8bcc996f44069c96b178de951a7101e0a63864be37aef12fdbe0bfe41d1799 )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,3),
    },
}

task 9 'view-object'. lines 75-75:
Owner: Object ID: ( BFC9a860864495ee17c01896280573b1dd56c90fcbfc6db11b19dd442f91a0f83c3a4fc )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
    value: 0u64,
}

task 10 'view-object'. lines 77-77:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 11 'view-object'. lines 79-79:
Owner: Account Address ( BFC00ab340fb31f0174cba64ca258e9e2c162d822ec582f65ef6aac52b996b281299a01 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 0u64,
}

task 12 'programmable'. lines 81-82:
Error: Error checking transaction input objects: IncorrectUserSignature { error: "Object object(2,2) is owned by account address object(2,1), but given owner/signer address is @A" }

task 13 'view-object'. lines 84-86:
Owner: Object ID: ( BFC524d6d8bcc996f44069c96b178de951a7101e0a63864be37aef12fdbe0bfe41d1799 )
Version: 2
Contents: sui::dynamic_field::Field<sui::dynamic_object_field::Wrapper<u64>, sui::object::ID> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    name: sui::dynamic_object_field::Wrapper<u64> {
        name: 0u64,
    },
    value: sui::object::ID {
        bytes: fake(2,3),
    },
}

task 14 'view-object'. lines 87-87:
Owner: Object ID: ( BFC9a860864495ee17c01896280573b1dd56c90fcbfc6db11b19dd442f91a0f83c3a4fc )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,3),
        },
    },
    value: 0u64,
}

task 15 'view-object'. lines 89-89:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
    value: 0u64,
}

task 16 'view-object'. lines 91-91:
Owner: Account Address ( BFC00ab340fb31f0174cba64ca258e9e2c162d822ec582f65ef6aac52b996b281299a01 )
Version: 2
Contents: tto::M1::A {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 0u64,
}

task 17 'programmable'. lines 93-96:
Error: Error checking transaction input objects: IncorrectUserSignature { error: "Object object(2,2) is owned by account address object(2,1), but given owner/signer address is @A" }

task 18 'programmable'. lines 98-99:
Error: INVALID TEST. Could not load object argument object(2,2)

task 19 'programmable'. lines 101-102:
Error: INVALID TEST. Could not load object argument object(2,2)

task 20 'programmable'. lines 104-107:
Error: INVALID TEST. Could not load object argument object(2,2)

task 21 'programmable'. lines 109-110:
Error: INVALID TEST. Could not load object argument object(2,2)

task 22 'programmable'. lines 112-113:
Error: INVALID TEST. Could not load object argument object(2,2)

task 23 'programmable'. lines 115-116:
Error: INVALID TEST. Could not load object argument object(2,2)
