processed 4 tasks

task 1 'publish'. lines 6-25:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 589000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 27-27:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 262200,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 3 'view-object'. lines 29-29:
Owner: Account Address ( BFC0000000000000000000000000000000000000000000000000000000000000042e850 )
Version: 3
Contents: Test::M1::Object {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}
