processed 10 tasks

task 1 'publish'. lines 6-45:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 361000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 47-47:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 127300,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 3 'run'. lines 49-49:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 127300,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 4 'view-object'. lines 51-51:
Owner: Shared
Version: 3
Contents: t2::o2::Obj2 {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 5 'view-object'. lines 53-55:
Owner: Shared
Version: 4
Contents: t2::o2::Obj2 {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
}

task 6 'programmable'. lines 56-58:
mutated: object(0,0), object(2,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 127300,  storage_rebate: 187348, non_refundable_storage_fee: 1892

task 7 'run'. lines 60-60:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 130720,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 8 'view-object'. lines 62-64:
Owner: Shared
Version: 6
Contents: sui::coin::Coin<sui::bfc::BFC> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(7,0),
        },
    },
    balance: sui::balance::Balance<sui::bfc::BFC> {
        value: 0u64,
    },
}

task 9 'programmable'. lines 65-70:
created: object(9,0)
mutated: object(0,0), object(7,0)
gas summary: computation_cost: 1000000, storage_cost: 196080,  storage_rebate: 129413, non_refundable_storage_fee: 1307
