[package]
name = "sui-test-validator"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]

[[bin]]
name = "bfc-test-validator"
path = "src/main.rs"