processed 21 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 10-26:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5114800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 28:
//# run Test::M1::no_emit --sender A --args 0
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 30:
//# run Test::M1::emit_2 --sender A --args 2
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [2, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [3, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 32:
//# run Test::M1::emit_2 --sender B --args 4
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: B, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [4, 0, 0, 0, 0, 0, 0, 0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: B, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [] }, contents: [5, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 5, line 34:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 36-43:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "Hy3nTvuhYyqe3ZFyMVhXCubDKoA2qAVrBPPt1a8nkHUh"
        },
        {
          "digest": "AtwL6ekjRvate3PFw9Rn28nsmjfj3iS6wvNVqgSCL8PT"
        },
        {
          "digest": "3ek6GoyGMzT1vJT2bz12tgperU8rGz52aU5B5yviDZuv"
        },
        {
          "digest": "8L3oVGo6Phi1kV24Ay1SXEijrw9pJpB1Zw2puSxV2j5t"
        },
        {
          "digest": "F5yZ8AhDd5DWt8Mi5xYhvBRSgj9ieUTacHKEEiGkJV3x"
        }
      ]
    }
  }
}

task 7, lines 45-57:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 8, lines 59-72:
//# run-graphql --cursors {"tx":3,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 9, lines 74-89:
//# run-graphql --cursors {"tx":1,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 10, lines 92-104:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 11, lines 106-118:
//# run-graphql --cursors {"tx":4,"e":0,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 12, lines 121-133:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 13, lines 135-148:
//# run-graphql --cursors {"tx":3,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 14, lines 150-165:
//# run-graphql --cursors {"tx":4,"e":1,"c":1}
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 15, lines 168-180:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 16, lines 182-195:
//# run-graphql --cursors {"tx":4,"e":1,"c":1}
Response: {
  "data": null,
  "errors": [
    {
      "message": "Unknown field \"json\" on type \"Event\".",
      "locations": [
        {
          "line": 9,
          "column": 17
        }
      ]
    }
  ]
}

task 17, lines 197-210:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 18, lines 212-225:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 19, lines 227-240:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}

task 20, lines 242-255:
//# run-graphql
Response: {
  "data": {
    "events": {
      "edges": []
    }
  }
}
