processed 10 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 6-29:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 6315600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 32:
//# run Test::M1::emit_T1 --sender A
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [Struct(StructTag { address: Test, module: Identifier("M1"), name: Identifier("T1"), type_params: [] })] }, contents: [0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 34:
//# run Test::M1::emit_T2 --sender A
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [Struct(StructTag { address: Test, module: Identifier("M1"), name: Identifier("T2"), type_params: [] })] }, contents: [0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 36:
//# run Test::M1::emit_both --sender A
events: Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [Struct(StructTag { address: Test, module: Identifier("M1"), name: Identifier("T1"), type_params: [] })] }, contents: [0] }, Event { package_id: Test, transaction_module: Identifier("M1"), sender: A, type_: StructTag { address: Test, module: Identifier("M1"), name: Identifier("EventA"), type_params: [Struct(StructTag { address: Test, module: Identifier("M1"), name: Identifier("T2"), type_params: [] })] }, contents: [0] }
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5, line 38:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 40-47:
//# run-graphql
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "3xRjDhxs4asfUjuEsJQKH9EMgSgs9Vk1SFyM3y6vvaym"
        },
        {
          "digest": "4RQmU65joaJkKnqiomqYtjz8mBMXxRGweq9pM94cUYuP"
        },
        {
          "digest": "BwiWwJjbFBkVSpwS5vxHpv8zdivQejsSYziQCp2hHNud"
        },
        {
          "digest": "Gkqgj3QURrLLaNNpAXNWwUdF9jWjJQLioEi4H7D2UhTS"
        },
        {
          "digest": "AzzaphQeWzrpKfTohHRAMU5zwHm4RQCA9iHdUAUyB8Qd"
        }
      ]
    }
  }
}

task 7, lines 49-64:
//# run-graphql
Response: {
  "data": {
    "events": {
      "nodes": [
        {
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "contents": {
            "type": {
              "repr": "0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::EventA<0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::T1>"
            },
            "json": {
              "value": {
                "dummy_field": false
              }
            }
          }
        },
        {
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "contents": {
            "type": {
              "repr": "0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::EventA<0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::T2>"
            },
            "json": {
              "value": {
                "dummy_field": false
              }
            }
          }
        },
        {
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "contents": {
            "type": {
              "repr": "0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::EventA<0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::T1>"
            },
            "json": {
              "value": {
                "dummy_field": false
              }
            }
          }
        },
        {
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "contents": {
            "type": {
              "repr": "0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::EventA<0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::T2>"
            },
            "json": {
              "value": {
                "dummy_field": false
              }
            }
          }
        }
      ]
    }
  }
}

task 8, lines 66-81:
//# run-graphql
Response: {
  "data": {
    "events": {
      "nodes": [
        {
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "contents": {
            "type": {
              "repr": "0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::EventA<0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::T1>"
            },
            "json": {
              "value": {
                "dummy_field": false
              }
            }
          }
        },
        {
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "contents": {
            "type": {
              "repr": "0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::EventA<0x487b388b57455af20825fe6c61e4886971fcc9cca902be66ff6166afea82a1e5::M1::T1>"
            },
            "json": {
              "value": {
                "dummy_field": false
              }
            }
          }
        }
      ]
    }
  }
}

task 9, lines 83-98:
//# run-graphql
Response: {
  "data": {
    "events": {
      "nodes": []
    }
  }
}
