processed 6 tasks

task 1 'publish'. lines 8-32:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 46360,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 33-35:
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 13072,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 3 'run'. lines 36-38:
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 13072,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 4 'run'. lines 39-41:
Error: Transaction Effects Status: Insufficient Gas.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InsufficientGas, source: Some(VMError { major_status: OUT_OF_GAS, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: Test, name: Identifier("M1") }), indices: [], offsets: [(FunctionDefinitionIndex(0), 12)] }), command: Some(0) } }

task 5 'run'. lines 42-42:
Error: Transaction Effects Status: Insufficient Gas.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InsufficientGas, source: Some(VMError { major_status: OUT_OF_GAS, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: Test, name: Identifier("M1") }), indices: [], offsets: [(FunctionDefinitionIndex(0), 12)] }), command: Some(0) } }
