processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-32:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 824600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 34-36:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 261440,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 3 'run'. lines 38-38:
mutated: object(0,0), object(1,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 294880,  storage_rebate: 391248, non_refundable_storage_fee: 3952

task 4 'run'. lines 40-40:
mutated: object(0,0), object(1,0)
unwrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 395200,  storage_rebate: 291931, non_refundable_storage_fee: 2949
