processed 8 tasks

init:
A: object(0,0), B: object(0,1), C: object(0,2)

task 1 'programmable'. lines 8-10:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 130720,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 12-12:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 2
Contents: sui::coin::Coin<sui::bfc::BFC> {id: sui::object::UID {id: sui::object::ID {bytes: fake(1,0)}}, balance: sui::balance::Balance<sui::bfc::BFC> {value: 10u64}}

task 3 'run'. lines 14-14:
created: object(3,0)
mutated: object(0,1), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 196080,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 4 'view-object'. lines 16-16:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 3
Contents: sui::coin::Coin<sui::bfc::BFC> {id: sui::object::UID {id: sui::object::ID {bytes: fake(1,0)}}, balance: sui::balance::Balance<sui::bfc::BFC> {value: 0u64}}

task 5 'view-object'. lines 18-18:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: sui::coin::Coin<sui::bfc::BFC> {id: sui::object::UID {id: sui::object::ID {bytes: fake(3,0)}}, balance: sui::balance::Balance<sui::bfc::BFC> {value: 10u64}}

task 6 'run'. lines 20-20:
Error: Error checking transaction input objects: IncorrectUserSignature { error: "Object \"BFC1072bade492e0fd6d20bb161f633c46bacb3748f5289878ff87574c606f8cc858206\" is owned by account address \"BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c\", but given owner/signer address is \"BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7\"" }

task 7 'view-object'. lines 22-22:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 3
Contents: sui::coin::Coin<sui::bfc::BFC> {id: sui::object::UID {id: sui::object::ID {bytes: fake(1,0)}}, balance: sui::balance::Balance<sui::bfc::BFC> {value: 0u64}}
