processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-32:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 82460,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 34-36:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 26144,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 3 'run'. lines 38-38:
mutated: object(0,0), object(1,0)
wrapped: object(2,0)
gas summary: computation_cost: 100000, storage_cost: 29488,  storage_rebate: 39125, non_refundable_storage_fee: 395

task 4 'run'. lines 40-40:
mutated: object(0,0), object(1,0)
unwrapped: object(2,0)
gas summary: computation_cost: 100000, storage_cost: 39520,  storage_rebate: 29193, non_refundable_storage_fee: 295
