processed 4 tasks

task 1 'publish'. lines 8-15:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 186960,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 16-18:
Error: Error checking transaction input objects: BFCObjectNotFound { object_id: "BFC00000000000000000000000000000000000000000000000000000000000002425475", version: None }

task 3 'run'. lines 19-19:
Error: Transaction Effects Status: Function Not Found.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: FunctionNotFound, source: Some("Could not resolve function 'foo' in module Test::M"), command: Some(0) } }
