processed 9 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 8-70:
created: object(1,0)
mutated: object(0,3)
gas summary: computation_cost: 1000000, storage_cost: 478040,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 72-72:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 135280,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 74-74:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 10u64}

task 4 'run'. lines 76-76:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 135280,  storage_rebate: 133927, non_refundable_storage_fee: 1353

task 5 'view-object'. lines 78-78:
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 3
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 10u64}

task 6 'run'. lines 80-80:
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 135280,  storage_rebate: 0, non_refundable_storage_fee: 0

task 7 'run'. lines 82-82:
events: Event { package_id: test, transaction_module: Identifier("object_basics"), sender: B, type_: StructTag { address: test, module: Identifier("object_basics"), name: Identifier("NewValueEvent"), type_params: [] }, contents: [20, 0, 0, 0, 0, 0, 0, 0] }
mutated: object(0,1), object(2,0), object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 205200,  storage_rebate: 203148, non_refundable_storage_fee: 2052

task 8 'run'. lines 84-84:
mutated: object(0,1)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 133927, non_refundable_storage_fee: 1353
