processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-42:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 72656,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 44-44:
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 27056,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 3 'view-object'. lines 46-46:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 10u64}

task 4 'run'. lines 48-48:
created: object(4,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 100000, storage_cost: 29564,  storage_rebate: 13844, non_refundable_storage_fee: 140

task 5 'run'. lines 50-50:
mutated: object(0,0)
unwrapped: object(2,0)
deleted: object(4,0)
gas summary: computation_cost: 100000, storage_cost: 27056,  storage_rebate: 29268, non_refundable_storage_fee: 296

task 6 'view-object'. lines 52-52:
Owner: Immutable
Version: 5
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 10u64}
