processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 14-61:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7835600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 63-63:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2705600,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3 'run'. lines 65-65:
created: object(3,0)
mutated: object(0,1)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2956400,  storage_rebate: 2678544, non_refundable_storage_fee: 27056

task 4 'run'. lines 67-67:
mutated: object(0,1)
deleted: object(3,0)
unwrapped_then_deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 2926836, non_refundable_storage_fee: 29564

task 5 'run'. lines 69-69:
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2956400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6 'run'. lines 71-71:
mutated: object(0,1)
deleted: object(5,0)
unwrapped_then_deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 2926836, non_refundable_storage_fee: 29564
