processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 14-65:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 78356,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 67-67:
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 27056,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 3 'run'. lines 69-69:
created: object(3,0)
mutated: object(0,2)
wrapped: object(2,0)
gas summary: computation_cost: 100000, storage_cost: 29564,  storage_rebate: 26785, non_refundable_storage_fee: 271

task 4 'run'. lines 71-71:
mutated: object(0,2)
deleted: object(3,0)
unwrapped_then_deleted: object(2,0)
gas summary: computation_cost: 100000, storage_cost: 13072,  storage_rebate: 29268, non_refundable_storage_fee: 296

task 5 'run'. lines 73-73:
created: object(5,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 29564,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 6 'run'. lines 75-75:
mutated: object(0,2)
deleted: object(5,0)
unwrapped_then_deleted: object(_)
gas summary: computation_cost: 100000, storage_cost: 13072,  storage_rebate: 29268, non_refundable_storage_fee: 296
