processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-71:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 939360,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 73-73:
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 270560,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 3 'view-object'. lines 75-75:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 10u64}

task 4 'run'. lines 77-77:
created: object(4,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 100000, storage_cost: 295640,  storage_rebate: 138442, non_refundable_storage_fee: 1398

task 5 'run'. lines 79-79:
mutated: object(0,0)
unwrapped: object(2,0)
deleted: object(4,0)
gas summary: computation_cost: 100000, storage_cost: 270560,  storage_rebate: 292684, non_refundable_storage_fee: 2956

task 6 'view-object'. lines 81-81:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 5
Contents: test::object_basics::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, value: 10u64}
