processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 14-61:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 391780,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 63-63:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 135280,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 3 'run'. lines 65-65:
created: object(3,0)
mutated: object(0,1)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 147820,  storage_rebate: 133927, non_refundable_storage_fee: 1353

task 4 'run'. lines 67-67:
mutated: object(0,1)
deleted: object(3,0)
unwrapped_then_deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 146342, non_refundable_storage_fee: 1478

task 5 'run'. lines 69-69:
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 147820,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 6 'run'. lines 71-71:
mutated: object(0,1)
deleted: object(5,0)
unwrapped_then_deleted: object(_)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 146342, non_refundable_storage_fee: 1478
