// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// This file is generated by genversion.mjs. Do not edit it directly.

<<<<<<< HEAD
export const PACKAGE_VERSION = '0.1.5';
export const TARGETED_RPC_VERSION = '1.1.4';
=======
export const PACKAGE_VERSION = '0.51.2';
export const TARGETED_RPC_VERSION = '1.24.0';
>>>>>>> mainnet-v1.24.1
