processed 14 tasks

init:
A: object(0,0)

task 1, lines 8-72:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 9614000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 74-76:
//# programmable --sender A --inputs @A
//> 0: test::m::new();
//> TransferObjects([Result(0)], Input(0))
created: object(2,0), object(2,1), object(2,2), object(2,3), object(2,4)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 10070000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 78:
//# view-object 2,2
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: test::m::Obj {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 0u64,
}

task 4, lines 80-81:
//# programmable --sender A --inputs object(2,2) 1 2 3
//> test::m::set(Input(0), Input(1), Input(2), Input(3))
mutated: object(0,0), object(2,2), object(2,3), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 5160400,  storage_rebate: 5108796, non_refundable_storage_fee: 51604

task 5, line 83:
//# view-object 2,2
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: test::m::Obj {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 1u64,
}

task 6, lines 85-86:
//# programmable --sender A --inputs object(2,2)
//> test::m::remove(Input(0))
mutated: object(0,0), object(2,2)
deleted: object(2,1), object(2,4)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 6267492, non_refundable_storage_fee: 63308

task 7, lines 88-91:
//# view-object 2,2
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: test::m::Obj {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,2),
        },
    },
    value: 1u64,
}

task 8, lines 93-94:
//# programmable --sender A --inputs object(2,2)@2 0 0 vector[0] --dev-inspect
//> test::m::check(Input(0), Input(1), Input(2), Input(3))
mutated: object(_), object(2,2)
gas summary: computation_cost: 500000, storage_cost: 2591600,  storage_rebate: 1271556, non_refundable_storage_fee: 12844

task 9, lines 96-97:
//# programmable --sender A --inputs object(2,2)@3 1 2 vector[3] --dev-inspect
//> test::m::check(Input(0), Input(1), Input(2), Input(3))
mutated: object(_), object(2,2)
gas summary: computation_cost: 500000, storage_cost: 2591600,  storage_rebate: 1271556, non_refundable_storage_fee: 12844

task 10, lines 99-103:
//# programmable --sender A --inputs object(2,2)@4 1 2 vector[] --dev-inspect
//> test::m::check(Input(0), Input(1), Input(2), Input(3))
// dev-inspect with 'check' and _incorrect_ values
mutated: object(_), object(2,2)
gas summary: computation_cost: 500000, storage_cost: 2591600,  storage_rebate: 1271556, non_refundable_storage_fee: 12844

task 11, lines 105-106:
//# programmable --sender A --inputs object(2,2)@3 0 0 vector[0] --dev-inspect
//> test::m::check(Input(0), Input(1), Input(2), Input(3))
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 3, instruction: 10, function_name: Some("check") }, 0) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 3, instruction: 10, function_name: Some("check") }, 0) in command 0

task 12, lines 108-109:
//# programmable --sender A --inputs object(2,2)@4 1 2 vector[3] --dev-inspect
//> test::m::check(Input(0), Input(1), Input(2), Input(3))
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("dynamic_field") }, function: 11, instruction: 0, function_name: Some("borrow_child_object") }, 1) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: sui, name: Identifier("dynamic_field") }, function: 11, instruction: 0, function_name: Some("borrow_child_object") }, 1) in command 0

task 13, lines 111-112:
//# programmable --sender A --inputs object(2,2)@2 1 2 vector[] --dev-inspect
//> test::m::check(Input(0), Input(1), Input(2), Input(3))
Error: Transaction Effects Status: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 3, instruction: 10, function_name: Some("check") }, 0) in command 0
Execution Error: MoveAbort(MoveLocation { module: ModuleId { address: test, name: Identifier("m") }, function: 3, instruction: 10, function_name: Some("check") }, 0) in command 0
