processed 12 tasks

init:
A: object(0,0)

task 1, lines 13-52:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8648800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 54:
//# run Test::m::create_obj --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2553600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 56:
//# run Test::m::add_df --sender A --args object(2,0)
created: object(3,0), object(3,1), object(3,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6855200,  storage_rebate: 2528064, non_refundable_storage_fee: 25536

task 4, line 58:
//# run Test::m::add_dof --sender A --args object(2,0)
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2528064, non_refundable_storage_fee: 25536

task 5, line 60:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 62-118:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject",
              "contents": {
                "type": {
                  "repr": "0xde52859aa3c6a7390116b86e70a5ca4fe54ea64572bd1109102ac89d1bca6deb::m::Child"
                },
                "bcs": "lPEzgmNfhheUhzivSG5jOIvj0HgmdHdBiIVOAOOLgaE=",
                "data": {
                  "Struct": [
                    {
                      "name": "id",
                      "value": {
                        "UID": [
                          148,
                          241,
                          51,
                          130,
                          99,
                          95,
                          134,
                          23,
                          148,
                          135,
                          56,
                          175,
                          72,
                          110,
                          99,
                          56,
                          139,
                          227,
                          208,
                          120,
                          38,
                          116,
                          119,
                          65,
                          136,
                          133,
                          78,
                          0,
                          227,
                          139,
                          129,
                          161
                        ]
                      }
                    }
                  ]
                }
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AQAAAAAAAAA=",
              "data": {
                "Number": "1"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AgAAAAAAAAA=",
              "data": {
                "Number": "2"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AAAAAAAAAAA=",
              "data": {
                "Number": "0"
              }
            }
          }
        ]
      }
    },
    "owner": {
      "dynamicFields": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject",
              "contents": {
                "type": {
                  "repr": "0xde52859aa3c6a7390116b86e70a5ca4fe54ea64572bd1109102ac89d1bca6deb::m::Child"
                },
                "bcs": "lPEzgmNfhheUhzivSG5jOIvj0HgmdHdBiIVOAOOLgaE=",
                "data": {
                  "Struct": [
                    {
                      "name": "id",
                      "value": {
                        "UID": [
                          148,
                          241,
                          51,
                          130,
                          99,
                          95,
                          134,
                          23,
                          148,
                          135,
                          56,
                          175,
                          72,
                          110,
                          99,
                          56,
                          139,
                          227,
                          208,
                          120,
                          38,
                          116,
                          119,
                          65,
                          136,
                          133,
                          78,
                          0,
                          227,
                          139,
                          129,
                          161
                        ]
                      }
                    }
                  ]
                }
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AQAAAAAAAAA=",
              "data": {
                "Number": "1"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AgAAAAAAAAA=",
              "data": {
                "Number": "2"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AAAAAAAAAAA=",
              "data": {
                "Number": "0"
              }
            }
          }
        ]
      }
    }
  }
}

task 7, line 120:
//# run Test::m::wrap --sender A --args object(2,0)
created: object(7,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2804400,  storage_rebate: 2528064, non_refundable_storage_fee: 25536

task 8, line 122:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 124-180:
//# run-graphql
Response: {
  "data": {
    "object": null,
    "owner": {
      "dynamicFields": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject",
              "contents": {
                "type": {
                  "repr": "0xde52859aa3c6a7390116b86e70a5ca4fe54ea64572bd1109102ac89d1bca6deb::m::Child"
                },
                "bcs": "lPEzgmNfhheUhzivSG5jOIvj0HgmdHdBiIVOAOOLgaE=",
                "data": {
                  "Struct": [
                    {
                      "name": "id",
                      "value": {
                        "UID": [
                          148,
                          241,
                          51,
                          130,
                          99,
                          95,
                          134,
                          23,
                          148,
                          135,
                          56,
                          175,
                          72,
                          110,
                          99,
                          56,
                          139,
                          227,
                          208,
                          120,
                          38,
                          116,
                          119,
                          65,
                          136,
                          133,
                          78,
                          0,
                          227,
                          139,
                          129,
                          161
                        ]
                      }
                    }
                  ]
                }
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AQAAAAAAAAA=",
              "data": {
                "Number": "1"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AgAAAAAAAAA=",
              "data": {
                "Number": "2"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AAAAAAAAAAA=",
              "data": {
                "Number": "0"
              }
            }
          }
        ]
      }
    }
  }
}

task 10, lines 182-201:
//# run-graphql
Response: {
  "data": {
    "owner": {
      "dynamicField": {
        "name": {
          "type": {
            "repr": "u64"
          },
          "data": {
            "Number": "0"
          },
          "bcs": "AAAAAAAAAAA="
        },
        "value": {
          "__typename": "MoveValue",
          "type": {
            "repr": "u64"
          },
          "bcs": "AAAAAAAAAAA=",
          "data": {
            "Number": "0"
          }
        }
      }
    }
  }
}

task 11, lines 203-219:
//# run-graphql
Response: {
  "data": {
    "owner": {
      "dynamicObjectField": {
        "value": {
          "__typename": "MoveObject",
          "contents": {
            "type": {
              "repr": "0xde52859aa3c6a7390116b86e70a5ca4fe54ea64572bd1109102ac89d1bca6deb::m::Child"
            },
            "bcs": "lPEzgmNfhheUhzivSG5jOIvj0HgmdHdBiIVOAOOLgaE=",
            "data": {
              "Struct": [
                {
                  "name": "id",
                  "value": {
                    "UID": [
                      148,
                      241,
                      51,
                      130,
                      99,
                      95,
                      134,
                      23,
                      148,
                      135,
                      56,
                      175,
                      72,
                      110,
                      99,
                      56,
                      139,
                      227,
                      208,
                      120,
                      38,
                      116,
                      119,
                      65,
                      136,
                      133,
                      78,
                      0,
                      227,
                      139,
                      129,
                      161
                    ]
                  }
                }
              ]
            }
          }
        }
      }
    }
  }
}
