processed 12 tasks

init:
A: object(0,0)

task 1, lines 13-52:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8648800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 54:
//# run Test::m::create_obj --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2553600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 56:
//# run Test::m::add_df --sender A --args object(2,0)
created: object(3,0), object(3,1), object(3,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6855200,  storage_rebate: 2528064, non_refundable_storage_fee: 25536

task 4, line 58:
//# run Test::m::add_dof --sender A --args object(2,0)
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2528064, non_refundable_storage_fee: 25536

task 5, line 60:
//# create-checkpoint
Checkpoint created: 1

task 6, lines 62-118:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject",
              "contents": {
                "type": {
                  "repr": "0xdcbbcedf290c9a9468ac93e72a2d77fb2e73ba6762205a275008fe84b52329e4::m::Child"
                },
                "bcs": "ZbU0dUdShZFTdTZDa73yFPr93Y9DQE3Xl+hdckxr3JU=",
                "data": {
                  "Struct": [
                    {
                      "name": "id",
                      "value": {
                        "UID": [
                          101,
                          181,
                          52,
                          117,
                          71,
                          82,
                          133,
                          145,
                          83,
                          117,
                          54,
                          67,
                          107,
                          189,
                          242,
                          20,
                          250,
                          253,
                          221,
                          143,
                          67,
                          64,
                          77,
                          215,
                          151,
                          232,
                          93,
                          114,
                          76,
                          107,
                          220,
                          149
                        ]
                      }
                    }
                  ]
                }
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AAAAAAAAAAA=",
              "data": {
                "Number": "0"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AQAAAAAAAAA=",
              "data": {
                "Number": "1"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AgAAAAAAAAA=",
              "data": {
                "Number": "2"
              }
            }
          }
        ]
      }
    },
    "owner": {
      "dynamicFields": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject",
              "contents": {
                "type": {
                  "repr": "0xdcbbcedf290c9a9468ac93e72a2d77fb2e73ba6762205a275008fe84b52329e4::m::Child"
                },
                "bcs": "ZbU0dUdShZFTdTZDa73yFPr93Y9DQE3Xl+hdckxr3JU=",
                "data": {
                  "Struct": [
                    {
                      "name": "id",
                      "value": {
                        "UID": [
                          101,
                          181,
                          52,
                          117,
                          71,
                          82,
                          133,
                          145,
                          83,
                          117,
                          54,
                          67,
                          107,
                          189,
                          242,
                          20,
                          250,
                          253,
                          221,
                          143,
                          67,
                          64,
                          77,
                          215,
                          151,
                          232,
                          93,
                          114,
                          76,
                          107,
                          220,
                          149
                        ]
                      }
                    }
                  ]
                }
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AAAAAAAAAAA=",
              "data": {
                "Number": "0"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AQAAAAAAAAA=",
              "data": {
                "Number": "1"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AgAAAAAAAAA=",
              "data": {
                "Number": "2"
              }
            }
          }
        ]
      }
    }
  }
}

task 7, line 120:
//# run Test::m::wrap --sender A --args object(2,0)
created: object(7,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2804400,  storage_rebate: 2528064, non_refundable_storage_fee: 25536

task 8, line 122:
//# create-checkpoint
Checkpoint created: 2

task 9, lines 124-180:
//# run-graphql
Response: {
  "data": {
    "object": null,
    "owner": {
      "dynamicFields": {
        "nodes": [
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveObject",
              "contents": {
                "type": {
                  "repr": "0xdcbbcedf290c9a9468ac93e72a2d77fb2e73ba6762205a275008fe84b52329e4::m::Child"
                },
                "bcs": "ZbU0dUdShZFTdTZDa73yFPr93Y9DQE3Xl+hdckxr3JU=",
                "data": {
                  "Struct": [
                    {
                      "name": "id",
                      "value": {
                        "UID": [
                          101,
                          181,
                          52,
                          117,
                          71,
                          82,
                          133,
                          145,
                          83,
                          117,
                          54,
                          67,
                          107,
                          189,
                          242,
                          20,
                          250,
                          253,
                          221,
                          143,
                          67,
                          64,
                          77,
                          215,
                          151,
                          232,
                          93,
                          114,
                          76,
                          107,
                          220,
                          149
                        ]
                      }
                    }
                  ]
                }
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "u64"
              },
              "data": {
                "Number": "0"
              },
              "bcs": "AAAAAAAAAAA="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AAAAAAAAAAA=",
              "data": {
                "Number": "0"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "vector<u8>"
              },
              "data": {
                "Vector": []
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AQAAAAAAAAA=",
              "data": {
                "Number": "1"
              }
            }
          },
          {
            "name": {
              "type": {
                "repr": "bool"
              },
              "data": {
                "Bool": false
              },
              "bcs": "AA=="
            },
            "value": {
              "__typename": "MoveValue",
              "type": {
                "repr": "u64"
              },
              "bcs": "AgAAAAAAAAA=",
              "data": {
                "Number": "2"
              }
            }
          }
        ]
      }
    }
  }
}

task 10, lines 182-201:
//# run-graphql
Response: {
  "data": {
    "owner": {
      "dynamicField": {
        "name": {
          "type": {
            "repr": "u64"
          },
          "data": {
            "Number": "0"
          },
          "bcs": "AAAAAAAAAAA="
        },
        "value": {
          "__typename": "MoveValue",
          "type": {
            "repr": "u64"
          },
          "bcs": "AAAAAAAAAAA=",
          "data": {
            "Number": "0"
          }
        }
      }
    }
  }
}

task 11, lines 203-219:
//# run-graphql
Response: {
  "data": {
    "owner": {
      "dynamicObjectField": {
        "value": {
          "__typename": "MoveObject",
          "contents": {
            "type": {
              "repr": "0xdcbbcedf290c9a9468ac93e72a2d77fb2e73ba6762205a275008fe84b52329e4::m::Child"
            },
            "bcs": "ZbU0dUdShZFTdTZDa73yFPr93Y9DQE3Xl+hdckxr3JU=",
            "data": {
              "Struct": [
                {
                  "name": "id",
                  "value": {
                    "UID": [
                      101,
                      181,
                      52,
                      117,
                      71,
                      82,
                      133,
                      145,
                      83,
                      117,
                      54,
                      67,
                      107,
                      189,
                      242,
                      20,
                      250,
                      253,
                      221,
                      143,
                      67,
                      64,
                      77,
                      215,
                      151,
                      232,
                      93,
                      114,
                      76,
                      107,
                      220,
                      149
                    ]
                  }
                }
              ]
            }
          }
        }
      }
    }
  }
}
