processed 25 tasks

init:
validator_0: object(0,0)

task 1, lines 6-25:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5890000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 27:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 29:
//# run Test::M1::create --args 0 @validator_0
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 31:
//# view-object 0,0
Owner: Account Address ( BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9 )
Version: 1
Contents: sui_system::staking_pool::StakedBfc {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(0,0),
        },
    },
    pool_id: sui::object::ID {
        bytes: _,
    },
    stake_activation_epoch: 0u64,
    principal: sui::balance::Balance<sui::bfc::BFC> {
        value: 200000000000000u64,
    },
}

task 5, line 33:
//# view-object 2,0
Owner: Account Address ( BFC0000000000000000000000000000000000000000000000000000000000000042e850 )
Version: 3
Contents: Test::M1::Object {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 6, line 35:
//# view-object 3,0
Owner: Account Address ( BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9 )
Version: 4
Contents: Test::M1::Object {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    value: 0u64,
}

task 7, line 37:
//# create-checkpoint 4
Checkpoint created: 4

task 8, line 39:
//# view-checkpoint
CheckpointSummary { epoch: 0, seq: 4, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { base_point: 0, rate: 0, computation_cost: 3000000, storage_cost: 11134000, storage_rebate: 2588256, non_refundable_storage_fee: 26144 }}

task 9, line 41:
//# advance-epoch 6
Epoch advanced: 5

task 10, line 43:
//# view-checkpoint
CheckpointSummary { epoch: 5, seq: 10, content_digest: 4A2sRZopCiB1gAjAotFVpUy7zHdWFHmZaiBJgPg1c2x8,
            epoch_rolling_gas_cost_summary: GasCostSummary { base_point: 0, rate: 0, computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 11, lines 45-50:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    }
  }
}

task 12, line 52:
//# create-checkpoint
Checkpoint created: 11

task 13, line 54:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { base_point: 0, rate: 0, computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 14, lines 56-61:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  }
}

task 15, lines 63-68:
//# run-graphql --show-usage --show-headers --show-service-version
Headers: {
    "content-type": "application/json",
    "content-length": "157",
    "x-sui-rpc-version": "42.43.44-testing-no-sha",
    "vary": "origin, access-control-request-method, access-control-request-headers",
    "access-control-allow-origin": "*",
}
Service version: 42.43.44-testing-no-sha
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 2,
      "outputNodes": 2,
      "depth": 2,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 41
    }
  }
}

task 16, line 70:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { base_point: 0, rate: 0, computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 17, lines 72-75:
//# advance-epoch
Epoch advanced: 6

task 18, lines 77-92:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x8bdbb2a9b93d0b47761d845ff909043989f3f3e8f02ef6f0623eb18dca94da65",
              "digest": "8C2DrBYiFRKJ7gLmZUG2bx9b6NCVNm45xGXvK56YWMu3",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    }
  }
}

task 19, lines 94-149:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    },
    "second": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x8bdbb2a9b93d0b47761d845ff909043989f3f3e8f02ef6f0623eb18dca94da65",
              "digest": "8C2DrBYiFRKJ7gLmZUG2bx9b6NCVNm45xGXvK56YWMu3",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "val_objs": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x2947f4314d19ef49644e66aaa44753ea3441b63e4bac80df8d48c7e8b5427da3",
              "digest": "AyZoMYhCX48vzsQyZmoRP6aLovzbkjzqhiWJ17ZyMXrx",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x2c120c6d64991694a3aaf991bf0527bcd296554e5f373163d688a546a99b2173",
              "digest": "HyhgjvEBvytVWweDcsRFAekEd9iX4m9TPvDjicwwdYGk",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x8ba08fab38d2e5ee60ebb982cb3049145721482b4dd548d803e1bdef1b1fb402",
              "digest": "EedNA5bUJA4b4q5D8JkZRGw6Kny3xTejvQ2LyaGBjxfH",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xb638c2243cab5575dd5d5280d7f6babd66e9aeacbe3af678523ef63c6c820056",
              "digest": "48NpWK2EToFHbGmFKSGChWbg8mZcKJKEpM67TJNv2kqN",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xba6510851d95dc53de7a369f37fc291cb73273871d469344b26ab55c52a8e4a0",
              "digest": "98WLn5Jmm2DVy2A2uteno8hhs8feBcieGxSVBv57kft7",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xf9b82a488dc84c9fa709b2605d5fb43eef23b938d431bd7f6a1702293d662801",
              "digest": "2eGYN2r8XAHkEoKbPPiHaZZx8SwUw5QJzsWPCRYPFUMd",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "object": {
      "version": 3,
      "owner": {
        "__typename": "AddressOwner",
        "owner": {
          "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
        }
      }
    }
  }
}

task 20, lines 151-167:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": {
          "nodes": [
            {
              "address": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
              }
            }
          ]
        }
      }
    },
    "address": {
      "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
    }
  }
}

task 21, lines 169-175:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "referenceGasPrice": "234"
    }
  }
}

task 22, line 177:
//# run Test::M1::create --args 0 @A --gas-price 999
created: object(22,0)
mutated: object(0,1)
gas summary: computation_cost: 999000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 23, line 179:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 24, line 181:
//# run Test::M1::create --args 0 @A --gas-price 235
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 235000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072
