processed 25 tasks

init:
validator_0: object(0,0)

task 1, lines 6-25:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 5890000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 27:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 29:
//# run Test::M1::create --args 0 @validator_0
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 31:
//# view-object 0,0
Owner: Account Address ( BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9 )
Version: 1
Contents: sui_system::staking_pool::StakedBfc {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(0,0),
        },
    },
    pool_id: sui::object::ID {
        bytes: _,
    },
    stake_activation_epoch: 0u64,
    principal: sui::balance::Balance<sui::bfc::BFC> {
        value: 200000000000000u64,
    },
}

task 5, line 33:
//# view-object 2,0
Owner: Account Address ( BFC0000000000000000000000000000000000000000000000000000000000000042e850 )
Version: 3
Contents: Test::M1::Object {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    value: 0u64,
}

task 6, line 35:
//# view-object 3,0
Owner: Account Address ( BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9 )
Version: 4
Contents: Test::M1::Object {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(3,0),
        },
    },
    value: 0u64,
}

task 7, line 37:
//# create-checkpoint 4
Checkpoint created: 4

task 8, line 39:
//# view-checkpoint
CheckpointSummary { epoch: 0, seq: 4, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { base_point: 0, rate: 0, computation_cost: 3000000, storage_cost: 11134000, storage_rebate: 2588256, non_refundable_storage_fee: 26144 }}

task 9, line 41:
//# advance-epoch 6
Epoch advanced: 5

task 10, line 43:
//# view-checkpoint
CheckpointSummary { epoch: 5, seq: 10, content_digest: 6hiiNRMPrWA25JdgsHU5kEYfeHhPmhdkmCzwgtonfj3D,
            epoch_rolling_gas_cost_summary: GasCostSummary { base_point: 0, rate: 0, computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 11, lines 45-50:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    }
  }
}

task 12, line 52:
//# create-checkpoint
Checkpoint created: 11

task 13, line 54:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { base_point: 0, rate: 0, computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 14, lines 56-61:
//# run-graphql
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  }
}

task 15, lines 63-68:
//# run-graphql --show-usage --show-headers --show-service-version
Headers: {
    "content-type": "application/json",
    "content-length": "157",
    "x-sui-rpc-version": "42.43.44-testing-no-sha",
    "vary": "origin, access-control-request-method, access-control-request-headers",
    "access-control-allow-origin": "*",
}
Service version: 42.43.44-testing-no-sha
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 11
    }
  },
  "extensions": {
    "usage": {
      "inputNodes": 2,
      "outputNodes": 2,
      "depth": 2,
      "variables": 0,
      "fragments": 0,
      "queryPayload": 41
    }
  }
}

task 16, line 70:
//# view-checkpoint
CheckpointSummary { epoch: 6, seq: 11, content_digest: D3oWLCcqoa1D15gxzvMaDemNNY8YYVspAkYkcmtQKWRt,
            epoch_rolling_gas_cost_summary: GasCostSummary { base_point: 0, rate: 0, computation_cost: 0, storage_cost: 0, storage_rebate: 0, non_refundable_storage_fee: 0 }}

task 17, lines 72-75:
//# advance-epoch
Epoch advanced: 6

task 18, lines 77-92:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x692571e476bf62a51040a5f46d8432af7ffca4fd51616e3192d518457c9ad2e5",
              "digest": "2PgsizBQUbvwHAJo8C6nVEYzQUGHhWxedXqvnX155WZ4",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    }
  }
}

task 19, lines 94-149:
//# run-graphql
Response: {
  "data": {
    "address": {
      "objects": {
        "edges": []
      }
    },
    "second": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x692571e476bf62a51040a5f46d8432af7ffca4fd51616e3192d518457c9ad2e5",
              "digest": "2PgsizBQUbvwHAJo8C6nVEYzQUGHhWxedXqvnX155WZ4",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "val_objs": {
      "objects": {
        "edges": [
          {
            "node": {
              "address": "0x808a248f6f25e11b19023ab5674685034c7c849c07b8b8acc9f738b6c8f4d63a",
              "digest": "GLKx2xcmsk545W6jWPJUuLevoa9keW9hCaFttyp9mo9u",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x831eaf0ce77b2f0f4f5df853aa87a4b9fa65b663495f03d44d81834008e58f42",
              "digest": "F9iFQAnjHYwCPvxjZMf4UAJNKBSurxG1wsfUZhq9enij",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0x9520c2d057e05edecd730d4bfd0674cf207f828619dc369ce82c138ff967232e",
              "digest": "FVtJtxfn8mcseayCXkp5xgFdahF8aBnSYzd1M2Ribms9",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xe359ca449bbc6aa4fd2b3bdb58f77336c83e6fa13d4347a5e03f42223f398675",
              "digest": "B3UQQBizvip3ZW7f5U4Bw7BvPb6LGczghW8iQjsSAFg1",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xe52b71fb0b97a2586678b067aad6b8e6dfb6f9da36015bd9b7ffce389c53322f",
              "digest": "44ezCM4q2ztqQzh6p9RZVT2oPRhNQa4PwXXb45u5wDLv",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          },
          {
            "node": {
              "address": "0xf9b82a488dc84c9fa709b2605d5fb43eef23b938d431bd7f6a1702293d662801",
              "digest": "6D7mj59v4XZFTKjeL3E6aB9z6Ydz7NjuJVBnZ3RSB5Jk",
              "owner": {
                "__typename": "AddressOwner"
              }
            }
          }
        ]
      }
    },
    "object": {
      "version": 3,
      "owner": {
        "__typename": "AddressOwner",
        "owner": {
          "address": "0x0000000000000000000000000000000000000000000000000000000000000042"
        }
      }
    }
  }
}

task 20, lines 151-167:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "validatorSet": {
        "activeValidators": {
          "nodes": [
            {
              "address": {
                "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
              }
            }
          ]
        }
      }
    },
    "address": {
      "address": "0xa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a"
    }
  }
}

task 21, lines 169-175:
//# run-graphql
Response: {
  "data": {
    "epoch": {
      "referenceGasPrice": "234"
    }
  }
}

task 22, line 177:
//# run Test::M1::create --args 0 @A --gas-price 999
created: object(22,0)
mutated: object(0,1)
gas summary: computation_cost: 999000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 23, line 179:
//# run Test::M1::create --args 0 @A --gas-price 1000
created: object(23,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 24, line 181:
//# run Test::M1::create --args 0 @A --gas-price 235
created: object(24,0)
mutated: object(0,1)
gas summary: computation_cost: 235000, storage_cost: 2622000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072
