version: "3.9"

services:
  backend:
    image: mysten/zklogin:prover-stable
    ports:
      - '8070:8080'
    volumes:
      - /opt/software/zklogin-ceremony-contributions/zkLogin-main.zkey:/app/binaries/zkLogin.zkey
    environment:
      - ZKEY=/app/binaries/zkLogin.zkey
      - WITNESS_BINARIES=/app/binaries

  frontend:
    image: mysten/zklogin:prover-fe-stable
    command: '8080'
    ports:
      - '8090:8080'
    environment:
      - PROVER_URI=http://backend:8070/input
      - NODE_ENV=production
      - DEBUG=zkLogin:info,jwks


