version: "3.9"

services:
  backend:
    image: mysten/zklogin:prover-stable
    volumes:
      - /opt/software/zklogin-ceremony-contributions/zkLogin-test.zkey:/app/binaries/zkLogin.zkey
    environment:
      - ZKEY=/app/binaries/zkLogin.zkey
      - WITNESS_BINARIES=/app/binaries

  frontend:
    image: mysten/zklogin:prover-fe-stable
    command: '8080'
    ports:
      - '8090:8080'
    environment:
      - PROVER_URI=http://backend:8080/input
      - NODE_ENV=production
      - REDIS_URI=redis://cache:6379
      - SALT_URI=https://devsalt.openblock.vip/get_jwk
      - ENVIRONMENT=dev
      - DEBUG=zkLogin:info,jwks
  cache:
    image: redis:latest