version: "3.9"

services:
  backend:
    image: harbor.openblock.vip/zklogin/obc-zklogin:prover-stable
    volumes:
      -  /opt/software/zklogin-ceremony/circuit_final.zkey:/app/binaries/zkLogin.zkey
    environment:
      - ZKEY=/app/binaries/zkLogin.zkey
      - WITNESS_BINARIES=/app/binaries

  frontend:
    image: harbor.openblock.vip/zklogin/obc-zklogin:prover-fe-stable
    command: '8080'
    ports:
      - '8090:8080'
      - '9184:9184'
    environment:
      - PROVER_URI=http://backend:8080/input
      - NODE_ENV=production
      - REDIS_URI=redis://cache:6379
      - SALT_URI=https://ocean.zkpoint.org/get_jwk
      - ENVIRONMENT=prod
      - DEBUG=zkLogin:info,jwks
  cache:
    image: redis:latest