processed 6 tasks

task 1, lines 6-24:
//# publish
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5958400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 26:
//# run test::m::create
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2576400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 28:
//# run test::m::check --args object(2,0) 0
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2576400,  storage_rebate: 2550636, non_refundable_storage_fee: 25764

task 4, line 30:
//# advance-epoch
Epoch advanced: 1

task 5, line 32:
//# run test::m::check --args object(2,0) 1
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2576400,  storage_rebate: 2550636, non_refundable_storage_fee: 25764
