processed 18 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-77:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 997880,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 79-79:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 376200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 81-81:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4 'view-object'. lines 83-83:
Owner: Account Address ( BFC59f4b97c9b85ff2e1579d4f0342b269f005a6c5fa5303e39e1fcceb2c41c9dad2d09 )
Version: 2
Contents: test::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5 'programmable'. lines 85-87:
mutated: object(0,0), object(2,0)
deleted: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 255360,  storage_rebate: 372438, non_refundable_storage_fee: 3762

task 6 'run'. lines 89-89:
created: object(6,0), object(6,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 378480,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 7 'view-object'. lines 91-91:
Owner: Account Address ( BFC434af715142adec4bdf7227f522a3549bf8ee52d34b0c71c92ec44910e366325ad6a )
Version: 4
Contents: test::m::Cup<u64> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(6,0),
        },
    },
}

task 8 'view-object'. lines 93-93:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(6,1),
        },
    },
}

task 9 'programmable'. lines 95-99:
mutated: object(0,0), object(6,1)
deleted: object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 255360,  storage_rebate: 374695, non_refundable_storage_fee: 3785

task 10 'run'. lines 101-101:
created: object(10,0), object(10,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 376200,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 11 'view-object'. lines 103-103:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 6
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(10,0),
        },
    },
}

task 12 'view-object'. lines 105-105:
Owner: Account Address ( BFCa896096322e4346d8bf45098c1e7baca0ca41178ed262d96b9b0e04877683ef1a9dd )
Version: 6
Contents: test::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(10,1),
        },
    },
}

task 13 'programmable'. lines 107-113:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call sui::transfer::receive. Use the public variant instead, sui::transfer::public_receive"), command: Some(1) } }

task 14 'run'. lines 115-115:
created: object(14,0), object(14,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 379240,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 15 'view-object'. lines 117-117:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 8
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(14,0),
        },
    },
}

task 16 'view-object'. lines 119-119:
Owner: Account Address ( BFC93b57efd21977f9157dd47978ea59d8d39443f9336e26a405f8fe639bd4f537a4e9a )
Version: 8
Contents: test::m::Store {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(14,1),
        },
    },
}

task 17 'programmable'. lines 121-125:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call sui::transfer::receive. Use the public variant instead, sui::transfer::public_receive"), command: Some(1) } }
