processed 10 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 8-29:
created: object(1,0)
mutated: object(0,3)
gas summary: computation_cost: 1000000, storage_cost: 6102800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 31-31:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 33-33:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}}

task 4 'transfer-object'. lines 35-35:
Error: Transaction Effects Status: Invalid Transfer Object, object does not have public transfer.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidTransferObject, source: None, command: Some(0) } }

task 5 'view-object'. lines 37-40:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: test::m::S {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}}

task 6 'run'. lines 42-42:
created: object(6,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2819600,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 7 'view-object'. lines 44-44:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: test::m::Cup<test::m::S> {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}}

task 8 'transfer-object'. lines 46-46:
Error: Transaction Effects Status: Invalid Transfer Object, object does not have public transfer.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: InvalidTransferObject, source: None, command: Some(0) } }

task 9 'view-object'. lines 48-48:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 5
Contents: test::m::Cup<test::m::S> {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}}
