processed 18 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-77:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 9978800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 79-79:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3762000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 81-81:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4 'view-object'. lines 83-83:
Owner: Account Address ( BFC59f4b97c9b85ff2e1579d4f0342b269f005a6c5fa5303e39e1fcceb2c41c9dad2d09 )
Version: 2
Contents: test::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5 'programmable'. lines 85-87:
mutated: object(0,0), object(2,0)
deleted: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 2553600,  storage_rebate: 3724380, non_refundable_storage_fee: 37620

task 6 'run'. lines 89-89:
created: object(6,0), object(6,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3784800,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 7 'view-object'. lines 91-91:
Owner: Account Address ( BFCb266e97326e28d08f8664112179195f2b481b09ba98d4f891e8e2372c4740b5a8757 )
Version: 4
Contents: test::m::Cup<u64> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(6,0),
        },
    },
}

task 8 'view-object'. lines 93-93:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(6,1),
        },
    },
}

task 9 'programmable'. lines 95-99:
mutated: object(0,0), object(6,1)
deleted: object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 2553600,  storage_rebate: 3746952, non_refundable_storage_fee: 37848

task 10 'run'. lines 101-101:
created: object(10,0), object(10,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3762000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 11 'view-object'. lines 103-103:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 6
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(10,0),
        },
    },
}

task 12 'view-object'. lines 105-105:
Owner: Account Address ( BFC23f1dd4c1670406ea612d5887e8667e9a640f8da59b3227edd7d8958561e20fd745a )
Version: 6
Contents: test::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(10,1),
        },
    },
}

task 13 'programmable'. lines 107-113:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call sui::transfer::receive. Use the public variant instead, sui::transfer::public_receive"), command: Some(1) } }

task 14 'run'. lines 115-115:
created: object(14,0), object(14,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3792400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 15 'view-object'. lines 117-117:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 8
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(14,0),
        },
    },
}

task 16 'view-object'. lines 119-119:
Owner: Account Address ( BFC673cd0ddc2b9ef48bc1415b6c92e967398bfd516823bd20730deab060faf7fac3676 )
Version: 8
Contents: test::m::Store {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(14,1),
        },
    },
}

task 17 'programmable'. lines 121-125:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call sui::transfer::receive. Use the public variant instead, sui::transfer::public_receive"), command: Some(1) } }
