processed 20 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 9-77:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 498940,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 79-79:
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 188100,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 81-81:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4 'view-object'. lines 83-83:
Owner: Account Address ( BFC59f4b97c9b85ff2e1579d4f0342b269f005a6c5fa5303e39e1fcceb2c41c9dad2d09 )
Version: 2
Contents: test::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 5 'programmable'. lines 85-87:
mutated: object(0,0), object(2,0)
deleted: object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 127680,  storage_rebate: 186219, non_refundable_storage_fee: 1881

task 6 'run'. lines 89-89:
created: object(6,0), object(6,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 189240,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 7 'view-object'. lines 91-91:
Owner: Account Address ( BFC2125af07dadd747481e05040b9c152887e8ca2cda3b98fd0df8b7e0e74b389af95ba )
Version: 4
Contents: test::m::Cup<u64> {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(6,0),
        },
    },
}

task 8 'view-object'. lines 93-93:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(6,1),
        },
    },
}

task 9 'programmable'. lines 95-99:
mutated: object(0,0), object(6,1)
deleted: object(6,0)
gas summary: computation_cost: 1000000, storage_cost: 127680,  storage_rebate: 187348, non_refundable_storage_fee: 1892

task 10 'run'. lines 101-101:
created: object(10,0), object(10,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 188100,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 11 'view-object'. lines 103-103:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 6
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(10,0),
        },
    },
}

task 12 'view-object'. lines 105-105:
Owner: Account Address ( BFCe54000d066e980a3e7749b101edee05154fd814fb022b71fdd1405b0d7c299b19975 )
Version: 6
Contents: test::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(10,1),
        },
    },
}

task 13 'programmable'. lines 107-109:
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: VMVerificationOrDeserializationError, source: Some(VMError { major_status: CONSTRAINT_NOT_SATISFIED, sub_status: None, message: None, exec_state: None, location: Module(ModuleId { address: sui, name: Identifier("transfer") }), indices: [], offsets: [] }), command: Some(1) } }

task 14 'programmable'. lines 111-117:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call sui::transfer::receive. Use the public variant instead, sui::transfer::public_receive"), command: Some(1) } }

task 15 'run'. lines 119-119:
created: object(15,0), object(15,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 189620,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 16 'view-object'. lines 121-121:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 9
Contents: test::m::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(15,0),
        },
    },
}

task 17 'view-object'. lines 123-123:
Owner: Account Address ( BFC7260fdcd82eb9b59a2d846bc997781ce357d0473f617c1ba8b5a679e0de3878d2dce )
Version: 9
Contents: test::m::Store {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(15,1),
        },
    },
}

task 18 'programmable'. lines 125-129:
Error: Transaction Effects Status: Non Entry Function Invoked. Move Call must start with an entry function
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: NonEntryFunctionInvoked, source: Some("Cannot directly call sui::transfer::receive. Use the public variant instead, sui::transfer::public_receive"), command: Some(1) } }

task 19 'programmable'. lines 130-134:
mutated: object(0,0)
deleted: object(15,0), object(15,1)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 187724, non_refundable_storage_fee: 1896
