processed 6 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 8-18:
//# publish
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5221200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 20:
//# run test::m::mint_s
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, line 22:
//# view-object 2,0
Owner: Shared( 3 )
Version: 3
Contents: test::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, line 24:
//# transfer-object 2,0 --sender A --recipient B
Error: Transaction Effects Status: Invalid command argument at 0. Immutable objects cannot be passed by-value.
Debug of error: CommandArgumentError { arg_idx: 0, kind: InvalidObjectByValue } at command Some(0)

task 5, line 26:
//# view-object 2,0
Owner: Shared( 3 )
Version: 4
Contents: test::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}
