processed 8 tasks

init:
A: object(0,0)

task 1, lines 8-39:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6543600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 41:
//# run a::m::mint --sender A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 43:
//# view-object 2,0
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: a::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}

task 4, line 45:
//# run a::m::wrap --sender A --args object(2,0)
created: object(4,0)
mutated: object(0,0)
wrapped: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2758800,  storage_rebate: 2490444, non_refundable_storage_fee: 25156

task 5, line 47:
//# view-object 4,0
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: a::m::T {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(4,0),
        },
    },
    s: a::m::S {
        id: sui::object::UID {
            id: sui::object::ID {
                bytes: fake(2,0),
            },
        },
    },
}

task 6, line 49:
//# run a::m::unwrap --sender A --args object(4,0)
mutated: object(0,0)
unwrapped: object(2,0)
deleted: object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 2515600,  storage_rebate: 2731212, non_refundable_storage_fee: 27588

task 7, line 51:
//# view-object 2,0
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: a::m::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
}
