processed 17 tasks

init:
A: object(0,0)

task 1, lines 6-86:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 10906000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 88-89:
//# run P0::M::new_o
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2584000,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3, lines 91-92:
//# run P0::M::new_w
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2576400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, lines 94-95:
//# run P0::M::new_dof
created: object(4,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5, lines 97-98:
//# run P0::M::new_dof
created: object(5,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 6, lines 101-104:
//# run P0::M::connect --args object(2,0) object(3,0) object(4,0) object(5,0)
created: object(6,0), object(6,1)
mutated: object(0,1), object(2,0), object(4,0), object(5,0)
wrapped: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 10260000,  storage_rebate: 6357780, non_refundable_storage_fee: 64220

task 7, lines 106-108:
//# view-object 2,0
Owner: Account Address ( BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9 )
Version: 7
Contents: P0::M::O {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
    wrapped: std::option::Option<P0::M::W> {
        vec: vector[
            P0::M::W {
                id: sui::object::UID {
                    id: sui::object::ID {
                        bytes: fake(3,0),
                    },
                },
                count: 0u64,
            },
        ],
    },
}

task 8, lines 110-111:
//# run P0::M::touch_root --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2888000,  storage_rebate: 2859120, non_refundable_storage_fee: 28880

task 9, lines 113-114:
//# run P0::M::touch_wrapped --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2888000,  storage_rebate: 2859120, non_refundable_storage_fee: 28880

task 10, lines 116-117:
//# run P0::M::touch_inner --args object(2,0)
mutated: object(0,1), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 4172400,  storage_rebate: 4130676, non_refundable_storage_fee: 41724

task 11, lines 119-120:
//# run P0::M::touch_outer --args object(2,0)
mutated: object(0,1), object(2,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 4172400,  storage_rebate: 4130676, non_refundable_storage_fee: 41724

task 12, line 122:
//# view-object 2,0
Owner: Account Address ( BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9 )
Version: 11
Contents: P0::M::O {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 1u64,
    wrapped: std::option::Option<P0::M::W> {
        vec: vector[
            P0::M::W {
                id: sui::object::UID {
                    id: sui::object::ID {
                        bytes: fake(3,0),
                    },
                },
                count: 1u64,
            },
        ],
    },
}

task 13, line 124:
//# create-checkpoint
Checkpoint created: 1

task 14, lines 126-141:
//# run-graphql
Response: {
  "data": {
    "latest": {
      "asObject": {
        "asMoveObject": {
          "version": 11,
          "contents": {
            "json": {
              "id": "0x294868d87a1e9cdd5420ca09df222cd53c4d927b0bc394df7c5d79ae1de3a53a",
              "count": "1",
              "wrapped": {
                "id": "0x8675b69b70a9d8a4d7d3e6f3950d7b2d5bb2fe37840ad26803c70e5d438acecb",
                "count": "1"
              }
            }
          }
        }
      }
    },
    "versioned": {
      "asObject": null
    },
    "beforeWrappedBump": {
      "asObject": null
    },
    "beforeBump": {
      "asObject": null
    }
  }
}

task 15, lines 143-171:
//# run-graphql
Response: {
  "data": {
    "unversioned": {
      "dynamicObjectField": {
        "value": null
      }
    },
    "latest": {
      "dynamicObjectField": null
    },
    "afterFirstInnerBump": {
      "dynamicObjectField": null
    },
    "beforeFirstInnerBump": {
      "dynamicObjectField": null
    },
    "beforeBumps": {
      "dynamicObjectField": null
    }
  }
}

task 16, lines 173-194:
//# run-graphql
Response: {
  "data": {
    "unversioned": {
      "dynamicObjectField": {
        "value": null
      }
    },
    "latest": {
      "dynamicObjectField": null
    },
    "beforeInnerBump": {
      "dynamicObjectField": null
    }
  }
}
