processed 13 tasks

init:
A: object(0,0)

task 1, lines 14-55:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8793200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 57:
//# run Test::M1::parent --sender A --args @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 59:
//# view-object 2,0
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: Test::M1::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
}

task 4, line 61:
//# run Test::M1::add_df --sender A --args object(2,0)
created: object(4,0), object(4,1), object(4,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 8983200,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5, line 63:
//# view-object 2,0
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: Test::M1::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
}

task 6, line 65:
//# run Test::M1::add_more_df --sender A --args object(2,0)
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 8983200,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 7, line 67:
//# view-object 2,0
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: Test::M1::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
}

task 8, line 69:
//# run Test::M1::remove_df --sender A --args object(2,0)
mutated: object(0,0), object(2,0)
deleted: object(4,0), object(4,1), object(4,2)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 8893368, non_refundable_storage_fee: 89832

task 9, line 71:
//# run Test::M1::mutate_parent --sender A --args object(2,0)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 10, line 73:
//# create-checkpoint
Checkpoint created: 1

task 11, lines 75-138:
//# run-graphql
Response: {
  "data": {
    "latest": {
      "version": 6,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBGPa5Hd3ZYF/v+gmCio4ZmpMBEoLv6uyrqhfSkJzvz2AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IBa+v23+oVbgFJFtRwYIo1uY8KPGixGz6fbfy3k+X0VYAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IKBa3lN0rdouIRFnjm9bDmoFW4Q+fQCTL5Y1w+EyOWRoAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    },
    "df123_removed": {
      "version": 5,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBGPa5Hd3ZYF/v+gmCio4ZmpMBEoLv6uyrqhfSkJzvz2AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IBa+v23+oVbgFJFtRwYIo1uY8KPGixGz6fbfy3k+X0VYAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IKBa3lN0rdouIRFnjm9bDmoFW4Q+fQCTL5Y1w+EyOWRoAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    },
    "df456_added": {
      "version": 4,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBGPa5Hd3ZYF/v+gmCio4ZmpMBEoLv6uyrqhfSkJzvz2AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IBa+v23+oVbgFJFtRwYIo1uY8KPGixGz6fbfy3k+X0VYAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IFGh6392+hg5gnZaJnevpoMEaVl21VnIpEMZjl+HTgJsAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ=="
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IGDBRQy3Km0T4jdoQPZ9/Lz3buc73xDwKI07/5HJ9wiSAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg=="
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IKBa3lN0rdouIRFnjm9bDmoFW4Q+fQCTL5Y1w+EyOWRoAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IOJf7TxnxH1NR3h2PYM6oIYorRtOLJU2pv0NBG5GvYCgAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw=="
              },
              "value": {
                "json": "df3"
              }
            }
          }
        ]
      },
      "df1": {
        "name": {
          "bcs": "A2RmMQ=="
        },
        "value": {
          "json": "df1"
        }
      },
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    }
  }
}

task 12, lines 140-178:
//# run-graphql
Response: {
  "data": {
    "latest_owner": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBGPa5Hd3ZYF/v+gmCio4ZmpMBEoLv6uyrqhfSkJzvz2AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "IBa+v23+oVbgFJFtRwYIo1uY8KPGixGz6fbfy3k+X0VYAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IKBa3lN0rdouIRFnjm9bDmoFW4Q+fQCTL5Y1w+EyOWRoAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    }
  }
}
