processed 37 tasks

init:
A: object(0,0)

task 1, lines 12-82:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 11331600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 84-86:
//# programmable --sender A --inputs @A 42
//> 0: Test::M1::parent(Input(0));
//> 1: Test::M1::child(Input(0));
created: object(2,0), object(2,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3868400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 88:
//# view-object 2,1
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: Test::M1::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 4, line 90:
//# view-object 2,0
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: Test::M1::Child {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 0u64,
}

task 5, lines 92-94:
//# programmable --sender A --inputs object(2,1) object(2,0) 420
//> Test::M1::add_child(Input(0), Input(1), Input(2));
//> Test::M1::mutate_child_via_parent(Input(0), Input(2));
created: object(5,0)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 6323200,  storage_rebate: 3829716, non_refundable_storage_fee: 38684

task 6, line 96:
//# view-object 2,1
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: Test::M1::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 7, line 98:
//# view-object 2,0
Owner: Object ID: ( BFC17411f8a6213b4d42f92a0244b13fd15e39fdde00c75e4061e6ce158383543665f93 )
Version: 3
Contents: Test::M1::Child {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 1u64,
}

task 8, line 100:
//# create-checkpoint
Checkpoint created: 1

task 9, lines 102-164:
//# run-graphql
Response: {
  "data": {
    "parent_version_2_no_dof": {
      "address": "0x5282685e0025ad9dfd4e99ba465e5a15048af3e79a28920460a1ad5557c9bfd2",
      "dynamicFields": {
        "edges": []
      }
    },
    "parent_version_3_has_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBdBH4piE7TUL5KgJEsT/RXjn93gDHXkBh5s4Vg4NUNmAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "child_version_2_no_parent": {
      "address": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
      "owner": {}
    },
    "child_version_3_has_parent": {
      "owner": {
        "parent": {
          "address": "0x17411f8a6213b4d42f92a0244b13fd15e39fdde00c75e4061e6ce15838354366"
        }
      }
    }
  }
}

task 10, lines 166-168:
//# programmable --sender A --inputs object(2,1) 420
//> Test::M1::mutate_child_via_parent(Input(0), Input(1));
//> Test::M1::add_df(Input(0));
created: object(10,0), object(10,1), object(10,2)
mutated: object(0,0), object(2,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 10229600,  storage_rebate: 3829716, non_refundable_storage_fee: 38684

task 11, line 170:
//# view-object 2,1
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 4
Contents: Test::M1::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 12, line 172:
//# view-object 2,0
Owner: Object ID: ( BFC17411f8a6213b4d42f92a0244b13fd15e39fdde00c75e4061e6ce158383543665f93 )
Version: 4
Contents: Test::M1::Child {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 13, line 174:
//# create-checkpoint
Checkpoint created: 2

task 14, lines 176-236:
//# run-graphql --cursors @{obj_5_0,1} @{obj_5_0,2}
Response: {
  "data": {
    "parent_version_4_show_dof_and_dfs": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBdBH4piE7TUL5KgJEsT/RXjn93gDHXkBh5s4Vg4NUNmAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IEgAeLNRj4SjykaQj4FoZ/4bA/OcaAJeq4Ig9THwtEdtAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IFWvS6320AIuiKw0wx1UDWx0bTr8ZIz+oCRnMFTpaqarAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "INE6pXaIpyOqkz3KdFu5VY+bmU0watK7urpduyf165O+AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_3_only_dof": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBdBH4piE7TUL5KgJEsT/RXjn93gDHXkBh5s4Vg4NUNmAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
                    "count": "1"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "use_dof_version_3_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_parent_version_4": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEgAeLNRj4SjykaQj4FoZ/4bA/OcaAJeq4Ig9THwtEdtAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IFWvS6320AIuiKw0wx1UDWx0bTr8ZIz+oCRnMFTpaqarAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "INE6pXaIpyOqkz3KdFu5VY+bmU0watK7urpduyf165O+AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "use_dof_version_3_cursor_at_parent_version_3": {
      "dynamicFields": {
        "edges": []
      }
    },
    "use_dof_version_4_cursor_at_version_3": {
      "dynamicFields": {
        "edges": []
      }
    }
  }
}

task 15, lines 238-275:
//# run-graphql
Response: {
  "data": {
    "parent_version_3": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
              "count": "1"
            }
          }
        }
      },
      "dfNotAvailableYet": null
    },
    "parent_version_4": {
      "dynamicObjectField": {
        "name": {
          "bcs": "pAEAAAAAAAA=",
          "type": {
            "repr": "u64"
          }
        },
        "value": {
          "contents": {
            "json": {
              "id": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
              "count": "2"
            }
          }
        }
      },
      "dfAddedHere": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    }
  }
}

task 16, lines 278-279:
//# programmable --sender A --inputs object(2,1)
//> Test::M1::add_more_df(Input(0));
created: object(16,0), object(16,1), object(16,2)
mutated: object(0,0), object(2,1)
gas summary: computation_cost: 1000000, storage_cost: 8922400,  storage_rebate: 2535588, non_refundable_storage_fee: 25612

task 17, line 281:
//# view-object 2,1
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 5
Contents: Test::M1::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 18, line 283:
//# view-object 2,0
Owner: Object ID: ( BFC17411f8a6213b4d42f92a0244b13fd15e39fdde00c75e4061e6ce158383543665f93 )
Version: 4
Contents: Test::M1::Child {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 19, line 285:
//# create-checkpoint
Checkpoint created: 3

task 20, lines 287-337:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,3}
Response: {
  "data": {
    "parent_version_4_has_4_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBdBH4piE7TUL5KgJEsT/RXjn93gDHXkBh5s4Vg4NUNmAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IEgAeLNRj4SjykaQj4FoZ/4bA/OcaAJeq4Ig9THwtEdtAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IFWvS6320AIuiKw0wx1UDWx0bTr8ZIz+oCRnMFTpaqarAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "INE6pXaIpyOqkz3KdFu5VY+bmU0watK7urpduyf165O+AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEgAeLNRj4SjykaQj4FoZ/4bA/OcaAJeq4Ig9THwtEdtAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IFWvS6320AIuiKw0wx1UDWx0bTr8ZIz+oCRnMFTpaqarAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "INE6pXaIpyOqkz3KdFu5VY+bmU0watK7urpduyf165O+AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_5_has_7_children": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBdBH4piE7TUL5KgJEsT/RXjn93gDHXkBh5s4Vg4NUNmAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IEd74ExytHEGUvf0C6S2x1/DcD66pjRD3yMh1sNIJ6baAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IEgAeLNRj4SjykaQj4FoZ/4bA/OcaAJeq4Ig9THwtEdtAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IFWvS6320AIuiKw0wx1UDWx0bTr8ZIz+oCRnMFTpaqarAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "ILLGLnIO50UEmacU4YdTzb/dSEu1ESAbgNK+pbwNMGCXAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IM6AUTh/vTcl7cJGWuKrQjsaWNN5/7c9eVpxij+LMhcGAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "INE6pXaIpyOqkz3KdFu5VY+bmU0watK7urpduyf165O+AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_5_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEd74ExytHEGUvf0C6S2x1/DcD66pjRD3yMh1sNIJ6baAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IEgAeLNRj4SjykaQj4FoZ/4bA/OcaAJeq4Ig9THwtEdtAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IFWvS6320AIuiKw0wx1UDWx0bTr8ZIz+oCRnMFTpaqarAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "ILLGLnIO50UEmacU4YdTzb/dSEu1ESAbgNK+pbwNMGCXAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IM6AUTh/vTcl7cJGWuKrQjsaWNN5/7c9eVpxij+LMhcGAwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "INE6pXaIpyOqkz3KdFu5VY+bmU0watK7urpduyf165O+AwAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    }
  }
}

task 21, lines 339-340:
//# programmable --sender A --inputs object(2,1) 420
//> Test::M1::remove_df(Input(0));
mutated: object(0,0), object(2,1)
deleted: object(10,0), object(10,1), object(10,2)
gas summary: computation_cost: 1000000, storage_cost: 2561200,  storage_rebate: 8833176, non_refundable_storage_fee: 89224

task 22, line 342:
//# view-object 2,1
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 6
Contents: Test::M1::Parent {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,1),
        },
    },
}

task 23, line 344:
//# view-object 2,0
Owner: Object ID: ( BFC17411f8a6213b4d42f92a0244b13fd15e39fdde00c75e4061e6ce158383543665f93 )
Version: 4
Contents: Test::M1::Child {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    count: 2u64,
}

task 24, line 346:
//# create-checkpoint
Checkpoint created: 4

task 25, lines 348-398:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,4}
Response: {
  "data": {
    "parent_version_4_has_df1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBdBH4piE7TUL5KgJEsT/RXjn93gDHXkBh5s4Vg4NUNmBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IEgAeLNRj4SjykaQj4FoZ/4bA/OcaAJeq4Ig9THwtEdtBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IFWvS6320AIuiKw0wx1UDWx0bTr8ZIz+oCRnMFTpaqarBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "INE6pXaIpyOqkz3KdFu5VY+bmU0watK7urpduyf165O+BAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_on_dof_consistent": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEgAeLNRj4SjykaQj4FoZ/4bA/OcaAJeq4Ig9THwtEdtAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df1"
              }
            }
          },
          {
            "cursor": "IFWvS6320AIuiKw0wx1UDWx0bTr8ZIz+oCRnMFTpaqarAgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "INE6pXaIpyOqkz3KdFu5VY+bmU0watK7urpduyf165O+AgAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df2"
              }
            }
          }
        ]
      }
    },
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBdBH4piE7TUL5KgJEsT/RXjn93gDHXkBh5s4Vg4NUNmBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IEd74ExytHEGUvf0C6S2x1/DcD66pjRD3yMh1sNIJ6baBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "ILLGLnIO50UEmacU4YdTzb/dSEu1ESAbgNK+pbwNMGCXBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IM6AUTh/vTcl7cJGWuKrQjsaWNN5/7c9eVpxij+LMhcGBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEd74ExytHEGUvf0C6S2x1/DcD66pjRD3yMh1sNIJ6baBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "ILLGLnIO50UEmacU4YdTzb/dSEu1ESAbgNK+pbwNMGCXBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IM6AUTh/vTcl7cJGWuKrQjsaWNN5/7c9eVpxij+LMhcGBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      }
    }
  }
}

task 26, lines 400-431:
//# run-graphql
Response: {
  "data": {
    "parent_version_4": {
      "dfAtParentVersion4": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}

task 28, line 435:
//# create-checkpoint
Checkpoint created: 5

task 30, line 439:
//# create-checkpoint
Checkpoint created: 6

task 32, line 443:
//# create-checkpoint
Checkpoint created: 7

task 34, line 447:
//# create-checkpoint
Checkpoint created: 8

task 35, lines 449-507:
//# run-graphql --cursors @{obj_5_0,2} @{obj_5_0,4}
Response: {
  "data": {
    "availableRange": {
      "first": {
        "sequenceNumber": 4
      },
      "last": {
        "sequenceNumber": 8
      }
    },
    "parent_version_4_outside_consistent_range": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBdBH4piE7TUL5KgJEsT/RXjn93gDHXkBh5s4Vg4NUNmCAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
                    "count": "2"
                  }
                }
              }
            }
          }
        ]
      }
    },
    "parent_version_4_paginated_outside_consistent_range": null,
    "parent_version_6_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IBdBH4piE7TUL5KgJEsT/RXjn93gDHXkBh5s4Vg4NUNmCAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "pAEAAAAAAAA=",
                "type": {
                  "repr": "u64"
                }
              },
              "value": {
                "contents": {
                  "json": {
                    "id": "0xd981b8550a26e946ebb157c8ce530395f23671c6fe03f79c43bca39378a591d7",
                    "count": "2"
                  }
                }
              }
            }
          },
          {
            "cursor": "IEd74ExytHEGUvf0C6S2x1/DcD66pjRD3yMh1sNIJ6baCAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "ILLGLnIO50UEmacU4YdTzb/dSEu1ESAbgNK+pbwNMGCXCAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IM6AUTh/vTcl7cJGWuKrQjsaWNN5/7c9eVpxij+LMhcGCAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      }
    },
    "parent_version_6_paginated_no_df_1_2_3": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IEd74ExytHEGUvf0C6S2x1/DcD66pjRD3yMh1sNIJ6baBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "ILLGLnIO50UEmacU4YdTzb/dSEu1ESAbgNK+pbwNMGCXBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "IM6AUTh/vTcl7cJGWuKrQjsaWNN5/7c9eVpxij+LMhcGBAAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA==",
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
                }
              },
              "value": {
                "json": "df4"
              }
            }
          }
        ]
      }
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 42,
          "column": 5
        }
      ],
      "path": [
        "parent_version_4_paginated_outside_consistent_range",
        "dynamicFields"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}

task 36, lines 509-540:
//# run-graphql
Response: {
  "data": {
    "parent_version_4": {
      "dfAtParentVersion4_outside_range": {
        "name": {
          "bcs": "A2RmMQ==",
          "type": {
            "repr": "0x0000000000000000000000000000000000000000000000000000000000000001::string::String"
          }
        },
        "value": {
          "json": "df1"
        }
      }
    },
    "parent_version_6": {
      "dfAtParentVersion6": null
    }
  }
}
