processed 17 tasks

init:
A: object(0,0)

task 1, lines 20-68:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 9089600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 70:
//# run Test::M1::parent --sender A --args @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 72:
//# run Test::M1::child --sender A --args @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 74:
//# run Test::M1::child --sender A --args @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5, line 76:
//# run Test::M1::add_child --sender A --args object(2,0) object(3,0) 42
created: object(5,0)
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 6384000,  storage_rebate: 3889908, non_refundable_storage_fee: 39292

task 6, line 78:
//# run Test::M1::add_nested_child --sender A --args object(2,0) 42 object(4,0) 420
created: object(6,0)
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 6384000,  storage_rebate: 3889908, non_refundable_storage_fee: 39292

task 7, line 80:
//# run Test::M1::reclaim_and_freeze_child --sender A --args object(2,0) 42
mutated: object(0,0), object(2,0), object(3,0)
deleted: object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 3929200,  storage_rebate: 6320160, non_refundable_storage_fee: 63840

task 8, line 82:
//# create-checkpoint
Checkpoint created: 1

task 9, lines 84-114:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xe012012d1f6f732e225f74b8fbe494f3508f65fa314a4040084a58df05eb025b",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0xe012012d1f6f732e225f74b8fbe494f3508f65fa314a4040084a58df05eb025b",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": []
              }
            }
          }
        ]
      }
    }
  }
}

task 10, lines 116-146:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xe012012d1f6f732e225f74b8fbe494f3508f65fa314a4040084a58df05eb025b",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0xe012012d1f6f732e225f74b8fbe494f3508f65fa314a4040084a58df05eb025b",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x21c2267a09a8ddcf6c1a41acbd643afd009cd74841eb8d26cb9d3b5dda7dce2e",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0x21c2267a09a8ddcf6c1a41acbd643afd009cd74841eb8d26cb9d3b5dda7dce2e",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 11, lines 148-178:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": []
      }
    }
  }
}

task 12, lines 180-210:
//# run-graphql
Response: {
  "data": {
    "object": null
  }
}

task 13, lines 212-239:
//# run-graphql
Response: {
  "data": {
    "object": {
      "owner": {
        "parent": {
          "address": "0x694f7eb1a591cedb80ef89e9439ee9b4b1e74f692a3f60249417b94381c8e7a5"
        }
      },
      "dynamicFields": {
        "nodes": []
      }
    }
  }
}

task 14, lines 241-258:
//# run-graphql
Response: {
  "data": {
    "object": null
  }
}

task 15, lines 260-287:
//# run-graphql
Response: {
  "data": {
    "object": {
      "owner": {
        "_": null
      },
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x21c2267a09a8ddcf6c1a41acbd643afd009cd74841eb8d26cb9d3b5dda7dce2e",
              "version": 6,
              "contents": {
                "json": {
                  "id": "0x21c2267a09a8ddcf6c1a41acbd643afd009cd74841eb8d26cb9d3b5dda7dce2e",
                  "count": "0"
                }
              }
            }
          }
        ]
      }
    }
  }
}

task 16, lines 289-316:
//# run-graphql
Response: {
  "data": {
    "object": {
      "owner": {
        "_": null
      },
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x21c2267a09a8ddcf6c1a41acbd643afd009cd74841eb8d26cb9d3b5dda7dce2e",
              "version": 6,
              "contents": {
                "json": {
                  "id": "0x21c2267a09a8ddcf6c1a41acbd643afd009cd74841eb8d26cb9d3b5dda7dce2e",
                  "count": "0"
                }
              }
            }
          }
        ]
      }
    }
  }
}
