processed 17 tasks

init:
A: object(0,0)

task 1, lines 24-75:
//# publish
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 9279600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 77:
//# run Test::M1::parent --sender A --args @A
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2622000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 79:
//# run Test::M1::child --sender A --args @A
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 81:
//# run Test::M1::child --sender A --args @A
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 5, line 83:
//# run Test::M1::add_child --sender A --args object(2,0) object(3,0) 42
created: object(5,0)
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 6384000,  storage_rebate: 3889908, non_refundable_storage_fee: 39292

task 6, line 85:
//# run Test::M1::add_nested_child --sender A --args object(2,0) 42 object(4,0) 420
created: object(6,0)
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 6384000,  storage_rebate: 3889908, non_refundable_storage_fee: 39292

task 7, line 87:
//# run Test::M1::mutate_child_on_parent --sender A --args object(2,0) 42
mutated: object(0,0), object(2,0), object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 3929200,  storage_rebate: 3889908, non_refundable_storage_fee: 39292

task 8, line 89:
//# run Test::M1::mutate_nested_child_on_parent --sender A --args object(2,0) 42 420
mutated: object(0,0), object(2,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 3929200,  storage_rebate: 3889908, non_refundable_storage_fee: 39292

task 9, line 91:
//# create-checkpoint
Checkpoint created: 1

task 10, lines 93-123:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xddf4cb91726703e1e6546aed1b441234a0b9c1f3ec5bd8cf1dc5dcae7e3a52c3",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0xddf4cb91726703e1e6546aed1b441234a0b9c1f3ec5bd8cf1dc5dcae7e3a52c3",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": []
              }
            }
          }
        ]
      }
    }
  }
}

task 11, lines 125-155:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xddf4cb91726703e1e6546aed1b441234a0b9c1f3ec5bd8cf1dc5dcae7e3a52c3",
              "version": 5,
              "contents": {
                "json": {
                  "id": "0xddf4cb91726703e1e6546aed1b441234a0b9c1f3ec5bd8cf1dc5dcae7e3a52c3",
                  "count": "0"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x6e57cd1675ddff958d52b2201e7e4da81c08d0407d08ade1ff57cd5ba9f64547",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0x6e57cd1675ddff958d52b2201e7e4da81c08d0407d08ade1ff57cd5ba9f64547",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 12, lines 157-187:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xddf4cb91726703e1e6546aed1b441234a0b9c1f3ec5bd8cf1dc5dcae7e3a52c3",
              "version": 7,
              "contents": {
                "json": {
                  "id": "0xddf4cb91726703e1e6546aed1b441234a0b9c1f3ec5bd8cf1dc5dcae7e3a52c3",
                  "count": "1"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x6e57cd1675ddff958d52b2201e7e4da81c08d0407d08ade1ff57cd5ba9f64547",
                      "version": 6,
                      "contents": {
                        "json": {
                          "id": "0x6e57cd1675ddff958d52b2201e7e4da81c08d0407d08ade1ff57cd5ba9f64547",
                          "count": "0"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 13, lines 189-219:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0xddf4cb91726703e1e6546aed1b441234a0b9c1f3ec5bd8cf1dc5dcae7e3a52c3",
              "version": 7,
              "contents": {
                "json": {
                  "id": "0xddf4cb91726703e1e6546aed1b441234a0b9c1f3ec5bd8cf1dc5dcae7e3a52c3",
                  "count": "1"
                }
              },
              "dynamicFields": {
                "nodes": [
                  {
                    "value": {
                      "address": "0x6e57cd1675ddff958d52b2201e7e4da81c08d0407d08ade1ff57cd5ba9f64547",
                      "version": 8,
                      "contents": {
                        "json": {
                          "id": "0x6e57cd1675ddff958d52b2201e7e4da81c08d0407d08ade1ff57cd5ba9f64547",
                          "count": "1"
                        }
                      }
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}

task 14, lines 221-238:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": []
      }
    }
  }
}

task 15, lines 240-257:
//# run-graphql
Response: {
  "data": {
    "object": null
  }
}

task 16, lines 259-276:
//# run-graphql
Response: {
  "data": {
    "object": {
      "dynamicFields": {
        "nodes": [
          {
            "value": {
              "address": "0x6e57cd1675ddff958d52b2201e7e4da81c08d0407d08ade1ff57cd5ba9f64547",
              "version": 6,
              "contents": {
                "json": {
                  "id": "0x6e57cd1675ddff958d52b2201e7e4da81c08d0407d08ade1ff57cd5ba9f64547",
                  "count": "0"
                }
              }
            }
          }
        ]
      }
    }
  }
}
