processed 9 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-21:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5502400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'publish'. lines 23-52:
created: object(2,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 7987600,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 3 'publish'. lines 55-82:
created: object(3,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 8534800,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4 'run'. lines 84-84:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2546000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 5 'run'. lines 86-86:
created: object(5,0), object(5,1)
mutated: object(0,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 6239600,  storage_rebate: 2520540, non_refundable_storage_fee: 25460

task 6 'view-object'. lines 88-88:
Owner: Object ID: ( BFC7c99314a9fc9546d22d80564eb589705e712cf2f6ae5052571b45798d52c4816b0e6 )
Version: 3
Contents: t3::o3::Obj3 {id: sui::object::UID {id: sui::object::ID {bytes: fake(4,0)}}}

task 7 'view-object'. lines 90-92:
Owner: Shared
Version: 3
Contents: t2::o2::Obj2 {id: sui::object::UID {id: sui::object::ID {bytes: fake(5,1)}}}

task 8 'run'. lines 93-93:
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: 0xf3f1cf64d645f397f16e0a55037aee1444630dda3cdf61fae61ee7b9c70a8bc1, parent_id: 0x7c99314a9fc9546d22d80564eb589705e712cf2f6ae5052571b45798d52c4816 }
