processed 4 tasks

task 1 'publish'. lines 8-42:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 481080,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 44-44:
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 130720,  storage_rebate: 129413, non_refundable_storage_fee: 1307

task 3 'run'. lines 46-46:
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 130720,  storage_rebate: 129413, non_refundable_storage_fee: 1307
