processed 4 tasks

task 1 'publish'. lines 8-42:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 240540,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 44-44:
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 3 'run'. lines 46-46:
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654
