processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-27:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 6353600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 29-29:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 31-31:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 2565684, non_refundable_storage_fee: 25916

task 4 'run'. lines 33-33:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2591600,  storage_rebate: 2565684, non_refundable_storage_fee: 25916
