processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-24:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 316540,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 26-29:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 31-34:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 4 'run'. lines 36-39:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 5 'run'. lines 41-44:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 6 'run'. lines 46-49:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 7 'run'. lines 51-51:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654
