processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-27:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 316540,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 29-32:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 34-37:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 4 'run'. lines 39-42:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 5 'run'. lines 44-47:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 6 'run'. lines 49-52:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 7 'run'. lines 54-54:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 64706, non_refundable_storage_fee: 654
