processed 2 tasks

task 0 'publish'. lines 6-28:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5289600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1 'publish'. lines 30-59:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5487200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072
