processed 2 tasks

task 0 'publish'. lines 6-23:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1 'publish'. lines 25-43:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 5251600,  storage_rebate: 1294128, non_refundable_storage_fee: 13072
