processed 3 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-12:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 60192,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'upgrade'. lines 14-23:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 100000, storage_cost: 69692,  storage_rebate: 29118, non_refundable_storage_fee: 294
