processed 8 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-23:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 79876,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'upgrade'. lines 24-41:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 100000, storage_cost: 85500,  storage_rebate: 29118, non_refundable_storage_fee: 294

task 3 'upgrade'. lines 42-71:
created: object(3,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 100000, storage_cost: 97736,  storage_rebate: 29118, non_refundable_storage_fee: 294

task 4 'upgrade'. lines 72-99:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 100000, storage_cost: 108604,  storage_rebate: 29118, non_refundable_storage_fee: 294

task 5 'run'. lines 101-101:
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 13072,  storage_rebate: 0, non_refundable_storage_fee: 0

task 6 'run'. lines 103-103:
created: object(6,0)
mutated: object(0,2)
gas summary: computation_cost: 100000, storage_cost: 27512,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 7 'view-object'. lines 105-105:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: V0::base_module::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(6,0)}}, field0: 10u64, field1: 10u64}
