processed 8 tasks

init:
A: object(0,0)

task 1, lines 6-20:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 7987600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 21-35:
//# upgrade --package V0 --upgrade-capability 1,1 --sender A
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 8550000,  storage_rebate: 2911788, non_refundable_storage_fee: 29412

task 3, lines 36-60:
//# upgrade --package V1 --upgrade-capability 1,1 --sender A
created: object(3,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 9773600,  storage_rebate: 2911788, non_refundable_storage_fee: 29412

task 4, lines 61-83:
//# upgrade --package V2 --upgrade-capability 1,1 --sender A
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 10700800,  storage_rebate: 2911788, non_refundable_storage_fee: 29412

task 5, line 85:
//# run V3::friend_module::call_friend
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 1307200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 6, line 87:
//# run V3::friend_module::call_public
created: object(6,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2751200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 7, line 89:
//# view-object 6,0
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 3
Contents: V0::base_module::Object {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(6,0),
        },
    },
    field0: 10u64,
    field1: 10u64,
}
