processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-12:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 65360,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'upgrade'. lines 14-24:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 100000, storage_cost: 73872,  storage_rebate: 29118, non_refundable_storage_fee: 294

task 3 'publish'. lines 26-32:
created: object(3,0), object(3,1)
mutated: object(0,0)
gas summary: computation_cost: 100000, storage_cost: 65208,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 4 'upgrade'. lines 34-41:
created: object(4,0)
mutated: object(0,0), object(3,1)
gas summary: computation_cost: 100000, storage_cost: 71136,  storage_rebate: 29118, non_refundable_storage_fee: 294
