processed 5 tasks

init:
A: object(0,0)

task 1, lines 6-16:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1), object(1,2)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 8876800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 18-33:
//# upgrade --package A0 --upgrade-capability 1,2 --sender A
created: object(2,0)
mutated: object(0,0), object(1,2)
gas summary: computation_cost: 1000000, storage_cost: 8557600,  storage_rebate: 2911788, non_refundable_storage_fee: 29412

task 3, line 35:
//# run A1::m::test --type-args A0::m::A --args object(1,1) --sender A
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 3131200,  storage_rebate: 3099888, non_refundable_storage_fee: 31312

task 4, line 37:
//# run A1::m::test --type-args A1::m::B --args object(1,1) --sender A
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 3131200,  storage_rebate: 3099888, non_refundable_storage_fee: 31312
