processed 7 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-12:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 326800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'upgrade'. lines 15-21:
created: object(2,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 354160,  storage_rebate: 145589, non_refundable_storage_fee: 1471

task 3 'upgrade'. lines 23-33:
created: object(3,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 369360,  storage_rebate: 145589, non_refundable_storage_fee: 1471

task 4 'publish'. lines 36-42:
created: object(4,0), object(4,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 326040,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 5 'upgrade'. lines 44-50:
created: object(5,0)
mutated: object(0,0), object(4,1)
gas summary: computation_cost: 1000000, storage_cost: 353400,  storage_rebate: 145589, non_refundable_storage_fee: 1471

task 6 'upgrade'. lines 52-59:
created: object(6,0)
mutated: object(0,0), object(4,1)
gas summary: computation_cost: 1000000, storage_cost: 355680,  storage_rebate: 145589, non_refundable_storage_fee: 1471
