processed 12 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 14-48:
//# publish
created: object(1,0), object(1,1)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 9530400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 50-56:
//# programmable --sender A --inputs object(1,0) 42 @A
//> 0: test::counter::inc(Input(0));
//> 1: test::counter::inc_by(Input(0), Input(1));
//> 2: sui::coin::value<sui::sui::SUI>(Gas);
//> 3: test::counter::inc_by(Input(0), Result(2));
//> 4: test::counter::take(Input(0), Input(1));
//> 5: TransferObjects([Result(4)], Input(2))
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Debug of error: VMVerificationOrDeserializationError at command Some(2)

task 3, lines 58-60:
//# programmable --sender A --inputs 42 @B
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 62:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 64-68:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "66dq5rJjBZCLxqercLMzeP9CpZ15XGneh6zCaSY3ioLy"
  }
}

task 6, lines 70-74:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32602,
    "message": "Invalid Params: Transaction 11111111111111111111111111111111 not found"
  }
}

task 7, lines 76-86:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "digest": "66dq5rJjBZCLxqercLMzeP9CpZ15XGneh6zCaSY3ioLy",
    "rawTransaction": "AAADAQFg3SN14Wi8F7nOUSsxy+BbXB90ZLATdsA5OlO5+BpHlQIAAAAAAAAAAQAIKgAAAAAAAAAAIPzMmkIbuxPBpmoaqY8K11Ap7elIV3ecaRW0T5QGi5IeBgDUeNOlWiPIs64DuVCW02VxRGCkXBEQ3P/KmqvviECqzAdjb3VudGVyA2luYwABAQAAANR406VaI8izrgO5UJbTZXFEYKRcERDc/8qaq++IQKrMB2NvdW50ZXIGaW5jX2J5AAIBAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIEY29pbgV2YWx1ZQEHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDc3VpA1NVSQABAADUeNOlWiPIs64DuVCW02VxRGCkXBEQ3P/KmqvviECqzAdjb3VudGVyBmluY19ieQACAQAAAgIAANR406VaI8izrgO5UJbTZXFEYKRcERDc/8qaq++IQKrMB2NvdW50ZXIEdGFrZQACAQAAAQEAAQECBAABAgD8zJpCG7sTwaZqGqmPCtdQKe3pSFd3nGkVtE+UBouSHgGdvt7Fx71RQqW/tT3XUPyOv6FohIb94gRfRbRUwukxBQEAAAAAAAAAIDVwhRo+NzubO7PkIQgOrvxe4tYqD+mMcqb/pzdnTFhX/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh7oAwAAAAAAAADyBSoBAAAAAA==",
    "rawEffects": [
      1,
      1,
      13,
      1,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      202,
      154,
      59,
      0,
      0,
      0,
      0,
      64,
      66,
      15,
      0,
      0,
      0,
      0,
      0,
      80,
      180,
      40,
      0,
      0,
      0,
      0,
      0,
      236,
      140,
      20,
      0,
      0,
      0,
      0,
      0,
      36,
      53,
      0,
      0,
      0,
      0,
      0,
      0,
      32,
      75,
      187,
      251,
      60,
      126,
      156,
      161,
      28,
      5,
      83,
      254,
      206,
      29,
      91,
      76,
      211,
      95,
      10,
      130,
      133,
      162,
      254,
      95,
      197,
      65,
      137,
      254,
      206,
      143,
      204,
      185,
      166,
      1,
      1,
      0,
      0,
      0,
      0,
      2,
      32,
      71,
      12,
      122,
      125,
      243,
      155,
      91,
      248,
      74,
      107,
      133,
      103,
      110,
      79,
      41,
      141,
      98,
      75,
      213,
      250,
      80,
      22,
      75,
      161,
      237,
      83,
      79,
      50,
      108,
      111,
      59,
      38,
      32,
      207,
      0,
      174,
      36,
      105,
      90,
      172,
      121,
      239,
      223,
      126,
      47,
      34,
      111,
      25,
      175,
      61,
      103,
      11,
      159,
      182,
      250,
      155,
      243,
      236,
      46,
      173,
      245,
      208,
      163,
      78,
      242,
      3,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2,
      96,
      221,
      35,
      117,
      225,
      104,
      188,
      23,
      185,
      206,
      81,
      43,
      49,
      203,
      224,
      91,
      92,
      31,
      116,
      100,
      176,
      19,
      118,
      192,
      57,
      58,
      83,
      185,
      248,
      26,
      71,
      149,
      1,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      32,
      42,
      27,
      224,
      175,
      20,
      241,
      9,
      208,
      153,
      54,
      169,
      252,
      248,
      56,
      74,
      121,
      181,
      113,
      28,
      68,
      228,
      15,
      253,
      114,
      33,
      48,
      77,
      224,
      144,
      230,
      136,
      160,
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      32,
      39,
      91,
      83,
      233,
      170,
      54,
      2,
      52,
      232,
      231,
      123,
      241,
      222,
      31,
      249,
      61,
      142,
      80,
      3,
      235,
      181,
      61,
      54,
      41,
      146,
      222,
      55,
      46,
      107,
      116,
      96,
      254,
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      157,
      190,
      222,
      197,
      199,
      189,
      81,
      66,
      165,
      191,
      181,
      61,
      215,
      80,
      252,
      142,
      191,
      161,
      104,
      132,
      134,
      253,
      226,
      4,
      95,
      69,
      180,
      84,
      194,
      233,
      49,
      5,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      32,
      53,
      112,
      133,
      26,
      62,
      55,
      59,
      155,
      59,
      179,
      228,
      33,
      8,
      14,
      174,
      252,
      94,
      226,
      214,
      42,
      15,
      233,
      140,
      114,
      166,
      255,
      167,
      55,
      103,
      76,
      88,
      87,
      0,
      252,
      204,
      154,
      66,
      27,
      187,
      19,
      193,
      166,
      106,
      26,
      169,
      143,
      10,
      215,
      80,
      41,
      237,
      233,
      72,
      87,
      119,
      156,
      105,
      21,
      180,
      79,
      148,
      6,
      139,
      146,
      30,
      1,
      32,
      69,
      109,
      15,
      69,
      95,
      46,
      157,
      169,
      80,
      157,
      190,
      176,
      141,
      108,
      253,
      65,
      79,
      20,
      51,
      137,
      101,
      249,
      238,
      119,
      223,
      63,
      10,
      118,
      83,
      3,
      184,
      91,
      0,
      252,
      204,
      154,
      66,
      27,
      187,
      19,
      193,
      166,
      106,
      26,
      169,
      143,
      10,
      215,
      80,
      41,
      237,
      233,
      72,
      87,
      119,
      156,
      105,
      21,
      180,
      79,
      148,
      6,
      139,
      146,
      30,
      0,
      0,
      0
    ]
  }
}

task 8, lines 88-98:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "digest": "66dq5rJjBZCLxqercLMzeP9CpZ15XGneh6zCaSY3ioLy",
    "transaction": {
      "data": {
        "messageVersion": "v1",
        "transaction": {
          "kind": "ProgrammableTransaction",
          "inputs": [
            {
              "type": "object",
              "objectType": "sharedObject",
              "objectId": "BFC60dd2375e168bc17b9ce512b31cbe05b5c1f7464b01376c0393a53b9f81a47950a74",
              "initialSharedVersion": "2",
              "mutable": true
            },
            {
              "type": "pure",
              "valueType": "u64",
              "value": "42"
            },
            {
              "type": "pure",
              "valueType": "address",
              "value": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "transactions": [
            {
              "MoveCall": {
                "package": "BFCd478d3a55a23c8b3ae03b95096d365714460a45c1110dcffca9aabef8840aacc9705",
                "module": "counter",
                "function": "inc",
                "arguments": [
                  {
                    "Input": 0
                  }
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFCd478d3a55a23c8b3ae03b95096d365714460a45c1110dcffca9aabef8840aacc9705",
                "module": "counter",
                "function": "inc_by",
                "arguments": [
                  {
                    "Input": 0
                  },
                  {
                    "Input": 1
                  }
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFC000000000000000000000000000000000000000000000000000000000000000268e4",
                "module": "coin",
                "function": "value",
                "type_arguments": [
                  "0x2::sui::SUI"
                ],
                "arguments": [
                  "GasCoin"
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFCd478d3a55a23c8b3ae03b95096d365714460a45c1110dcffca9aabef8840aacc9705",
                "module": "counter",
                "function": "inc_by",
                "arguments": [
                  {
                    "Input": 0
                  },
                  {
                    "Result": 2
                  }
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFCd478d3a55a23c8b3ae03b95096d365714460a45c1110dcffca9aabef8840aacc9705",
                "module": "counter",
                "function": "take",
                "arguments": [
                  {
                    "Input": 0
                  },
                  {
                    "Input": 1
                  }
                ]
              }
            },
            {
              "TransferObjects": [
                [
                  {
                    "Result": 4
                  }
                ],
                {
                  "Input": 2
                }
              ]
            }
          ]
        },
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "gasData": {
          "payment": [
            {
              "objectId": "BFC9dbedec5c7bd5142a5bfb53dd750fc8ebfa1688486fde2045f45b454c2e931058af6",
              "version": 1,
              "digest": "4bc82eYUX8ZhQoVADGneqbEAEmydMUZNbSj17J5sM5Hg"
            }
          ],
          "owner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
          "price": "1000",
          "budget": "5000000000"
        }
      },
      "txSignatures": [
        "ACegBfY5uM4evaSdWuPQOu3P7ZUlSNBoLwGAyP4bZJgbf+/qXtd75G7YWSIQewi3Dvo++E5x41tppGlzGcaLKwp/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
      ]
    },
    "effects": {
      "messageVersion": "v1",
      "status": {
        "status": "failure",
        "error": "VMVerificationOrDeserializationError in command 2"
      },
      "executedEpoch": "0",
      "gasUsed": {
        "computationCost": "1000000",
        "storageCost": "2667600",
        "storageRebate": "1346796",
        "nonRefundableStorageFee": "13604"
      },
      "modifiedAtVersions": [
        {
          "objectId": "BFC60dd2375e168bc17b9ce512b31cbe05b5c1f7464b01376c0393a53b9f81a47950a74",
          "sequenceNumber": "2"
        },
        {
          "objectId": "BFC9dbedec5c7bd5142a5bfb53dd750fc8ebfa1688486fde2045f45b454c2e931058af6",
          "sequenceNumber": "1"
        }
      ],
      "sharedObjects": [
        {
          "objectId": "BFC60dd2375e168bc17b9ce512b31cbe05b5c1f7464b01376c0393a53b9f81a47950a74",
          "version": 2,
          "digest": "3qNn9jtVh71zsCtiqRw8cTuT9uSo1hReTsub7MJiVT7D"
        }
      ],
      "transactionDigest": "66dq5rJjBZCLxqercLMzeP9CpZ15XGneh6zCaSY3ioLy",
      "mutated": [
        {
          "owner": {
            "Shared": {
              "initial_shared_version": 2
            }
          },
          "reference": {
            "objectId": "BFC60dd2375e168bc17b9ce512b31cbe05b5c1f7464b01376c0393a53b9f81a47950a74",
            "version": 3,
            "digest": "3edfv8ujo5yxnEeN2Jg9AQkQWHdgAfHSHDgQ58hbakz1"
          }
        },
        {
          "owner": {
            "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
          },
          "reference": {
            "objectId": "BFC9dbedec5c7bd5142a5bfb53dd750fc8ebfa1688486fde2045f45b454c2e931058af6",
            "version": 3,
            "digest": "5g1asm7Zvrt1UETA9bhNXM32XqrmoiGWnRLcatX5AUq8"
          }
        }
      ],
      "gasObject": {
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "reference": {
          "objectId": "BFC9dbedec5c7bd5142a5bfb53dd750fc8ebfa1688486fde2045f45b454c2e931058af6",
          "version": 3,
          "digest": "5g1asm7Zvrt1UETA9bhNXM32XqrmoiGWnRLcatX5AUq8"
        }
      },
      "dependencies": [
        "5nLyzPM3ZSM1EV8GvnKH9xRfaJbwUzD8y2miPY6rHSUM",
        "Ew3ziLcdeZAFjbzCDyxEyTiGgMiAVSYpSsT8ofC3sjb7"
      ]
    }
  }
}

task 9, lines 100-109:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "digest": "66dq5rJjBZCLxqercLMzeP9CpZ15XGneh6zCaSY3ioLy",
    "events": []
  }
}

task 10, lines 111-120:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 5,
  "result": {
    "digest": "66dq5rJjBZCLxqercLMzeP9CpZ15XGneh6zCaSY3ioLy",
    "balanceChanges": [
      {
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "coinType": "0x2::bfc::BFC",
        "amount": "-2320804"
      }
    ]
  }
}

task 11, lines 122-131:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 6,
  "result": {
    "digest": "AqE6PBNEMmWba71kqc7cyrewZnm5EXS7TvteVoYgAnTo",
    "balanceChanges": [
      {
        "owner": {
          "AddressOwner": "BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9"
        },
        "coinType": "0x2::bfc::BFC",
        "amount": "42"
      },
      {
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "coinType": "0x2::bfc::BFC",
        "amount": "-2320314"
      }
    ]
  }
}
