processed 12 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 14-48:
//# publish
created: object(1,0), object(1,1)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 9530400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 50-56:
//# programmable --sender A --inputs object(1,0) 42 @A
//> 0: test::counter::inc(Input(0));
//> 1: test::counter::inc_by(Input(0), Input(1));
//> 2: sui::coin::value<sui::sui::SUI>(Gas);
//> 3: test::counter::inc_by(Input(0), Result(2));
//> 4: test::counter::take(Input(0), Input(1));
//> 5: TransferObjects([Result(4)], Input(2))
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Debug of error: VMVerificationOrDeserializationError at command Some(2)

task 3, lines 58-60:
//# programmable --sender A --inputs 42 @B
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 62:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 64-68:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "HawWnbcNujMZHsrcRJn2BJWXx71LAMgQZx584xoJo3js"
  }
}

task 6, lines 70-74:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32602,
    "message": "Invalid Params: Transaction 11111111111111111111111111111111 not found"
  }
}

task 7, lines 76-86:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "digest": "HawWnbcNujMZHsrcRJn2BJWXx71LAMgQZx584xoJo3js",
    "rawTransaction": "AAADAQHdHN+CqCF59/A0R0vm8Ipjv1QOhO+t+H1rHmxdDp0cegIAAAAAAAAAAQAIKgAAAAAAAAAAIPzMmkIbuxPBpmoaqY8K11Ap7elIV3ecaRW0T5QGi5IeBgAui54vsQk2GQX3shn79LaDRXN60Yp1ATjvLY3iFX7j/Qdjb3VudGVyA2luYwABAQAAAC6Lni+xCTYZBfeyGfv0toNFc3rRinUBOO8tjeIVfuP9B2NvdW50ZXIGaW5jX2J5AAIBAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIEY29pbgV2YWx1ZQEHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDc3VpA1NVSQABAAAui54vsQk2GQX3shn79LaDRXN60Yp1ATjvLY3iFX7j/Qdjb3VudGVyBmluY19ieQACAQAAAgIAAC6Lni+xCTYZBfeyGfv0toNFc3rRinUBOO8tjeIVfuP9B2NvdW50ZXIEdGFrZQACAQAAAQEAAQECBAABAgD8zJpCG7sTwaZqGqmPCtdQKe3pSFd3nGkVtE+UBouSHgGgFiVtyYWOdFkQQWUtUVyIjgiw4nNQ/OrYoUhCZrUO8AEAAAAAAAAAIHnrfFP0k7DVfgbnaX6WTAsrb16+gwRhE0mfR1coeZ4P/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh7oAwAAAAAAAADyBSoBAAAAAA==",
    "rawEffects": [
      1,
      1,
      13,
      1,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      202,
      154,
      59,
      0,
      0,
      0,
      0,
      64,
      66,
      15,
      0,
      0,
      0,
      0,
      0,
      80,
      180,
      40,
      0,
      0,
      0,
      0,
      0,
      236,
      140,
      20,
      0,
      0,
      0,
      0,
      0,
      36,
      53,
      0,
      0,
      0,
      0,
      0,
      0,
      32,
      246,
      108,
      203,
      211,
      86,
      33,
      98,
      215,
      94,
      234,
      204,
      59,
      165,
      184,
      92,
      210,
      58,
      243,
      45,
      206,
      169,
      233,
      220,
      209,
      140,
      96,
      185,
      150,
      90,
      46,
      74,
      62,
      1,
      0,
      0,
      0,
      0,
      0,
      2,
      32,
      89,
      12,
      128,
      60,
      90,
      160,
      70,
      251,
      213,
      105,
      251,
      179,
      86,
      110,
      202,
      202,
      156,
      212,
      172,
      5,
      168,
      110,
      15,
      186,
      189,
      205,
      102,
      37,
      98,
      59,
      164,
      146,
      32,
      107,
      42,
      89,
      161,
      172,
      136,
      185,
      220,
      39,
      80,
      55,
      194,
      17,
      173,
      154,
      100,
      23,
      122,
      37,
      239,
      24,
      151,
      229,
      225,
      1,
      74,
      231,
      181,
      201,
      225,
      3,
      177,
      3,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2,
      160,
      22,
      37,
      109,
      201,
      133,
      142,
      116,
      89,
      16,
      65,
      101,
      45,
      81,
      92,
      136,
      142,
      8,
      176,
      226,
      115,
      80,
      252,
      234,
      216,
      161,
      72,
      66,
      102,
      181,
      14,
      240,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      32,
      121,
      235,
      124,
      83,
      244,
      147,
      176,
      213,
      126,
      6,
      231,
      105,
      126,
      150,
      76,
      11,
      43,
      111,
      94,
      190,
      131,
      4,
      97,
      19,
      73,
      159,
      71,
      87,
      40,
      121,
      158,
      15,
      0,
      252,
      204,
      154,
      66,
      27,
      187,
      19,
      193,
      166,
      106,
      26,
      169,
      143,
      10,
      215,
      80,
      41,
      237,
      233,
      72,
      87,
      119,
      156,
      105,
      21,
      180,
      79,
      148,
      6,
      139,
      146,
      30,
      1,
      32,
      190,
      96,
      3,
      248,
      20,
      224,
      197,
      94,
      210,
      125,
      144,
      114,
      98,
      165,
      212,
      152,
      187,
      211,
      24,
      61,
      197,
      107,
      156,
      130,
      203,
      66,
      193,
      160,
      38,
      223,
      187,
      226,
      0,
      252,
      204,
      154,
      66,
      27,
      187,
      19,
      193,
      166,
      106,
      26,
      169,
      143,
      10,
      215,
      80,
      41,
      237,
      233,
      72,
      87,
      119,
      156,
      105,
      21,
      180,
      79,
      148,
      6,
      139,
      146,
      30,
      0,
      221,
      28,
      223,
      130,
      168,
      33,
      121,
      247,
      240,
      52,
      71,
      75,
      230,
      240,
      138,
      99,
      191,
      84,
      14,
      132,
      239,
      173,
      248,
      125,
      107,
      30,
      108,
      93,
      14,
      157,
      28,
      122,
      1,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      32,
      249,
      152,
      220,
      87,
      179,
      133,
      111,
      123,
      71,
      229,
      226,
      211,
      188,
      50,
      170,
      245,
      230,
      226,
      69,
      84,
      53,
      235,
      53,
      134,
      70,
      84,
      189,
      18,
      26,
      30,
      54,
      108,
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      32,
      14,
      208,
      116,
      3,
      190,
      12,
      107,
      83,
      134,
      97,
      61,
      222,
      51,
      5,
      153,
      24,
      200,
      166,
      221,
      87,
      177,
      193,
      215,
      39,
      155,
      221,
      181,
      102,
      27,
      219,
      127,
      192,
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ]
  }
}

task 8, lines 88-98:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "digest": "HawWnbcNujMZHsrcRJn2BJWXx71LAMgQZx584xoJo3js",
    "transaction": {
      "data": {
        "messageVersion": "v1",
        "transaction": {
          "kind": "ProgrammableTransaction",
          "inputs": [
            {
              "type": "object",
              "objectType": "sharedObject",
              "objectId": "BFCdd1cdf82a82179f7f034474be6f08a63bf540e84efadf87d6b1e6c5d0e9d1c7a55f4",
              "initialSharedVersion": "2",
              "mutable": true
            },
            {
              "type": "pure",
              "valueType": "u64",
              "value": "42"
            },
            {
              "type": "pure",
              "valueType": "address",
              "value": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "transactions": [
            {
              "MoveCall": {
                "package": "BFC2e8b9e2fb109361905f7b219fbf4b68345737ad18a750138ef2d8de2157ee3fd81d5",
                "module": "counter",
                "function": "inc",
                "arguments": [
                  {
                    "Input": 0
                  }
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFC2e8b9e2fb109361905f7b219fbf4b68345737ad18a750138ef2d8de2157ee3fd81d5",
                "module": "counter",
                "function": "inc_by",
                "arguments": [
                  {
                    "Input": 0
                  },
                  {
                    "Input": 1
                  }
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFC000000000000000000000000000000000000000000000000000000000000000268e4",
                "module": "coin",
                "function": "value",
                "type_arguments": [
                  "0x2::sui::SUI"
                ],
                "arguments": [
                  "GasCoin"
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFC2e8b9e2fb109361905f7b219fbf4b68345737ad18a750138ef2d8de2157ee3fd81d5",
                "module": "counter",
                "function": "inc_by",
                "arguments": [
                  {
                    "Input": 0
                  },
                  {
                    "Result": 2
                  }
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFC2e8b9e2fb109361905f7b219fbf4b68345737ad18a750138ef2d8de2157ee3fd81d5",
                "module": "counter",
                "function": "take",
                "arguments": [
                  {
                    "Input": 0
                  },
                  {
                    "Input": 1
                  }
                ]
              }
            },
            {
              "TransferObjects": [
                [
                  {
                    "Result": 4
                  }
                ],
                {
                  "Input": 2
                }
              ]
            }
          ]
        },
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "gasData": {
          "payment": [
            {
              "objectId": "BFCa016256dc9858e74591041652d515c888e08b0e27350fcead8a1484266b50ef0b0b0",
              "version": 1,
              "digest": "9CvbaQW3bz5xEj6Gt9d3mZfadgb5mPUDvKqrPcuPX1Wn"
            }
          ],
          "owner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
          "price": "1000",
          "budget": "5000000000"
        }
      },
      "txSignatures": [
        "AMPQM94xMQihRZyH93ufde2chyFRq+sqKT83HISu6XpFFPAkXSBtDLzWOmPXQnpUIzD1oO7xSxTSRf213NvsuQ1/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
      ]
    },
    "effects": {
      "messageVersion": "v1",
      "status": {
        "status": "failure",
        "error": "VMVerificationOrDeserializationError in command 2"
      },
      "executedEpoch": "0",
      "gasUsed": {
        "computationCost": "1000000",
        "storageCost": "2667600",
        "storageRebate": "1346796",
        "nonRefundableStorageFee": "13604"
      },
      "modifiedAtVersions": [
        {
          "objectId": "BFCa016256dc9858e74591041652d515c888e08b0e27350fcead8a1484266b50ef0b0b0",
          "sequenceNumber": "1"
        },
        {
          "objectId": "BFCdd1cdf82a82179f7f034474be6f08a63bf540e84efadf87d6b1e6c5d0e9d1c7a55f4",
          "sequenceNumber": "2"
        }
      ],
      "sharedObjects": [
        {
          "objectId": "BFCdd1cdf82a82179f7f034474be6f08a63bf540e84efadf87d6b1e6c5d0e9d1c7a55f4",
          "version": 2,
          "digest": "HoKi392criAX4jXGyQ7vPQwohLoxQ7wQrGHFXNgL2kG3"
        }
      ],
      "transactionDigest": "HawWnbcNujMZHsrcRJn2BJWXx71LAMgQZx584xoJo3js",
      "mutated": [
        {
          "owner": {
            "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
          },
          "reference": {
            "objectId": "BFCa016256dc9858e74591041652d515c888e08b0e27350fcead8a1484266b50ef0b0b0",
            "version": 3,
            "digest": "Dp9NzYFmaNNr8AbvLPkby8W5iwsgWsLMkK5qH35c3HhK"
          }
        },
        {
          "owner": {
            "Shared": {
              "initial_shared_version": 2
            }
          },
          "reference": {
            "objectId": "BFCdd1cdf82a82179f7f034474be6f08a63bf540e84efadf87d6b1e6c5d0e9d1c7a55f4",
            "version": 3,
            "digest": "zq4m46BbAjDQVVbdeYGjgo9pVELpEMNFcmCYk39U45u"
          }
        }
      ],
      "gasObject": {
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "reference": {
          "objectId": "BFCa016256dc9858e74591041652d515c888e08b0e27350fcead8a1484266b50ef0b0b0",
          "version": 3,
          "digest": "Dp9NzYFmaNNr8AbvLPkby8W5iwsgWsLMkK5qH35c3HhK"
        }
      },
      "dependencies": [
        "6zcLn41t4757WYJmj8y7bFttm8z1SXHeNoDyZjMueBr9",
        "8DL5YUyMosF7FDJy2Mfy9JvoPpCvFzHvTvjxEfCqU7yJ"
      ]
    }
  }
}

task 9, lines 100-109:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "digest": "HawWnbcNujMZHsrcRJn2BJWXx71LAMgQZx584xoJo3js",
    "events": []
  }
}

task 10, lines 111-120:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 5,
  "result": {
    "digest": "HawWnbcNujMZHsrcRJn2BJWXx71LAMgQZx584xoJo3js",
    "balanceChanges": [
      {
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "coinType": "0x2::bfc::BFC",
        "amount": "-2320804"
      }
    ]
  }
}

task 11, lines 122-131:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 6,
  "result": {
    "digest": "HikSsHFoizRK24nZ9nd6HA9KjM1kBhJ8LDjpXbSxrgQQ",
    "balanceChanges": [
      {
        "owner": {
          "AddressOwner": "BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9"
        },
        "coinType": "0x2::bfc::BFC",
        "amount": "42"
      },
      {
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "coinType": "0x2::bfc::BFC",
        "amount": "-2320314"
      }
    ]
  }
}
