processed 12 tasks

init:
A: object(0,0), B: object(0,1)

task 1, lines 14-48:
//# publish
created: object(1,0), object(1,1)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 9530400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, lines 50-56:
//# programmable --sender A --inputs object(1,0) 42 @A
//> 0: test::counter::inc(Input(0));
//> 1: test::counter::inc_by(Input(0), Input(1));
//> 2: sui::coin::value<sui::sui::SUI>(Gas);
//> 3: test::counter::inc_by(Input(0), Result(2));
//> 4: test::counter::take(Input(0), Input(1));
//> 5: TransferObjects([Result(4)], Input(2))
Error: Transaction Effects Status: Move Bytecode Verification Error. Please run the Bytecode Verifier for more information.
Debug of error: VMVerificationOrDeserializationError at command Some(2)

task 3, lines 58-60:
//# programmable --sender A --inputs 42 @B
//> 0: SplitCoins(Gas, [Input(0)]);
//> 1: TransferObjects([Result(0)], Input(1))
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2614400,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 4, line 62:
//# create-checkpoint
Checkpoint created: 1

task 5, lines 64-68:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "digest": "DMjGh8aQTBSyVSDxuBgjAYHXK88u7nvAvbKnngFfRCmA"
  }
}

task 6, lines 70-74:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "code": -32602,
    "message": "Invalid Params: Transaction 11111111111111111111111111111111 not found"
  }
}

task 7, lines 76-86:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 2,
  "result": {
    "digest": "DMjGh8aQTBSyVSDxuBgjAYHXK88u7nvAvbKnngFfRCmA",
    "rawTransaction": "AAADAQGV53OObe5mytZ7lG7Eup5OLBJyInH/bEb3IUWdvkcUegIAAAAAAAAAAQAIKgAAAAAAAAAAIPzMmkIbuxPBpmoaqY8K11Ap7elIV3ecaRW0T5QGi5IeBgAn7pqN36ciYK1nkmPyU9PLvR2qNM7alcWojHHbahx+1Adjb3VudGVyA2luYwABAQAAACfumo3fpyJgrWeSY/JT08u9Hao0ztqVxaiMcdtqHH7UB2NvdW50ZXIGaW5jX2J5AAIBAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIEY29pbgV2YWx1ZQEHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDc3VpA1NVSQABAAAn7pqN36ciYK1nkmPyU9PLvR2qNM7alcWojHHbahx+1Adjb3VudGVyBmluY19ieQACAQAAAgIAACfumo3fpyJgrWeSY/JT08u9Hao0ztqVxaiMcdtqHH7UB2NvdW50ZXIEdGFrZQACAQAAAQEAAQECBAABAgD8zJpCG7sTwaZqGqmPCtdQKe3pSFd3nGkVtE+UBouSHgH8yl8mdcjoFWDoPbNdNQDHLlByQHAGFpdsK6zON6CI1QEAAAAAAAAAIIPBlrOkcDjy9HaHipRbcJ+kQFmX0/G6khFZtM+W9W1K/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh7oAwAAAAAAAADyBSoBAAAAAA==",
    "rawEffects": [
      1,
      1,
      13,
      1,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      202,
      154,
      59,
      0,
      0,
      0,
      0,
      64,
      66,
      15,
      0,
      0,
      0,
      0,
      0,
      80,
      180,
      40,
      0,
      0,
      0,
      0,
      0,
      236,
      140,
      20,
      0,
      0,
      0,
      0,
      0,
      36,
      53,
      0,
      0,
      0,
      0,
      0,
      0,
      32,
      183,
      155,
      167,
      158,
      108,
      231,
      43,
      3,
      164,
      147,
      242,
      225,
      173,
      45,
      219,
      12,
      189,
      180,
      91,
      0,
      128,
      211,
      189,
      242,
      48,
      145,
      22,
      56,
      102,
      94,
      90,
      173,
      1,
      1,
      0,
      0,
      0,
      0,
      2,
      32,
      25,
      163,
      136,
      1,
      196,
      183,
      80,
      148,
      97,
      166,
      178,
      72,
      126,
      100,
      218,
      171,
      179,
      152,
      214,
      198,
      141,
      126,
      170,
      128,
      124,
      6,
      64,
      75,
      147,
      145,
      151,
      165,
      32,
      123,
      54,
      91,
      163,
      145,
      61,
      241,
      17,
      64,
      51,
      32,
      4,
      182,
      101,
      79,
      228,
      241,
      7,
      219,
      113,
      168,
      186,
      95,
      146,
      21,
      233,
      4,
      51,
      225,
      234,
      222,
      206,
      3,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      2,
      149,
      231,
      115,
      142,
      109,
      238,
      102,
      202,
      214,
      123,
      148,
      110,
      196,
      186,
      158,
      78,
      44,
      18,
      114,
      34,
      113,
      255,
      108,
      70,
      247,
      33,
      69,
      157,
      190,
      71,
      20,
      122,
      1,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      32,
      244,
      52,
      94,
      90,
      235,
      34,
      125,
      202,
      50,
      190,
      120,
      240,
      134,
      122,
      43,
      3,
      5,
      178,
      222,
      243,
      226,
      141,
      241,
      178,
      219,
      216,
      234,
      249,
      101,
      129,
      250,
      28,
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      32,
      219,
      72,
      246,
      196,
      145,
      84,
      12,
      61,
      171,
      132,
      173,
      63,
      186,
      192,
      21,
      0,
      48,
      15,
      167,
      45,
      137,
      1,
      254,
      229,
      246,
      93,
      15,
      181,
      199,
      240,
      11,
      144,
      2,
      2,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      252,
      202,
      95,
      38,
      117,
      200,
      232,
      21,
      96,
      232,
      61,
      179,
      93,
      53,
      0,
      199,
      46,
      80,
      114,
      64,
      112,
      6,
      22,
      151,
      108,
      43,
      172,
      206,
      55,
      160,
      136,
      213,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      32,
      131,
      193,
      150,
      179,
      164,
      112,
      56,
      242,
      244,
      118,
      135,
      138,
      148,
      91,
      112,
      159,
      164,
      64,
      89,
      151,
      211,
      241,
      186,
      146,
      17,
      89,
      180,
      207,
      150,
      245,
      109,
      74,
      0,
      252,
      204,
      154,
      66,
      27,
      187,
      19,
      193,
      166,
      106,
      26,
      169,
      143,
      10,
      215,
      80,
      41,
      237,
      233,
      72,
      87,
      119,
      156,
      105,
      21,
      180,
      79,
      148,
      6,
      139,
      146,
      30,
      1,
      32,
      210,
      231,
      13,
      140,
      233,
      68,
      73,
      127,
      31,
      138,
      34,
      194,
      161,
      48,
      100,
      124,
      79,
      94,
      144,
      155,
      199,
      234,
      63,
      167,
      218,
      223,
      43,
      72,
      85,
      221,
      22,
      145,
      0,
      252,
      204,
      154,
      66,
      27,
      187,
      19,
      193,
      166,
      106,
      26,
      169,
      143,
      10,
      215,
      80,
      41,
      237,
      233,
      72,
      87,
      119,
      156,
      105,
      21,
      180,
      79,
      148,
      6,
      139,
      146,
      30,
      0,
      0,
      0
    ]
  }
}

task 8, lines 88-98:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 3,
  "result": {
    "digest": "DMjGh8aQTBSyVSDxuBgjAYHXK88u7nvAvbKnngFfRCmA",
    "transaction": {
      "data": {
        "messageVersion": "v1",
        "transaction": {
          "kind": "ProgrammableTransaction",
          "inputs": [
            {
              "type": "object",
              "objectType": "sharedObject",
              "objectId": "BFC95e7738e6dee66cad67b946ec4ba9e4e2c12722271ff6c46f721459dbe47147a9255",
              "initialSharedVersion": "2",
              "mutable": true
            },
            {
              "type": "pure",
              "valueType": "u64",
              "value": "42"
            },
            {
              "type": "pure",
              "valueType": "address",
              "value": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            }
          ],
          "transactions": [
            {
              "MoveCall": {
                "package": "BFC27ee9a8ddfa72260ad679263f253d3cbbd1daa34ceda95c5a88c71db6a1c7ed4b9aa",
                "module": "counter",
                "function": "inc",
                "arguments": [
                  {
                    "Input": 0
                  }
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFC27ee9a8ddfa72260ad679263f253d3cbbd1daa34ceda95c5a88c71db6a1c7ed4b9aa",
                "module": "counter",
                "function": "inc_by",
                "arguments": [
                  {
                    "Input": 0
                  },
                  {
                    "Input": 1
                  }
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFC000000000000000000000000000000000000000000000000000000000000000268e4",
                "module": "coin",
                "function": "value",
                "type_arguments": [
                  "0x2::sui::SUI"
                ],
                "arguments": [
                  "GasCoin"
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFC27ee9a8ddfa72260ad679263f253d3cbbd1daa34ceda95c5a88c71db6a1c7ed4b9aa",
                "module": "counter",
                "function": "inc_by",
                "arguments": [
                  {
                    "Input": 0
                  },
                  {
                    "Result": 2
                  }
                ]
              }
            },
            {
              "MoveCall": {
                "package": "BFC27ee9a8ddfa72260ad679263f253d3cbbd1daa34ceda95c5a88c71db6a1c7ed4b9aa",
                "module": "counter",
                "function": "take",
                "arguments": [
                  {
                    "Input": 0
                  },
                  {
                    "Input": 1
                  }
                ]
              }
            },
            {
              "TransferObjects": [
                [
                  {
                    "Result": 4
                  }
                ],
                {
                  "Input": 2
                }
              ]
            }
          ]
        },
        "sender": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
        "gasData": {
          "payment": [
            {
              "objectId": "BFCfcca5f2675c8e81560e83db35d3500c72e507240700616976c2bacce37a088d52761",
              "version": 1,
              "digest": "9sKcv3NRxETQVMDSfKyMz7S8SizoYbu5uDdeii9T2w69"
            }
          ],
          "owner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7",
          "price": "1000",
          "budget": "5000000000"
        }
      },
      "txSignatures": [
        "ALOGSdnE9kxoctaM5H2xf3hOayWVt2zB9nJni1pRCZA2NSe5irQw0aKuAcQO6GDK1ENvXaqtkTfiQQ2nRmMjNAV/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
      ]
    },
    "effects": {
      "messageVersion": "v1",
      "status": {
        "status": "failure",
        "error": "VMVerificationOrDeserializationError in command 2"
      },
      "executedEpoch": "0",
      "gasUsed": {
        "computationCost": "1000000",
        "storageCost": "2667600",
        "storageRebate": "1346796",
        "nonRefundableStorageFee": "13604"
      },
      "modifiedAtVersions": [
        {
          "objectId": "BFC95e7738e6dee66cad67b946ec4ba9e4e2c12722271ff6c46f721459dbe47147a9255",
          "sequenceNumber": "2"
        },
        {
          "objectId": "BFCfcca5f2675c8e81560e83db35d3500c72e507240700616976c2bacce37a088d52761",
          "sequenceNumber": "1"
        }
      ],
      "sharedObjects": [
        {
          "objectId": "BFC95e7738e6dee66cad67b946ec4ba9e4e2c12722271ff6c46f721459dbe47147a9255",
          "version": 2,
          "digest": "HSGo1cmfa2B8x2naJF734yLu8UHJSm8dvnMuxaW62WWX"
        }
      ],
      "transactionDigest": "DMjGh8aQTBSyVSDxuBgjAYHXK88u7nvAvbKnngFfRCmA",
      "mutated": [
        {
          "owner": {
            "Shared": {
              "initial_shared_version": 2
            }
          },
          "reference": {
            "objectId": "BFC95e7738e6dee66cad67b946ec4ba9e4e2c12722271ff6c46f721459dbe47147a9255",
            "version": 3,
            "digest": "FkzpJHyzvmGA7qTamVFCu7PUcdjG7zS3BSU4Ygfo9o5H"
          }
        },
        {
          "owner": {
            "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
          },
          "reference": {
            "objectId": "BFCfcca5f2675c8e81560e83db35d3500c72e507240700616976c2bacce37a088d52761",
            "version": 3,
            "digest": "FCGxjWnk2YCpDsHvV9uBqaxRPvWjZUrETE7Yy5VxsTPn"
          }
        }
      ],
      "gasObject": {
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "reference": {
          "objectId": "BFCfcca5f2675c8e81560e83db35d3500c72e507240700616976c2bacce37a088d52761",
          "version": 3,
          "digest": "FCGxjWnk2YCpDsHvV9uBqaxRPvWjZUrETE7Yy5VxsTPn"
        }
      },
      "dependencies": [
        "2j5pac5w9qyom8YfwRYyFxPLkVKrYo62KGGhnk4w13uN",
        "9HyDqQBP9R4aYy1uS85u8hDiEjU8zhthwt2FseNTJjdP"
      ]
    }
  }
}

task 9, lines 100-109:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 4,
  "result": {
    "digest": "DMjGh8aQTBSyVSDxuBgjAYHXK88u7nvAvbKnngFfRCmA",
    "events": []
  }
}

task 10, lines 111-120:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 5,
  "result": {
    "digest": "DMjGh8aQTBSyVSDxuBgjAYHXK88u7nvAvbKnngFfRCmA",
    "balanceChanges": [
      {
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "coinType": "0x2::bfc::BFC",
        "amount": "-2320804"
      }
    ]
  }
}

task 11, lines 122-131:
//# run-jsonrpc
Response: {
  "jsonrpc": "2.0",
  "id": 6,
  "result": {
    "digest": "9cHxoWf12UaZ4wHDbbRHnaKcrPAWZcsCdeZxrrrUvYJ1",
    "balanceChanges": [
      {
        "owner": {
          "AddressOwner": "BFCa7b032703878aa74c3126935789fd1d4d7e111d5911b09247d6963061c312b5a5cf9"
        },
        "coinType": "0x2::bfc::BFC",
        "amount": "42"
      },
      {
        "owner": {
          "AddressOwner": "BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7"
        },
        "coinType": "0x2::bfc::BFC",
        "amount": "-2320314"
      }
    ]
  }
}
