processed 3 tasks

task 0 'publish'. lines 7-17:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4780400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1 'publish'. lines 19-29:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4506800,  storage_rebate: 1294128, non_refundable_storage_fee: 13072

task 2 'publish'. lines 31-41:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 4499200,  storage_rebate: 1294128, non_refundable_storage_fee: 13072
