processed 4 tasks

task 0 'publish'. lines 7-22:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 250420,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1 'publish'. lines 24-39:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 234840,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 2 'publish'. lines 41-56:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 234460,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 3 'publish'. lines 58-76:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 257260,  storage_rebate: 64706, non_refundable_storage_fee: 654
