processed 4 tasks

task 0 'publish'. lines 7-17:
created: object(1,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 239020,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1 'publish'. lines 19-29:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 225340,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 2 'publish'. lines 31-41:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 224960,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 3 'publish'. lines 43-55:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 245100,  storage_rebate: 64706, non_refundable_storage_fee: 654
