processed 3 tasks

task 0 'publish'. lines 7-22:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 50084,  storage_rebate: 0, non_refundable_storage_fee: 0

task 1 'publish'. lines 24-39:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 46968,  storage_rebate: 12941, non_refundable_storage_fee: 131

task 2 'publish'. lines 41-56:
created: object(3,0)
mutated: object(0,1)
gas summary: computation_cost: 100000, storage_cost: 46892,  storage_rebate: 12941, non_refundable_storage_fee: 131
