processed 4 tasks

task 1, lines 6-19:
//# publish
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6961600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 21:
//# view-object 1,1
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: Test::M1::Object {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(1,1),
        },
    },
    value: 42u64,
}

task 3, line 23:
//# view-object 1,0
1,0::M1
