processed 4 tasks

task 1 'publish'. lines 6-23:
created: object(1,0), object(1,1)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 348080,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 25-25:
Owner: Account Address ( BFCfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e71f7 )
Version: 2
Contents: Test::M1::Object {id: sui::object::UID {id: sui::object::ID {bytes: fake(1,1)}}, value: 42u64}

task 3 'view-object'. lines 27-27:
1,0::M1
