processed 4 tasks

init:
A: object(0,0)

task 1, lines 6-33:
//# publish --sender A
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
unchanged_shared: 0x0000000000000000000000000000000000000000000000000000000000000403
gas summary: computation_cost: 1000000, storage_cost: 15982800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 35:
//# create-checkpoint
Checkpoint created: 1

task 3, lines 37-85:
//# run-graphql
Response: {
  "data": {
    "suiCoins": {
      "edges": [
        {
          "cursor": "ICMtsg/qbX5pTRZyyE75MzHctzMlAf3qYIM4uGQquvEfAQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
              }
            }
          }
        },
        {
          "cursor": "IDOndvV5J4fSkOyjx+pSodppRbAXPQp2zFwNt3UF8rHgAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
              }
            }
          }
        },
        {
          "cursor": "IJ8jnHxiAzgk2SxtF6lsMI5mgzyYtCkhYevqltFR67j2AQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983017200",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "IFxWW1X/sBNhthneKBJkVCECxoLZDaTcyc1tcX4tArphAQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x42d531a71e9bd17bba64f822812ce22a8180e92fc762108b690408f8a130b89a::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IF/hK1afHhxJqlC6CzH67IQY98J5kGl6kar1NXljHBSaAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x42d531a71e9bd17bba64f822812ce22a8180e92fc762108b690408f8a130b89a::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IOW/nCv1vFTvnsi7jdhZrXiCKjFEPSMeW6GSLqhdsXBPAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x42d531a71e9bd17bba64f822812ce22a8180e92fc762108b690408f8a130b89a::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "IJ8jnHxiAzgk2SxtF6lsMI5mgzyYtCkhYevqltFR67j2AQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983017200",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpiZmM6OkJGQyIsImMiOjF9",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::bfc::BFC"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983017200"
            }
          },
          {
            "cursor": "eyJ0IjoiMHg0MmQ1MzFhNzFlOWJkMTdiYmE2NGY4MjI4MTJjZTIyYTgxODBlOTJmYzc2MjEwOGI2OTA0MDhmOGExMzBiODlhOjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0x42d531a71e9bd17bba64f822812ce22a8180e92fc762108b690408f8a130b89a::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpiZmM6OkJGQyIsImMiOjF9"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHg0MmQ1MzFhNzFlOWJkMTdiYmE2NGY4MjI4MTJjZTIyYTgxODBlOTJmYzc2MjEwOGI2OTA0MDhmOGExMzBiODlhOjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
