name: Trigger builds for images and binaries

on:
  workflow_dispatch:
  push:
    branches: 
      - 'devnet'
      - 'testnet'
      - 'mainnet'
      - 'releases/sui-*-release'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Docker Builds in MystenLabs/sui-operations
        uses: peter-evans/repository-dispatch@v2 # pin@v2
        with:
          repository: MystenLabs/sui-operations
          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
          event-type: build-docker-images
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "ref_name": "${{ github.ref_name }}"}'

  release-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Release binaries builds in MystenLabs/sui-operations
        uses: peter-evans/repository-dispatch@v2 # pin@v2
        with:
          repository: MystenLabs/sui-operations
          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
          event-type: build-release-binaries
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
