processed 10 tasks

init:
A: object(0,0)

task 1, lines 6-31:
//# publish --upgradeable --sender A
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 8215600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2, line 33:
//# run Test::f::create_and_test
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2523200,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3, line 35:
//# view-object 2,0
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 2
Contents: Test::f::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    data: Test::f::F::V1{},
}

task 4, line 37:
//# run Test::f::update_inner --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2584000,  storage_rebate: 2497968, non_refundable_storage_fee: 25232

task 5, line 39:
//# view-object 2,0
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 3
Contents: Test::f::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    data: Test::f::F::V4{
        x: 42u64,
    },
}

task 6, lines 41-70:
//# upgrade --package Test --upgrade-capability 1,1 --sender A
created: object(6,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 9180800,  storage_rebate: 2911788, non_refundable_storage_fee: 29412

task 7, line 72:
//# view-object 2,0
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 3
Contents: fake(1,0)::f::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    data: fake(1,0)::f::F::V4{
        x: 42u64,
    },
}

task 8, line 74:
//# run Test::f::update_inner2 --args object(2,0)
mutated: object(0,1), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2644800,  storage_rebate: 2558160, non_refundable_storage_fee: 25840

task 9, line 76:
//# view-object 2,0
Owner: Account Address ( BFCd31b7b5068b139941cedc52b036f55c894fd394a170e2ba34245a324f1d16c8bc24c )
Version: 4
Contents: fake(1,0)::f::S {
    id: sui::object::UID {
        id: sui::object::ID {
            bytes: fake(2,0),
        },
    },
    data: fake(1,0)::f::F::V3{
        pos0: 42u64,
        pos1: 43u64,
    },
}
